/**
 * Admin Client Config
 *
 * Auto-generated by questpie codegen — do not edit.
 *
 * Pass this directly to <AdminLayoutProvider admin={admin} />
 */

import _modules from "../modules";
type _AdminModuleMergeAcc = Record<string, unknown>;
const _mergedModules = (Array.isArray(_modules)
	? _modules.reduce<_AdminModuleMergeAcc>((acc, mod) => {
		for (const [k, v] of Object.entries(mod)) acc[k] = typeof v === "object" && v !== null && !Array.isArray(v) ? { ...(typeof acc[k] === "object" && acc[k] !== null && !Array.isArray(acc[k]) ? acc[k] as Record<string, unknown> : {}), ...(v as Record<string, unknown>) } : v;
		return acc;
	}, {}) : _modules) as _AdminModuleMergeAcc;

const admin = _mergedModules;

export default admin;
