/**
 * Admin Client Config
 *
 * Auto-generated by questpie codegen — do not edit.
 *
 * Pass this directly to <AdminLayoutProvider admin={admin} />
 */

import _modules from "../modules";

const admin = _modules;

export default admin;
