/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import { activity as _coll_activity } from "../collections/activity";
import _coll_admin_audit_log from "../collections/admin-audit-log";
import _coll_agent_memory from "../collections/agent-memory";
import _coll_assets from "../collections/assets";
import { chatMessages as _coll_chat_messages } from "../collections/chat-messages";
import { chatSessions as _coll_chat_sessions } from "../collections/chat-sessions";
import _coll_document_store from "../collections/document-store";
import { environments as _coll_environments } from "../collections/environments";
import _coll_memory_settings from "../collections/memory-settings";
import { models as _coll_models } from "../collections/models";
import { projects as _coll_projects } from "../collections/projects";
import { providers as _coll_providers } from "../collections/providers";
import { runLinks as _coll_run_links } from "../collections/run-links";
import { scheduleExecutions as _coll_schedule_executions } from "../collections/schedule-executions";
import { schedules as _coll_schedules } from "../collections/schedules";
import { scripts as _coll_scripts } from "../collections/scripts";
import { secrets as _coll_secrets } from "../collections/secrets";
import { taskRelations as _coll_task_relations } from "../collections/task-relations";
import { tasks as _coll_tasks } from "../collections/tasks";

// ── Jobs ───────────────────────────────────────────────────
import _job_chatTurnProducer from "../jobs/chat-turn-producer";
import _job_cleanup from "../jobs/cleanup";
import _job_runAvailable from "../jobs/run-available";
import _job_scheduleTick from "../jobs/schedule-tick";
import _job_taskEscalation from "../jobs/task-escalation";
import _job_taskTurnProducer from "../jobs/task-turn-producer";

// ── Routes ─────────────────────────────────────────────────
import _route_apps_appId_fn from "../routes/apps/[appId]/[fn]";
import _route_apps_appId_fs_spread_path from "../routes/apps/[appId]/fs/[...path]";
import _route_apps_appId_token from "../routes/apps/[appId]/token";
import _route_chat from "../routes/chat";
import _route_chat_chatId_approve from "../routes/chat/[chatId]/approve";
import _route_chat_chatId_cancel from "../routes/chat/[chatId]/cancel";
import _route_chat_chatId_stream from "../routes/chat/[chatId]/stream";
import _route_events from "../routes/events";
import _route_intake from "../routes/intake";
import _route_runs_runId from "../routes/runs/[runId]";
import _route_runs_runId_artifacts from "../routes/runs/[runId]/artifacts";
import _route_runs_runId_artifacts_artifactId_content from "../routes/runs/[runId]/artifacts/[artifactId]/content";
import _route_runs_runId_events from "../routes/runs/[runId]/events";
import _route_runs_runId_stream from "../routes/runs/[runId]/stream";
import _route_runStream from "../routes/run-stream";
import _route_workspaceInspection_content from "../routes/workspace-inspection/content";
import _route_workspaceInspection_diff from "../routes/workspace-inspection/diff";
import _route_workspaceInspection_list from "../routes/workspace-inspection/list";
import _route_workspaceInspection_read from "../routes/workspace-inspection/read";

// ── Services ───────────────────────────────────────────────
import _svc_gitProviderAdapters from "../services/git-provider-adapters";
import _svc_knowledgeResource from "../services/knowledge-resource";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260507T095449_jolly_red_phoenix from "../migrations/20260507T095449_jolly_red_phoenix";
import _mig_20260516T185000_auth_user_admin_columns_repair from "../migrations/20260516T185000_auth_user_admin_columns_repair";
import _mig_20260517T095535_happy_orange_unicorn from "../migrations/20260517T095535_happy_orange_unicorn";
import _mig_20260519T135407_add_run_links_and_ai_module from "../migrations/20260519T135407_add_run_links_and_ai_module";
import _mig_20260519T142100_backfill_legacy_runs_into_run_links from "../migrations/20260519T142100_backfill_legacy_runs_into_run_links";
import _mig_20260519T145500_link_schedule_executions_to_run_links from "../migrations/20260519T145500_link_schedule_executions_to_run_links";
import _mig_20260519T161500_drop_legacy_execution_infra from "../migrations/20260519T161500_drop_legacy_execution_infra";
import _mig_20260529T001500_drop_workflow_configs from "../migrations/20260529T001500_drop_workflow_configs";
import _mig_20260529T003000_drop_capabilities from "../migrations/20260529T003000_drop_capabilities";
import _mig_20260604T111500_add_api_key_config_id from "../migrations/20260604T111500_add_api_key_config_id";
import _mig_20260606T003509_v2_schema from "../migrations/20260606T003509_v2_schema";
import _mig_20260606T004300_autopilot_memories from "../migrations/20260606T004300_autopilot_memories";
import _mig_20260606T170505_calm_yellow_panda from "../migrations/20260606T170505_calm_yellow_panda";
import _mig_20260607T120000_add_ai_runs_system_prompt from "../migrations/20260607T120000_add_ai_runs_system_prompt";
import _mig_20260607T130000_make_assets_upload_cols_nullable from "../migrations/20260607T130000_make_assets_upload_cols_nullable";
import _mig_20260614T120000_add_harness_resumable_fields from "../migrations/20260614T120000_add_harness_resumable_fields";
import _mig_20260630T202927_add_run_link_worker_kind_finalize from "../migrations/20260630T202927_add_run_link_worker_kind_finalize";

// ── Seeds ──────────────────────────────────────────────────
import _seed_demoCoverageData from "../seeds/demo-coverage-data";
import _seed_demoParentIssues from "../seeds/demo-parent-issues";
import _seed_demoProductData from "../seeds/demo-product-data";
import _seed_demoStressData from "../seeds/demo-stress-data";
import _seed_makeAMiniappSkill from "../seeds/make-a-miniapp-skill";
import _seed_runtimeDefaults from "../seeds/runtime-defaults";
import _seed_socialSchedulerApp from "../seeds/social-scheduler-app";

// ── Views ──────────────────────────────────────────────────
import _view_fileDetail from "../views/file-detail";
import _view_filesView from "../views/files-view";
import _view_taskDetail from "../views/task-detail";

// ── Workflows ──────────────────────────────────────────────
import _wf_taskPipeline from "../workflows/task-pipeline";

// ── McpTools ───────────────────────────────────────────────
import { artifactCreate as _mcpTool_artifact_create } from "../mcp-tools/run-artifacts";
import { knowledgeDelete as _mcpTool_knowledge_delete } from "../mcp-tools/knowledge";
import { knowledgeList as _mcpTool_knowledge_list } from "../mcp-tools/knowledge";
import { knowledgeRead as _mcpTool_knowledge_read } from "../mcp-tools/knowledge";
import { knowledgeSearch as _mcpTool_knowledge_search } from "../mcp-tools/knowledge";
import { knowledgeWrite as _mcpTool_knowledge_write } from "../mcp-tools/knowledge";
import { runArtifactContent as _mcpTool_run_artifact_content } from "../mcp-tools/run-artifacts";
import { runArtifactCreate as _mcpTool_run_artifact_create } from "../mcp-tools/run-artifacts";
import { runArtifacts as _mcpTool_run_artifacts } from "../mcp-tools/run-artifacts";
import { runCode as _mcpTool_run_code } from "../mcp-tools/run-code";
import { runEvents as _mcpTool_run_events } from "../mcp-tools/read-model";
import { runGet as _mcpTool_run_get } from "../mcp-tools/read-model";
import { runList as _mcpTool_run_list } from "../mcp-tools/read-model";
import { scheduleGet as _mcpTool_schedule_get } from "../mcp-tools/schedule-tools";
import { scheduleList as _mcpTool_schedule_list } from "../mcp-tools/schedule-tools";
import { scheduleTrigger as _mcpTool_schedule_trigger } from "../mcp-tools/schedule-tools";
import { taskCancel as _mcpTool_task_cancel } from "../mcp-tools/task-mutations";
import _mcpTool_task_create from "../mcp-tools/task-create";
import { taskDependencies as _mcpTool_task_dependencies } from "../mcp-tools/task-graph";
import { taskDependents as _mcpTool_task_dependents } from "../mcp-tools/task-graph";
import { taskGet as _mcpTool_task_get } from "../mcp-tools/read-model";
import { taskList as _mcpTool_task_list } from "../mcp-tools/read-model";
import { taskRetry as _mcpTool_task_retry } from "../mcp-tools/task-mutations";
import { taskUpdate as _mcpTool_task_update } from "../mcp-tools/task-mutations";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _mcpConfig from "../config/mcp";

import type { AppCollections, AppGlobals, AppJobs, _ModuleCollections, _AppDefaultServices, _AppServicesSeam, _AppTopLevelServices, _AppCustomServiceNamespaces, AppWorkflows, _Registry_Collections, _Registry_Globals, _Registry_Jobs, _Registry_Routes, _Registry_Services, _Registry_Emails, _Registry_FieldTypes, _Registry_Views, _Registry_Components, _Registry_Blocks, _Registry_Workflows, _Registry_McpTools, _AllModuleFields } from "./entities.gen";
import type { AnyCollectionOrBuilder, AnyGlobalOrBuilder, CollectionAPI, DrizzleClientFromQuestpieConfig, InferContextExtensionsFromAppConfig, InferSessionFromAuthConfig, MailerService, Questpie, QuestpieConfig, QueueClient, QueueJobType, ServiceInstancesInNamespace, TablesFromConfig, z } from "questpie/types";

import type { WorkflowClient } from "@questpie/workflows/server";
type _MPSubModules<M> = M extends { modules: infer S extends readonly any[] } ? S : readonly [];
type _MPConfigValue<M, K extends string> = M extends { config: infer C } ? (C extends Record<K, infer V> ? V : {}) : {};
type _MPConfigSub<A extends readonly any[], K extends string> = A extends readonly [infer H, ...infer T extends readonly any[]] ? _MPConfigSub<_MPSubModules<H>, K> & _MPConfigValue<H, K> & _MPConfigSub<T, K> : {};
type _AppAppConfig = typeof _appConfig;
type _AppContextExtensions = Partial<InferContextExtensionsFromAppConfig<_AppAppConfig>>;
type _AppAuthConfig = _MPConfigSub<typeof _modules, "auth"> & typeof _authConfig;
type _AppSessionAuthConfig = _AppAuthConfig;
type _AppSession = NonNullable<InferSessionFromAuthConfig<_AppSessionAuthConfig>> | null;

type _CollectionsAPI = { [K in keyof AppCollections]: CollectionAPI<AppCollections[K], AppCollections> };
type _JobHandlerCollections = _ModuleCollections & {
	activity: typeof _coll_activity;
	admin_audit_log: typeof _coll_admin_audit_log;
	agent_memory: typeof _coll_agent_memory;
	assets: typeof _coll_assets;
	chat_messages: typeof _coll_chat_messages;
	chat_sessions: typeof _coll_chat_sessions;
	document_store: typeof _coll_document_store;
	environments: typeof _coll_environments;
	memory_settings: typeof _coll_memory_settings;
	models: typeof _coll_models;
	projects: typeof _coll_projects;
	providers: typeof _coll_providers;
	run_links: typeof _coll_run_links;
	schedule_executions: typeof _coll_schedule_executions;
	schedules: typeof _coll_schedules;
	scripts: typeof _coll_scripts;
	secrets: typeof _coll_secrets;
	task_relations: typeof _coll_task_relations;
	tasks: typeof _coll_tasks;
};
type _JobHandlerCollectionsAPI = {
	activity: CollectionAPI<typeof _coll_activity, _JobHandlerCollections>;
	admin_audit_log: CollectionAPI<typeof _coll_admin_audit_log, _JobHandlerCollections>;
	agent_memory: CollectionAPI<typeof _coll_agent_memory, _JobHandlerCollections>;
	assets: CollectionAPI<typeof _coll_assets, _JobHandlerCollections>;
	chat_messages: CollectionAPI<typeof _coll_chat_messages, _JobHandlerCollections>;
	chat_sessions: CollectionAPI<typeof _coll_chat_sessions, _JobHandlerCollections>;
	document_store: CollectionAPI<typeof _coll_document_store, _JobHandlerCollections>;
	environments: CollectionAPI<typeof _coll_environments, _JobHandlerCollections>;
	memory_settings: CollectionAPI<typeof _coll_memory_settings, _JobHandlerCollections>;
	models: CollectionAPI<typeof _coll_models, _JobHandlerCollections>;
	projects: CollectionAPI<typeof _coll_projects, _JobHandlerCollections>;
	providers: CollectionAPI<typeof _coll_providers, _JobHandlerCollections>;
	run_links: CollectionAPI<typeof _coll_run_links, _JobHandlerCollections>;
	schedule_executions: CollectionAPI<typeof _coll_schedule_executions, _JobHandlerCollections>;
	schedules: CollectionAPI<typeof _coll_schedules, _JobHandlerCollections>;
	scripts: CollectionAPI<typeof _coll_scripts, _JobHandlerCollections>;
	secrets: CollectionAPI<typeof _coll_secrets, _JobHandlerCollections>;
	task_relations: CollectionAPI<typeof _coll_task_relations, _JobHandlerCollections>;
	tasks: CollectionAPI<typeof _coll_tasks, _JobHandlerCollections>;
};
type _ExecutionContextJob<T> = T extends { name: infer TName extends string; schema: z.ZodSchema<infer TPayload> } ? QueueJobType<TPayload, TName> : never;
type _ExecutionContextJobs = {
	chatTurnProducer: _ExecutionContextJob<typeof _job_chatTurnProducer>;
	cleanup: _ExecutionContextJob<typeof _job_cleanup>;
	runAvailable: _ExecutionContextJob<typeof _job_runAvailable>;
	scheduleTick: _ExecutionContextJob<typeof _job_scheduleTick>;
	taskEscalation: _ExecutionContextJob<typeof _job_taskEscalation>;
	taskTurnProducer: _ExecutionContextJob<typeof _job_taskTurnProducer>;
};
type _ExecutionContextServiceDefinitions = {
	gitProviderAdapters: typeof _svc_gitProviderAdapters;
	knowledgeResource: typeof _svc_knowledgeResource;
};
type _ExecutionContextDefaultServices = ServiceInstancesInNamespace<_ExecutionContextServiceDefinitions, "services">;
type _AppCollectionDefinitions = AppCollections & Record<string, AnyCollectionOrBuilder>;
type _AppGlobalDefinitions = AppGlobals & Record<string, AnyGlobalOrBuilder>;
type _AppQuestpieConfig = Omit<QuestpieConfig, "app" | "db" | "collections" | "globals" | "auth" | "~contextExtensions"> & {
	app: (typeof _runtime)["app"];
	db: (typeof _runtime)["db"];
	collections: _AppCollectionDefinitions;
	globals: _AppGlobalDefinitions;
	auth: _AppAuthConfig;
	storage: (typeof _runtime)["storage"];
	"~contextExtensions": _AppContextExtensions;
};
type _AppQuestpieBase = Questpie<_AppQuestpieConfig>;
type _AppDb = DrizzleClientFromQuestpieConfig<_AppQuestpieConfig>;
type _AppGlobalsAPI = _AppQuestpieBase["globals"];
type _AppStorage = _AppQuestpieBase["storage"];
type _AppTables = TablesFromConfig<_AppQuestpieConfig>;
export type _AppQuestpie = Omit<_AppQuestpieBase, "collections" | "globals"> & {
	collections: _CollectionsAPI;
	globals: _AppGlobalsAPI;
};

// ── AppContext augmentation — auto-types ALL handlers ──────
type _AppInfraRecord = {
	// Infrastructure
	app: _AppQuestpie;
	db: _AppDb;
	email: _AppQuestpie["email"];
	queue: QueueClient<AppJobs>;
	storage: _AppStorage;
	kv: _AppQuestpie["kv"];
	logger: _AppQuestpie["logger"];
	search: _AppQuestpie["search"];
	realtime: _AppQuestpie["realtime"];

	// Entity APIs
	collections: _CollectionsAPI;
	globals: _AppGlobalsAPI;
	tables: _AppTables;

	// Request-scoped
	session: _AppSession;
	t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

	// User services
	services: _AppDefaultServices;
};
type _AppInfraContext = _AppInfraRecord & _AppCustomServiceNamespaces;
type _AppCoreContext = _AppContextExtensions & _AppInfraContext;
type _ServiceCreateInfra = Omit<_AppInfraRecord, "services"> & { services: Questpie.Services };

declare global {
	namespace Questpie {
		interface AppContext extends _AppCoreContext, _AppTopLevelServices {
			workflows: WorkflowClient<AppWorkflows>;
		}

		interface JobHandlerContext {
			// Infrastructure
			db: _AppDb;
			email: _AppQuestpie["email"];
			queue: QueueClient<_ExecutionContextJobs>;
			storage: _AppStorage;
			kv: _AppQuestpie["kv"];
			logger: _AppQuestpie["logger"];
			search: _AppQuestpie["search"];
			realtime: _AppQuestpie["realtime"];

			// Entity APIs
			collections: _JobHandlerCollectionsAPI;
			globals: _AppGlobalsAPI;
			tables: _AppTables;

			// Request-scoped
			session: _AppSession;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

			// Workflows client — typed by AppWorkflows (name + schema preserved)
			workflows: WorkflowClient<AppWorkflows>;

			// User services
			services: _ExecutionContextDefaultServices;
		}

		interface WorkflowContext {
			// Infrastructure
			db: _AppDb;
			email: _AppQuestpie["email"];
			queue: QueueClient<_ExecutionContextJobs>;
			storage: _AppStorage;
			kv: _AppQuestpie["kv"];
			logger: _AppQuestpie["logger"];
			search: _AppQuestpie["search"];
			realtime: _AppQuestpie["realtime"];

			// Entity APIs
			collections: _JobHandlerCollectionsAPI;
			globals: _AppGlobalsAPI;
			tables: _AppTables;

			// Request-scoped
			session: _AppSession;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

			// Workflows client — typed by AppWorkflows (name + schema preserved)
			workflows: WorkflowClient<AppWorkflows>;

			// User services
			services: _ExecutionContextDefaultServices;
		}

		interface Services extends _AppServicesSeam {}
		interface ServiceCreateContext extends _AppContextExtensions, _ServiceCreateInfra {}
		// Names-only marker — the `ServiceCreateContext` fallback conditional
		// probes THIS interface's keys instead of the real one (whose base
		// resolves through module service definitions and would cycle).
		interface ServiceCreateContextGenerated { generated: unknown }

		// Typed service surface for appConfig({ context }) resolvers.
		// Excludes _AppContextExtensions — the resolver produces them.
		interface ContextResolverContext {
			collections: _CollectionsAPI;
			globals: _AppGlobalsAPI;
			logger: _AppQuestpie["logger"];
			kv: _AppQuestpie["kv"];
			queue: QueueClient<AppJobs>;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;
			services: _AppDefaultServices;
		}

		// App-level hook / default-access ctx infra seams (CL-05).
		// Filled with the real infra MINUS _AppContextExtensions, so the
		// app-level hooks/access predicates get precise db/session/
		// collections/globals/queue WITHOUT re-entering the extensions cycle.
		interface AppHookContext extends _AppInfraContext {}
		interface AppDefaultAccessContext extends _AppInfraContext {}

		// appConfig({ context }) resolver session/db — off the cyclic edge.
		interface ContextResolverBase {
			session: _AppSession;
			db: _AppDb;
		}

		interface Registry {
			collections: _Registry_Collections;
			globals: _Registry_Globals;
			jobs: _Registry_Jobs;
			routes: _Registry_Routes;
			services: _Registry_Services;
			emails: _Registry_Emails;
			"~fieldTypes": _Registry_FieldTypes & _AllModuleFields;
			views: _Registry_Views;
			components: _Registry_Components;
			blocks: _Registry_Blocks;
			workflows: _Registry_Workflows;
			mcpTools: _Registry_McpTools;
		}
	}
}

/** Resolved auth session for this app (`{ user, session } | null`). */
export type AppAuthConfig = _AppAuthConfig;

export type AppSession = _AppSession;

/** Authenticated user shape from the app session. */
export type AppSessionUser = NonNullable<_AppSession>["user"];
