/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import { createApp, createContextFactory } from "questpie/app";
import "./names.gen";
import type { AccessContext, AppDefinition, CollectionSelect, GlobalSelect, HookContext, Where } from "questpie/types";
import type { AppCollections, AppGlobals, AppRoutes } from "./entities.gen";
import type { _AppQuestpie, AppAuthConfig, AppSession, AppSessionUser } from "./context.gen";

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import { activity as _coll_activity } from "../collections/activity";
import _coll_admin_audit_log from "../collections/admin-audit-log";
import _coll_agent_memory from "../collections/agent-memory";
import _coll_assets from "../collections/assets";
import { chatMessages as _coll_chat_messages } from "../collections/chat-messages";
import { chatSessions as _coll_chat_sessions } from "../collections/chat-sessions";
import _coll_document_store from "../collections/document-store";
import { environments as _coll_environments } from "../collections/environments";
import _coll_memory_settings from "../collections/memory-settings";
import { models as _coll_models } from "../collections/models";
import { projects as _coll_projects } from "../collections/projects";
import { providers as _coll_providers } from "../collections/providers";
import { runLinks as _coll_run_links } from "../collections/run-links";
import { scheduleExecutions as _coll_schedule_executions } from "../collections/schedule-executions";
import { schedules as _coll_schedules } from "../collections/schedules";
import { scripts as _coll_scripts } from "../collections/scripts";
import { secrets as _coll_secrets } from "../collections/secrets";
import { taskRelations as _coll_task_relations } from "../collections/task-relations";
import { tasks as _coll_tasks } from "../collections/tasks";

// ── Jobs ───────────────────────────────────────────────────
import _job_chatTurnProducer from "../jobs/chat-turn-producer";
import _job_cleanup from "../jobs/cleanup";
import _job_scheduleTick from "../jobs/schedule-tick";
import _job_taskEscalation from "../jobs/task-escalation";
import _job_taskTurnProducer from "../jobs/task-turn-producer";

// ── Routes ─────────────────────────────────────────────────
import _route_apps_appId_fn from "../routes/apps/[appId]/[fn]";
import _route_apps_appId_fs_spread_path from "../routes/apps/[appId]/fs/[...path]";
import _route_apps_appId_token from "../routes/apps/[appId]/token";
import _route_chat from "../routes/chat";
import _route_chat_chatId_approve from "../routes/chat/[chatId]/approve";
import _route_chat_chatId_cancel from "../routes/chat/[chatId]/cancel";
import _route_chat_chatId_stream from "../routes/chat/[chatId]/stream";
import _route_events from "../routes/events";
import _route_intake from "../routes/intake";
import _route_runs_runId from "../routes/runs/[runId]";
import _route_runs_runId_artifacts from "../routes/runs/[runId]/artifacts";
import _route_runs_runId_artifacts_artifactId_content from "../routes/runs/[runId]/artifacts/[artifactId]/content";
import _route_runs_runId_events from "../routes/runs/[runId]/events";
import _route_runStream from "../routes/run-stream";
import _route_workspaceInspection_content from "../routes/workspace-inspection/content";
import _route_workspaceInspection_diff from "../routes/workspace-inspection/diff";
import _route_workspaceInspection_list from "../routes/workspace-inspection/list";
import _route_workspaceInspection_read from "../routes/workspace-inspection/read";

// ── Services ───────────────────────────────────────────────
import _svc_gitProviderAdapters from "../services/git-provider-adapters";
import _svc_knowledgeResource from "../services/knowledge-resource";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260507T095449_jolly_red_phoenix from "../migrations/20260507T095449_jolly_red_phoenix";
import _mig_20260516T185000_auth_user_admin_columns_repair from "../migrations/20260516T185000_auth_user_admin_columns_repair";
import _mig_20260517T095535_happy_orange_unicorn from "../migrations/20260517T095535_happy_orange_unicorn";
import _mig_20260519T135407_add_run_links_and_ai_module from "../migrations/20260519T135407_add_run_links_and_ai_module";
import _mig_20260519T142100_backfill_legacy_runs_into_run_links from "../migrations/20260519T142100_backfill_legacy_runs_into_run_links";
import _mig_20260519T145500_link_schedule_executions_to_run_links from "../migrations/20260519T145500_link_schedule_executions_to_run_links";
import _mig_20260519T161500_drop_legacy_execution_infra from "../migrations/20260519T161500_drop_legacy_execution_infra";
import _mig_20260529T001500_drop_workflow_configs from "../migrations/20260529T001500_drop_workflow_configs";
import _mig_20260529T003000_drop_capabilities from "../migrations/20260529T003000_drop_capabilities";
import _mig_20260604T111500_add_api_key_config_id from "../migrations/20260604T111500_add_api_key_config_id";
import _mig_20260606T003509_v2_schema from "../migrations/20260606T003509_v2_schema";
import _mig_20260606T004300_autopilot_memories from "../migrations/20260606T004300_autopilot_memories";
import _mig_20260606T170505_calm_yellow_panda from "../migrations/20260606T170505_calm_yellow_panda";
import _mig_20260607T120000_add_ai_runs_system_prompt from "../migrations/20260607T120000_add_ai_runs_system_prompt";
import _mig_20260607T130000_make_assets_upload_cols_nullable from "../migrations/20260607T130000_make_assets_upload_cols_nullable";
import _mig_20260614T120000_add_harness_resumable_fields from "../migrations/20260614T120000_add_harness_resumable_fields";
import _mig_20260630T202927_add_run_link_worker_kind_finalize from "../migrations/20260630T202927_add_run_link_worker_kind_finalize";

// ── Seeds ──────────────────────────────────────────────────
import _seed_demoCoverageData from "../seeds/demo-coverage-data";
import _seed_demoParentIssues from "../seeds/demo-parent-issues";
import _seed_demoProductData from "../seeds/demo-product-data";
import _seed_demoStressData from "../seeds/demo-stress-data";
import _seed_makeAMiniappSkill from "../seeds/make-a-miniapp-skill";
import _seed_runtimeDefaults from "../seeds/runtime-defaults";
import _seed_socialSchedulerApp from "../seeds/social-scheduler-app";

// ── Views ──────────────────────────────────────────────────
import _view_fileDetail from "../views/file-detail";
import _view_filesView from "../views/files-view";
import _view_taskDetail from "../views/task-detail";

// ── Workflows ──────────────────────────────────────────────
import _wf_taskPipeline from "../workflows/task-pipeline";

// ── McpTools ───────────────────────────────────────────────
import { artifactCreate as _mcpTool_artifact_create } from "../mcp-tools/run-artifacts";
import { knowledgeDelete as _mcpTool_knowledge_delete } from "../mcp-tools/knowledge";
import { knowledgeList as _mcpTool_knowledge_list } from "../mcp-tools/knowledge";
import { knowledgeRead as _mcpTool_knowledge_read } from "../mcp-tools/knowledge";
import { knowledgeSearch as _mcpTool_knowledge_search } from "../mcp-tools/knowledge";
import { knowledgeWrite as _mcpTool_knowledge_write } from "../mcp-tools/knowledge";
import { runArtifactContent as _mcpTool_run_artifact_content } from "../mcp-tools/run-artifacts";
import { runArtifactCreate as _mcpTool_run_artifact_create } from "../mcp-tools/run-artifacts";
import { runArtifacts as _mcpTool_run_artifacts } from "../mcp-tools/run-artifacts";
import { runCode as _mcpTool_run_code } from "../mcp-tools/run-code";
import { runEvents as _mcpTool_run_events } from "../mcp-tools/read-model";
import { runGet as _mcpTool_run_get } from "../mcp-tools/read-model";
import { runList as _mcpTool_run_list } from "../mcp-tools/read-model";
import { scheduleGet as _mcpTool_schedule_get } from "../mcp-tools/schedule-tools";
import { scheduleList as _mcpTool_schedule_list } from "../mcp-tools/schedule-tools";
import { scheduleTrigger as _mcpTool_schedule_trigger } from "../mcp-tools/schedule-tools";
import { taskCancel as _mcpTool_task_cancel } from "../mcp-tools/task-mutations";
import _mcpTool_task_create from "../mcp-tools/task-create";
import { taskDependencies as _mcpTool_task_dependencies } from "../mcp-tools/task-graph";
import { taskDependents as _mcpTool_task_dependents } from "../mcp-tools/task-graph";
import { taskGet as _mcpTool_task_get } from "../mcp-tools/read-model";
import { taskList as _mcpTool_task_list } from "../mcp-tools/read-model";
import { taskRetry as _mcpTool_task_retry } from "../mcp-tools/task-mutations";
import { taskUpdate as _mcpTool_task_update } from "../mcp-tools/task-mutations";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _mcpConfig from "../config/mcp";

export type * from "./entities.gen";
export type * from "./context.gen";

/**
 * Select/document type for a collection key — prefer over `Record<string, any>` for docs.
 */
export type CollectionDoc<K extends keyof AppCollections> = CollectionSelect<AppCollections[K]>;

/**
 * Select/document type for a global key.
 */
export type GlobalDoc<K extends keyof AppGlobals> = GlobalSelect<AppGlobals[K]>;

/**
 * Typed `where` filter for a collection key — prefer over `Record<string, unknown>`
 * when building a `where` clause dynamically before a `find`/`findOne` call.
 */
export type CollectionWhere<K extends keyof AppCollections> = Where<AppCollections[K], AppConfig>;

/**
 * Access-rule ctx for shared helpers. `K` narrows `data` to that collection's row.
 *
 * CYCLE RULE: import these only from files NOT imported by a collection
 * (routes, services, jobs, scripts). Helpers imported by collections take
 * the package-level `AccessContext` from "questpie" instead — see the
 * type-inference reference.
 *
 * @example
 * ```ts
 * export async function isOwner(ctx: AccessRuleContext<"posts">) {
 *   return ctx.data?.authorId === ctx.session?.user.id; // ctx.collections typed
 * }
 * ```
 */
export type AccessRuleContext<K extends keyof AppCollections | unknown = unknown> =
	AccessContext<K extends keyof AppCollections ? CollectionDoc<K> : unknown>;

/**
 * Hook ctx for shared helpers. `K` narrows `data` to that collection's row.
 * Same cycle rule as `AccessRuleContext`.
 */
export type HookRuleContext<K extends keyof AppCollections | unknown = unknown> =
	HookContext<K extends keyof AppCollections ? CollectionDoc<K> : unknown>;

/**
 * Flat config type for client APIs.
 * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.
 * For handler context, use `AppContext` (auto-typed via module augmentation).
 */
export type AppConfig = {
	collections: AppCollections;
	globals: AppGlobals;
	routes: AppRoutes;
	storage: (typeof _runtime)["storage"];
	auth: AppAuthConfig;
};

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

var _appPromise: Promise<unknown> | undefined;

_appPromise = createApp(
	({
		modules: _modules,
		collections: {
			activity: _coll_activity,
			admin_audit_log: _coll_admin_audit_log,
			agent_memory: _coll_agent_memory,
			assets: _coll_assets,
			chat_messages: _coll_chat_messages,
			chat_sessions: _coll_chat_sessions,
			document_store: _coll_document_store,
			environments: _coll_environments,
			memory_settings: _coll_memory_settings,
			models: _coll_models,
			projects: _coll_projects,
			providers: _coll_providers,
			run_links: _coll_run_links,
			schedule_executions: _coll_schedule_executions,
			schedules: _coll_schedules,
			scripts: _coll_scripts,
			secrets: _coll_secrets,
			task_relations: _coll_task_relations,
			tasks: _coll_tasks,
		},
		jobs: {
			chatTurnProducer: _job_chatTurnProducer,
			cleanup: _job_cleanup,
			scheduleTick: _job_scheduleTick,
			taskEscalation: _job_taskEscalation,
			taskTurnProducer: _job_taskTurnProducer,
		},
		routes: {
			"apps/[appId]/[fn]": _route_apps_appId_fn,
			"apps/[appId]/fs/[...path]": _route_apps_appId_fs_spread_path,
			"apps/[appId]/token": _route_apps_appId_token,
			chat: _route_chat,
			"chat/[chatId]/approve": _route_chat_chatId_approve,
			"chat/[chatId]/cancel": _route_chat_chatId_cancel,
			"chat/[chatId]/stream": _route_chat_chatId_stream,
			events: _route_events,
			intake: _route_intake,
			"runs/[runId]": _route_runs_runId,
			"runs/[runId]/artifacts": _route_runs_runId_artifacts,
			"runs/[runId]/artifacts/[artifactId]/content": _route_runs_runId_artifacts_artifactId_content,
			"runs/[runId]/events": _route_runs_runId_events,
			runStream: _route_runStream,
			"workspaceInspection/content": _route_workspaceInspection_content,
			"workspaceInspection/diff": _route_workspaceInspection_diff,
			"workspaceInspection/list": _route_workspaceInspection_list,
			"workspaceInspection/read": _route_workspaceInspection_read,
		},
		services: {
			gitProviderAdapters: _svc_gitProviderAdapters,
			knowledgeResource: _svc_knowledgeResource,
		},
		migrations: [_mig_20260507T095449_jolly_red_phoenix, _mig_20260516T185000_auth_user_admin_columns_repair, _mig_20260517T095535_happy_orange_unicorn, _mig_20260519T135407_add_run_links_and_ai_module, _mig_20260519T142100_backfill_legacy_runs_into_run_links, _mig_20260519T145500_link_schedule_executions_to_run_links, _mig_20260519T161500_drop_legacy_execution_infra, _mig_20260529T001500_drop_workflow_configs, _mig_20260529T003000_drop_capabilities, _mig_20260604T111500_add_api_key_config_id, _mig_20260606T003509_v2_schema, _mig_20260606T004300_autopilot_memories, _mig_20260606T170505_calm_yellow_panda, _mig_20260607T120000_add_ai_runs_system_prompt, _mig_20260607T130000_make_assets_upload_cols_nullable, _mig_20260614T120000_add_harness_resumable_fields, _mig_20260630T202927_add_run_link_worker_kind_finalize],
		seeds: [_seed_demoCoverageData, _seed_demoParentIssues, _seed_demoProductData, _seed_demoStressData, _seed_makeAMiniappSkill, _seed_runtimeDefaults, _seed_socialSchedulerApp],
		views: {
			fileDetail: _view_fileDetail,
			filesView: _view_filesView,
			taskDetail: _view_taskDetail,
		},
		workflows: {
			[_wf_taskPipeline.name]: _wf_taskPipeline,
		},
		mcpTools: {
			artifact_create: _mcpTool_artifact_create,
			knowledge_delete: _mcpTool_knowledge_delete,
			knowledge_list: _mcpTool_knowledge_list,
			knowledge_read: _mcpTool_knowledge_read,
			knowledge_search: _mcpTool_knowledge_search,
			knowledge_write: _mcpTool_knowledge_write,
			run_artifact_content: _mcpTool_run_artifact_content,
			run_artifact_create: _mcpTool_run_artifact_create,
			run_artifacts: _mcpTool_run_artifacts,
			run_code: _mcpTool_run_code,
			run_events: _mcpTool_run_events,
			run_get: _mcpTool_run_get,
			run_list: _mcpTool_run_list,
			schedule_get: _mcpTool_schedule_get,
			schedule_list: _mcpTool_schedule_list,
			schedule_trigger: _mcpTool_schedule_trigger,
			task_cancel: _mcpTool_task_cancel,
			task_create: _mcpTool_task_create,
			task_dependencies: _mcpTool_task_dependencies,
			task_dependents: _mcpTool_task_dependents,
			task_get: _mcpTool_task_get,
			task_list: _mcpTool_task_list,
			task_retry: _mcpTool_task_retry,
			task_update: _mcpTool_task_update,
		},
		config: {
			app: _appConfig,
			auth: _authConfig,
			admin: _adminConfig,
			mcp: _mcpConfig,
		},
	}) satisfies AppDefinition,
	_runtime,
);

export const app = (await _appPromise) as unknown as _AppQuestpie;

/** Fully typed QUESTPIE app instance. */
export type App = typeof app;

// ── createContext — typed context for scripts ──────────────
/**
 * Create a typed AppContext for use in scripts, tests, or standalone code.
 * Resolves all services and provides flat access to infrastructure.
 *
 * @example
 * ```ts
 * import { createContext } from "#questpie";
 *
 * const ctx = await createContext();
 * const posts = await ctx.collections.posts.find({});
 * ```
 */
export async function createContext(
	options?: Parameters<ReturnType<typeof createContextFactory>>[0],
) {
	while (!_appPromise) {
		await new Promise((resolve) => setTimeout(resolve, 0));
	}

	return createContextFactory((await _appPromise) as _AppQuestpie)(options);
}

// Factories: import { collection, global, ... } from '#questpie/factories';
