/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { aiRunEventsCollection as _coll_ai_run_events } from "../collections/ai-run-events";
import { aiRunsCollection as _coll_ai_runs } from "../collections/ai-runs";
import { aiWorkerLeasesCollection as _coll_ai_worker_leases } from "../collections/ai-worker-leases";
import { aiWorkersCollection as _coll_ai_workers } from "../collections/ai-workers";

// ── Jobs ────────────────────────────────────────────
import _job_workerTimeout from "../jobs/worker-timeout";

// ── Routes ────────────────────────────────────────────
import _route_enrollmentEnroll from "../routes/enrollment-enroll";
import _route_enrollmentTokens from "../routes/enrollment-tokens";
import _route_runComplete from "../routes/run-complete";
import _route_runEvents from "../routes/run-events";
import _route_runStream from "../routes/run-stream";
import _route_workerDeregister from "../routes/worker-deregister";
import _route_workerHeartbeat from "../routes/worker-heartbeat";
import _route_workerPoll from "../routes/worker-poll";
import _route_workerRegister from "../routes/worker-register";

// ── Services ────────────────────────────────────────────
import _svc_workerManager from "../services/worker-manager";

// ── Singles ────────────────────────────────────────────────
import _adminConfig from "../config/admin";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { RouteDefinition, RouteParamsFromKey } from "questpie/types";

export type AiCollections = {
	ai_run_events: typeof _coll_ai_run_events;
	ai_runs: typeof _coll_ai_runs;
	ai_worker_leases: typeof _coll_ai_worker_leases;
	ai_workers: typeof _coll_ai_workers;
};

export type AiGlobals = Record<never, never>;

export type AiJobs = {
	workerTimeout: Omit<typeof _job_workerTimeout, "handler"> & { handler: (args: unknown) => Promise<unknown> };
};

export type AiRoutes = {
	enrollmentEnroll: typeof _route_enrollmentEnroll extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"enrollmentEnroll">> : typeof _route_enrollmentEnroll;
	enrollmentTokens: typeof _route_enrollmentTokens extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"enrollmentTokens">> : typeof _route_enrollmentTokens;
	runComplete: typeof _route_runComplete extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"runComplete">> : typeof _route_runComplete;
	runEvents: typeof _route_runEvents extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"runEvents">> : typeof _route_runEvents;
	runStream: typeof _route_runStream extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"runStream">> : typeof _route_runStream;
	workerDeregister: typeof _route_workerDeregister extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"workerDeregister">> : typeof _route_workerDeregister;
	workerHeartbeat: typeof _route_workerHeartbeat extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"workerHeartbeat">> : typeof _route_workerHeartbeat;
	workerPoll: typeof _route_workerPoll extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"workerPoll">> : typeof _route_workerPoll;
	workerRegister: typeof _route_workerRegister extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"workerRegister">> : typeof _route_workerRegister;
};

export type AiFieldTypes = Record<never, never>;

export type AiViews = Record<never, never>;

export type AiComponents = Record<never, never>;

export type AiBlocks = Record<never, never>;

export type AiServices = {
	workerManager: typeof _svc_workerManager;
};

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type AiModule = {
	name: "questpie-ai";
	collections: AiCollections;
	jobs: AiJobs;
	routes: AiRoutes;
	services: AiServices;
	globals: AiGlobals;
	fieldTypes: AiFieldTypes;
	views: AiViews;
	components: AiComponents;
	blocks: AiBlocks;
	messages: Record<never, never>;
	emails: Record<never, never>;
	migrations: readonly unknown[];
	seeds: readonly unknown[];
	config: {
		admin: typeof _adminConfig;
	};
};

const _module: AiModule = {
	name: "questpie-ai" as const,
	collections: {
		ai_run_events: _coll_ai_run_events,
		ai_runs: _coll_ai_runs,
		ai_worker_leases: _coll_ai_worker_leases,
		ai_workers: _coll_ai_workers,
	} as AiCollections,
	jobs: {
		workerTimeout: _job_workerTimeout,
	} as AiJobs,
	routes: {
		enrollmentEnroll: _route_enrollmentEnroll,
		enrollmentTokens: _route_enrollmentTokens,
		runComplete: _route_runComplete,
		runEvents: _route_runEvents,
		runStream: _route_runStream,
		workerDeregister: _route_workerDeregister,
		workerHeartbeat: _route_workerHeartbeat,
		workerPoll: _route_workerPoll,
		workerRegister: _route_workerRegister,
	} as AiRoutes,
	services: {
		workerManager: _svc_workerManager,
	} as AiServices,
	globals: {},
	messages: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	views: {},
	components: {},
	blocks: {},
	config: {
		admin: _adminConfig,
	},
};

export default _module;
