import { mcpOAuthScopeCatalog } from "../../oauth-scope-catalog.js";
/**
 * MCP Module
 *
 * Backend module for the QUESTPIE Model Context Protocol endpoint.
 *
 * Exports:
 * - `mcpModule` — static module definition (generated by codegen from file convention)
 * - `McpModule` — type of the static module
 */
import generatedModule from "./.generated/module.js";

export type {
	McpCollections,
	McpFieldTypes,
	McpGlobals,
	McpJobs,
	McpMcpTools,
	McpRoutes,
} from "./.generated/module.js";

export type McpModule = typeof mcpModule;

export const mcpModule = {
	...generatedModule,
	oauthScopeCatalogs: {
		mcp: mcpOAuthScopeCatalog,
	},
} as const;

export default mcpModule;
