/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Routes ────────────────────────────────────────────
import _route_mcp from "../routes/mcp";
import _route_mcp_DELETE from "../routes/mcp.delete";
import _route_mcp_GET from "../routes/mcp.get";
import _route_mcp_OPTIONS from "../routes/mcp.options";

// ── Singles ────────────────────────────────────────────────
import _plugin from "../plugin";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { RouteDefinition, RouteParamsFromKey } from "questpie/types";

export type McpCollections = Record<never, never>;

export type McpChannels = Record<never, never>;

export type McpGlobals = Record<never, never>;

export type McpJobs = Record<never, never>;

export type McpRoutes = {
	mcp: typeof _route_mcp extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"mcp">> : typeof _route_mcp;
	"mcp:DELETE": typeof _route_mcp_DELETE extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"mcp:DELETE">> : typeof _route_mcp_DELETE;
	"mcp:GET": typeof _route_mcp_GET extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"mcp:GET">> : typeof _route_mcp_GET;
	"mcp:OPTIONS": typeof _route_mcp_OPTIONS extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"mcp:OPTIONS">> : typeof _route_mcp_OPTIONS;
};

export type McpFieldTypes = Record<never, never>;

export type McpMcpTools = Record<never, never>;

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type McpModule = {
	name: "questpie-mcp";
	routes: McpRoutes;
	collections: McpCollections;
	channels: McpChannels;
	globals: McpGlobals;
	jobs: McpJobs;
	fieldTypes: McpFieldTypes;
	mcpTools: McpMcpTools;
	messages: Record<never, never>;
	services: Record<never, never>;
	emails: Record<never, never>;
	migrations: readonly unknown[];
	seeds: readonly unknown[];
	plugin: typeof _plugin;
};

const _module: McpModule = {
	name: "questpie-mcp" as const,
	routes: {
		mcp: _route_mcp,
		"mcp:DELETE": _route_mcp_DELETE,
		"mcp:GET": _route_mcp_GET,
		"mcp:OPTIONS": _route_mcp_OPTIONS,
	} as McpRoutes,
	collections: {},
	channels: {},
	globals: {},
	jobs: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	mcpTools: {},
	plugin: _plugin,
};

export default _module;
