/** Generated from a live PostgreSQL catalog after applying `internalProtocolV7Sql`. */

export const internalProtocolV7ConstraintsB = [
	[
		"observed_dependency_plans",
		"dependency_plan_digest_sha256",
		"c",
		"CHECK (plan_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"observed_dependency_plans",
		"observed_dependency_plans_application_name_scope_identity__fkey",
		"f",
		"FOREIGN KEY (application_name, scope_identity, binding_identity, deployment_digest, authority_partition_digest, query_identity, input_digest, wire_version) REFERENCES questpie_internal.realtime_watch_bindings(application_name, scope_identity, binding_identity, deployment_digest, authority_partition_digest, query_identity, input_digest, wire_version) ON DELETE CASCADE",
	],
	[
		"observed_dependency_plans",
		"observed_dependency_plans_pkey",
		"p",
		"PRIMARY KEY (application_name, scope_identity, binding_identity)",
	],
	[
		"processed_change_facts",
		"processed_change_facts_application_name_consumer_id_fkey",
		"f",
		"FOREIGN KEY (application_name, consumer_id) REFERENCES questpie_internal.reconciliation_consumers(application_name, consumer_id) ON DELETE CASCADE",
	],
	[
		"processed_change_facts",
		"processed_change_facts_application_name_fact_identity_fkey",
		"f",
		"FOREIGN KEY (application_name, fact_identity) REFERENCES questpie_internal.change_ledger(application_name, fact_identity) ON DELETE CASCADE",
	],
	[
		"processed_change_facts",
		"processed_change_facts_pkey",
		"p",
		"PRIMARY KEY (application_name, consumer_id, fact_identity)",
	],
	[
		"protocol",
		"protocol_checksum_sha256",
		"c",
		"CHECK (checksum ~ '^[0-9a-f]{64}$'::text)",
	],
	["protocol", "protocol_pkey", "p", "PRIMARY KEY (singleton)"],
	["protocol", "protocol_singleton_true", "c", "CHECK (singleton)"],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_ack_shape",
		"c",
		"CHECK (ack_slot IS NULL AND acknowledged_at IS NULL OR ack_slot = 1 AND acknowledged_at IS NOT NULL)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_authority_sha256",
		"c",
		"CHECK (authority_partition_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_delivery_known",
		"c",
		"CHECK (delivery_kind = ANY (ARRAY['initial'::text, 'reset'::text, 'update'::text]))",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_dependency_bounded",
		"c",
		"CHECK (octet_length(dependency_plan_bytes) <= 262144)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_deployment_sha256",
		"c",
		"CHECK (deployment_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_input_sha256",
		"c",
		"CHECK (input_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_latest_slot",
		"c",
		"CHECK (latest_slot IS NULL OR latest_slot = 1)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_positive",
		"c",
		"CHECK (generation > 0)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_reset_shape",
		"c",
		"CHECK (delivery_kind = 'reset'::text AND (reset_reason = ANY (ARRAY['authority-changed'::text, 'deployment-changed'::text, 'resume-unavailable'::text])) OR delivery_kind <> 'reset'::text AND reset_reason IS NULL)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_result_bounded",
		"c",
		"CHECK (octet_length(result_bytes) <= 1048576)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_token_digest_sha256",
		"c",
		"CHECK (token_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generation_wire_positive",
		"c",
		"CHECK (wire_version > 0)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generations_application_name_scope_identi_fkey",
		"f",
		"FOREIGN KEY (application_name, scope_identity, binding_identity, deployment_digest, authority_partition_digest, query_identity, input_digest, wire_version) REFERENCES questpie_internal.realtime_watch_bindings(application_name, scope_identity, binding_identity, deployment_digest, authority_partition_digest, query_identity, input_digest, wire_version) ON DELETE CASCADE",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generations_pkey",
		"p",
		"PRIMARY KEY (application_name, scope_identity, binding_identity, generation)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_attachment_binding_key",
		"u",
		"UNIQUE (application_name, scope_identity, deployment_digest, authority_partition_digest, principal_kind, principal_id)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_attachments_pkey",
		"p",
		"PRIMARY KEY (application_name, scope_identity)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_authority_digest_sha256",
		"c",
		"CHECK (authority_partition_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_deployment_digest_sha256",
		"c",
		"CHECK (deployment_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_expiry_exact",
		"c",
		"CHECK (expires_at = (renewed_at + '00:00:30'::interval))",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_holder_generation_positive",
		"c",
		"CHECK (holder_generation > 0)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_identity_bounded",
		"c",
		"CHECK (length(scope_identity) >= 1 AND length(scope_identity) <= 256 AND octet_length(scope_identity) <= 1024)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_lifecycle_shape",
		"c",
		"CHECK (renewed_at >= opened_at AND (state = 'attached'::text AND authority_partition_digest IS NULL AND withdrawn_at IS NULL OR state = 'open'::text AND authority_partition_digest IS NOT NULL AND withdrawn_at IS NULL OR state = 'withdrawn'::text AND withdrawn_at IS NOT NULL AND withdrawn_at >= opened_at))",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_principal_id_bounded",
		"c",
		"CHECK (length(principal_id) >= 1 AND length(principal_id) <= 1024 AND octet_length(principal_id) <= 4096)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_principal_kind_known",
		"c",
		"CHECK (principal_kind = ANY (ARRAY['anonymous'::text, 'service'::text, 'user'::text]))",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_state_known",
		"c",
		"CHECK (state = ANY (ARRAY['attached'::text, 'open'::text, 'withdrawn'::text]))",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_active_slot_bounded",
		"c",
		"CHECK (active_slot IS NULL OR active_slot >= 1 AND active_slot <= 64)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_authority_digest_sha256",
		"c",
		"CHECK (authority_partition_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_authority_key",
		"u",
		"UNIQUE (application_name, scope_identity, binding_identity, deployment_digest, authority_partition_digest, query_identity, input_digest, wire_version)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_deployment_digest_sha256",
		"c",
		"CHECK (deployment_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_identity_bounded",
		"c",
		"CHECK (length(binding_identity) >= 1 AND length(binding_identity) <= 256 AND octet_length(binding_identity) <= 1024)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_input_digest_sha256",
		"c",
		"CHECK (input_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_invalidation_order",
		"c",
		"CHECK (evaluated_invalidation_generation >= 0 AND evaluated_invalidation_generation <= invalidation_generation)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_lifecycle_shape",
		"c",
		"CHECK (state = 'open'::text AND active_slot IS NOT NULL AND withdrawn_at IS NULL OR state = 'withdrawn'::text AND active_slot IS NULL AND withdrawn_at IS NOT NULL AND withdrawn_at >= opened_at)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_payload_bounded",
		"c",
		"CHECK ((octet_length(query_bytes) + octet_length(input_bytes) + octet_length(context_input_bytes)) <= 1048576)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_principal_id_bounded",
		"c",
		"CHECK (length(principal_id) >= 1 AND length(principal_id) <= 1024 AND octet_length(principal_id) <= 4096)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_principal_kind_known",
		"c",
		"CHECK (principal_kind = ANY (ARRAY['anonymous'::text, 'service'::text, 'user'::text]))",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_query_identity_bounded",
		"c",
		"CHECK (length(query_identity) >= 1 AND length(query_identity) <= 256 AND octet_length(query_identity) <= 1024)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_resume_shape",
		"c",
		"CHECK (NOT resume_requested AND requested_resume_token IS NULL OR resume_requested AND requested_resume_token IS NOT NULL AND length(requested_resume_token) >= 1 AND octet_length(requested_resume_token) <= 4096)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_scope_fkey",
		"f",
		"FOREIGN KEY (application_name, scope_identity, deployment_digest, authority_partition_digest, principal_kind, principal_id) REFERENCES questpie_internal.realtime_scope_attachments(application_name, scope_identity, deployment_digest, authority_partition_digest, principal_kind, principal_id) ON DELETE CASCADE",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_state_known",
		"c",
		"CHECK (state = ANY (ARRAY['open'::text, 'withdrawn'::text]))",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_wire_version_positive",
		"c",
		"CHECK (wire_version > 0)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_bindings_pkey",
		"p",
		"PRIMARY KEY (application_name, scope_identity, binding_identity)",
	],
	[
		"reconciliation_consumers",
		"reconciliation_consumers_pkey",
		"p",
		"PRIMARY KEY (application_name, consumer_id)",
	],
	[
		"retained_live_query_results",
		"retained_age_exact",
		"c",
		"CHECK (expires_at = (created_at + '24:00:00'::interval))",
	],
	[
		"retained_live_query_results",
		"retained_authority_digest_sha256",
		"c",
		"CHECK (authority_partition_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"retained_live_query_results",
		"retained_dependency_bytes_bounded",
		"c",
		"CHECK (octet_length(dependency_plan_bytes) <= 262144)",
	],
	[
		"retained_live_query_results",
		"retained_deployment_digest_sha256",
		"c",
		"CHECK (deployment_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"retained_live_query_results",
		"retained_expiry_order",
		"c",
		"CHECK (expires_at > created_at)",
	],
	[
		"retained_live_query_results",
		"retained_generation_positive",
		"c",
		"CHECK (retained_generation > 0)",
	],
	[
		"retained_live_query_results",
		"retained_input_digest_sha256",
		"c",
		"CHECK (input_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"retained_live_query_results",
		"retained_live_query_results_pkey",
		"p",
		"PRIMARY KEY (application_name, token_digest)",
	],
	[
		"retained_live_query_results",
		"retained_result_bytes_bounded",
		"c",
		"CHECK (octet_length(result_bytes) <= 1048576)",
	],
	[
		"retained_live_query_results",
		"retained_token_digest_sha256",
		"c",
		"CHECK (token_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"retained_live_query_results",
		"retained_wire_version_positive",
		"c",
		"CHECK (wire_version > 0)",
	],
	[
		"schema_migration_receipts",
		"migration_base_digest_sha256",
		"c",
		"CHECK (base_schema_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"schema_migration_receipts",
		"migration_checksum_sha256",
		"c",
		"CHECK (checksum ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"schema_migration_receipts",
		"migration_sequence_positive",
		"c",
		"CHECK (sequence > 0)",
	],
	[
		"schema_migration_receipts",
		"migration_target_digest_sha256",
		"c",
		"CHECK (target_schema_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"schema_migration_receipts",
		"schema_migration_receipts_application_name_sequence_key",
		"u",
		"UNIQUE (application_name, sequence)",
	],
	[
		"schema_migration_receipts",
		"schema_migration_receipts_pkey",
		"p",
		"PRIMARY KEY (application_name, migration_identity)",
	],
	[
		"seed_attempt_events",
		"seed_attempt_checksum_sha256",
		"c",
		"CHECK (checksum ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"seed_attempt_events",
		"seed_attempt_event_known",
		"c",
		"CHECK (event = ANY (ARRAY['started'::text, 'succeeded'::text, 'failed'::text, 'interrupted'::text, 'alreadyApplied'::text, 'blocked'::text]))",
	],
	[
		"seed_attempt_events",
		"seed_attempt_events_pkey",
		"p",
		"PRIMARY KEY (application_name, attempt_id, sequence)",
	],
	[
		"seed_attempt_events",
		"seed_attempt_sequence_nonnegative",
		"c",
		"CHECK (sequence >= 0)",
	],
	[
		"seed_receipts",
		"seed_applied_digest_sha256",
		"c",
		"CHECK (applied_schema_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"seed_receipts",
		"seed_checksum_sha256",
		"c",
		"CHECK (checksum ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"seed_receipts",
		"seed_receipts_pkey",
		"p",
		"PRIMARY KEY (application_name, seed_identity)",
	],
] as const;
