/** Candidate protocol delta generated from its isolated PostgreSQL 17 catalog. */
export const internalProtocolV9Constraints = [
	[
		"durable_run_events",
		"durable_event_error_code_known",
		"c",
		"CHECK (error_code IS NULL OR (error_code = ANY (ARRAY['CHECKPOINT_INVALID'::text, 'EFFECT_AMBIGUOUS'::text, 'EFFECT_CONFLICT'::text, 'HANDLER_FAILED'::text, 'REACTION_ERROR'::text, 'RESOURCE_LIMIT'::text, 'RETRY_EXHAUSTED'::text, 'RUN_AS_DENIED'::text, 'VALIDATION_FAILED'::text])))",
	],
	[
		"durable_runs",
		"durable_run_failure_code_known",
		"c",
		"CHECK (failure_code IS NULL OR (failure_code = ANY (ARRAY['CHECKPOINT_INVALID'::text, 'EFFECT_AMBIGUOUS'::text, 'EFFECT_CONFLICT'::text, 'HANDLER_FAILED'::text, 'REACTION_ERROR'::text, 'RESOURCE_LIMIT'::text, 'RETRY_EXHAUSTED'::text, 'RUN_AS_DENIED'::text, 'VALIDATION_FAILED'::text])))",
	],
	[
		"mutation_checkpoints",
		"checkpoint_call_bounded",
		"c",
		"CHECK (length(call_id) >= 1 AND length(call_id) <= 256)",
	],
	[
		"mutation_checkpoints",
		"checkpoint_command_digest",
		"c",
		"CHECK (command_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"mutation_checkpoints",
		"checkpoint_contract_digest",
		"c",
		"CHECK (contract_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"mutation_checkpoints",
		"checkpoint_input_digest",
		"c",
		"CHECK (input_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"mutation_checkpoints",
		"checkpoint_name_bounded",
		"c",
		"CHECK (checkpoint_name ~ '^[A-Za-z0-9_-]{1,64}$'::text)",
	],
	[
		"mutation_checkpoints",
		"checkpoint_ordinal_bounded",
		"c",
		"CHECK (ordinal >= 1 AND ordinal <= 64)",
	],
	[
		"mutation_checkpoints",
		"checkpoint_principal_kind",
		"c",
		"CHECK (principal_kind = ANY (ARRAY['anonymous'::text, 'service'::text, 'user'::text]))",
	],
	[
		"mutation_checkpoints",
		"checkpoint_receipt_shape",
		"c",
		"CHECK (state = 'reserved'::text AND receipt_transaction_id IS NULL AND receipt_result_digest IS NULL OR state = 'completed'::text AND receipt_transaction_id IS NOT NULL AND receipt_result_digest IS NOT NULL)",
	],
	[
		"mutation_checkpoints",
		"checkpoint_result_digest",
		"c",
		"CHECK (receipt_result_digest IS NULL OR receipt_result_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"mutation_checkpoints",
		"checkpoint_runtime_graph_digest",
		"c",
		"CHECK (runtime_graph_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"mutation_checkpoints",
		"checkpoint_state",
		"c",
		"CHECK (state = ANY (ARRAY['reserved'::text, 'completed'::text]))",
	],
	[
		"mutation_checkpoints",
		"mutation_checkpoints_application_name_run_id_checkpoint_nam_key",
		"u",
		"UNIQUE (application_name, run_id, checkpoint_name)",
	],
	[
		"mutation_checkpoints",
		"mutation_checkpoints_application_name_run_id_fkey",
		"f",
		"FOREIGN KEY (application_name, run_id) REFERENCES questpie_internal.durable_runs(application_name, run_id) ON DELETE CASCADE",
	],
	[
		"mutation_checkpoints",
		"mutation_checkpoints_pkey",
		"p",
		"PRIMARY KEY (application_name, run_id, ordinal)",
	],
	[
		"schedule_activations",
		"schedule_activations_application_name_accepted_revision_key",
		"u",
		"UNIQUE (application_name, accepted_revision)",
	],
	[
		"schedule_activations",
		"schedule_activations_application_name_target_digest_fkey",
		"f",
		"FOREIGN KEY (application_name, target_digest) REFERENCES questpie_internal.schedule_catalogs(application_name, target_digest)",
	],
	[
		"schedule_activations",
		"schedule_activations_check",
		"c",
		"CHECK (accepted_revision = (expected_revision + 1))",
	],
	[
		"schedule_activations",
		"schedule_activations_expected_revision_check",
		"c",
		"CHECK (expected_revision >= 0)",
	],
	[
		"schedule_activations",
		"schedule_activations_pkey",
		"p",
		"PRIMARY KEY (application_name, request_identity)",
	],
	[
		"schedule_activations",
		"schedule_activations_request_identity_check",
		"c",
		"CHECK (request_identity ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"schedule_catalogs",
		"schedule_catalogs_canonical_json_check",
		"c",
		"CHECK (octet_length(canonical_json) <= 262144)",
	],
	[
		"schedule_catalogs",
		"schedule_catalogs_pkey",
		"p",
		"PRIMARY KEY (application_name, target_digest)",
	],
	[
		"schedule_catalogs",
		"schedule_catalogs_target_digest_check",
		"c",
		"CHECK (target_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"schedule_frontiers",
		"schedule_frontiers_application_name_fkey",
		"f",
		"FOREIGN KEY (application_name) REFERENCES questpie_internal.schedule_heads(application_name)",
	],
	[
		"schedule_frontiers",
		"schedule_frontiers_pkey",
		"p",
		"PRIMARY KEY (application_name, job_identity)",
	],
	[
		"schedule_frontiers",
		"schedule_frontiers_program_digest_check",
		"c",
		"CHECK (program_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"schedule_heads",
		"schedule_heads_check",
		"c",
		"CHECK (revision = 0 AND target_digest IS NULL AND activated_at IS NULL OR revision > 0 AND target_digest ~ '^[0-9a-f]{64}$'::text AND activated_at IS NOT NULL)",
	],
	[
		"schedule_heads",
		"schedule_heads_pkey",
		"p",
		"PRIMARY KEY (application_name)",
	],
	[
		"schedule_heads",
		"schedule_heads_revision_check",
		"c",
		"CHECK (revision >= 0)",
	],
	[
		"schedule_ticks",
		"schedule_ticks_application_name_accepted_revision_fkey",
		"f",
		"FOREIGN KEY (application_name, accepted_revision) REFERENCES questpie_internal.schedule_activations(application_name, accepted_revision)",
	],
	[
		"schedule_ticks",
		"schedule_ticks_application_name_run_id_fkey",
		"f",
		"FOREIGN KEY (application_name, run_id) REFERENCES questpie_internal.durable_runs(application_name, run_id)",
	],
	[
		"schedule_ticks",
		"schedule_ticks_pkey",
		"p",
		"PRIMARY KEY (application_name, job_identity, scheduled_minute)",
	],
	[
		"schedule_ticks",
		"schedule_ticks_program_digest_check",
		"c",
		"CHECK (program_digest ~ '^[0-9a-f]{64}$'::text)",
	],
] as const;
