const internalProtocolV3RealtimeTables = [
	"observed_dependency_plans",
	"realtime_binding_generations",
	"realtime_scope_attachments",
	"realtime_watch_bindings",
] as const;

const internalProtocolV3RealtimeColumns = [
	["realtime_scope_attachments", "application_name", "text", true],
	["realtime_scope_attachments", "scope_identity", "text", true],
	["realtime_scope_attachments", "deployment_digest", "text", true],
	["realtime_scope_attachments", "authority_partition_digest", "text", false],
	["realtime_scope_attachments", "principal_kind", "text", true],
	["realtime_scope_attachments", "principal_id", "text", true],
	["realtime_scope_attachments", "holder_generation", "bigint", true],
	["realtime_scope_attachments", "opened_at", "timestamp with time zone", true],
	[
		"realtime_scope_attachments",
		"renewed_at",
		"timestamp with time zone",
		true,
	],
	[
		"realtime_scope_attachments",
		"expires_at",
		"timestamp with time zone",
		true,
	],
	["realtime_scope_attachments", "state", "text", true],
	[
		"realtime_scope_attachments",
		"withdrawn_at",
		"timestamp with time zone",
		false,
	],
	["realtime_watch_bindings", "application_name", "text", true],
	["realtime_watch_bindings", "scope_identity", "text", true],
	["realtime_watch_bindings", "binding_identity", "text", true],
	["realtime_watch_bindings", "deployment_digest", "text", true],
	["realtime_watch_bindings", "authority_partition_digest", "text", true],
	["realtime_watch_bindings", "principal_kind", "text", true],
	["realtime_watch_bindings", "principal_id", "text", true],
	["realtime_watch_bindings", "active_slot", "smallint", false],
	["realtime_watch_bindings", "query_identity", "text", true],
	["realtime_watch_bindings", "query_bytes", "bytea", true],
	["realtime_watch_bindings", "input_bytes", "bytea", true],
	["realtime_watch_bindings", "input_digest", "text", true],
	["realtime_watch_bindings", "context_input_bytes", "bytea", true],
	["realtime_watch_bindings", "wire_version", "integer", true],
	["realtime_watch_bindings", "resume_requested", "boolean", true],
	["realtime_watch_bindings", "requested_resume_token", "text", false],
	["realtime_watch_bindings", "opened_at", "timestamp with time zone", true],
	["realtime_watch_bindings", "state", "text", true],
	[
		"realtime_watch_bindings",
		"withdrawn_at",
		"timestamp with time zone",
		false,
	],
	["realtime_watch_bindings", "invalidation_generation", "bigint", true],
	[
		"realtime_watch_bindings",
		"evaluated_invalidation_generation",
		"bigint",
		true,
	],
	[
		"realtime_watch_bindings",
		"invalidated_at",
		"timestamp with time zone",
		true,
	],
	["observed_dependency_plans", "application_name", "text", true],
	["observed_dependency_plans", "scope_identity", "text", true],
	["observed_dependency_plans", "binding_identity", "text", true],
	["observed_dependency_plans", "deployment_digest", "text", true],
	["observed_dependency_plans", "authority_partition_digest", "text", true],
	["observed_dependency_plans", "query_identity", "text", true],
	["observed_dependency_plans", "input_digest", "text", true],
	["observed_dependency_plans", "wire_version", "integer", true],
	["observed_dependency_plans", "retained_generation", "bigint", true],
	["observed_dependency_plans", "plan_digest", "text", true],
	["observed_dependency_plans", "plan_bytes", "bytea", true],
	[
		"observed_dependency_plans",
		"replaced_at",
		"timestamp with time zone",
		true,
	],
	["realtime_binding_generations", "application_name", "text", true],
	["realtime_binding_generations", "scope_identity", "text", true],
	["realtime_binding_generations", "binding_identity", "text", true],
	["realtime_binding_generations", "deployment_digest", "text", true],
	["realtime_binding_generations", "authority_partition_digest", "text", true],
	["realtime_binding_generations", "query_identity", "text", true],
	["realtime_binding_generations", "input_digest", "text", true],
	["realtime_binding_generations", "wire_version", "integer", true],
	["realtime_binding_generations", "generation", "bigint", true],
	["realtime_binding_generations", "token_digest", "text", true],
	["realtime_binding_generations", "result_bytes", "bytea", true],
	["realtime_binding_generations", "dependency_plan_bytes", "bytea", true],
	["realtime_binding_generations", "delivery_kind", "text", true],
	["realtime_binding_generations", "reset_reason", "text", false],
	["realtime_binding_generations", "latest_slot", "smallint", false],
	["realtime_binding_generations", "ack_slot", "smallint", false],
	[
		"realtime_binding_generations",
		"created_at",
		"timestamp with time zone",
		true,
	],
	[
		"realtime_binding_generations",
		"acknowledged_at",
		"timestamp with time zone",
		false,
	],
] as const;

export { internalProtocolV3RealtimeColumns, internalProtocolV3RealtimeTables };
