/** Candidate protocol delta generated from its isolated PostgreSQL 17 catalog. */
export const internalProtocolV9Columns = [
	["mutation_checkpoints", "application_name", "text", true],
	["mutation_checkpoints", "run_id", "uuid", true],
	["mutation_checkpoints", "ordinal", "smallint", true],
	["mutation_checkpoints", "checkpoint_name", "text", true],
	["mutation_checkpoints", "operation_name", "text", true],
	["mutation_checkpoints", "call_id", "text", true],
	["mutation_checkpoints", "command_digest", "text", true],
	["mutation_checkpoints", "input_digest", "text", true],
	["mutation_checkpoints", "contract_digest", "text", true],
	["mutation_checkpoints", "runtime_graph_digest", "text", true],
	["mutation_checkpoints", "tenant_id", "text", true],
	["mutation_checkpoints", "principal_kind", "text", true],
	["mutation_checkpoints", "principal_id", "text", true],
	["mutation_checkpoints", "state", "text", true],
	["mutation_checkpoints", "receipt_transaction_id", "xid8", false],
	["mutation_checkpoints", "receipt_result_digest", "text", false],
	["schedule_activations", "application_name", "text", true],
	["schedule_activations", "request_identity", "text", true],
	["schedule_activations", "expected_revision", "bigint", true],
	["schedule_activations", "target_digest", "text", true],
	["schedule_activations", "accepted_revision", "bigint", true],
	["schedule_activations", "activated_at", "timestamp with time zone", true],
	["schedule_catalogs", "application_name", "text", true],
	["schedule_catalogs", "target_digest", "text", true],
	["schedule_catalogs", "canonical_json", "text", true],
	["schedule_frontiers", "application_name", "text", true],
	["schedule_frontiers", "job_identity", "text", true],
	["schedule_frontiers", "program_digest", "text", true],
	["schedule_frontiers", "frontier_minute", "timestamp with time zone", true],
	["schedule_heads", "application_name", "text", true],
	["schedule_heads", "revision", "bigint", true],
	["schedule_heads", "target_digest", "text", false],
	["schedule_heads", "activated_at", "timestamp with time zone", false],
	["schedule_ticks", "application_name", "text", true],
	["schedule_ticks", "job_identity", "text", true],
	["schedule_ticks", "scheduled_minute", "timestamp with time zone", true],
	["schedule_ticks", "accepted_revision", "bigint", true],
	["schedule_ticks", "program_digest", "text", true],
	["schedule_ticks", "run_id", "uuid", true],
	["schedule_ticks", "accepted_at", "timestamp with time zone", true],
] as const;
