/** Generated from a live PostgreSQL catalog after applying `internalProtocolV4Sql`. */

export const internalProtocolV4Tables = [
	"durable_attempts",
	"durable_cancellations",
	"durable_effects",
	"durable_maintenance_commands",
	"durable_run_events",
	"durable_runs",
] as const;

export const internalProtocolV4ReplacedConstraints = [
	[
		"pending_reaction_intents",
		"reaction_intent_state_pending",
		"c",
		"CHECK (state = 'pending'::text)",
	],
] as const;

export const internalProtocolV4Columns = [
	["durable_attempts", "application_name", "text", true],
	["durable_attempts", "attempt_id", "uuid", true],
	["durable_attempts", "run_id", "uuid", true],
	["durable_attempts", "attempt_number", "integer", true],
	["durable_attempts", "worker_id", "text", true],
	["durable_attempts", "lease_token_digest", "text", true],
	["durable_attempts", "lease_expires_at", "timestamp with time zone", true],
	["durable_attempts", "deadline_at", "timestamp with time zone", true],
	["durable_attempts", "started_at", "timestamp with time zone", true],
	["durable_attempts", "heartbeat_at", "timestamp with time zone", true],
	["durable_attempts", "outcome", "text", false],
	["durable_attempts", "failure_code", "text", false],
	["durable_cancellations", "application_name", "text", true],
	["durable_cancellations", "cancellation_id", "uuid", true],
	["durable_cancellations", "run_id", "uuid", true],
	["durable_cancellations", "requested_by_kind", "text", true],
	["durable_cancellations", "requested_by_id", "text", true],
	["durable_cancellations", "reason", "text", true],
	["durable_cancellations", "requested_at", "timestamp with time zone", true],
	["durable_effects", "application_name", "text", true],
	["durable_effects", "run_id", "uuid", true],
	["durable_effects", "effect_name", "text", true],
	["durable_effects", "effect_id", "uuid", true],
	["durable_effects", "input_digest", "text", true],
	["durable_effects", "status", "text", true],
	["durable_effects", "receipt", "text", false],
	["durable_effects", "reserved_attempt_id", "uuid", true],
	["durable_effects", "settled_attempt_id", "uuid", false],
	["durable_effects", "reserved_at", "timestamp with time zone", true],
	["durable_effects", "settled_at", "timestamp with time zone", false],
	["durable_maintenance_commands", "application_name", "text", true],
	["durable_maintenance_commands", "command_id", "uuid", true],
	["durable_maintenance_commands", "run_id", "uuid", true],
	["durable_maintenance_commands", "command", "text", true],
	["durable_maintenance_commands", "outcome", "text", true],
	["durable_maintenance_commands", "rejection_code", "text", false],
	["durable_maintenance_commands", "actor_kind", "text", true],
	["durable_maintenance_commands", "actor_id", "text", true],
	["durable_maintenance_commands", "state_before", "text", true],
	["durable_maintenance_commands", "state_after", "text", true],
	[
		"durable_maintenance_commands",
		"requested_at",
		"timestamp with time zone",
		true,
	],
	["durable_run_events", "application_name", "text", true],
	["durable_run_events", "run_id", "uuid", true],
	["durable_run_events", "sequence", "integer", true],
	["durable_run_events", "occurred_at", "timestamp with time zone", true],
	["durable_run_events", "resource_identity", "text", true],
	["durable_run_events", "dispatch_id", "uuid", true],
	["durable_run_events", "attempt_id", "uuid", false],
	["durable_run_events", "lease_token_digest", "text", false],
	["durable_run_events", "causation_id", "text", true],
	["durable_run_events", "correlation_id", "text", true],
	["durable_run_events", "kind", "text", true],
	["durable_run_events", "error_code", "text", false],
	["durable_runs", "application_name", "text", true],
	["durable_runs", "run_id", "uuid", true],
	["durable_runs", "dispatch_id", "uuid", true],
	["durable_runs", "resource_identity", "text", true],
	["durable_runs", "tenant_id", "text", true],
	["durable_runs", "principal_kind", "text", true],
	["durable_runs", "principal_id", "text", true],
	["durable_runs", "run_as", "text", true],
	["durable_runs", "context_input_bytes", "bytea", true],
	["durable_runs", "payload_bytes", "bytea", true],
	["durable_runs", "retry_bytes", "bytea", true],
	["durable_runs", "runtime_build_digest", "text", true],
	["durable_runs", "executable_digest", "text", true],
	["durable_runs", "causation_kind", "text", true],
	["durable_runs", "causation_id", "text", true],
	["durable_runs", "correlation_id", "text", true],
	["durable_runs", "state", "text", true],
	["durable_runs", "attempt_count", "integer", true],
	["durable_runs", "current_attempt_id", "uuid", false],
	["durable_runs", "lease_token_digest", "text", false],
	["durable_runs", "lease_expires_at", "timestamp with time zone", false],
	["durable_runs", "available_at", "timestamp with time zone", true],
	["durable_runs", "horizon_at", "timestamp with time zone", true],
	["durable_runs", "cancellation_requested", "boolean", true],
	["durable_runs", "event_sequence", "integer", true],
	["durable_runs", "result_bytes", "bytea", false],
	["durable_runs", "failure_code", "text", false],
	["durable_runs", "dead_letter", "boolean", true],
	["durable_runs", "accepted_at", "timestamp with time zone", true],
	["durable_runs", "terminal_at", "timestamp with time zone", false],
] as const;

export const internalProtocolV4Constraints = [
	[
		"durable_attempts",
		"durable_attempt_failure_shape",
		"c",
		"CHECK (failure_code IS NULL OR outcome = 'failed'::text)",
	],
	[
		"durable_attempts",
		"durable_attempt_lease_digest_sha256",
		"c",
		"CHECK (lease_token_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"durable_attempts",
		"durable_attempt_number_bounded",
		"c",
		"CHECK (attempt_number >= 1 AND attempt_number <= 8)",
	],
	[
		"durable_attempts",
		"durable_attempt_number_unique",
		"u",
		"UNIQUE (application_name, run_id, attempt_number)",
	],
	[
		"durable_attempts",
		"durable_attempt_outcome_known",
		"c",
		"CHECK (outcome IS NULL OR (outcome = ANY (ARRAY['cancelled'::text, 'failed'::text, 'leaseSuperseded'::text, 'succeeded'::text])))",
	],
	[
		"durable_attempts",
		"durable_attempt_worker_bounded",
		"c",
		"CHECK (length(worker_id) >= 1 AND length(worker_id) <= 128)",
	],
	[
		"durable_attempts",
		"durable_attempts_application_name_run_id_fkey",
		"f",
		"FOREIGN KEY (application_name, run_id) REFERENCES questpie_internal.durable_runs(application_name, run_id) ON DELETE CASCADE",
	],
	[
		"durable_attempts",
		"durable_attempts_pkey",
		"p",
		"PRIMARY KEY (application_name, attempt_id)",
	],
	[
		"durable_cancellations",
		"durable_cancellation_actor_kind_known",
		"c",
		"CHECK (requested_by_kind = ANY (ARRAY['anonymous'::text, 'service'::text, 'user'::text]))",
	],
	[
		"durable_cancellations",
		"durable_cancellation_reason_bounded",
		"c",
		"CHECK (length(reason) >= 1 AND length(reason) <= 256)",
	],
	[
		"durable_cancellations",
		"durable_cancellation_run_unique",
		"u",
		"UNIQUE (application_name, run_id)",
	],
	[
		"durable_cancellations",
		"durable_cancellations_application_name_run_id_fkey",
		"f",
		"FOREIGN KEY (application_name, run_id) REFERENCES questpie_internal.durable_runs(application_name, run_id) ON DELETE CASCADE",
	],
	[
		"durable_cancellations",
		"durable_cancellations_pkey",
		"p",
		"PRIMARY KEY (application_name, cancellation_id)",
	],
	[
		"durable_effects",
		"durable_effect_identity_unique",
		"u",
		"UNIQUE (application_name, effect_id)",
	],
	[
		"durable_effects",
		"durable_effect_input_digest_sha256",
		"c",
		"CHECK (input_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"durable_effects",
		"durable_effect_name_bounded",
		"c",
		"CHECK (length(effect_name) >= 1 AND length(effect_name) <= 63)",
	],
	[
		"durable_effects",
		"durable_effect_receipt_bounded",
		"c",
		"CHECK (receipt IS NULL OR length(receipt) <= 256)",
	],
	[
		"durable_effects",
		"durable_effect_settled_shape",
		"c",
		"CHECK (status = 'succeeded'::text AND receipt IS NOT NULL AND settled_attempt_id IS NOT NULL AND settled_at IS NOT NULL OR status = 'acknowledged'::text AND receipt IS NULL AND settled_at IS NOT NULL OR (status = ANY (ARRAY['ambiguous'::text, 'pending'::text])) AND receipt IS NULL AND settled_at IS NULL)",
	],
	[
		"durable_effects",
		"durable_effect_status_known",
		"c",
		"CHECK (status = ANY (ARRAY['acknowledged'::text, 'ambiguous'::text, 'pending'::text, 'succeeded'::text]))",
	],
	[
		"durable_effects",
		"durable_effects_application_name_run_id_fkey",
		"f",
		"FOREIGN KEY (application_name, run_id) REFERENCES questpie_internal.durable_runs(application_name, run_id) ON DELETE CASCADE",
	],
	[
		"durable_effects",
		"durable_effects_pkey",
		"p",
		"PRIMARY KEY (application_name, run_id, effect_name)",
	],
	[
		"durable_maintenance_commands",
		"durable_command_actor_kind_known",
		"c",
		"CHECK (actor_kind = ANY (ARRAY['anonymous'::text, 'service'::text, 'user'::text]))",
	],
	[
		"durable_maintenance_commands",
		"durable_command_known",
		"c",
		"CHECK (command = ANY (ARRAY['acknowledgeAmbiguity'::text, 'cancelRun'::text, 'retryRun'::text]))",
	],
	[
		"durable_maintenance_commands",
		"durable_command_outcome_known",
		"c",
		"CHECK (outcome = ANY (ARRAY['applied'::text, 'rejected'::text]))",
	],
	[
		"durable_maintenance_commands",
		"durable_command_outcome_shape",
		"c",
		"CHECK (outcome = 'applied'::text AND rejection_code IS NULL OR outcome = 'rejected'::text AND rejection_code IS NOT NULL)",
	],
	[
		"durable_maintenance_commands",
		"durable_maintenance_commands_application_name_run_id_fkey",
		"f",
		"FOREIGN KEY (application_name, run_id) REFERENCES questpie_internal.durable_runs(application_name, run_id) ON DELETE CASCADE",
	],
	[
		"durable_maintenance_commands",
		"durable_maintenance_commands_pkey",
		"p",
		"PRIMARY KEY (application_name, command_id)",
	],
	[
		"durable_run_events",
		"durable_event_error_code_known",
		"c",
		"CHECK (error_code IS NULL OR (error_code = ANY (ARRAY['EFFECT_AMBIGUOUS'::text, 'EFFECT_CONFLICT'::text, 'HANDLER_FAILED'::text, 'REACTION_ERROR'::text, 'RESOURCE_LIMIT'::text, 'RETRY_EXHAUSTED'::text, 'RUN_AS_DENIED'::text, 'VALIDATION_FAILED'::text])))",
	],
	[
		"durable_run_events",
		"durable_event_kind_known",
		"c",
		"CHECK (kind = ANY (ARRAY['accepted'::text, 'ambiguityAcknowledged'::text, 'attemptStarted'::text, 'cancellationRequested'::text, 'cancelled'::text, 'effectAmbiguous'::text, 'effectSettled'::text, 'failed'::text, 'leaseSuperseded'::text, 'retryScheduled'::text, 'succeeded'::text]))",
	],
	[
		"durable_run_events",
		"durable_event_lease_digest_sha256",
		"c",
		"CHECK (lease_token_digest IS NULL OR lease_token_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"durable_run_events",
		"durable_event_sequence_bounded",
		"c",
		"CHECK (sequence >= 1 AND sequence <= 1024)",
	],
	[
		"durable_run_events",
		"durable_run_events_application_name_run_id_fkey",
		"f",
		"FOREIGN KEY (application_name, run_id) REFERENCES questpie_internal.durable_runs(application_name, run_id)",
	],
	[
		"durable_run_events",
		"durable_run_events_pkey",
		"p",
		"PRIMARY KEY (application_name, run_id, sequence)",
	],
	[
		"durable_runs",
		"durable_run_as_known",
		"c",
		"CHECK (run_as = 'caller'::text)",
	],
	[
		"durable_runs",
		"durable_run_attempt_count_bounded",
		"c",
		"CHECK (attempt_count >= 0 AND attempt_count <= 8)",
	],
	[
		"durable_runs",
		"durable_run_causation_kind_known",
		"c",
		"CHECK (causation_kind = 'mutationDispatch'::text)",
	],
	[
		"durable_runs",
		"durable_run_context_bytes_bounded",
		"c",
		"CHECK (octet_length(context_input_bytes) <= 262144)",
	],
	[
		"durable_runs",
		"durable_run_dispatch_unique",
		"u",
		"UNIQUE (application_name, dispatch_id)",
	],
	[
		"durable_runs",
		"durable_run_event_sequence_bounded",
		"c",
		"CHECK (event_sequence >= 0 AND event_sequence <= 1024)",
	],
	[
		"durable_runs",
		"durable_run_failure_code_known",
		"c",
		"CHECK (failure_code IS NULL OR (failure_code = ANY (ARRAY['EFFECT_AMBIGUOUS'::text, 'EFFECT_CONFLICT'::text, 'HANDLER_FAILED'::text, 'REACTION_ERROR'::text, 'RESOURCE_LIMIT'::text, 'RETRY_EXHAUSTED'::text, 'RUN_AS_DENIED'::text, 'VALIDATION_FAILED'::text])))",
	],
	[
		"durable_runs",
		"durable_run_failure_shape",
		"c",
		"CHECK (state = 'failed'::text AND failure_code IS NOT NULL OR state <> 'failed'::text AND NOT dead_letter)",
	],
	[
		"durable_runs",
		"durable_run_lease_digest_sha256",
		"c",
		"CHECK (lease_token_digest IS NULL OR lease_token_digest ~ '^[0-9a-f]{64}$'::text)",
	],
	[
		"durable_runs",
		"durable_run_lease_shape",
		"c",
		"CHECK (state = 'running'::text AND current_attempt_id IS NOT NULL AND lease_token_digest IS NOT NULL AND lease_expires_at IS NOT NULL OR state <> 'running'::text AND current_attempt_id IS NULL AND lease_token_digest IS NULL AND lease_expires_at IS NULL)",
	],
	[
		"durable_runs",
		"durable_run_payload_bytes_bounded",
		"c",
		"CHECK (octet_length(payload_bytes) <= 262144)",
	],
	[
		"durable_runs",
		"durable_run_principal_kind_known",
		"c",
		"CHECK (principal_kind = ANY (ARRAY['anonymous'::text, 'service'::text, 'user'::text]))",
	],
	[
		"durable_runs",
		"durable_run_result_bytes_bounded",
		"c",
		"CHECK (result_bytes IS NULL OR octet_length(result_bytes) <= 262144)",
	],
	[
		"durable_runs",
		"durable_run_result_shape",
		"c",
		"CHECK (state = 'succeeded'::text AND result_bytes IS NOT NULL AND failure_code IS NULL OR state <> 'succeeded'::text AND result_bytes IS NULL)",
	],
	[
		"durable_runs",
		"durable_run_retry_bytes_bounded",
		"c",
		"CHECK (octet_length(retry_bytes) <= 4096)",
	],
	[
		"durable_runs",
		"durable_run_state_known",
		"c",
		"CHECK (state = ANY (ARRAY['cancelled'::text, 'delayed'::text, 'failed'::text, 'ready'::text, 'running'::text, 'succeeded'::text]))",
	],
	[
		"durable_runs",
		"durable_run_terminal_shape",
		"c",
		"CHECK ((state = ANY (ARRAY['cancelled'::text, 'failed'::text, 'succeeded'::text])) AND terminal_at IS NOT NULL OR (state = ANY (ARRAY['delayed'::text, 'ready'::text, 'running'::text])) AND terminal_at IS NULL)",
	],
	[
		"durable_runs",
		"durable_runs_application_name_dispatch_id_fkey",
		"f",
		"FOREIGN KEY (application_name, dispatch_id) REFERENCES questpie_internal.pending_reaction_intents(application_name, record_id)",
	],
	[
		"durable_runs",
		"durable_runs_pkey",
		"p",
		"PRIMARY KEY (application_name, run_id)",
	],
	[
		"pending_reaction_intents",
		"reaction_intent_state_known",
		"c",
		"CHECK (state = ANY (ARRAY['accepted'::text, 'pending'::text]))",
	],
] as const;

export const internalProtocolV4Indexes = [
	[
		"durable_attempts",
		"durable_attempt_number_unique",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX durable_attempt_number_unique ON questpie_internal.durable_attempts USING btree (application_name, run_id, attempt_number)",
	],
	[
		"durable_attempts",
		"durable_attempts_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_attempts_pkey ON questpie_internal.durable_attempts USING btree (application_name, attempt_id)",
	],
	[
		"durable_cancellations",
		"durable_cancellation_run_unique",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX durable_cancellation_run_unique ON questpie_internal.durable_cancellations USING btree (application_name, run_id)",
	],
	[
		"durable_cancellations",
		"durable_cancellations_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_cancellations_pkey ON questpie_internal.durable_cancellations USING btree (application_name, cancellation_id)",
	],
	[
		"durable_effects",
		"durable_effect_identity_unique",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX durable_effect_identity_unique ON questpie_internal.durable_effects USING btree (application_name, effect_id)",
	],
	[
		"durable_effects",
		"durable_effects_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_effects_pkey ON questpie_internal.durable_effects USING btree (application_name, run_id, effect_name)",
	],
	[
		"durable_maintenance_commands",
		"durable_maintenance_commands_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_maintenance_commands_pkey ON questpie_internal.durable_maintenance_commands USING btree (application_name, command_id)",
	],
	[
		"durable_maintenance_commands",
		"durable_maintenance_commands_run_idx",
		"btree",
		false,
		false,
		"CREATE INDEX durable_maintenance_commands_run_idx ON questpie_internal.durable_maintenance_commands USING btree (application_name, run_id, requested_at)",
	],
	[
		"durable_run_events",
		"durable_run_events_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_run_events_pkey ON questpie_internal.durable_run_events USING btree (application_name, run_id, sequence)",
	],
	[
		"durable_runs",
		"durable_run_dispatch_unique",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX durable_run_dispatch_unique ON questpie_internal.durable_runs USING btree (application_name, dispatch_id)",
	],
	[
		"durable_runs",
		"durable_runs_claim_idx",
		"btree",
		false,
		false,
		"CREATE INDEX durable_runs_claim_idx ON questpie_internal.durable_runs USING btree (application_name, state, available_at, run_id)",
	],
	[
		"durable_runs",
		"durable_runs_lease_idx",
		"btree",
		false,
		false,
		"CREATE INDEX durable_runs_lease_idx ON questpie_internal.durable_runs USING btree (application_name, state, lease_expires_at)",
	],
	[
		"durable_runs",
		"durable_runs_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_runs_pkey ON questpie_internal.durable_runs USING btree (application_name, run_id)",
	],
	[
		"durable_runs",
		"durable_runs_resource_idx",
		"btree",
		false,
		false,
		"CREATE INDEX durable_runs_resource_idx ON questpie_internal.durable_runs USING btree (application_name, resource_identity, state)",
	],
] as const;
