/** Generated from a live PostgreSQL catalog after applying `internalProtocolV7Sql`. */

export const internalProtocolV7Columns = [
	["application_bindings", "application_name", "text", true],
	["application_bindings", "postgres_schema", "text", true],
	["application_bindings", "created_at", "timestamp with time zone", true],
	["change_ledger", "application_name", "text", true],
	["change_ledger", "fact_identity", "uuid", true],
	["change_ledger", "fact_id", "bigint", true],
	["change_ledger", "transaction_id", "xid8", true],
	["change_ledger", "collection_identity", "text", true],
	["change_ledger", "change_kind", "text", true],
	["change_ledger", "old_key", "jsonb", false],
	["change_ledger", "new_key", "jsonb", false],
	["change_ledger", "conservative", "boolean", true],
	["change_ledger", "captured_at", "timestamp with time zone", true],
	["durable_attempts", "application_name", "text", true],
	["durable_attempts", "attempt_id", "uuid", true],
	["durable_attempts", "run_id", "uuid", true],
	["durable_attempts", "attempt_number", "integer", true],
	["durable_attempts", "worker_id", "text", true],
	["durable_attempts", "lease_token_digest", "text", true],
	["durable_attempts", "lease_expires_at", "timestamp with time zone", true],
	["durable_attempts", "deadline_at", "timestamp with time zone", true],
	["durable_attempts", "started_at", "timestamp with time zone", true],
	["durable_attempts", "heartbeat_at", "timestamp with time zone", true],
	["durable_attempts", "outcome", "text", false],
	["durable_attempts", "failure_code", "text", false],
	["durable_cancellations", "application_name", "text", true],
	["durable_cancellations", "cancellation_id", "uuid", true],
	["durable_cancellations", "run_id", "uuid", true],
	["durable_cancellations", "requested_by_kind", "text", true],
	["durable_cancellations", "requested_by_id", "text", true],
	["durable_cancellations", "reason", "text", true],
	["durable_cancellations", "requested_at", "timestamp with time zone", true],
	["durable_dispatches", "application_name", "text", true],
	["durable_dispatches", "tenant_id", "text", true],
	["durable_dispatches", "source_operation", "text", true],
	["durable_dispatches", "principal_kind", "text", true],
	["durable_dispatches", "principal_id", "text", true],
	["durable_dispatches", "call_id", "text", true],
	["durable_dispatches", "dispatch_slot", "text", true],
	["durable_dispatches", "record_id", "uuid", true],
	["durable_dispatches", "resource_identity", "text", true],
	["durable_dispatches", "input_digest", "text", true],
	["durable_dispatches", "payload_bytes", "bytea", true],
	["durable_dispatches", "transaction_id", "xid8", true],
	["durable_dispatches", "recorded_at", "timestamp with time zone", true],
	["durable_dispatches", "state", "text", true],
	["durable_dispatches", "resource_kind", "text", true],
	["durable_effects", "application_name", "text", true],
	["durable_effects", "run_id", "uuid", true],
	["durable_effects", "effect_name", "text", true],
	["durable_effects", "effect_id", "uuid", true],
	["durable_effects", "input_digest", "text", true],
	["durable_effects", "status", "text", true],
	["durable_effects", "receipt", "text", false],
	["durable_effects", "reserved_attempt_id", "uuid", true],
	["durable_effects", "settled_attempt_id", "uuid", false],
	["durable_effects", "reserved_at", "timestamp with time zone", true],
	["durable_effects", "settled_at", "timestamp with time zone", false],
	["durable_maintenance_commands", "application_name", "text", true],
	["durable_maintenance_commands", "command_id", "uuid", true],
	["durable_maintenance_commands", "run_id", "uuid", true],
	["durable_maintenance_commands", "command", "text", true],
	["durable_maintenance_commands", "outcome", "text", true],
	["durable_maintenance_commands", "rejection_code", "text", false],
	["durable_maintenance_commands", "actor_kind", "text", true],
	["durable_maintenance_commands", "actor_id", "text", true],
	["durable_maintenance_commands", "state_before", "text", true],
	["durable_maintenance_commands", "state_after", "text", true],
	[
		"durable_maintenance_commands",
		"requested_at",
		"timestamp with time zone",
		true,
	],
	["durable_maintenance_commands", "reason", "text", false],
	["durable_run_events", "application_name", "text", true],
	["durable_run_events", "run_id", "uuid", true],
	["durable_run_events", "sequence", "integer", true],
	["durable_run_events", "occurred_at", "timestamp with time zone", true],
	["durable_run_events", "resource_identity", "text", true],
	["durable_run_events", "dispatch_id", "uuid", true],
	["durable_run_events", "attempt_id", "uuid", false],
	["durable_run_events", "lease_token_digest", "text", false],
	["durable_run_events", "causation_id", "text", true],
	["durable_run_events", "correlation_id", "text", true],
	["durable_run_events", "kind", "text", true],
	["durable_run_events", "error_code", "text", false],
	["durable_runs", "application_name", "text", true],
	["durable_runs", "run_id", "uuid", true],
	["durable_runs", "dispatch_id", "uuid", true],
	["durable_runs", "resource_identity", "text", true],
	["durable_runs", "tenant_id", "text", true],
	["durable_runs", "principal_kind", "text", true],
	["durable_runs", "principal_id", "text", true],
	["durable_runs", "run_as", "text", true],
	["durable_runs", "context_input_bytes", "bytea", true],
	["durable_runs", "payload_bytes", "bytea", true],
	["durable_runs", "retry_bytes", "bytea", true],
	["durable_runs", "runtime_build_digest", "text", true],
	["durable_runs", "executable_digest", "text", true],
	["durable_runs", "causation_kind", "text", true],
	["durable_runs", "causation_id", "text", true],
	["durable_runs", "correlation_id", "text", true],
	["durable_runs", "state", "text", true],
	["durable_runs", "attempt_count", "integer", true],
	["durable_runs", "current_attempt_id", "uuid", false],
	["durable_runs", "lease_token_digest", "text", false],
	["durable_runs", "lease_expires_at", "timestamp with time zone", false],
	["durable_runs", "available_at", "timestamp with time zone", true],
	["durable_runs", "horizon_at", "timestamp with time zone", true],
	["durable_runs", "cancellation_requested", "boolean", true],
	["durable_runs", "event_sequence", "integer", true],
	["durable_runs", "result_bytes", "bytea", false],
	["durable_runs", "failure_code", "text", false],
	["durable_runs", "dead_letter", "boolean", true],
	["durable_runs", "accepted_at", "timestamp with time zone", true],
	["durable_runs", "terminal_at", "timestamp with time zone", false],
	["durable_runs", "semantic_version", "integer", true],
	["mutation_call_receipts", "application_name", "text", true],
	["mutation_call_receipts", "tenant_id", "text", true],
	["mutation_call_receipts", "operation_name", "text", true],
	["mutation_call_receipts", "principal_kind", "text", true],
	["mutation_call_receipts", "principal_id", "text", true],
	["mutation_call_receipts", "call_id", "text", true],
	["mutation_call_receipts", "input_digest", "text", true],
	["mutation_call_receipts", "transaction_id", "xid8", true],
	[
		"mutation_call_receipts",
		"operation_time",
		"timestamp with time zone",
		true,
	],
	["mutation_call_receipts", "outcome", "text", true],
	["mutation_call_receipts", "result_bytes", "bytea", false],
	["mutation_call_receipts", "committed_at", "timestamp with time zone", false],
	["observed_dependency_plans", "application_name", "text", true],
	["observed_dependency_plans", "scope_identity", "text", true],
	["observed_dependency_plans", "binding_identity", "text", true],
	["observed_dependency_plans", "deployment_digest", "text", true],
	["observed_dependency_plans", "authority_partition_digest", "text", true],
	["observed_dependency_plans", "query_identity", "text", true],
	["observed_dependency_plans", "input_digest", "text", true],
	["observed_dependency_plans", "wire_version", "integer", true],
	["observed_dependency_plans", "retained_generation", "bigint", true],
	["observed_dependency_plans", "plan_digest", "text", true],
	["observed_dependency_plans", "plan_bytes", "bytea", true],
	[
		"observed_dependency_plans",
		"replaced_at",
		"timestamp with time zone",
		true,
	],
	["processed_change_facts", "application_name", "text", true],
	["processed_change_facts", "consumer_id", "text", true],
	["processed_change_facts", "fact_identity", "uuid", true],
	["processed_change_facts", "processed_at", "timestamp with time zone", true],
	["protocol", "singleton", "boolean", true],
	["protocol", "version", "integer", true],
	["protocol", "checksum", "text", true],
	["realtime_binding_generations", "application_name", "text", true],
	["realtime_binding_generations", "scope_identity", "text", true],
	["realtime_binding_generations", "binding_identity", "text", true],
	["realtime_binding_generations", "deployment_digest", "text", true],
	["realtime_binding_generations", "authority_partition_digest", "text", true],
	["realtime_binding_generations", "query_identity", "text", true],
	["realtime_binding_generations", "input_digest", "text", true],
	["realtime_binding_generations", "wire_version", "integer", true],
	["realtime_binding_generations", "generation", "bigint", true],
	["realtime_binding_generations", "token_digest", "text", true],
	["realtime_binding_generations", "result_bytes", "bytea", true],
	["realtime_binding_generations", "dependency_plan_bytes", "bytea", true],
	["realtime_binding_generations", "delivery_kind", "text", true],
	["realtime_binding_generations", "reset_reason", "text", false],
	["realtime_binding_generations", "latest_slot", "smallint", false],
	["realtime_binding_generations", "ack_slot", "smallint", false],
	[
		"realtime_binding_generations",
		"created_at",
		"timestamp with time zone",
		true,
	],
	[
		"realtime_binding_generations",
		"acknowledged_at",
		"timestamp with time zone",
		false,
	],
	["realtime_scope_attachments", "application_name", "text", true],
	["realtime_scope_attachments", "scope_identity", "text", true],
	["realtime_scope_attachments", "deployment_digest", "text", true],
	["realtime_scope_attachments", "authority_partition_digest", "text", false],
	["realtime_scope_attachments", "principal_kind", "text", true],
	["realtime_scope_attachments", "principal_id", "text", true],
	["realtime_scope_attachments", "holder_generation", "bigint", true],
	["realtime_scope_attachments", "opened_at", "timestamp with time zone", true],
	[
		"realtime_scope_attachments",
		"renewed_at",
		"timestamp with time zone",
		true,
	],
	[
		"realtime_scope_attachments",
		"expires_at",
		"timestamp with time zone",
		true,
	],
	["realtime_scope_attachments", "state", "text", true],
	[
		"realtime_scope_attachments",
		"withdrawn_at",
		"timestamp with time zone",
		false,
	],
	["realtime_watch_bindings", "application_name", "text", true],
	["realtime_watch_bindings", "scope_identity", "text", true],
	["realtime_watch_bindings", "binding_identity", "text", true],
	["realtime_watch_bindings", "deployment_digest", "text", true],
	["realtime_watch_bindings", "authority_partition_digest", "text", true],
	["realtime_watch_bindings", "principal_kind", "text", true],
	["realtime_watch_bindings", "principal_id", "text", true],
	["realtime_watch_bindings", "active_slot", "smallint", false],
	["realtime_watch_bindings", "query_identity", "text", true],
	["realtime_watch_bindings", "query_bytes", "bytea", true],
	["realtime_watch_bindings", "input_bytes", "bytea", true],
	["realtime_watch_bindings", "input_digest", "text", true],
	["realtime_watch_bindings", "context_input_bytes", "bytea", true],
	["realtime_watch_bindings", "wire_version", "integer", true],
	["realtime_watch_bindings", "resume_requested", "boolean", true],
	["realtime_watch_bindings", "requested_resume_token", "text", false],
	["realtime_watch_bindings", "opened_at", "timestamp with time zone", true],
	["realtime_watch_bindings", "state", "text", true],
	[
		"realtime_watch_bindings",
		"withdrawn_at",
		"timestamp with time zone",
		false,
	],
	["realtime_watch_bindings", "invalidation_generation", "bigint", true],
	[
		"realtime_watch_bindings",
		"evaluated_invalidation_generation",
		"bigint",
		true,
	],
	[
		"realtime_watch_bindings",
		"invalidated_at",
		"timestamp with time zone",
		true,
	],
	["reconciliation_consumers", "application_name", "text", true],
	["reconciliation_consumers", "consumer_id", "text", true],
	["reconciliation_consumers", "xid_horizon", "xid8", true],
	[
		"reconciliation_consumers",
		"acknowledged_at",
		"timestamp with time zone",
		true,
	],
	["retained_live_query_results", "application_name", "text", true],
	["retained_live_query_results", "token_digest", "text", true],
	["retained_live_query_results", "authority_partition_digest", "text", true],
	["retained_live_query_results", "deployment_digest", "text", true],
	["retained_live_query_results", "query_identity", "text", true],
	["retained_live_query_results", "input_digest", "text", true],
	["retained_live_query_results", "wire_version", "integer", true],
	["retained_live_query_results", "retained_generation", "bigint", true],
	["retained_live_query_results", "result_bytes", "bytea", true],
	["retained_live_query_results", "dependency_plan_bytes", "bytea", true],
	[
		"retained_live_query_results",
		"created_at",
		"timestamp with time zone",
		true,
	],
	[
		"retained_live_query_results",
		"expires_at",
		"timestamp with time zone",
		true,
	],
	["schema_migration_receipts", "application_name", "text", true],
	["schema_migration_receipts", "migration_identity", "text", true],
	["schema_migration_receipts", "sequence", "integer", true],
	["schema_migration_receipts", "parent_identity", "text", false],
	["schema_migration_receipts", "checksum", "text", true],
	["schema_migration_receipts", "base_schema_digest", "text", true],
	["schema_migration_receipts", "target_schema_digest", "text", true],
	["schema_migration_receipts", "applied_at", "timestamp with time zone", true],
	["seed_attempt_events", "application_name", "text", true],
	["seed_attempt_events", "attempt_id", "uuid", true],
	["seed_attempt_events", "sequence", "smallint", true],
	["seed_attempt_events", "seed_identity", "text", true],
	["seed_attempt_events", "checksum", "text", true],
	["seed_attempt_events", "event", "text", true],
	["seed_attempt_events", "occurred_at", "timestamp with time zone", true],
	["seed_attempt_events", "error_code", "text", false],
	["seed_receipts", "application_name", "text", true],
	["seed_receipts", "seed_identity", "text", true],
	["seed_receipts", "checksum", "text", true],
	["seed_receipts", "applied_schema_digest", "text", true],
	["seed_receipts", "committed_at", "timestamp with time zone", true],
	["seed_receipts", "attempt_id", "uuid", true],
] as const;
