/** Generated from a live PostgreSQL catalog after applying `internalProtocolV7Sql`. */

export const internalProtocolV7Indexes = [
	[
		"application_bindings",
		"application_bindings_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX application_bindings_pkey ON questpie_internal.application_bindings USING btree (application_name)",
	],
	[
		"application_bindings",
		"application_bindings_postgres_schema_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX application_bindings_postgres_schema_key ON questpie_internal.application_bindings USING btree (postgres_schema)",
	],
	[
		"change_ledger",
		"change_ledger_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX change_ledger_pkey ON questpie_internal.change_ledger USING btree (application_name, fact_identity)",
	],
	[
		"change_ledger",
		"change_ledger_reconcile_idx",
		"btree",
		false,
		false,
		"CREATE INDEX change_ledger_reconcile_idx ON questpie_internal.change_ledger USING btree (application_name, transaction_id, collection_identity, fact_id)",
	],
	[
		"durable_attempts",
		"durable_attempt_number_unique",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX durable_attempt_number_unique ON questpie_internal.durable_attempts USING btree (application_name, run_id, attempt_number)",
	],
	[
		"durable_attempts",
		"durable_attempts_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_attempts_pkey ON questpie_internal.durable_attempts USING btree (application_name, attempt_id)",
	],
	[
		"durable_cancellations",
		"durable_cancellation_run_unique",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX durable_cancellation_run_unique ON questpie_internal.durable_cancellations USING btree (application_name, run_id)",
	],
	[
		"durable_cancellations",
		"durable_cancellations_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_cancellations_pkey ON questpie_internal.durable_cancellations USING btree (application_name, cancellation_id)",
	],
	[
		"durable_dispatches",
		"durable_dispatch_origin_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX durable_dispatch_origin_key ON questpie_internal.durable_dispatches USING btree (application_name, tenant_id, source_operation, principal_kind, principal_id, call_id, dispatch_slot)",
	],
	[
		"durable_dispatches",
		"durable_dispatches_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_dispatches_pkey ON questpie_internal.durable_dispatches USING btree (application_name, record_id)",
	],
	[
		"durable_effects",
		"durable_effect_identity_unique",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX durable_effect_identity_unique ON questpie_internal.durable_effects USING btree (application_name, effect_id)",
	],
	[
		"durable_effects",
		"durable_effects_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_effects_pkey ON questpie_internal.durable_effects USING btree (application_name, run_id, effect_name)",
	],
	[
		"durable_maintenance_commands",
		"durable_maintenance_commands_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_maintenance_commands_pkey ON questpie_internal.durable_maintenance_commands USING btree (application_name, command_id)",
	],
	[
		"durable_maintenance_commands",
		"durable_maintenance_commands_run_idx",
		"btree",
		false,
		false,
		"CREATE INDEX durable_maintenance_commands_run_idx ON questpie_internal.durable_maintenance_commands USING btree (application_name, run_id, requested_at)",
	],
	[
		"durable_run_events",
		"durable_run_events_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_run_events_pkey ON questpie_internal.durable_run_events USING btree (application_name, run_id, sequence)",
	],
	[
		"durable_runs",
		"durable_run_dispatch_unique",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX durable_run_dispatch_unique ON questpie_internal.durable_runs USING btree (application_name, dispatch_id)",
	],
	[
		"durable_runs",
		"durable_runs_claim_idx",
		"btree",
		false,
		false,
		"CREATE INDEX durable_runs_claim_idx ON questpie_internal.durable_runs USING btree (application_name, state, available_at, run_id)",
	],
	[
		"durable_runs",
		"durable_runs_lease_idx",
		"btree",
		false,
		false,
		"CREATE INDEX durable_runs_lease_idx ON questpie_internal.durable_runs USING btree (application_name, state, lease_expires_at)",
	],
	[
		"durable_runs",
		"durable_runs_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX durable_runs_pkey ON questpie_internal.durable_runs USING btree (application_name, run_id)",
	],
	[
		"durable_runs",
		"durable_runs_resource_idx",
		"btree",
		false,
		false,
		"CREATE INDEX durable_runs_resource_idx ON questpie_internal.durable_runs USING btree (application_name, resource_identity, state)",
	],
	[
		"mutation_call_receipts",
		"mutation_call_receipts_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX mutation_call_receipts_pkey ON questpie_internal.mutation_call_receipts USING btree (application_name, tenant_id, operation_name, principal_kind, principal_id, call_id)",
	],
	[
		"observed_dependency_plans",
		"observed_dependency_plans_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX observed_dependency_plans_pkey ON questpie_internal.observed_dependency_plans USING btree (application_name, scope_identity, binding_identity)",
	],
	[
		"processed_change_facts",
		"processed_change_facts_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX processed_change_facts_pkey ON questpie_internal.processed_change_facts USING btree (application_name, consumer_id, fact_identity)",
	],
	[
		"protocol",
		"protocol_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX protocol_pkey ON questpie_internal.protocol USING btree (singleton)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generations_ack_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX realtime_binding_generations_ack_key ON questpie_internal.realtime_binding_generations USING btree (application_name, scope_identity, binding_identity, ack_slot)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generations_latest_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX realtime_binding_generations_latest_key ON questpie_internal.realtime_binding_generations USING btree (application_name, scope_identity, binding_identity, latest_slot)",
	],
	[
		"realtime_binding_generations",
		"realtime_binding_generations_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX realtime_binding_generations_pkey ON questpie_internal.realtime_binding_generations USING btree (application_name, scope_identity, binding_identity, generation)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_attachment_binding_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX realtime_scope_attachment_binding_key ON questpie_internal.realtime_scope_attachments USING btree (application_name, scope_identity, deployment_digest, authority_partition_digest, principal_kind, principal_id)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_attachments_expiry_idx",
		"btree",
		false,
		false,
		"CREATE INDEX realtime_scope_attachments_expiry_idx ON questpie_internal.realtime_scope_attachments USING btree (application_name, deployment_digest, state, expires_at)",
	],
	[
		"realtime_scope_attachments",
		"realtime_scope_attachments_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX realtime_scope_attachments_pkey ON questpie_internal.realtime_scope_attachments USING btree (application_name, scope_identity)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_binding_authority_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX realtime_watch_binding_authority_key ON questpie_internal.realtime_watch_bindings USING btree (application_name, scope_identity, binding_identity, deployment_digest, authority_partition_digest, query_identity, input_digest, wire_version)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_bindings_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX realtime_watch_bindings_pkey ON questpie_internal.realtime_watch_bindings USING btree (application_name, scope_identity, binding_identity)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_bindings_principal_slot_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX realtime_watch_bindings_principal_slot_key ON questpie_internal.realtime_watch_bindings USING btree (application_name, deployment_digest, principal_kind, principal_id, active_slot)",
	],
	[
		"realtime_watch_bindings",
		"realtime_watch_bindings_scope_scan_idx",
		"btree",
		false,
		false,
		"CREATE INDEX realtime_watch_bindings_scope_scan_idx ON questpie_internal.realtime_watch_bindings USING btree (application_name, scope_identity, state, binding_identity)",
	],
	[
		"reconciliation_consumers",
		"reconciliation_consumers_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX reconciliation_consumers_pkey ON questpie_internal.reconciliation_consumers USING btree (application_name, consumer_id)",
	],
	[
		"retained_live_query_results",
		"retained_live_query_results_expiry_idx",
		"btree",
		false,
		false,
		"CREATE INDEX retained_live_query_results_expiry_idx ON questpie_internal.retained_live_query_results USING btree (application_name, expires_at)",
	],
	[
		"retained_live_query_results",
		"retained_live_query_results_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX retained_live_query_results_pkey ON questpie_internal.retained_live_query_results USING btree (application_name, token_digest)",
	],
	[
		"schema_migration_receipts",
		"schema_migration_receipts_application_name_sequence_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX schema_migration_receipts_application_name_sequence_key ON questpie_internal.schema_migration_receipts USING btree (application_name, sequence)",
	],
	[
		"schema_migration_receipts",
		"schema_migration_receipts_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX schema_migration_receipts_pkey ON questpie_internal.schema_migration_receipts USING btree (application_name, migration_identity)",
	],
	[
		"seed_attempt_events",
		"seed_attempt_events_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX seed_attempt_events_pkey ON questpie_internal.seed_attempt_events USING btree (application_name, attempt_id, sequence)",
	],
	[
		"seed_receipts",
		"seed_receipts_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX seed_receipts_pkey ON questpie_internal.seed_receipts USING btree (application_name, seed_identity)",
	],
] as const;
