/** Candidate protocol delta generated from its isolated PostgreSQL 17 catalog. */
export const internalProtocolV9Indexes = [
	[
		"mutation_checkpoints",
		"mutation_checkpoints_application_name_run_id_checkpoint_nam_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX mutation_checkpoints_application_name_run_id_checkpoint_nam_key ON questpie_internal.mutation_checkpoints USING btree (application_name, run_id, checkpoint_name)",
	],
	[
		"mutation_checkpoints",
		"mutation_checkpoints_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX mutation_checkpoints_pkey ON questpie_internal.mutation_checkpoints USING btree (application_name, run_id, ordinal)",
	],
	[
		"schedule_activations",
		"schedule_activations_application_name_accepted_revision_key",
		"btree",
		true,
		false,
		"CREATE UNIQUE INDEX schedule_activations_application_name_accepted_revision_key ON questpie_internal.schedule_activations USING btree (application_name, accepted_revision)",
	],
	[
		"schedule_activations",
		"schedule_activations_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX schedule_activations_pkey ON questpie_internal.schedule_activations USING btree (application_name, request_identity)",
	],
	[
		"schedule_catalogs",
		"schedule_catalogs_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX schedule_catalogs_pkey ON questpie_internal.schedule_catalogs USING btree (application_name, target_digest)",
	],
	[
		"schedule_frontiers",
		"schedule_frontiers_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX schedule_frontiers_pkey ON questpie_internal.schedule_frontiers USING btree (application_name, job_identity)",
	],
	[
		"schedule_heads",
		"schedule_heads_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX schedule_heads_pkey ON questpie_internal.schedule_heads USING btree (application_name)",
	],
	[
		"schedule_ticks",
		"schedule_ticks_pkey",
		"btree",
		true,
		true,
		"CREATE UNIQUE INDEX schedule_ticks_pkey ON questpie_internal.schedule_ticks USING btree (application_name, job_identity, scheduled_minute)",
	],
] as const;
