export type {
	CodegenPlugin,
	CodegenResult,
	CrossTargetValidator,
	CategoryDeclaration,
	CodegenTargetGenerateContext,
	CodegenTargetContribution,
	CodegenTargetOutput,
	DiscoveredFile,
	DiscoverPattern,
	DiscoveryResult,
	MultiTargetCodegenResult,
	ProjectionError,
	ResolvedTarget,
	ScaffoldConfig,
	ScaffoldContext,
	SingletonFactory,
	RegistryExtension,
	BuilderFactory,
	CodegenContext,
	CodegenOptions,
	CallbackParamDefinition,
} from "#questpie/cli/codegen/types.js";

export {
	categoryRecordEntry,
	categoryTypeEntry,
	importStatement,
	safeKey,
	sortedValues,
	sourceBasename,
} from "#questpie/cli/codegen/category-emit.js";
