/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { wfEventCollection as _coll_wf_event } from "../collections/wf-event";
import { wfInstanceCollection as _coll_wf_instance } from "../collections/wf-instance";
import { wfLogCollection as _coll_wf_log } from "../collections/wf-log";
import { wfStepCollection as _coll_wf_step } from "../collections/wf-step";

// ── Jobs ────────────────────────────────────────────
import _job_wfExecute from "../jobs/wf-execute";
import _job_wfMaintenance from "../jobs/wf-maintenance";
import _job_wfResume from "../jobs/wf-resume";

// ── Routes ────────────────────────────────────────────
import _route_cancelAllWorkflowInstances from "../routes/cancel-all-workflow-instances";
import _route_cancelWorkflowInstance from "../routes/cancel-workflow-instance";
import _route_getWorkflowInstance from "../routes/get-workflow-instance";
import _route_listWorkflowDefinitions from "../routes/list-workflow-definitions";
import _route_listWorkflowInstances from "../routes/list-workflow-instances";
import _route_retryAllWorkflowInstances from "../routes/retry-all-workflow-instances";
import _route_retryWorkflowInstance from "../routes/retry-workflow-instance";
import _route_sendWorkflowEvent from "../routes/send-workflow-event";
import _route_triggerWorkflow from "../routes/trigger-workflow";

// ── Services ────────────────────────────────────────────
import _svc_workflows from "../services/workflows";

// ── Singles ────────────────────────────────────────────────
import _adminConfig from "../config/admin";

// ── Entity key registry (names only — acyclic by construction) ─────
declare global {
	namespace Questpie {
		interface CollectionKeys { wf_event: unknown; wf_instance: unknown; wf_log: unknown; wf_step: unknown }
		interface JobKeys { wfExecute: unknown; wfMaintenance: unknown; wfResume: unknown }
	}
}

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { RouteDefinition, RouteParamsFromKey } from "questpie/types";

export interface WorkflowsCollections {
	wf_event: typeof _coll_wf_event;
	wf_instance: typeof _coll_wf_instance;
	wf_log: typeof _coll_wf_log;
	wf_step: typeof _coll_wf_step;
}

export interface WorkflowsJobs {
	wfExecute: Omit<typeof _job_wfExecute, "handler"> & { handler: (args: unknown) => Promise<unknown> };
	wfMaintenance: Omit<typeof _job_wfMaintenance, "handler"> & { handler: (args: unknown) => Promise<unknown> };
	wfResume: Omit<typeof _job_wfResume, "handler"> & { handler: (args: unknown) => Promise<unknown> };
}

export interface WorkflowsRoutes {
	cancelAllWorkflowInstances: typeof _route_cancelAllWorkflowInstances extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"cancelAllWorkflowInstances">> : typeof _route_cancelAllWorkflowInstances;
	cancelWorkflowInstance: typeof _route_cancelWorkflowInstance extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"cancelWorkflowInstance">> : typeof _route_cancelWorkflowInstance;
	getWorkflowInstance: typeof _route_getWorkflowInstance extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"getWorkflowInstance">> : typeof _route_getWorkflowInstance;
	listWorkflowDefinitions: typeof _route_listWorkflowDefinitions extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"listWorkflowDefinitions">> : typeof _route_listWorkflowDefinitions;
	listWorkflowInstances: typeof _route_listWorkflowInstances extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"listWorkflowInstances">> : typeof _route_listWorkflowInstances;
	retryAllWorkflowInstances: typeof _route_retryAllWorkflowInstances extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"retryAllWorkflowInstances">> : typeof _route_retryAllWorkflowInstances;
	retryWorkflowInstance: typeof _route_retryWorkflowInstance extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"retryWorkflowInstance">> : typeof _route_retryWorkflowInstance;
	sendWorkflowEvent: typeof _route_sendWorkflowEvent extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"sendWorkflowEvent">> : typeof _route_sendWorkflowEvent;
	triggerWorkflow: typeof _route_triggerWorkflow extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"triggerWorkflow">> : typeof _route_triggerWorkflow;
}

export interface WorkflowsServices {
	workflows: typeof _svc_workflows;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type WorkflowsModule = {
	name: "questpie-workflows";
	collections: WorkflowsCollections;
	jobs: WorkflowsJobs;
	routes: WorkflowsRoutes;
	services: WorkflowsServices;
	globals: {};
	messages: {};
	emails: {};
	migrations: readonly unknown[];
	seeds: readonly unknown[];
	fieldTypes: {};
	views: {};
	components: {};
	blocks: {};
	config: {
		admin: typeof _adminConfig;
	};
};

const _module: WorkflowsModule = {
	name: "questpie-workflows" as const,
	collections: {
		wf_event: _coll_wf_event,
		wf_instance: _coll_wf_instance,
		wf_log: _coll_wf_log,
		wf_step: _coll_wf_step,
	} as WorkflowsCollections,
	jobs: {
		wfExecute: _job_wfExecute,
		wfMaintenance: _job_wfMaintenance,
		wfResume: _job_wfResume,
	} as WorkflowsJobs,
	routes: {
		cancelAllWorkflowInstances: _route_cancelAllWorkflowInstances,
		cancelWorkflowInstance: _route_cancelWorkflowInstance,
		getWorkflowInstance: _route_getWorkflowInstance,
		listWorkflowDefinitions: _route_listWorkflowDefinitions,
		listWorkflowInstances: _route_listWorkflowInstances,
		retryAllWorkflowInstances: _route_retryAllWorkflowInstances,
		retryWorkflowInstance: _route_retryWorkflowInstance,
		sendWorkflowEvent: _route_sendWorkflowEvent,
		triggerWorkflow: _route_triggerWorkflow,
	} as WorkflowsRoutes,
	services: {
		workflows: _svc_workflows,
	} as WorkflowsServices,
	globals: {},
	messages: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	views: {},
	components: {},
	blocks: {},
	config: {
		admin: _adminConfig,
	},
};

export default _module;
