/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { wfEventCollection as _coll_wf_event } from "../collections/wf-event";
import { wfInstanceCollection as _coll_wf_instance } from "../collections/wf-instance";
import { wfLogCollection as _coll_wf_log } from "../collections/wf-log";
import { wfStepCollection as _coll_wf_step } from "../collections/wf-step";
// ── Singles ────────────────────────────────────────────────
import _dashboard from "../dashboard";
// ── Jobs ────────────────────────────────────────────
import _job_wfExecute from "../jobs/wf-execute";
import _job_wfMaintenance from "../jobs/wf-maintenance";
import _job_wfResume from "../jobs/wf-resume";
// ── Routes ────────────────────────────────────────────
import _route_cancel_all_workflow_instances from "../routes/cancel-all-workflow-instances";
import _route_cancel_workflow_instance from "../routes/cancel-workflow-instance";
import _route_get_workflow_instance from "../routes/get-workflow-instance";
import _route_list_workflow_definitions from "../routes/list-workflow-definitions";
import _route_list_workflow_instances from "../routes/list-workflow-instances";
import _route_retry_all_workflow_instances from "../routes/retry-all-workflow-instances";
import _route_retry_workflow_instance from "../routes/retry-workflow-instance";
import _route_send_workflow_event from "../routes/send-workflow-event";
import _route_trigger_workflow from "../routes/trigger-workflow";
// ── Services ────────────────────────────────────────────
import _svc_workflowService from "../services/workflow-service";
import _sidebar from "../sidebar";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface WorkflowsCollections {
	wf_event: typeof _coll_wf_event;
	wf_instance: typeof _coll_wf_instance;
	wf_log: typeof _coll_wf_log;
	wf_step: typeof _coll_wf_step;
}

export interface WorkflowsJobs {
	wfExecute: typeof _job_wfExecute;
	wfMaintenance: typeof _job_wfMaintenance;
	wfResume: typeof _job_wfResume;
}

export interface WorkflowsRoutes {
	"cancel-all-workflow-instances": typeof _route_cancel_all_workflow_instances;
	"cancel-workflow-instance": typeof _route_cancel_workflow_instance;
	"get-workflow-instance": typeof _route_get_workflow_instance;
	"list-workflow-definitions": typeof _route_list_workflow_definitions;
	"list-workflow-instances": typeof _route_list_workflow_instances;
	"retry-all-workflow-instances": typeof _route_retry_all_workflow_instances;
	"retry-workflow-instance": typeof _route_retry_workflow_instance;
	"send-workflow-event": typeof _route_send_workflow_event;
	"trigger-workflow": typeof _route_trigger_workflow;
}

export interface WorkflowsServices {
	workflowService: typeof _svc_workflowService;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-workflows" as const,
	collections: {
		wf_event: _coll_wf_event,
		wf_instance: _coll_wf_instance,
		wf_log: _coll_wf_log,
		wf_step: _coll_wf_step,
	} as WorkflowsCollections,
	jobs: {
		wfExecute: _job_wfExecute,
		wfMaintenance: _job_wfMaintenance,
		wfResume: _job_wfResume,
	} as WorkflowsJobs,
	routes: {
		"cancel-all-workflow-instances": _route_cancel_all_workflow_instances,
		"cancel-workflow-instance": _route_cancel_workflow_instance,
		"get-workflow-instance": _route_get_workflow_instance,
		"list-workflow-definitions": _route_list_workflow_definitions,
		"list-workflow-instances": _route_list_workflow_instances,
		"retry-all-workflow-instances": _route_retry_all_workflow_instances,
		"retry-workflow-instance": _route_retry_workflow_instance,
		"send-workflow-event": _route_send_workflow_event,
		"trigger-workflow": _route_trigger_workflow,
	} as WorkflowsRoutes,
	services: {
		workflowService: _svc_workflowService,
	} as WorkflowsServices,
	globals: {},
	functions: {},
	messages: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	views: {},
	components: {},
	blocks: {},
	dashboard: [_dashboard],
	sidebar: [_sidebar],
};

export type WorkflowsModule = typeof _module;
export default _module;
