/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import "./names.gen";
// ── Env (validated before everything else) ─────────────────
import _env from "../env";

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import { appointments as _coll_appointments } from "../collections/appointments";
import { barberServices as _coll_barber_services } from "../collections/barber-services";
import { barbers as _coll_barbers } from "../collections/barbers";
import { blogPosts as _coll_blog_posts } from "../collections/blog-posts";
import { pages as _coll_pages } from "../collections/pages";
import { reviews as _coll_reviews } from "../collections/reviews";
import { services as _coll_services } from "../collections/services";

// ── Globals ────────────────────────────────────────────────
import { siteSettings as _glob_site_settings } from "../globals/site-settings";

// ── Jobs ───────────────────────────────────────────────────
import _job_notifyBlogSubscribers from "../jobs/notify-blog-subscribers";
import _job_sendAppointmentCancellation from "../jobs/send-appointment-cancellation";
import _job_sendAppointmentConfirmation from "../jobs/send-appointment-confirmation";
import _job_sendAppointmentReminder from "../jobs/send-appointment-reminder";

// ── Routes ─────────────────────────────────────────────────
import _route_createBooking from "../routes/create-booking";
import _route_getActiveBarbers from "../routes/get-active-barbers";
import _route_getAvailableTimeSlots from "../routes/get-available-time-slots";
import _route_getRevenueStats from "../routes/get-revenue-stats";

// ── Services ───────────────────────────────────────────────
import _svc_blog from "../services/blog";

// ── Emails ─────────────────────────────────────────────────
import _email_appointmentConfirmation from "../emails/appointment-confirmation";
import _email_newBlogPost from "../emails/new-blog-post";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260206T174642_gentle_azure_eagle from "../migrations/20260206T174642_gentle_azure_eagle";
import _mig_20260206T180920_fancy_green_tiger from "../migrations/20260206T180920_fancy_green_tiger";
import _mig_20260211T100836_calm_blue_phoenix from "../migrations/20260211T100836_calm_blue_phoenix";
import _mig_20260218T195452_calm_blue_dragon from "../migrations/20260218T195452_calm_blue_dragon";
import _mig_20260218T223923_fancy_blue_panda from "../migrations/20260218T223923_fancy_blue_panda";
import _mig_20260218T235924_kind_crimson_falcon from "../migrations/20260218T235924_kind_crimson_falcon";
import _mig_20260307T122102_eager_red_eagle from "../migrations/20260307T122102_eager_red_eagle";
import _mig_20260307T135142_fancy_orange_tiger from "../migrations/20260307T135142_fancy_orange_tiger";
import _mig_20260424T221327_bold_yellow_phoenix from "../migrations/20260424T221327_bold_yellow_phoenix";
import _mig_20260427T093217_eager_blue_phoenix from "../migrations/20260427T093217_eager_blue_phoenix";
import _mig_20260429T170546_kind_yellow_eagle from "../migrations/20260429T170546_kind_yellow_eagle";
import _mig_20260615T084209_swift_orange_eagle from "../migrations/20260615T084209_swift_orange_eagle";
import _mig_20260712T094709_bold_red_griffin from "../migrations/20260712T094709_bold_red_griffin";
import _mig_20260712T195414_eager_red_tiger from "../migrations/20260712T195414_eager_red_tiger";
import _mig_20260721T210432_swift_blue_zebra from "../migrations/20260721T210432_swift_blue_zebra";
import _mig_20260721T220717_bright_pink_tiger from "../migrations/20260721T220717_bright_pink_tiger";
import _mig_20260724T085242_crdtCollaborationKernel from "../migrations/20260724T085242_crdt-collaboration-kernel";

// ── Seeds ──────────────────────────────────────────────────
import _seed_blogPosts from "../seeds/blog-posts";
import _seed_demoData from "../seeds/demo-data";
import _seed_siteSettings from "../seeds/site-settings";

// ── FieldTypes ─────────────────────────────────────────────
import { colorFieldType as _ftype_color } from "../fields/color";
import { ratingFieldType as _ftype_rating } from "../fields/rating";

// ── Blocks ─────────────────────────────────────────────────
import { bookingCtaBlock as _bloc_bookingCta } from "../blocks/booking-cta";
import { columnsBlock as _bloc_columns } from "../blocks/columns";
import { contactInfoBlock as _bloc_contactInfo } from "../blocks/contact-info";
import { ctaBlock as _bloc_cta } from "../blocks/cta";
import { dividerBlock as _bloc_divider } from "../blocks/divider";
import { galleryBlock as _bloc_gallery } from "../blocks/gallery";
import { headingBlock as _bloc_heading } from "../blocks/heading";
import { heroBlock as _bloc_hero } from "../blocks/hero";
import { hoursBlock as _bloc_hours } from "../blocks/hours";
import { imageTextBlock as _bloc_imageText } from "../blocks/image-text";
import { reviewsBlock as _bloc_reviews } from "../blocks/reviews";
import { servicesBlock as _bloc_services } from "../blocks/services";
import { spacerBlock as _bloc_spacer } from "../blocks/spacer";
import { statsBlock as _bloc_stats } from "../blocks/stats";
import { teamBlock as _bloc_team } from "../blocks/team";
import { textBlock as _bloc_text } from "../blocks/text";

// ── McpTools ───────────────────────────────────────────────
import _mcpTool_barbershop_checkAvailability from "../mcp-tools/check-availability";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _mcpConfig from "../config/mcp";
import _openapi from "../config/openapi";

import type { RouteParamsFromKey, RouteWithParams } from "questpie/types";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { ExtractModulePropArr, ExtractModulePropArrOverride, Override, ServiceCustomNamespaceInstances, ServiceInstanceOf, ServiceInstancesInNamespace, ServiceTopLevelInstances } from "questpie/types";
type _RouteDefinitionWithoutHandler<T> = T extends { mode: "raw" } ? Omit<T, "handler"> & { handler: (args: unknown) => Response | Promise<Response> } : Omit<T, "handler"> & { handler: (args: unknown) => unknown | Promise<unknown> };
export type _ModuleCollections = ExtractModulePropArrOverride<typeof _modules, "collections">;
export type _ModuleChannels = ExtractModulePropArr<typeof _modules, "channels">;
export type _ModuleGlobals = ExtractModulePropArr<typeof _modules, "globals">;
export type _ModuleJobs = ExtractModulePropArr<typeof _modules, "jobs">;
export type _ModuleRoutes = ExtractModulePropArr<typeof _modules, "routes">;
export type _ModuleServices = {};
export type _ModuleFieldTypes = ExtractModulePropArr<typeof _modules, "fieldTypes">;
export type _ModuleViews = ExtractModulePropArr<typeof _modules, "views">;
export type _ModuleComponents = ExtractModulePropArr<typeof _modules, "components">;
export type _ModuleBlocks = ExtractModulePropArr<typeof _modules, "blocks">;
export type _ModuleMcpTools = ExtractModulePropArr<typeof _modules, "mcpTools">;
// Registry category extraction from modules
export type _Registry_Collections = ExtractModulePropArrOverride<typeof _modules, "collections">;
export type _Registry_Channels = ExtractModulePropArr<typeof _modules, "channels">;
export type _Registry_Globals = ExtractModulePropArr<typeof _modules, "globals">;
export type _Registry_Jobs = ExtractModulePropArr<typeof _modules, "jobs">;
export type _Registry_Routes = ExtractModulePropArr<typeof _modules, "routes">;
export type _Registry_Services = {};
export type _Registry_Emails = ExtractModulePropArr<typeof _modules, "emails">;
export type _Registry_FieldTypes = ExtractModulePropArr<typeof _modules, "fieldTypes">;
export type _Registry_Views = ExtractModulePropArr<typeof _modules, "views">;
export type _Registry_Components = ExtractModulePropArr<typeof _modules, "components">;
export type _Registry_Blocks = ExtractModulePropArr<typeof _modules, "blocks">;
export type _Registry_McpTools = ExtractModulePropArr<typeof _modules, "mcpTools">;

// Recursive module property extraction (for fields contributed at each level)
import type { ExtractModuleProp } from "questpie/types";

export type _AllModuleFields = ExtractModuleProp<{ modules: typeof _modules }, "fields">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = Override<_ModuleCollections, {
	appointments: typeof _coll_appointments;
	barber_services: typeof _coll_barber_services;
	barbers: typeof _coll_barbers;
	blog_posts: typeof _coll_blog_posts;
	pages: typeof _coll_pages;
	reviews: typeof _coll_reviews;
	services: typeof _coll_services;
}>;

/** All channels in the app (modules + user, user overrides) */
export type AppChannels = _ModuleChannels;

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = _ModuleGlobals & {
	site_settings: typeof _glob_site_settings;
};

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs & {
	notifyBlogSubscribers: Omit<typeof _job_notifyBlogSubscribers, "handler"> & { handler: (args: unknown) => Promise<unknown> };
	sendAppointmentCancellation: Omit<typeof _job_sendAppointmentCancellation, "handler"> & { handler: (args: unknown) => Promise<unknown> };
	sendAppointmentConfirmation: Omit<typeof _job_sendAppointmentConfirmation, "handler"> & { handler: (args: unknown) => Promise<unknown> };
	sendAppointmentReminder: Omit<typeof _job_sendAppointmentReminder, "handler"> & { handler: (args: unknown) => Promise<unknown> };
};

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes & {
	createBooking: RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_createBooking>, RouteParamsFromKey<"createBooking">>;
	getActiveBarbers: RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_getActiveBarbers>, RouteParamsFromKey<"getActiveBarbers">>;
	getAvailableTimeSlots: RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_getAvailableTimeSlots>, RouteParamsFromKey<"getAvailableTimeSlots">>;
	getRevenueStats: RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_getRevenueStats>, RouteParamsFromKey<"getRevenueStats">>;
};

/** All service definitions in the app (modules + user, user overrides). */
type _AppServiceDefinitions = _ModuleServices & {
	blog: typeof _svc_blog;
};

/** All services in the app as resolved service instances. */
export type AppServices = {
	[K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]>;
};
export type _AppDefaultServices = ServiceInstancesInNamespace<_AppServiceDefinitions, "services">;
export type _AppServicesSeam = { [K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]> };
export type _AppTopLevelServices = ServiceTopLevelInstances<_AppServiceDefinitions>;
export type _AppCustomServiceNamespaces = ServiceCustomNamespaceInstances<_AppServiceDefinitions>;

/** All email templates in the app — use with email.sendTemplate() */
export type AppEmailTemplates = {
	appointmentConfirmation: typeof _email_appointmentConfirmation;
	newBlogPost: typeof _email_newBlogPost;
};

/** All fieldtypes in the app (modules + user, user overrides) */
export type AppFieldTypes = _ModuleFieldTypes & {
	color: typeof _ftype_color;
	rating: typeof _ftype_rating;
};

/** All views in the app (modules + user, user overrides) */
export type AppViews = _ModuleViews;

/** All components in the app (modules + user, user overrides) */
export type AppComponents = _ModuleComponents;

/** All blocks in the app (modules + user, user overrides) */
export type AppBlocks = _ModuleBlocks
	& { [K in typeof _bloc_bookingCta.state.name]: typeof _bloc_bookingCta }
	& { [K in typeof _bloc_columns.state.name]: typeof _bloc_columns }
	& { [K in typeof _bloc_contactInfo.state.name]: typeof _bloc_contactInfo }
	& { [K in typeof _bloc_cta.state.name]: typeof _bloc_cta }
	& { [K in typeof _bloc_divider.state.name]: typeof _bloc_divider }
	& { [K in typeof _bloc_gallery.state.name]: typeof _bloc_gallery }
	& { [K in typeof _bloc_heading.state.name]: typeof _bloc_heading }
	& { [K in typeof _bloc_hero.state.name]: typeof _bloc_hero }
	& { [K in typeof _bloc_hours.state.name]: typeof _bloc_hours }
	& { [K in typeof _bloc_imageText.state.name]: typeof _bloc_imageText }
	& { [K in typeof _bloc_reviews.state.name]: typeof _bloc_reviews }
	& { [K in typeof _bloc_services.state.name]: typeof _bloc_services }
	& { [K in typeof _bloc_spacer.state.name]: typeof _bloc_spacer }
	& { [K in typeof _bloc_stats.state.name]: typeof _bloc_stats }
	& { [K in typeof _bloc_team.state.name]: typeof _bloc_team }
	& { [K in typeof _bloc_text.state.name]: typeof _bloc_text };

/** All mcptools in the app (modules + user, user overrides) */
export type AppMcpTools = _ModuleMcpTools & {
	"barbershop.checkAvailability": typeof _mcpTool_barbershop_checkAvailability;
};
