/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate -c src/questpie/server/questpie.config.ts

import _envClient from "../env.client";
import { resolveClientEnv } from "questpie/env-client";

/** Typed client env for the vite consumer — server keys are physically absent. */
export const env = resolveClientEnv(_envClient, {
	APP_URL: import.meta.env.VITE_APP_URL,
}, "vite");
export type ClientEnv = typeof env;
