/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Typed factory functions with plugin extensions. Regenerate with: questpie generate

// ── Core Imports ───────────────────────────────────────────
import { CollectionBuilder, GlobalBuilder, wrapBuilderWithExtensions, builtinFields, type EmptyCollectionState, type EmptyGlobalState, type BuiltinFields, type CollectionBuilderState, type GlobalBuilderState, type FieldState, Field } from "questpie/builders";

// ── Runtime Field Imports ──────────────────────────────────
import { adminFields } from "@questpie/admin/fields";
import { colorFieldType as _ftype_color } from "../fields/color";
import { ratingFieldType as _ftype_rating } from "../fields/rating";

const _fieldExt: Record<string, { stateKey: string; resolve: (value: unknown) => unknown }> = {
	admin: { stateKey: "admin", resolve: (v: unknown) => v },
	form: {
		stateKey: "form",
		resolve(configOrFn: unknown) {
			if (typeof configOrFn === 'function') return configOrFn({ f: createFieldNameProxy() });
			return configOrFn;
		},
	},
};

// App field types (fields/ directory) — unwrap fieldType() definitions to factories
const _appFieldTypes = {
	"color": _ftype_color.factory,
	"rating": _ftype_rating.factory,
} as const;
type _AppFieldTypesMap = typeof _appFieldTypes;

// Merged field factories — builtins + module-contributed (e.g. richText, blocks) + user fields
const _rawFieldDefs = { ...builtinFields, ...adminFields, ..._appFieldTypes } as const;

// Wrap field factories so returned Field instances have extension methods
type _FieldFactory = (...args: never[]) => unknown;
function _wrapFieldFactory<TFactory extends _FieldFactory>(fn: TFactory): TFactory {
	return ((...args: Parameters<TFactory>) => wrapBuilderWithExtensions(fn(...args), _fieldExt, Field)) as unknown as TFactory;
}

const _allFieldDefs = Object.fromEntries(
	Object.entries(_rawFieldDefs).map(([k, v]) => [k, _wrapFieldFactory(v)])
) as unknown as typeof _rawFieldDefs;

// ── Entity key registry (names only — acyclic by construction) ─────
declare global {
	namespace Questpie {
		interface CollectionKeys { appointments: unknown; barber_services: unknown; barbers: unknown; blog_posts: unknown; pages: unknown; reviews: unknown; services: unknown }
		interface GlobalKeys { site_settings: unknown }
		interface JobKeys { notifyBlogSubscribers: unknown; sendAppointmentCancellation: unknown; sendAppointmentConfirmation: unknown; sendAppointmentReminder: unknown }
		interface RouteKeys { createBooking: unknown; getActiveBarbers: unknown; getAvailableTimeSlots: unknown; getRevenueStats: unknown }
		interface ServiceKeys { blog: unknown }
		interface EmailKeys { appointmentConfirmation: unknown; newBlogPost: unknown }
		interface FieldTypeKeys { color: unknown; rating: unknown }
		interface BlockKeys { bookingCta: unknown; columns: unknown; contactInfo: unknown; cta: unknown; divider: unknown; gallery: unknown; heading: unknown; hero: unknown; hours: unknown; imageText: unknown; reviews: unknown; services: unknown; spacer: unknown; stats: unknown; team: unknown; text: unknown }
		interface McpToolKeys { "barbershop.checkAvailability": unknown }
	}
}

// ── Plugin Imports ─────────────────────────────────────────
import { type AdminCollectionConfig, type AdminConfigContext, type ListViewConfig, type ListViewConfigContext, type FilterViewsByKind, type FormViewConfig, type FormViewConfigContext, type PreviewConfig, type ServerActionsConfig, type ActionsConfigContext, type AdminGlobalConfig, type AdminConfigInput, createViewCallbackProxy, createComponentCallbackProxy, createActionCallbackProxy, createActionFieldBuilderProxy } from "@questpie/admin/factories";
import { type AppConfigInput, type AuthConfig } from "questpie/types";
import { type McpConfig } from "@questpie/mcp";
import { type OpenApiModuleConfig } from "@questpie/openapi";
import { createFieldNameProxy } from "questpie/builders";

// ════════════════════════════════════════════════════════════
// Type extraction — driven by CategoryDeclaration
// ════════════════════════════════════════════════════════════

type _ViewsNames = (keyof Questpie.ViewsRegistry & string) | (string & {});
type _ViewsRecord = Questpie.ViewsRegistry;
type _ComponentsNames = (keyof Questpie.ComponentsRegistry & string) | (string & {});
type _ComponentsNames_Strict = keyof Questpie.ComponentsRegistry & string;
type _ComponentsRecord = Questpie.ComponentsRegistry;

// Field types — populated by module codegen via Questpie.FieldTypesMap
type _AllFieldTypes = Questpie.FieldTypesMap;

// ════════════════════════════════════════════════════════════
// Type augmentations — generated from plugin registries
// ════════════════════════════════════════════════════════════

declare module "questpie/builders" {
	interface CollectionBuilder<TState extends CollectionBuilderState> {
		admin(configFn: AdminCollectionConfig | ((ctx: AdminConfigContext<_ComponentsRecord>) => AdminCollectionConfig)): CollectionBuilder<TState>;
		list(configFn: (ctx: ListViewConfigContext<TState extends { fieldDefinitions: infer F extends Record<string, unknown> } ? F : Record<string, unknown>, FilterViewsByKind<_ViewsRecord, "list">, _ComponentsRecord>) => ListViewConfig): CollectionBuilder<TState>;
		form(configFn: (ctx: FormViewConfigContext<TState extends { fieldDefinitions: infer F extends Record<string, unknown> } ? F : Record<string, unknown>, FilterViewsByKind<_ViewsRecord, "form">>) => FormViewConfig): CollectionBuilder<TState>;
		preview(config: PreviewConfig): CollectionBuilder<TState>;
		actions(configFn: (ctx: ActionsConfigContext<Record<string, unknown>, _ComponentsRecord>) => ServerActionsConfig): CollectionBuilder<TState>;
	}
	interface GlobalBuilder<TState extends GlobalBuilderState> {
		admin(configFn: AdminGlobalConfig | ((ctx: AdminConfigContext<_ComponentsRecord>) => AdminGlobalConfig)): GlobalBuilder<TState>;
		form(configFn: (ctx: FormViewConfigContext<TState extends { fieldDefinitions: infer F extends Record<string, unknown> } ? F : Record<string, unknown>, FilterViewsByKind<_ViewsRecord, "form">>) => FormViewConfig): GlobalBuilder<TState>;
	}
	interface Field<TState extends FieldState = FieldState> {
		admin(config: unknown): Field<TState>;
		form(configFn: (ctx: { f: Record<string, string> }) => { fields: import('@questpie/admin/factories').FieldLayoutItem[] }): Field<TState>;
	}
}

declare global {
	namespace Questpie {
		interface FieldTypesMap extends BuiltinFields, _AppFieldTypesMap {}
		interface FieldTypeRegistry extends Record<keyof _AllFieldTypes, {}> {}
	}
}

declare module "@questpie/admin/factories" {
	interface ComponentTypeRegistry extends Record<_ComponentsNames_Strict, {}> {}
}

// ════════════════════════════════════════════════════════════
// Extension registries
// ════════════════════════════════════════════════════════════

const _collExt: Record<string, { stateKey: string; resolve: (value: unknown) => unknown }> = {
	admin: {
		stateKey: "admin",
		resolve(configOrFn: unknown) {
			if (typeof configOrFn === 'function') return configOrFn({ c: createComponentCallbackProxy() });
			return configOrFn;
		},
	},
	list: {
		stateKey: "adminList",
		resolve(configOrFn: unknown) {
			const resolved = typeof configOrFn === 'function' ? configOrFn({ v: createViewCallbackProxy(), f: createFieldNameProxy(), a: createActionCallbackProxy(), c: createComponentCallbackProxy() }) : configOrFn;
			return { ...{"view":"collection-table","showSearch":true,"showFilters":true,"showToolbar":true}, ...(resolved && typeof resolved === 'object' ? resolved : {}) };
		},
	},
	form: {
		stateKey: "adminForm",
		resolve(configOrFn: unknown) {
			const resolved = typeof configOrFn === 'function' ? configOrFn({ v: createViewCallbackProxy(), f: createFieldNameProxy() }) : configOrFn;
			return { ...{"view":"collection-form","showMeta":true}, ...(resolved && typeof resolved === 'object' ? resolved : {}) };
		},
	},
	preview: { stateKey: "adminPreview", resolve: (v: unknown) => v },
	actions: {
		stateKey: "adminActions",
		resolve(configOrFn: unknown) {
			if (typeof configOrFn === 'function') return configOrFn({ a: createActionCallbackProxy(), c: createComponentCallbackProxy(), f: createActionFieldBuilderProxy() });
			return configOrFn;
		},
	},
};

const _globExt: Record<string, { stateKey: string; resolve: (value: unknown) => unknown }> = {
	admin: {
		stateKey: "admin",
		resolve(configOrFn: unknown) {
			if (typeof configOrFn === 'function') return configOrFn({ c: createComponentCallbackProxy() });
			return configOrFn;
		},
	},
	form: {
		stateKey: "adminForm",
		resolve(configOrFn: unknown) {
			const resolved = typeof configOrFn === 'function' ? configOrFn({ v: createViewCallbackProxy(), f: createFieldNameProxy() }) : configOrFn;
			return { ...{"view":"global-form","showMeta":true}, ...(resolved && typeof resolved === 'object' ? resolved : {}) };
		},
	},
};

// ════════════════════════════════════════════════════════════
// Factory functions
// ════════════════════════════════════════════════════════════

/**
 * Create a typed collection builder with plugin extensions.
 *
 * @example
 * ```ts
 * import { collection } from "#questpie/factories";
 *
 * export default collection("posts")
 *   .fields(({ f }) => ({ title: f.text(255).required() }))
 *   .admin(({ c }) => ({ icon: c.icon("ph:article") }))
 *   .list(({ v, f }) => v.collectionTable({ columns: [f.title] }))
 * ```
 */
export function collection<TName extends string>(name: TName): CollectionBuilder<EmptyCollectionState<TName, undefined, _AllFieldTypes>> {
	return wrapBuilderWithExtensions(CollectionBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs), _collExt, CollectionBuilder) as unknown as CollectionBuilder<EmptyCollectionState<TName, undefined, _AllFieldTypes>>;
}

/**
 * Create a typed global builder with plugin extensions.
 */
export function global<TName extends string>(name: TName): GlobalBuilder<EmptyGlobalState<TName, undefined, _AllFieldTypes>> {
	return wrapBuilderWithExtensions(GlobalBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs), _globExt, GlobalBuilder) as unknown as GlobalBuilder<EmptyGlobalState<TName, undefined, _AllFieldTypes>>;
}

// ════════════════════════════════════════════════════════════
// Builder factory functions (plugin-contributed)
// ════════════════════════════════════════════════════════════

import { BlockBuilder } from "@questpie/admin/factories";
/**
 * Create a typed block builder with wrapped field defs.
 */
export function block<TName extends string>(name: TName): import('@questpie/admin/factories').BlockBuilder<{ name: TName }> {
	return BlockBuilder.create(name, _allFieldDefs) as unknown as import('@questpie/admin/factories').BlockBuilder<{ name: TName }>;
}

// ════════════════════════════════════════════════════════════
// Singleton factory functions
// ════════════════════════════════════════════════════════════

/** Typed factory for appConfig config. */
export function appConfig<T extends AppConfigInput>(config: T): T { return config; }

/** Typed factory for authConfig config. */
export function authConfig<T extends AuthConfig>(config: T): T { return config; }

/** Typed factory for adminConfig config. Accepts plain config or callback. */
export function adminConfig<T extends AdminConfigInput>(config: T): T;
export function adminConfig<T extends (...args: never[]) => AdminConfigInput>(cb: T): T;
export function adminConfig<T>(v: T): T { return v; }

/** Typed factory for mcpConfig config. Accepts plain config or callback. */
export function mcpConfig<T extends McpConfig>(config: T): T;
export function mcpConfig<T extends (...args: never[]) => McpConfig>(cb: T): T;
export function mcpConfig<T>(v: T): T { return v; }

/** Typed factory for openapi config. */
export function openapi<T extends OpenApiModuleConfig>(config: T): T { return config; }
