/**
 * Admin Client Template Generator
 *
 * Custom generator for the `admin-client` codegen target.
 * Produces `questpie/admin/.generated/client.ts` — a plain admin config
 * object that merges module defaults with user-discovered files.
 *
 * ## Architecture
 *
 * The admin-client target works identically to the server target:
 *
 * 1. **Package mode** (`generatePackageModules`): discovers files from
 *    `modules/admin/client/` → generates `modules/admin/client/.generated/module.ts`
 *    using the standard `generateModuleTemplate()` primitive.
 *
 * 2. **Root app mode** (`runAllTargets`): user has `admin/modules.ts` that imports
 *    module packages → this template imports `_mod` and merges generically with
 *    user-discovered files from `admin/{blocks,views,fields,...}/`.
 *
 * ## How to create an admin-client module (for third-party packages)
 *
 * 1. Create wrapper files in `modules/<name>/client/{fields,views,...}/`
 * 2. Run `questpie generate` — generates `client/.generated/module.ts`
 * 3. Create `client/index.ts` that re-exports the generated module
 * 4. Add `"./client/module"` to `package.json` exports
 *
 * ## How users extend admin
 *
 * Add files in `questpie/admin/{views,fields,pages,widgets,blocks,components}/`.
 * They are discovered automatically and merged over module defaults.
 *
 * ## Category key strategies
 *
 * - Default: use file key — `"bookingCta": _block_bookingCta`
 * - `keyFromProperty: "name"`: use runtime key — `[_view_kanban.name]: _view_kanban`
 *
 * The strategy is declared per-category in `CategoryDeclaration.keyFromProperty`.
 *
 */

import {
	categoryRecordEntry,
	generateModuleTemplate,
	importStatement,
	sortedValues,
} from "questpie/codegen";
import type {
	CategoryDeclaration,
	CodegenTargetGenerateContext,
	CodegenTargetOutput,
	DiscoveredFile,
} from "questpie/codegen";

/**
 * Generate the admin client output for one target run.
 *
 * Iterates `ctx.discovered.categories` generically — no hardcoded category names.
 * Any plugin can add categories, any user can add files in any category.
 *
 * Two shapes come out of here, and `ctx.module` picks between them. A package
 * module has to emit a module definition, because a hand-written `index.ts`
 * re-exports it and consumers read `AdminModule` and per-category keys off it.
 * An app emits the merged admin config instead.
 */
export function generateAdminClientTemplate(
	ctx: CodegenTargetGenerateContext,
): CodegenTargetOutput {
	if (ctx.module) return generateAdminClientModule(ctx, ctx.module.name);
	const lines: string[] = [];
	const modulesFile = ctx.discovered.singles.get("modules") ?? null;

	// Header
	lines.push("/**");
	lines.push(" * Admin Client Config");
	lines.push(" *");
	lines.push(" * Auto-generated by questpie codegen — do not edit.");
	lines.push(" *");
	lines.push(" * Pass this directly to <AdminLayoutProvider admin={admin} />");
	lines.push(" */");
	lines.push("");

	// ── 1. Import modules (if discovered) ───────────────────────
	if (modulesFile) {
		lines.push(importStatement(modulesFile));
		lines.push("type _AdminModuleMergeAcc = Record<string, unknown>;");
		lines.push(`const _mergedModules = (Array.isArray(${modulesFile.varName})`);
		lines.push(
			`\t? ${modulesFile.varName}.reduce<_AdminModuleMergeAcc>((acc, mod) => {`,
		);
		lines.push(
			'\t\tfor (const [k, v] of Object.entries(mod)) acc[k] = typeof v === "object" && v !== null && !Array.isArray(v) ? { ...(typeof acc[k] === "object" && acc[k] !== null && !Array.isArray(acc[k]) ? acc[k] as Record<string, unknown> : {}), ...(v as Record<string, unknown>) } : v;',
		);
		lines.push("\t\treturn acc;");
		lines.push(`\t}, {}) : ${modulesFile.varName}) as _AdminModuleMergeAcc;`);
	}

	// ── 2. Import all user-discovered category files ────────────
	const categoryFiles = new Map<string, DiscoveredFile[]>();

	for (const [cat, fileMap] of ctx.discovered.categories) {
		if (fileMap.size > 0) {
			const sorted = sortedValues(fileMap);
			categoryFiles.set(cat, sorted);
			for (const file of sorted) {
				lines.push(importStatement(file));
			}
		}
	}

	// ── 3. Import discovered singles (locale, translations, defaults) ──
	const singleFiles = new Map<string, DiscoveredFile>();
	for (const [key, file] of ctx.discovered.singles) {
		if (key === "modules") continue; // Already handled above
		singleFiles.set(key, file);
		lines.push(importStatement(file));
	}

	// ── 4. Import extras from transforms ────────────────────────
	for (const imp of ctx.extraImports) {
		lines.push(`import ${imp.name} from "${imp.path}";`);
	}

	lines.push("");

	// ── 5. Build the admin object ───────────────────────────────
	// Iterate categories generically — driven by ctx.discovered.categories,
	// NOT a hardcoded list. If a future plugin adds "themes" category, it
	// works automatically.

	const hasAnyUserFiles = categoryFiles.size > 0 || singleFiles.size > 0;
	const hasExtraCode = ctx.extraRuntimeCode.length > 0;

	// Determine all category names that need to appear in the output.
	// This includes categories with user files AND categories that exist
	// only in the module (no user files, but module provides them).
	const allCategories = new Set<string>();
	for (const cat of ctx.discovered.categories.keys()) {
		allCategories.add(cat);
	}
	// Also include categories declared by the target but not discovered
	// (module may provide them even if user has no files)
	if (ctx.target.categories) {
		for (const cat of Object.keys(ctx.target.categories)) {
			allCategories.add(cat);
		}
	}

	if (!hasAnyUserFiles && !hasExtraCode && !modulesFile) {
		// Nothing at all — emit empty object
		lines.push("const admin = {};");
	} else if (!hasAnyUserFiles && !hasExtraCode && modulesFile) {
		// Module only, no user overrides — re-export module directly
		lines.push("const admin = _mergedModules;");
	} else {
		lines.push("const admin = {");

		// Merge each category
		for (const cat of allCategories) {
			const files = categoryFiles.get(cat);
			const catDecl = ctx.target.categories?.[cat];

			if (modulesFile && files && files.length > 0) {
				// Module base + user overrides
				const entries = files
					.map((f) => categoryRecordEntry(f, catDecl))
					.join(", ");
				lines.push(
					`\t${cat}: { ...(_mergedModules[${JSON.stringify(cat)}] as Record<string, unknown>), ${entries} },`,
				);
			} else if (modulesFile && (!files || files.length === 0)) {
				// Module base, no user overrides — spread module category
				lines.push(
					`\t${cat}: { ...(_mergedModules[${JSON.stringify(cat)}] as Record<string, unknown>) },`,
				);
			} else if (files && files.length > 0) {
				// No module, user files only
				const entries = files
					.map((f) => categoryRecordEntry(f, catDecl))
					.join(", ");
				lines.push(`\t${cat}: { ${entries} },`);
			}
		}

		// Merge discovered singles (override module values)
		for (const [key, file] of singleFiles) {
			lines.push(`\t${key}: ${file.varName},`);
		}

		// Extra runtime code from transforms
		for (const code of ctx.extraRuntimeCode) {
			lines.push(`\t${code}`);
		}

		lines.push("};");
	}

	// Extra type declarations
	if (ctx.extraTypeDeclarations.length > 0) {
		lines.push("");
		for (const decl of ctx.extraTypeDeclarations) {
			lines.push(decl);
		}
	}

	lines.push("");
	lines.push("export default admin;");
	lines.push("");

	return { code: lines.join("\n") };
}

/**
 * Module-mode output: the standard module definition.
 *
 * Delegating keeps package modules on one emitter. The admin client target only
 * differs from the server target in what it discovers, not in the shape it has
 * to produce for a package, and the shared template is what carries the named
 * category types, the empty-category stubs and the registries file.
 */
function generateAdminClientModule(
	ctx: CodegenTargetGenerateContext,
	moduleName: string,
): CodegenTargetOutput {
	const categoryMeta = new Map<string, CategoryDeclaration>(
		Object.entries(ctx.target.categories ?? {}),
	);

	const result = generateModuleTemplate({
		moduleName,
		discovered: ctx.discovered,
		categoryMeta,
		regenerateCommand: ctx.regenerateCommand,
		extraImports: ctx.extraImports.length > 0 ? ctx.extraImports : undefined,
		extraTypeDeclarations:
			ctx.extraTypeDeclarations.length > 0
				? ctx.extraTypeDeclarations
				: undefined,
		extraModuleProperties:
			ctx.extraRuntimeCode.length > 0 ? ctx.extraRuntimeCode : undefined,
	});

	return {
		code: result.code,
		additionalFiles: result.registriesCode
			? { "registries.ts": result.registriesCode }
			: undefined,
	};
}
