/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

// ── Collections ────────────────────────────────────────────
import _coll_jwks from "../collections/jwks";
import _coll_oauthAccessToken from "../collections/oauth-access-token";
import _coll_oauthClient from "../collections/oauth-client";
import _coll_oauthClientAssertion from "../collections/oauth-client-assertion";
import _coll_oauthClientResource from "../collections/oauth-client-resource";
import _coll_oauthConsent from "../collections/oauth-consent";
import _coll_oauthRefreshToken from "../collections/oauth-refresh-token";
import _coll_oauthResource from "../collections/oauth-resource";

// ── Singles ────────────────────────────────────────────────
import _authConfig from "../config/auth";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export type OauthCollections = {
	jwks: typeof _coll_jwks;
	oauthAccessToken: typeof _coll_oauthAccessToken;
	oauthClient: typeof _coll_oauthClient;
	oauthClientAssertion: typeof _coll_oauthClientAssertion;
	oauthClientResource: typeof _coll_oauthClientResource;
	oauthConsent: typeof _coll_oauthConsent;
	oauthRefreshToken: typeof _coll_oauthRefreshToken;
	oauthResource: typeof _coll_oauthResource;
};

export type OauthChannels = Record<never, never>;

export type OauthGlobals = Record<never, never>;

export type OauthJobs = Record<never, never>;

export type OauthRoutes = Record<never, never>;

export type OauthFieldTypes = Record<never, never>;

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type OauthModule = {
	name: "questpie-oauth";
	collections: OauthCollections;
	channels: OauthChannels;
	globals: OauthGlobals;
	jobs: OauthJobs;
	routes: OauthRoutes;
	fieldTypes: OauthFieldTypes;
	messages: Record<never, never>;
	services: Record<never, never>;
	emailTemplates: Record<never, never>;
	migrations: readonly unknown[];
	seeds: readonly unknown[];
	config: {
		auth: typeof _authConfig;
	};
};

const _module: OauthModule = {
	name: "questpie-oauth" as const,
	collections: {
		jwks: _coll_jwks,
		oauthAccessToken: _coll_oauthAccessToken,
		oauthClient: _coll_oauthClient,
		oauthClientAssertion: _coll_oauthClientAssertion,
		oauthClientResource: _coll_oauthClientResource,
		oauthConsent: _coll_oauthConsent,
		oauthRefreshToken: _coll_oauthRefreshToken,
		oauthResource: _coll_oauthResource,
	} as OauthCollections,
	channels: {},
	globals: {},
	jobs: {},
	routes: {},
	messages: {},
	services: {},
	emailTemplates: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	config: {
		auth: _authConfig,
	},
};

export default _module;
