/**
 * Factory Template Generation
 *
 * Generates `.generated/factories.ts` — typed `collection()` and `global()`
 * factory functions with plugin extensions, singleton factory functions
 * (branding, sidebar, locale, etc.), and module-driven type extraction
 * for autocomplete on proxies (views, components, field types).
 *
 * Extension methods are intercepted by a Proxy wrapper that delegates to
 * `builder.set()`. Core builder methods are passed through and their results
 * are re-wrapped to preserve the Proxy chain across immutable builder calls.
 *
 * @see RFC-CONTEXT-FIRST §6 (Extension System Without Monkey-Patching)
 */

import type {
	CodegenPlugin,
	ModuleRegistryConfig,
	RegistryExtension,
	SingletonFactory,
} from "./types.js";

// ============================================================================
// Factory generation
// ============================================================================

export interface FactoryTemplateOptions {
	/** Codegen plugins with registries. */
	plugins: CodegenPlugin[];
	/** Whether modules.ts exists (new architecture). */
	hasModules: boolean;
}

/**
 * Generate `.generated/factories.ts` content.
 * Returns null if no plugins declare registries (no factories needed).
 */
export function generateFactoryTemplate(
	options: FactoryTemplateOptions,
): string | null {
	const { plugins, hasModules } = options;

	// Collect all extensions from all plugins
	const collExtensions = new Map<string, RegistryExtension>();
	const globalExtensions = new Map<string, RegistryExtension>();
	const singletonFactories = new Map<string, SingletonFactory>();
	const allImports = new Map<string, Set<string>>(); // from → Set<name>

	for (const plugin of plugins) {
		if (!plugin.registries) continue;

		if (plugin.registries.collectionExtensions) {
			for (const [name, ext] of Object.entries(
				plugin.registries.collectionExtensions,
			)) {
				collExtensions.set(name, ext);
				collectImports(ext, allImports);
			}
		}

		if (plugin.registries.globalExtensions) {
			for (const [name, ext] of Object.entries(
				plugin.registries.globalExtensions,
			)) {
				globalExtensions.set(name, ext);
				collectImports(ext, allImports);
			}
		}

		if (plugin.registries.singletonFactories) {
			for (const [name, factory] of Object.entries(
				plugin.registries.singletonFactories,
			)) {
				singletonFactories.set(name, factory);
				collectSingletonImports(factory, allImports);
			}
		}
	}

	// Collect module registries from all plugins
	const moduleRegistries = new Map<string, ModuleRegistryConfig>();
	for (const plugin of plugins) {
		if (plugin.registries?.moduleRegistries) {
			for (const [key, config] of Object.entries(plugin.registries.moduleRegistries)) {
				moduleRegistries.set(key, config);
			}
		}
	}

	// If nothing declared, no factories file needed
	if (
		collExtensions.size === 0 &&
		globalExtensions.size === 0 &&
		singletonFactories.size === 0
	) {
		return null;
	}

	// Collect all configTypePlaceholders → category mappings
	const placeholderCategories = new Map<string, string>();
	for (const ext of [...collExtensions.values(), ...globalExtensions.values()]) {
		if (ext.configTypePlaceholders) {
			for (const [placeholder, category] of Object.entries(
				ext.configTypePlaceholders,
			)) {
				placeholderCategories.set(placeholder, category);
			}
		}
	}

	const lines: string[] = [];

	// Header
	lines.push("/* eslint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push(
		"// Typed factory functions with plugin extensions. Regenerate with: questpie generate",
	);
	lines.push("");

	// Core imports
	lines.push("// ── Core Imports ───────────────────────────────────────────");
	lines.push(
		'import { CollectionBuilder, GlobalBuilder, builtinFields, type BuiltinFields, type EmptyCollectionState, type EmptyGlobalState } from "questpie";',
	);
	lines.push("");

	// Module import (for type extraction AND runtime field merging)
	if (hasModules) {
		lines.push("// ── Module import (for type extraction + runtime fields) ──");
		lines.push('import _modulesArr from "../modules";');
		lines.push("");
	}

	// Plugin imports (only types needed for signatures)
	if (allImports.size > 0) {
		lines.push("// ── Plugin Imports ─────────────────────────────────────────");
		for (const [from, names] of allImports) {
			const nameList = [...names]
				.filter((n) => /^[A-Z]/.test(n)) // only types (PascalCase)
				.map((n) => `type ${n}`)
				.join(", ");
			const valueList = [...names]
				.filter((n) => /^[a-z]/.test(n)) // runtime values (camelCase)
				.join(", ");
			const parts = [nameList, valueList].filter(Boolean).join(", ");
			if (parts) {
				lines.push(`import { ${parts} } from "${from}";`);
			}
		}
		lines.push("");
	}

	// ── Module type extraction ──────────────────────────────
	if (hasModules) {
		lines.push("// ════════════════════════════════════════════════════════════");
		lines.push("// Module type extraction — views, components, field types");
		lines.push("// ════════════════════════════════════════════════════════════");
		lines.push("");

		lines.push(
			"type _FlattenModules<T> = T extends readonly (infer M)[]",
		);
		lines.push(
			"  ? M | (M extends { modules: infer Sub } ? _FlattenModules<Sub> : never)",
		);
		lines.push("  : never;");
		lines.push("type _AllModules = _FlattenModules<typeof _modulesArr>;");
		lines.push("");

		// Extract keys helper
		lines.push("// Module registry names — extracted from module registrations");
		lines.push(
			'type _ExtractKeys<K extends string> = _AllModules extends infer M ? M extends Record<K, Record<infer V extends string, any>> ? V : never : never;',
		);

		// Dynamic: generate type alias for each moduleRegistry
		for (const [key] of moduleRegistries) {
			const typeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names`;
			lines.push(`type ${typeName} = _ExtractKeys<"${key}"> | (string & {});`);
		}
		lines.push("");

		// Extract field types from modules
		lines.push("// Field types — module-provided fields merged with builtins");
		lines.push(
			"type _U2I<U> = (U extends any ? (x: U) => void : never) extends (x: infer I) => void ? I : never;",
		);
		lines.push(
			'type _ModuleFieldTypes = _U2I<_AllModules extends infer M ? M extends { fields: infer F } ? F : never : never>;',
		);
		lines.push(
			"type _AllFieldTypes = [_ModuleFieldTypes] extends [never] ? BuiltinFields : BuiltinFields & _ModuleFieldTypes;",
		);
		lines.push("");
	} else {
		// No modules — use string fallback for all module registries
		lines.push("// No modules.ts — using string fallback for type extraction");
		for (const [key] of moduleRegistries) {
			const typeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names`;
			lines.push(`type ${typeName} = string;`);
		}
		lines.push("type _AllFieldTypes = BuiltinFields;");
		lines.push("");
	}

	// ── Runtime field merging ────────────────────────────────
	if (hasModules) {
		lines.push("// ── Runtime: merge module fields with builtins ──────────────");
		lines.push("function _extractModuleFields(modules: readonly any[]): Record<string, any> {");
		lines.push("\tconst merged: Record<string, any> = {};");
		lines.push("\tfor (const m of modules) {");
		lines.push("\t\tif (m.fields) Object.assign(merged, m.fields);");
		lines.push("\t\tif (m.modules) Object.assign(merged, _extractModuleFields(m.modules));");
		lines.push("\t}");
		lines.push("\treturn merged;");
		lines.push("}");
		lines.push("const _allRuntimeFields = { ...builtinFields, ..._extractModuleFields(_modulesArr) };");
		lines.push("");
	}

	// ── Type augmentations (declare module) ────────────────────
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// Type augmentations — generated from plugin registries");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	const placeholderMap = buildPlaceholderMap(moduleRegistries);

	lines.push('declare module "questpie" {');

	if (collExtensions.size > 0) {
		lines.push("\tinterface CollectionBuilder<TState> {");
		for (const [name, ext] of collExtensions) {
			const paramName = ext.isCallback ? "configFn" : "config";
			let paramType = ext.configType ?? "any";
			paramType = resolvePlaceholders(paramType, hasModules, placeholderMap);
			lines.push(
				`\t\t${name}(${paramName}: ${paramType}): CollectionBuilder<TState>;`,
			);
		}
		lines.push("\t}");
	}

	if (globalExtensions.size > 0) {
		lines.push("\tinterface GlobalBuilder<TState> {");
		for (const [name, ext] of globalExtensions) {
			const paramName = ext.isCallback ? "configFn" : "config";
			let paramType = ext.configType ?? "any";
			paramType = resolvePlaceholders(paramType, hasModules, placeholderMap);
			lines.push(
				`\t\t${name}(${paramName}: ${paramType}): GlobalBuilder<TState>;`,
			);
		}
		lines.push("\t}");
	}

	// Registry entries from module registries
	const registryEntries = [...moduleRegistries.entries()].filter(([_, c]) => c.registryKey);
	if (registryEntries.length > 0) {
		lines.push("\tinterface Registry {");
		for (const [key, config] of registryEntries) {
			const typeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names`;
			lines.push(`\t\t${config.registryKey}: Record<${typeName}, unknown>;`);
		}
		lines.push("\t}");
	}

	lines.push("}");
	lines.push("");

	// ── Extension registries + Proxy wrappers ─────────────────
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// Extension registries + Proxy wrappers");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	if (collExtensions.size > 0) {
		emitExtensionRegistry(lines, "_collExt", collExtensions);
		lines.push("");
		emitProxyWrapper(lines, "_wrapColl", "_collExt", "CollectionBuilder");
		lines.push("");
	}

	if (globalExtensions.size > 0) {
		emitExtensionRegistry(lines, "_globExt", globalExtensions);
		lines.push("");
		emitProxyWrapper(lines, "_wrapGlob", "_globExt", "GlobalBuilder");
		lines.push("");
	}

	// ── Factory functions ─────────────────────────────────────
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// Factory functions");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	// collection()
	if (collExtensions.size > 0) {
		lines.push("/**");
		lines.push(
			" * Create a typed collection builder with plugin extensions.",
		);
		lines.push(" *");
		lines.push(" * @example");
		lines.push(" * ```ts");
		lines.push(' * import { collection } from "#questpie";');
		lines.push(" *");
		lines.push(' * export default collection("posts")');
		lines.push(
			" *   .fields(({ f }) => ({ title: f.text({ required: true }) }))",
		);
		lines.push(
			' *   .admin(({ c }) => ({ icon: c.icon("ph:article") }))',
		);
		lines.push(
			" *   .list(({ v, f }) => v.table({ columns: [f.title] }))",
		);
		lines.push(" * ```");
		lines.push(" */");
		lines.push(
			"export function collection<TName extends string>(name: TName): CollectionBuilder<EmptyCollectionState<TName, undefined, _AllFieldTypes>> {",
		);
		lines.push("\treturn _wrapColl(new CollectionBuilder({");
		lines.push("\t\tname: name as string,");
		lines.push("\t\tfields: {},");
		lines.push("\t\tlocalized: [],");
		lines.push("\t\tvirtuals: undefined,");
		lines.push("\t\trelations: {},");
		lines.push("\t\tindexes: {},");
		lines.push("\t\ttitle: undefined,");
		lines.push("\t\toptions: {},");
		lines.push("\t\thooks: {},");
		lines.push("\t\taccess: {},");
		lines.push("\t\tsearchable: undefined,");
		lines.push("\t\tvalidation: undefined,");
		lines.push("\t\toutput: undefined,");
		lines.push("\t\tupload: undefined,");
		lines.push("\t\tfieldDefinitions: {},");
		if (hasModules) {
			lines.push('\t\t"~questpieApp": { state: { fields: _allRuntimeFields } },');
		} else {
			lines.push('\t\t"~questpieApp": undefined,');
		}
		lines.push("\t})) as any;");
		lines.push("}");
		lines.push("");
	}

	// global()
	if (globalExtensions.size > 0) {
		lines.push("/**");
		lines.push(" * Create a typed global builder with plugin extensions.");
		lines.push(" */");
		lines.push(
			"export function global<TName extends string>(name: TName): GlobalBuilder<EmptyGlobalState<TName, undefined, _AllFieldTypes>> {",
		);
		lines.push("\treturn _wrapGlob(new GlobalBuilder({");
		lines.push("\t\tname: name as string,");
		lines.push("\t\tfields: {},");
		lines.push("\t\tlocalized: [],");
		lines.push("\t\tvirtuals: {},");
		lines.push("\t\trelations: {},");
		lines.push("\t\toptions: {},");
		lines.push("\t\thooks: {},");
		lines.push("\t\taccess: {},");
		lines.push("\t\tfieldDefinitions: {},");
		if (hasModules) {
			lines.push('\t\t"~questpieApp": { state: { fields: _allRuntimeFields } },');
		} else {
			lines.push('\t\t"~questpieApp": undefined,');
		}
		lines.push("\t})) as any;");
		lines.push("}");
		lines.push("");
	}

	// ── Singleton factory functions ────────────────────────────
	if (singletonFactories.size > 0) {
		lines.push("// ════════════════════════════════════════════════════════════");
		lines.push("// Singleton factory functions");
		lines.push("// ════════════════════════════════════════════════════════════");
		lines.push("");

		for (const [name, factory] of singletonFactories) {
			emitSingletonFactory(lines, name, factory);
			lines.push("");
		}
	}

	return lines.join("\n");
}

// ============================================================================
// Singleton factory emission
// ============================================================================

/**
 * Emit a singleton factory function.
 * Non-callback: simple generic identity with type constraint.
 * Callback: overloaded identity accepting both plain config and callback.
 */
function emitSingletonFactory(
	lines: string[],
	name: string,
	factory: SingletonFactory,
): void {
	const { configType, isCallback } = factory;

	if (isCallback) {
		// Overloaded — accepts plain config or callback function
		lines.push(`/** Typed factory for ${name} config. Accepts plain config or callback. */`);
		lines.push(
			`export function ${name}<T extends ${configType}>(config: T): T;`,
		);
		lines.push(
			`export function ${name}<T extends (...args: any[]) => ${configType}>(cb: T): T;`,
		);
		lines.push(`export function ${name}(v: any): any { return v; }`);
	} else {
		// Simple identity with type constraint
		lines.push(`/** Typed factory for ${name} config. */`);
		lines.push(
			`export function ${name}<T extends ${configType}>(config: T): T { return config; }`,
		);
	}
}

// ============================================================================
// Placeholder resolution
// ============================================================================

/**
 * Build a placeholder → type alias mapping from moduleRegistries.
 * Each moduleRegistry with a `placeholder` gets an entry that maps
 * the placeholder token to the generated type alias name.
 */
function buildPlaceholderMap(
	moduleRegistries: Map<string, ModuleRegistryConfig>,
): Record<string, { withModules: string; fallback: string }> {
	const map: Record<string, { withModules: string; fallback: string }> = {};
	for (const [key, config] of moduleRegistries) {
		if (config.placeholder) {
			const typeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names`;
			map[config.placeholder] = { withModules: typeName, fallback: "string" };
		}
	}
	return map;
}

/**
 * Replace $PLACEHOLDER tokens in a configType string with resolved type aliases.
 */
function resolvePlaceholders(
	configType: string,
	hasModules: boolean,
	placeholderMap: Record<string, { withModules: string; fallback: string }>,
): string {
	let result = configType;
	for (const [placeholder, aliases] of Object.entries(placeholderMap)) {
		if (result.includes(placeholder)) {
			result = result.replaceAll(
				placeholder,
				hasModules ? aliases.withModules : aliases.fallback,
			);
		}
	}
	return result;
}

// ============================================================================
// Extension registry + Proxy wrapper emission
// ============================================================================

/**
 * Emit an extension registry object that maps method names to their
 * stateKey and resolve logic (callback context creation).
 */
function emitExtensionRegistry(
	lines: string[],
	varName: string,
	extensions: Map<string, RegistryExtension>,
): void {
	lines.push(
		`const ${varName}: Record<string, { stateKey: string; resolve: (v: any) => any }> = {`,
	);
	for (const [name, ext] of extensions) {
		if (ext.isCallback) {
			lines.push(`\t${name}: {`);
			lines.push(`\t\tstateKey: "${ext.stateKey}",`);
			lines.push("\t\tresolve(configOrFn: any) {");
			lines.push(
				`\t\t\tif (typeof configOrFn === 'function') return configOrFn(${emitCallbackContext(ext)});`,
			);
			lines.push("\t\t\treturn configOrFn;");
			lines.push("\t\t},");
			lines.push("\t},");
		} else {
			lines.push(
				`\t${name}: { stateKey: "${ext.stateKey}", resolve: (v: any) => v },`,
			);
		}
	}
	lines.push("};");
}

/**
 * Emit a Proxy wrapper function that intercepts extension method calls
 * and delegates to `builder.set()`. Also re-wraps builder-returning
 * methods so the Proxy chain is preserved across immutable builder calls.
 */
function emitProxyWrapper(
	lines: string[],
	fnName: string,
	registryVar: string,
	builderClass: string,
): void {
	lines.push(`function ${fnName}(builder: any): any {`);
	lines.push("\treturn new Proxy(builder, {");
	lines.push("\t\tget(target, prop, receiver) {");
	lines.push(
		`\t\t\tif (typeof prop === 'string' && prop in ${registryVar}) {`,
	);
	lines.push(`\t\t\t\tconst ext = ${registryVar}[prop];`);
	lines.push(
		`\t\t\t\treturn (configOrFn: any) => ${fnName}(target.set(ext.stateKey, ext.resolve(configOrFn)));`,
	);
	lines.push("\t\t\t}");
	lines.push("\t\t\tconst val = Reflect.get(target, prop, receiver);");
	lines.push("\t\t\tif (typeof val === 'function') {");
	lines.push("\t\t\t\treturn function(this: any, ...args: any[]) {");
	lines.push("\t\t\t\t\tconst result = val.apply(target, args);");
	lines.push(
		`\t\t\t\t\treturn result instanceof ${builderClass} ? ${fnName}(result) : result;`,
	);
	lines.push("\t\t\t\t};");
	lines.push("\t\t\t}");
	lines.push("\t\t\treturn val;");
	lines.push("\t\t},");
	lines.push("\t});");
	lines.push("}");
}

// ============================================================================
// Helpers
// ============================================================================

function collectImports(
	ext: RegistryExtension,
	allImports: Map<string, Set<string>>,
): void {
	if (!ext.imports) return;
	for (const imp of ext.imports) {
		let names = allImports.get(imp.from);
		if (!names) {
			names = new Set();
			allImports.set(imp.from, names);
		}
		names.add(imp.name);
	}
}

function collectSingletonImports(
	factory: SingletonFactory,
	allImports: Map<string, Set<string>>,
): void {
	for (const imp of factory.imports) {
		let names = allImports.get(imp.from);
		if (!names) {
			names = new Set();
			allImports.set(imp.from, names);
		}
		names.add(imp.name);
	}
}

/**
 * Emit the callback context object for a callback-style extension.
 * Creates simple proxies for field ref, view, action, and component helpers.
 */
function emitCallbackContext(ext: RegistryExtension): string {
	if (!ext.callbackContextParams || ext.callbackContextParams.length === 0) {
		return "{}";
	}

	const params: string[] = [];
	for (const param of ext.callbackContextParams) {
		switch (param) {
			case "f":
				// Field ref proxy: f.title → "title"
				params.push(
					'f: new Proxy({}, { get: (_, prop) => String(prop) })',
				);
				break;
			case "v":
				// View proxy: v.table({...}) → { view: "table", ...config }
				params.push(
					'v: new Proxy({}, { get: (_, prop) => (config: any) => ({ view: String(prop), ...config }) })',
				);
				break;
			case "c":
				// Component proxy: c.icon("ph:users") → { type: "icon", props: { name: "ph:users" } }
				params.push(
					'c: new Proxy({}, { get: (_, prop) => (...args: any[]) => ({ type: String(prop), props: typeof args[0] === "string" ? { name: args[0] } : args[0] ?? {} }) })',
				);
				break;
			case "a":
				// Action proxy: a.create → "create", a.custom(name, config) → { id: name, ...config }
				params.push(
					'a: new Proxy({ custom: (name: string, config: any) => ({ id: name, ...config }) }, { get: (target, prop) => (target as any)[prop] ?? String(prop) })',
				);
				break;
			default:
				params.push(`${param}: {}`);
		}
	}

	return `{ ${params.join(", ")} }`;
}
