/**
 * Module Template Generation
 *
 * Generates the `.generated/module.ts` file content for npm package modules.
 * The generated file:
 * 1. Imports all discovered entities (collections, functions, jobs, etc.)
 * 2. Imports sub-modules from `modules.ts` (if present)
 * 3. Emits type interfaces using typeof references (zero inference cost)
 * 4. Exports a plain static module definition object
 *
 * Unlike the root app template (template.ts), this does NOT:
 * - Import a runtime config
 * - Call createApp()
 * - Generate an App type
 *
 * @see RFC-MODULE-ARCHITECTURE §9.2 (Module — .generated/module.ts)
 */

import type { DiscoveryResult } from "./discover.js";
import type { DiscoveredFile } from "./types.js";

// ============================================================================
// Module template options
// ============================================================================

export interface ModuleTemplateOptions {
	/** Module name (e.g. "questpie-admin", "questpie-audit"). */
	moduleName: string;
	/** Discovery result with all found files. */
	discovered: DiscoveryResult;
	/** Additional imports from plugins (e.g. admin view/component factories). */
	extraImports?: Array<{ name: string; path: string }>;
	/** Additional type declarations from plugins. */
	extraTypeDeclarations?: string[];
	/**
	 * Additional runtime code to add to the module object.
	 * Each entry is a line like `listViews: { table: listView("table") },`.
	 */
	extraModuleProperties?: string[];
}

// ============================================================================
// Module template generation
// ============================================================================

/**
 * Generate the .generated/module.ts file content for a package module.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.2 (Module — .generated/module.ts)
 */
export function generateModuleTemplate(options: ModuleTemplateOptions): string {
	const lines: string[] = [];
	const {
		moduleName,
		discovered,
		extraImports,
		extraTypeDeclarations,
		extraModuleProperties,
	} = options;

	const modulesFile = discovered.singles.get("modules") ?? null;

	// Derive a PascalCase type prefix from the module name
	// "questpie-admin" → "Admin", "questpie-audit" → "Audit"
	const typePrefix = deriveTypePrefix(moduleName);

	// Header
	lines.push("/* eslint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push("// Regenerate with: questpie generate --module");
	lines.push("");

	// Import sub-modules
	if (modulesFile) {
		lines.push(
			"// ── Sub-Modules ────────────────────────────────────────────",
		);
		lines.push(importStatement(modulesFile));
		lines.push("");
	}

	// Import collections
	if (discovered.collections.size > 0) {
		lines.push(
			"// ── Collections ────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.collections)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import globals
	if (discovered.globals.size > 0) {
		lines.push(
			"// ── Globals ────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.globals)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import jobs
	if (discovered.jobs.size > 0) {
		lines.push(
			"// ── Jobs ───────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.jobs)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import functions
	if (discovered.functions.size > 0) {
		lines.push(
			"// ── Functions ──────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.functions)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import routes
	if (discovered.routes.size > 0) {
		lines.push(
			"// ── Routes ─────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.routes)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import messages
	if (discovered.messages.size > 0) {
		lines.push(
			"// ── Messages ───────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.messages)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import services
	if (discovered.services.size > 0) {
		lines.push(
			"// ── Services ───────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.services)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import auth
	if (discovered.auth) {
		lines.push(
			"// ── Auth ───────────────────────────────────────────────────",
		);
		lines.push(importStatement(discovered.auth));
		lines.push("");
	}

	// Import singles (locale, hooks, access, context, fields, sidebar, etc.)
	const singles = getNonModuleSingles(discovered.singles);
	if (singles.length > 0) {
		lines.push(
			"// ── Singles ────────────────────────────────────────────────",
		);
		for (const file of singles) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import custom (plugin-discovered directory files, e.g. blocks)
	for (const [stateKey, fileMap] of discovered.custom) {
		if (fileMap.size > 0) {
			const label = stateKey.charAt(0).toUpperCase() + stateKey.slice(1);
			lines.push(
				`// ── ${label} ──────────────────────────────────────────────`,
			);
			for (const file of sortedValues(fileMap)) {
				lines.push(importStatement(file));
			}
			lines.push("");
		}
	}

	// Extra plugin imports
	if (extraImports && extraImports.length > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const imp of extraImports) {
			lines.push(`import ${imp.name} from "${imp.path}";`);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// TYPES — module type extraction
	// ════════════════════════════════════════════════════════════

	const hasAnyEntities =
		discovered.collections.size > 0 ||
		discovered.globals.size > 0 ||
		discovered.jobs.size > 0 ||
		discovered.functions.size > 0 ||
		discovered.routes.size > 0;

	if (hasAnyEntities) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push(
			"// TYPES — composed from typeof references (zero inference cost)",
		);
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		// Always emit simple interfaces (no sub-module extends).
		//
		// Why not `extends _SubCollections`:
		//   Modules declare their OWN collections. When a module overrides a
		//   sub-module's collection (e.g. admin overrides starter's `account` with
		//   .merge().set("admin",...)), the override type is NOT a subtype of the
		//   original — TypeScript's `extends` constraint breaks.
		//
		//   Sub-module collection composition is handled upstream in the root app's
		//   index.ts via `ExtractFromModuleArray` and intersection types. Each module
		//   only needs to declare what IT directly provides.
		//
		// Why emit at all (not just infer from `_module`):
		//   Deep .merge().set() builder chains cause TS7056 ("inferred type exceeds
		//   maximum length"). Named interfaces give TypeScript a stable anchor.
		if (discovered.collections.size > 0) {
			emitSimpleTypeInterface(
				lines,
				`${typePrefix}Collections`,
				discovered.collections,
			);
		}
		if (discovered.globals.size > 0) {
			emitSimpleTypeInterface(
				lines,
				`${typePrefix}Globals`,
				discovered.globals,
			);
		}
		if (discovered.jobs.size > 0) {
			emitSimpleTypeInterface(lines, `${typePrefix}Jobs`, discovered.jobs);
		}
		if (discovered.functions.size > 0) {
			lines.push(`export interface ${typePrefix}Functions {`);
			const nested = buildNestedFunctions(discovered.functions);
			emitNestedTypeObject(lines, nested, 1);
			lines.push("}");
			lines.push("");
		}
		if (discovered.routes.size > 0) {
			emitSimpleTypeInterface(
				lines,
				`${typePrefix}Routes`,
				discovered.routes,
			);
		}
		for (const [stateKey, fileMap] of discovered.custom) {
			if (fileMap.size > 0) {
				const typeName = `${typePrefix}${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
				emitSimpleTypeInterface(lines, typeName, fileMap);
			}
		}
	}

	// Extra type declarations from plugins
	if (extraTypeDeclarations && extraTypeDeclarations.length > 0) {
		for (const decl of extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// MODULE DEFINITION — static plain object
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// MODULE DEFINITION — static plain object");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	lines.push("const _module = {");
	lines.push(`\tname: "${moduleName}" as const,`);

	// Sub-modules
	if (modulesFile) {
		lines.push(`\tmodules: ${modulesFile.varName},`);
	}

	// Collections — cast to named interface to prevent TS7056 with deep builder types
	if (discovered.collections.size > 0) {
		lines.push("\tcollections: {");
		for (const file of sortedValues(discovered.collections)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push(`\t} as ${typePrefix}Collections,`);
	}

	// Globals — cast to named interface to prevent TS7056
	if (discovered.globals.size > 0) {
		lines.push("\tglobals: {");
		for (const file of sortedValues(discovered.globals)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push(`\t} as ${typePrefix}Globals,`);
	}

	// Jobs — cast to named interface to prevent TS7056
	if (discovered.jobs.size > 0) {
		lines.push("\tjobs: {");
		for (const file of sortedValues(discovered.jobs)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push(`\t} as ${typePrefix}Jobs,`);
	}

	// Functions — nested
	if (discovered.functions.size > 0) {
		lines.push("\tfunctions: {");
		const nested = buildNestedFunctions(discovered.functions);
		emitNestedObject(lines, nested, 2);
		lines.push("\t},");
	}

	// Routes
	if (discovered.routes.size > 0) {
		lines.push("\troutes: {");
		for (const file of sortedValues(discovered.routes)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Messages
	if (discovered.messages.size > 0) {
		lines.push("\tmessages: {");
		for (const file of sortedValues(discovered.messages)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Services
	if (discovered.services.size > 0) {
		lines.push("\tservices: {");
		for (const file of sortedValues(discovered.services)) {
			lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Auth
	if (discovered.auth) {
		lines.push(`\tauth: ${discovered.auth.varName},`);
	}

	// Singles (hooks, access, sidebar as array, etc.)
	for (const file of singles) {
		// Some singles are arrays (sidebar, dashboard contributions)
		if (file.key === "sidebar" || file.key === "dashboard") {
			lines.push(`\t${safeKey(file.key)}: [${file.varName}],`);
		} else {
			lines.push(`\t${safeKey(file.key)}: ${file.varName},`);
		}
	}

	// Custom directory patterns (blocks, etc.)
	for (const [stateKey, fileMap] of discovered.custom) {
		if (fileMap.size > 0) {
			lines.push(`\t${safeKey(stateKey)}: {`);
			for (const file of sortedValues(fileMap)) {
				lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
			}
			lines.push("\t},");
		}
	}

	// Extra module properties from plugins
	if (extraModuleProperties && extraModuleProperties.length > 0) {
		for (const prop of extraModuleProperties) {
			lines.push(`\t${prop}`);
		}
	}

	lines.push("};");
	lines.push("");

	// Export type and default
	lines.push(`export type ${typePrefix}Module = typeof _module;`);
	lines.push("export default _module;");
	lines.push("");

	return lines.join("\n");
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Derive a PascalCase type prefix from a module name.
 * "questpie-admin" → "Admin"
 * "questpie-audit" → "Audit"
 * "billing" → "Billing"
 */
function deriveTypePrefix(moduleName: string): string {
	// Remove "questpie-" prefix if present
	const name = moduleName.replace(/^questpie-/, "");
	// Split on hyphens and PascalCase
	return name
		.split("-")
		.map((s) => s.charAt(0).toUpperCase() + s.slice(1))
		.join("");
}

/**
 * Get all singles except "modules" (which is handled separately).
 */
function getNonModuleSingles(
	singles: Map<string, DiscoveredFile>,
): DiscoveredFile[] {
	const result: DiscoveredFile[] = [];
	for (const [key, file] of singles) {
		if (key === "modules") continue;
		result.push(file);
	}
	return result.sort((a, b) => a.key.localeCompare(b.key));
}

/**
 * Emit a plain type interface for a module category (no sub-module extends).
 * Always emit named types to prevent TS7056 ("inferred type exceeds maximum
 * length") when collection builder types are deeply nested via .merge().set().
 */
function emitSimpleTypeInterface(
	lines: string[],
	typeName: string,
	fileMap: Map<string, DiscoveredFile>,
): void {
	lines.push(`export interface ${typeName} {`);
	for (const file of sortedValues(fileMap)) {
		lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
	}
	lines.push("}");
	lines.push("");
}

// ============================================================================
// Nested functions builder (shared with template.ts)
// ============================================================================

type NestedNode =
	| { type: "leaf"; varName: string }
	| { type: "branch"; children: Map<string, NestedNode> };

function buildNestedFunctions(
	functions: Map<string, DiscoveredFile>,
): Map<string, NestedNode> {
	const root = new Map<string, NestedNode>();
	for (const file of functions.values()) {
		const segments = file.key.split(".");
		let current = root;
		for (let i = 0; i < segments.length; i++) {
			const seg = segments[i];
			const isLast = i === segments.length - 1;
			if (isLast) {
				current.set(seg, { type: "leaf", varName: file.varName });
			} else {
				let node = current.get(seg);
				if (!node || node.type === "leaf") {
					node = { type: "branch", children: new Map() };
					current.set(seg, node);
				}
				current = (node as Extract<NestedNode, { type: "branch" }>).children;
			}
		}
	}
	return root;
}

function emitNestedObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: ${node.varName},`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedObject(lines, node.children, indent + 1);
			lines.push(`${tabs}},`);
		}
	}
}

function emitNestedTypeObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: typeof ${node.varName};`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedTypeObject(lines, node.children, indent + 1);
			lines.push(`${tabs}};`);
		}
	}
}

function sortedValues(map: Map<string, DiscoveredFile>): DiscoveredFile[] {
	return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
}

function importStatement(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	return `import ${file.varName} from "${file.importPath}";`;
}

function safeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return `"${key}"`;
}
