/**
 * Template Generation
 *
 * Generates the `.generated/index.ts` file content from discovered files.
 * The generated file:
 * 1. Imports the runtime config, modules, and all discovered entities
 * 2. Emits type interfaces using typeof references (zero inference cost)
 * 3. Calls createApp(definition, runtime) to create the app instance
 * 4. Exports the app and composed App type
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App — .generated/index.ts)
 */

import type { DiscoveryResult } from "./discover.js";
import type { CodegenPlugin, DiscoveredFile } from "./types.js";

// ============================================================================
// Template generation
// ============================================================================

export interface TemplateOptions {
	/** Path to questpie.config.ts relative to .generated directory. */
	configImportPath: string;
	/** Discovery result with all found files. */
	discovered: DiscoveryResult;
	/** Codegen plugins (for computing factory re-exports). */
	plugins?: CodegenPlugin[];
	/** Additional imports from plugins. */
	extraImports?: Array<{ name: string; path: string }>;
	/** Additional type declarations from plugins. */
	extraTypeDeclarations?: string[];
	/** Additional runtime code from plugins. */
	extraRuntimeCode?: string[];
	/** Additional entity keys to pass to createApp (from plugins). */
	extraEntities?: Map<string, string>;
}

/**
 * Generate the .generated/index.ts file content.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App — .generated/index.ts)
 */
export function generateTemplate(options: TemplateOptions): string {
	const lines: string[] = [];
	const {
		configImportPath,
		discovered,
		plugins,
		extraImports,
		extraTypeDeclarations,
		extraRuntimeCode,
		extraEntities,
	} = options;

	// modules.ts is required — new architecture only
	const modulesFile = discovered.singles.get("modules") ?? null;
	if (!modulesFile) {
		throw new Error(
			"[questpie] modules.ts is required. Create a modules.ts file in your questpie server directory.\n" +
			"See: https://questpie.com/docs/modules",
		);
	}

	// Header
	lines.push("/* eslint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push("// Regenerate with: questpie generate");
	lines.push("");

	// Import createApp + types
	lines.push(
		'import { createApp, extractAppServices, type Questpie, type AppContext, type Registry, type QuestpieConfig, type QueueClient } from "questpie";',
	);
	lines.push("");

	// Import runtime config
	lines.push("// ── Runtime ────────────────────────────────────────────────");
	lines.push(`import _runtime from "${configImportPath}";`);
	lines.push("");

	// Import modules from singles (new architecture)
	if (modulesFile) {
		lines.push(
			"// ── Modules ────────────────────────────────────────────────",
		);
		lines.push(importStatement(modulesFile));
		lines.push("");
	}

	// Import collections
	if (discovered.collections.size > 0) {
		lines.push(
			"// ── Collections ────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.collections)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import globals
	if (discovered.globals.size > 0) {
		lines.push(
			"// ── Globals ────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.globals)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import jobs
	if (discovered.jobs.size > 0) {
		lines.push(
			"// ── Jobs ───────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.jobs)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import functions
	if (discovered.functions.size > 0) {
		lines.push(
			"// ── Functions ──────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.functions)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import routes
	if (discovered.routes.size > 0) {
		lines.push(
			"// ── Routes ─────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.routes)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import messages
	if (discovered.messages.size > 0) {
		lines.push(
			"// ── Messages ───────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.messages)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import services
	if (discovered.services.size > 0) {
		lines.push(
			"// ── Services ───────────────────────────────────────────────",
		);
		lines.push(
			'import type { ServiceInstanceOf } from "questpie";',
		);
		for (const file of sortedValues(discovered.services)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import email templates
	if (discovered.emails.size > 0) {
		lines.push(
			"// ── Emails ──────────────────────────────────────────────────",
		);
		lines.push('import type { MailerService } from "questpie";');
		for (const file of sortedValues(discovered.emails)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import migrations
	if (discovered.migrations.size > 0) {
		lines.push(
			"// ── Migrations ─────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.migrations)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import seeds
	if (discovered.seeds.size > 0) {
		lines.push(
			"// ── Seeds ──────────────────────────────────────────────────",
		);
		for (const file of sortedValues(discovered.seeds)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import auth
	if (discovered.auth) {
		lines.push(
			"// ── Auth ───────────────────────────────────────────────────",
		);
		lines.push(importStatement(discovered.auth));
		lines.push("");
	}

	// Import core singles (locale, hooks, access, context) — excluding modules (already imported)
	const coreSingles = getCategorizedSingles(discovered.singles);
	if (coreSingles.core.length > 0) {
		lines.push(
			"// ── Core Singles ───────────────────────────────────────────",
		);
		for (const file of coreSingles.core) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import plugin singles (sidebar, dashboard, branding, adminLocale, etc.)
	if (coreSingles.plugin.length > 0) {
		lines.push(
			"// ── Plugin Singles ─────────────────────────────────────────",
		);
		for (const file of coreSingles.plugin) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import spread singles (sidebar, dashboard — mergeStrategy: "spread")
	for (const [stateKey, files] of discovered.spreads) {
		if (files.length > 0) {
			const label = stateKey.charAt(0).toUpperCase() + stateKey.slice(1);
			lines.push(
				`// ── ${label} (spread) ─────────────────────────────────────────`,
			);
			for (const file of files) {
				lines.push(importStatement(file));
			}
			lines.push("");
		}
	}

	// Import custom (plugin-discovered directory files, e.g. blocks)
	for (const [stateKey, fileMap] of discovered.custom) {
		if (fileMap.size > 0) {
			const label = stateKey.charAt(0).toUpperCase() + stateKey.slice(1);
			lines.push(
				`// ── ${label} ──────────────────────────────────────────────`,
			);
			for (const file of sortedValues(fileMap)) {
				lines.push(importStatement(file));
			}
			lines.push("");
		}
	}

	// Extra plugin imports
	if (extraImports && extraImports.length > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const imp of extraImports) {
			lines.push(`import ${imp.name} from "${imp.path}";`);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// TYPES — composed from typeof references (zero inference cost)
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push(
		"// TYPES — composed from typeof references (zero inference cost)",
	);
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	lines.push(
		"type _U2I<U> = (U extends any ? (x: U) => void : never) extends (x: infer I) => void ? I : never;",
	);
	lines.push(
		`type _Module = (typeof ${modulesFile.varName})[number];`,
	);
	lines.push(
		'type _MPRaw<K extends string> = _U2I<_Module extends infer M ? M extends Record<K, infer V> ? V : never : never>;',
	);
	lines.push(
		'type _MP<K extends string> = [_MPRaw<K>] extends [never] ? {} : _MPRaw<K>;',
	);
	lines.push("");

	// Extract each category
	const categories = [
		"collections",
		"globals",
		"jobs",
		"functions",
		"routes",
		"services",
	];
	for (const cat of categories) {
		const typeName = `_Module${cat.charAt(0).toUpperCase() + cat.slice(1)}`;
		lines.push(`type ${typeName} = _MP<"${cat}">;`);
	}
	// Also extract custom keys (blocks, etc.) from modules
	for (const [stateKey] of discovered.custom) {
		const moduleTypeName = `_Module${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
		lines.push(`type ${moduleTypeName} = _MP<"${stateKey}">;`);
	}
	// Also extract spread keys (sidebar, dashboard, etc.) from modules
	for (const [stateKey] of discovered.spreads) {
		const moduleTypeName = `_Module${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
		lines.push(`type ${moduleTypeName} = _MP<"${stateKey}">;`);
	}
	lines.push("");

	// AppCollections — module contributions + user overrides
	emitTypeInterface(
		lines,
		"AppCollections",
		"_ModuleCollections",
		discovered.collections,
	);
	// AppGlobals — module contributions + user overrides
	emitTypeInterface(lines, "AppGlobals", "_ModuleGlobals", discovered.globals);
	// AppJobs — module contributions + user overrides
	emitTypeInterface(lines, "AppJobs", "_ModuleJobs", discovered.jobs);

	// AppFunctions — module contributions + user overrides (nested from directory layout)
	{
		const hasUser = discovered.functions.size > 0;
		lines.push(
			"/** All functions in the app (modules + user, user overrides) */",
		);
		if (hasUser) {
			lines.push("export type AppFunctions = _ModuleFunctions & {");
			const nested = buildNestedFunctions(discovered.functions);
			emitNestedTypeObject(lines, nested, 1);
			lines.push("};");
		} else {
			lines.push("export type AppFunctions = _ModuleFunctions;");
		}
		lines.push("");
	}

	// AppRoutes — module contributions + user overrides
	emitTypeInterface(lines, "AppRoutes", "_ModuleRoutes", discovered.routes);

	// AppServices — user services with typed instances
	{
		const hasUserServices = discovered.services.size > 0;
		lines.push(
			"/** All services in the app (modules + user, user overrides). Values are service instances. */",
		);
		if (hasUserServices) {
			lines.push("export type AppServices = _ModuleServices & {");
			for (const file of sortedValues(discovered.services)) {
				lines.push(`\t${safeKey(file.key)}: ServiceInstanceOf<typeof ${file.varName}>;`);
			}
			lines.push("};");
		} else {
			lines.push("export type AppServices = _ModuleServices;");
		}
		lines.push("");
	}

	// AppEmailTemplates — typed record for email.sendTemplate()
	{
		const hasEmails = discovered.emails.size > 0;
		lines.push("/** All email templates in the app — use with email.sendTemplate() */");
		if (hasEmails) {
			lines.push("export type AppEmailTemplates = {");
			for (const file of sortedValues(discovered.emails)) {
				lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
			}
			lines.push("};");
		} else {
			lines.push("export type AppEmailTemplates = Record<string, never>;");
		}
		lines.push("");
	}

	// AppBlocks and other custom plugin types — module contributions + user overrides
	for (const [stateKey, fileMap] of discovered.custom) {
		const typeName = `App${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
		const moduleTypeName = `_Module${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
		emitTypeInterface(lines, typeName, moduleTypeName, fileMap);
	}

	// AppMessageKeys
	if (discovered.messages.size > 0) {
		lines.push("/** Message keys — union of all keys from all locales */");
		const msgParts = sortedValues(discovered.messages).map(
			(f) => `keyof typeof ${f.varName}`,
		);
		lines.push(`export type AppMessageKeys = ${msgParts.join(" | ")};`);
		lines.push("");
	}

	// Extra type declarations from plugins
	if (extraTypeDeclarations && extraTypeDeclarations.length > 0) {
		for (const decl of extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// _AppInternal — internal Questpie<> type used only for type derivation
	// Not exported — users see App (standalone interface) and AppContext (augmented)
	{
		const stateMembers: string[] = [];
		stateMembers.push("\tcollections: AppCollections;");
		stateMembers.push("\tglobals: AppGlobals;");
		stateMembers.push("\tjobs: AppJobs;");
		stateMembers.push("\tfunctions: AppFunctions;");
		stateMembers.push("\troutes: AppRoutes;");
		stateMembers.push("\tservices: AppServices;");
		for (const [stateKey] of discovered.custom) {
			const typeName = `App${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
			stateMembers.push(`\t${stateKey}: ${typeName};`);
		}
		if (discovered.messages.size > 0)
			stateMembers.push('\t"~messageKeys": AppMessageKeys;');

		lines.push("/** @internal — used only for type derivation, not exported */");
		lines.push("type _AppInternal = Questpie<QuestpieConfig & {");
		for (const member of stateMembers) {
			lines.push(member);
		}
		lines.push("}>;");
		lines.push("");
	}

	// ── AppContext augmentation — auto-types ALL handlers ──────
	// Uses `declare module "questpie"` to augment the empty AppContext interface
	// from the core package. Every hook, access rule, function, job, and route
	// handler automatically gets these typed properties.
	lines.push("// ── AppContext augmentation — auto-types ALL handlers ──────");
	lines.push('declare module "questpie" {');
	lines.push("\tinterface AppContext {");
	lines.push("\t\t// Infrastructure");
	lines.push("\t\tdb: _AppInternal['db'];");
	if (discovered.emails.size > 0) {
		lines.push("\t\temail: MailerService<AppEmailTemplates>;");
	} else {
		lines.push("\t\temail: _AppInternal['email'];");
	}
	lines.push("\t\tqueue: QueueClient<AppJobs>;");
	lines.push("\t\tstorage: _AppInternal['storage'];");
	lines.push("\t\tkv: _AppInternal['kv'];");
	lines.push("\t\tlogger: _AppInternal['logger'];");
	lines.push("\t\tsearch: _AppInternal['search'];");
	lines.push("\t\trealtime: _AppInternal['realtime'];");
	lines.push("");
	lines.push("\t\t// Entity APIs");
	lines.push("\t\tcollections: _AppInternal['api']['collections'];");
	lines.push("\t\tglobals: _AppInternal['api']['globals'];");
	lines.push("");
	lines.push("\t\t// Request-scoped");
	lines.push("\t\tsession: _AppInternal['auth'] extends { api: { getSession: (...args: any[]) => Promise<infer TSession> } } ? NonNullable<TSession> | null : null;");
	if (discovered.messages.size > 0) {
		lines.push("\t\tt: (key: AppMessageKeys | (string & {}), params?: Record<string, unknown>, locale?: string) => string;");
	} else {
		lines.push("\t\tt: (key: string, params?: Record<string, unknown>, locale?: string) => string;");
	}

	// User services — flat on context
	if (discovered.services.size > 0) {
		lines.push("");
		lines.push("\t\t// User services");
		for (const file of sortedValues(discovered.services)) {
			lines.push(`\t\t${safeKey(file.key)}: ServiceInstanceOf<typeof ${file.varName}>;`);
		}
	}

	lines.push("\t}");

	// Registry — augment with all app categories for autocomplete
	lines.push("\tinterface Registry {");
	lines.push("\t\tcollections: AppCollections;");
	lines.push("\t\tglobals: AppGlobals;");
	lines.push("\t\tjobs: AppJobs;");
	lines.push("\t\tfunctions: AppFunctions;");
	lines.push("\t\troutes: AppRoutes;");
	lines.push("\t\tservices: AppServices;");
	if (discovered.emails.size > 0) {
		lines.push("\t\temails: AppEmailTemplates;");
	}
	for (const [stateKey] of discovered.custom) {
		const typeName = `App${stateKey.charAt(0).toUpperCase() + stateKey.slice(1)}`;
		lines.push(`\t\t${stateKey}: ${typeName};`);
	}
	lines.push("\t}");

	lines.push("}");
	lines.push("");

	// AppConfig — flat type for client APIs (createClient<AppConfig>(), createAdminAuthClient<AppConfig>())
	lines.push("/**");
	lines.push(" * Flat config type for client APIs.");
	lines.push(" * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.");
	lines.push(" * For handler context, use `AppContext` (auto-typed via module augmentation).");
	lines.push(" */");
	lines.push("export type AppConfig = {");
	lines.push("\tcollections: AppCollections;");
	lines.push("\tglobals: AppGlobals;");
	if (discovered.auth) {
		lines.push(`\tauth: typeof ${discovered.auth.varName};`);
	}
	lines.push("};");
	lines.push("");


	// ════════════════════════════════════════════════════════════
	// RUNTIME — create the app instance
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// RUNTIME — create the app instance");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	emitNewArchitectureRuntime(lines, discovered, extraEntities);

	// createContext() — typed context factory for scripts/standalone usage
	lines.push("// ── createContext — typed context for scripts ──────────────");
	lines.push("/**");
	lines.push(" * Create a typed AppContext for use in scripts, tests, or standalone code.");
	lines.push(" * Resolves all services and provides flat access to infrastructure.");
	lines.push(" *");
	lines.push(" * @example");
	lines.push(" * ```ts");
	lines.push(' * import { createContext } from "#questpie";');
	lines.push(" *");
	lines.push(" * const ctx = await createContext();");
	lines.push(" * const posts = await ctx.collections.posts.find({});");
	lines.push(" * ```");
	lines.push(" */");
	lines.push("export async function createContext(options?: {");
	lines.push("\taccessMode?: 'system' | 'user';");
	lines.push("}): Promise<AppContext> {");
	lines.push("\tconst reqCtx = await (app as any).createContext({");
	lines.push("\t\taccessMode: options?.accessMode ?? 'system',");
	lines.push("\t});");
	lines.push("\tconst services = extractAppServices(app, {");
	lines.push("\t\tdb: (app as any).db,");
	lines.push("\t\tsession: reqCtx.session,");
	lines.push("\t});");
	lines.push("\treturn { ...services, locale: reqCtx.locale } as unknown as AppContext;");
	lines.push("}");
	lines.push("");

	// Re-export factories (collection, global, singletons) so users can import from #questpie
	lines.push("// ── Re-export factories for user code ──────────────────────");
	lines.push("// Import from #questpie: import { collection, global, branding, ... } from '#questpie';");
	const factoryNames = getFactoryNames(plugins);
	lines.push(`export { ${factoryNames.join(", ")} } from "./factories.js";`);
	lines.push("");

	// Extra runtime code from plugins
	if (extraRuntimeCode && extraRuntimeCode.length > 0) {
		for (const code of extraRuntimeCode) {
			lines.push(code);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ============================================================================
// Runtime emission — new architecture
// ============================================================================

/**
 * Emit the createApp(definition, _runtime) call for new architecture.
 * @see RFC-MODULE-ARCHITECTURE §9.1
 */
function emitNewArchitectureRuntime(
	lines: string[],
	discovered: DiscoveryResult,
	extraEntities?: Map<string, string>,
): void {
	const modulesFile = discovered.singles.get("modules");
	if (!modulesFile) {
		throw new Error("emitNewArchitectureRuntime called without modules.ts");
	}
	const coreSingles = getCategorizedSingles(discovered.singles);

	lines.push("export const app = createApp(");
	lines.push("\t{");

	// Modules
	lines.push(`\t\tmodules: ${modulesFile.varName} as any,`);

	// Collections
	if (discovered.collections.size > 0) {
		lines.push("\t\tcollections: {");
		for (const file of sortedValues(discovered.collections)) {
			lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t\t},");
	}

	// Globals
	if (discovered.globals.size > 0) {
		lines.push("\t\tglobals: {");
		for (const file of sortedValues(discovered.globals)) {
			lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t\t},");
	}

	// Jobs
	if (discovered.jobs.size > 0) {
		lines.push("\t\tjobs: {");
		for (const file of sortedValues(discovered.jobs)) {
			lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t\t},");
	}

	// Functions — build nested object from dot-separated keys
	if (discovered.functions.size > 0) {
		lines.push("\t\tfunctions: {");
		const nested = buildNestedFunctions(discovered.functions);
		emitNestedObject(lines, nested, 3);
		lines.push("\t\t},");
	}

	// Routes
	if (discovered.routes.size > 0) {
		lines.push("\t\troutes: {");
		for (const file of sortedValues(discovered.routes)) {
			lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t\t},");
	}

	// Messages
	if (discovered.messages.size > 0) {
		lines.push("\t\tmessages: {");
		for (const file of sortedValues(discovered.messages)) {
			lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t\t},");
	}

	// Services
	if (discovered.services.size > 0) {
		lines.push("\t\tservices: {");
		for (const file of sortedValues(discovered.services)) {
			lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t\t},");
	}

	// Email templates
	if (discovered.emails.size > 0) {
		lines.push("\t\temailTemplates: {");
		for (const file of sortedValues(discovered.emails)) {
			lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
		}
		lines.push("\t\t},");
	}

	// Migrations — flat array sorted by key (filename = migration ID)
	if (discovered.migrations.size > 0) {
		const migVars = sortedValues(discovered.migrations).map((f) => f.varName).join(", ");
		lines.push(`\t\tmigrations: [${migVars}],`);
	}

	// Seeds — flat array sorted by key
	if (discovered.seeds.size > 0) {
		const seedVars = sortedValues(discovered.seeds).map((f) => f.varName).join(", ");
		lines.push(`\t\tseeds: [${seedVars}],`);
	}

	// Auth
	if (discovered.auth) {
		lines.push(`\t\tauth: ${discovered.auth.varName},`);
	}

	// Core singles (locale, hooks, access, context)
	// Cast with `as any` because user files may use `as const` (readonly),
	// and the whole expression is cast to App anyway.
	for (const file of coreSingles.core) {
		lines.push(`\t\t${safeKey(file.key)}: ${file.varName} as any,`);
	}

	// Plugin singles (sidebar, dashboard, branding, adminLocale, etc.)
	for (const file of coreSingles.plugin) {
		lines.push(`\t\t${safeKey(file.key)}: ${file.varName} as any,`);
	}

	// Custom directory patterns (plugin-discovered, e.g. blocks)
	for (const [stateKey, fileMap] of discovered.custom) {
		if (fileMap.size > 0) {
			lines.push(`\t\t${safeKey(stateKey)}: {`);
			for (const file of sortedValues(fileMap)) {
				lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
			}
			lines.push("\t\t},");
		}
	}

	// Spread singles (sidebar, dashboard — mergeStrategy: "spread")
	// Each stateKey maps to an array of files spread into one array.
	for (const [stateKey, files] of discovered.spreads) {
		if (files.length > 0) {
			const spread = files.map((f) => `...(${f.varName} as any ?? [])`).join(", ");
			lines.push(`\t\t${safeKey(stateKey)}: [${spread}],`);
		}
	}

	// Extra entities from plugins
	if (extraEntities) {
		for (const [key, value] of extraEntities) {
			lines.push(`\t\t${safeKey(key)}: ${value},`);
		}
	}

	lines.push("\t},");
	lines.push("\t_runtime,");
	lines.push(") as unknown as _AppInternal;");
	lines.push("");
}

// ============================================================================
// Singles categorization
// ============================================================================

/** Well-known core single file keys (always available, not plugin-discovered). */
const CORE_SINGLE_KEYS = new Set([
	"modules",
	"locale",
	"hooks",
	"defaultAccess",
	"contextResolver",
]);

interface CategorizedSingles {
	/** Core singles (locale, hooks, access, context) — NOT modules. */
	core: DiscoveredFile[];
	/** Plugin-discovered singles (sidebar, dashboard, branding, adminLocale, etc.). */
	plugin: DiscoveredFile[];
}

/**
 * Categorize singles into core (always available) and plugin-discovered.
 * Excludes "modules" since that's handled separately.
 */
function getCategorizedSingles(
	singles: Map<string, DiscoveredFile>,
): CategorizedSingles {
	const core: DiscoveredFile[] = [];
	const plugin: DiscoveredFile[] = [];

	for (const [key, file] of singles) {
		if (key === "modules") continue; // handled separately
		if (CORE_SINGLE_KEYS.has(key)) {
			core.push(file);
		} else {
			plugin.push(file);
		}
	}

	// Sort for deterministic output
	core.sort((a, b) => a.key.localeCompare(b.key));
	plugin.sort((a, b) => a.key.localeCompare(b.key));

	return { core, plugin };
}

// ============================================================================
// Type interface emission helper
// ============================================================================

/**
 * Emit a type interface or type alias for a category (collections, globals, etc.).
 * When user has entities, emits `export interface X extends _ModuleX { ... }`.
 * Otherwise emits `export type X = _ModuleX;`.
 */
function emitTypeInterface(
	lines: string[],
	typeName: string,
	moduleTypeName: string,
	fileMap: Map<string, DiscoveredFile>,
): void {
	const label = typeName.replace(/^App/, "").toLowerCase();
	const hasUser = fileMap.size > 0;
	lines.push(`/** All ${label} in the app (modules + user, user overrides) */`);
	if (hasUser) {
		lines.push(`export type ${typeName} = ${moduleTypeName} & {`);
		for (const file of sortedValues(fileMap)) {
			lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
		}
		lines.push("};");
	} else {
		lines.push(`export type ${typeName} = ${moduleTypeName};`);
	}
	lines.push("");
}

// ============================================================================
// Nested functions builder
// ============================================================================

type NestedNode =
	| { type: "leaf"; varName: string }
	| { type: "branch"; children: Map<string, NestedNode> };

/**
 * Build a nested tree from dot-separated function keys.
 * "search" → { search: leaf }
 * "admin.stats" → { admin: { stats: leaf } }
 */
function buildNestedFunctions(
	functions: Map<string, DiscoveredFile>,
): Map<string, NestedNode> {
	const root = new Map<string, NestedNode>();

	for (const file of functions.values()) {
		const segments = file.key.split(".");
		let current = root;

		for (let i = 0; i < segments.length; i++) {
			const seg = segments[i];
			const isLast = i === segments.length - 1;

			if (isLast) {
				current.set(seg, { type: "leaf", varName: file.varName });
			} else {
				let node = current.get(seg);
				if (!node || node.type === "leaf") {
					node = { type: "branch", children: new Map() };
					current.set(seg, node);
				}
				current = (node as Extract<NestedNode, { type: "branch" }>).children;
			}
		}
	}

	return root;
}

/**
 * Emit a nested object structure as runtime code lines.
 */
function emitNestedObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: ${node.varName},`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedObject(lines, node.children, indent + 1);
			lines.push(`${tabs}},`);
		}
	}
}

/**
 * Emit a nested type structure for interface declarations.
 */
function emitNestedTypeObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: typeof ${node.varName};`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedTypeObject(lines, node.children, indent + 1);
			lines.push(`${tabs}};`);
		}
	}
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Sort discovered files by key for deterministic output.
 */
function sortedValues(map: Map<string, DiscoveredFile>): DiscoveredFile[] {
	return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
}

/**
 * Generate the import statement for a discovered file.
 * Uses default import for "default" exports, named import for "named" exports.
 */
function importStatement(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	// default or unknown — use default import
	return `import ${file.varName} from "${file.importPath}";`;
}

/**
 * Quote a key if it's not a valid identifier.
 */
function safeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return `"${key}"`;
}

/**
 * Collect all factory export names from plugins.
 * Always includes "collection" and "global", plus any singleton factories.
 */
function getFactoryNames(plugins?: CodegenPlugin[]): string[] {
	const names = new Set(["collection", "global"]);
	if (plugins) {
		for (const plugin of plugins) {
			if (plugin.registries?.singletonFactories) {
				for (const name of Object.keys(plugin.registries.singletonFactories)) {
					names.add(name);
				}
			}
		}
	}
	return [...names].sort();
}
