/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate -c src/questpie/server/questpie.config.ts

import { createApp } from "questpie/app";
import type { AppDefinition, RuntimeConfig } from "questpie/types";
import type { _AppQuestpie, AppSession } from "./context.gen";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_announcements from "../collections/announcements";
import _coll_cities from "../collections/cities";
import _coll_cityMembers from "../collections/city-members";
import _coll_contacts from "../collections/contacts";
import _coll_documents from "../collections/documents";
import _coll_news from "../collections/news";
import _coll_pages from "../collections/pages";
import _coll_submissions from "../collections/submissions";

// ── Globals ────────────────────────────────────────────────
import _glob_site_settings from "../globals/site-settings";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260725T184252_realtimeV3Umbrella from "../migrations/20260725T184252_realtime-v3-umbrella";
import _mig_20260726T163039_queueTransactionalDispatch from "../migrations/20260726T163039_queue-transactional-dispatch";
import _mig_20260730T182023_optimisticConcurrencyRevisions from "../migrations/20260730T182023_optimistic-concurrency-revisions";
import _mig_20260731T000040_realtimeIdempotency1 from "../migrations/20260731T000040_realtime-idempotency-1";
import _mig_20260731T084648_realtimeIdempotency1 from "../migrations/20260731T084648_realtime-idempotency-1";
import _mig_20260804T091856_uploadMultipleColumn from "../migrations/20260804T091856_upload-multiple-column";
import _mig_20260805T165224_realtimeDrainCursorIndex from "../migrations/20260805T165224_realtime-drain-cursor-index";
import _mig_20260805T180807_realtimeSettlementRetention from "../migrations/20260805T180807_realtime-settlement-retention";

// ── Blocks ─────────────────────────────────────────────────
import { accordionBlock as _bloc_accordion } from "../blocks/accordion";
import { announcementBannerBlock as _bloc_announcementBanner } from "../blocks/announcement-banner";
import { columnsBlock as _bloc_columns } from "../blocks/columns";
import { contactsListBlock as _bloc_contactsList } from "../blocks/contacts-list";
import { ctaBlock as _bloc_cta } from "../blocks/cta";
import { dividerBlock as _bloc_divider } from "../blocks/divider";
import { documentsListBlock as _bloc_documentsList } from "../blocks/documents-list";
import { galleryBlock as _bloc_gallery } from "../blocks/gallery";
import { headingBlock as _bloc_heading } from "../blocks/heading";
import { heroBlock as _bloc_hero } from "../blocks/hero";
import { imageBlock as _bloc_image } from "../blocks/image";
import { imageTextBlock as _bloc_imageText } from "../blocks/image-text";
import { latestNewsBlock as _bloc_latestNews } from "../blocks/latest-news";
import { spacerBlock as _bloc_spacer } from "../blocks/spacer";
import { textBlock as _bloc_text } from "../blocks/text";
import { videoBlock as _bloc_video } from "../blocks/video";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _openapi from "../config/openapi";

const _appDefinition = ({
	modules: _modules,
	collections: {
		announcements: _coll_announcements,
		cities: _coll_cities,
		cityMembers: _coll_cityMembers,
		contacts: _coll_contacts,
		documents: _coll_documents,
		news: _coll_news,
		pages: _coll_pages,
		submissions: _coll_submissions,
	},
	globals: {
		site_settings: _glob_site_settings,
	},
	migrations: [_mig_20260725T184252_realtimeV3Umbrella, _mig_20260726T163039_queueTransactionalDispatch, _mig_20260730T182023_optimisticConcurrencyRevisions, _mig_20260731T000040_realtimeIdempotency1, _mig_20260731T084648_realtimeIdempotency1, _mig_20260804T091856_uploadMultipleColumn, _mig_20260805T165224_realtimeDrainCursorIndex, _mig_20260805T180807_realtimeSettlementRetention],
	blocks: {
		[_bloc_accordion.state.name]: _bloc_accordion,
		[_bloc_announcementBanner.state.name]: _bloc_announcementBanner,
		[_bloc_columns.state.name]: _bloc_columns,
		[_bloc_contactsList.state.name]: _bloc_contactsList,
		[_bloc_cta.state.name]: _bloc_cta,
		[_bloc_divider.state.name]: _bloc_divider,
		[_bloc_documentsList.state.name]: _bloc_documentsList,
		[_bloc_gallery.state.name]: _bloc_gallery,
		[_bloc_heading.state.name]: _bloc_heading,
		[_bloc_hero.state.name]: _bloc_hero,
		[_bloc_image.state.name]: _bloc_image,
		[_bloc_imageText.state.name]: _bloc_imageText,
		[_bloc_latestNews.state.name]: _bloc_latestNews,
		[_bloc_spacer.state.name]: _bloc_spacer,
		[_bloc_text.state.name]: _bloc_text,
		[_bloc_video.state.name]: _bloc_video,
	},
	config: {
		app: _appConfig,
		auth: _authConfig,
		admin: _adminConfig,
		openapi: _openapi,
	},
}) satisfies AppDefinition;

export const createAppForRuntime = (async (runtime: RuntimeConfig) =>
	(await createApp(_appDefinition, runtime)) as unknown as _AppQuestpie) as ((
	runtime: RuntimeConfig,
) => Promise<_AppQuestpie>) & {
	readonly "~types"?: { session: AppSession };
};
