/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_announcements from "../collections/announcements";
import _coll_cities from "../collections/cities";
import _coll_cityMembers from "../collections/city-members";
import _coll_contacts from "../collections/contacts";
import _coll_documents from "../collections/documents";
import _coll_news from "../collections/news";
import _coll_pages from "../collections/pages";
import _coll_submissions from "../collections/submissions";

// ── Globals ────────────────────────────────────────────────
import _glob_site_settings from "../globals/site-settings";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260725T184252_realtimeV3Umbrella from "../migrations/20260725T184252_realtime-v3-umbrella";

// ── Blocks ─────────────────────────────────────────────────
import { accordionBlock as _bloc_accordion } from "../blocks/accordion";
import { announcementBannerBlock as _bloc_announcementBanner } from "../blocks/announcement-banner";
import { columnsBlock as _bloc_columns } from "../blocks/columns";
import { contactsListBlock as _bloc_contactsList } from "../blocks/contacts-list";
import { ctaBlock as _bloc_cta } from "../blocks/cta";
import { dividerBlock as _bloc_divider } from "../blocks/divider";
import { documentsListBlock as _bloc_documentsList } from "../blocks/documents-list";
import { galleryBlock as _bloc_gallery } from "../blocks/gallery";
import { headingBlock as _bloc_heading } from "../blocks/heading";
import { heroBlock as _bloc_hero } from "../blocks/hero";
import { imageBlock as _bloc_image } from "../blocks/image";
import { imageTextBlock as _bloc_imageText } from "../blocks/image-text";
import { latestNewsBlock as _bloc_latestNews } from "../blocks/latest-news";
import { spacerBlock as _bloc_spacer } from "../blocks/spacer";
import { textBlock as _bloc_text } from "../blocks/text";
import { videoBlock as _bloc_video } from "../blocks/video";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _openapi from "../config/openapi";

import type { AppCollections, AppChannels, AppGlobals, AppJobs, _ModuleCollections, _AppDefaultServices, _AppServicesSeam, _AppTopLevelServices, _AppCustomServiceNamespaces, _Registry_Collections, _Registry_Channels, _Registry_Globals, _Registry_Jobs, _Registry_Routes, _Registry_Services, _Registry_Emails, _Registry_FieldTypes, _Registry_Views, _Registry_Components, _Registry_Blocks, _AllModuleFields } from "./entities.gen";
import type { AnyCollectionOrBuilder, AnyGlobalOrBuilder, AuthorityActor, CollectionAPI, CrdtClientAPI, CrdtRegistryFromApp, CrdtServerAPI, DrizzleClientFromQuestpieConfig, InferContextExtensionsFromAppConfig, InferSessionFromAuthConfig, MailerService, Principal, Questpie, QuestpieConfig, QueueClient, QueueJobType, ServiceInstancesInNamespace, TablesFromConfig, z } from "questpie/types";
import type { ChannelsService } from "questpie/channels";

type _MPSubModules<M> = M extends { modules: infer S extends readonly any[] } ? S : readonly [];
type _MPConfigValue<M, K extends string> = M extends { config: infer C } ? (C extends Record<K, infer V> ? V : {}) : {};
type _MPConfigSub<A extends readonly any[], K extends string> = A extends readonly [infer H, ...infer T extends readonly any[]] ? _MPConfigSub<_MPSubModules<H>, K> & _MPConfigValue<H, K> & _MPConfigSub<T, K> : {};
type _AppAppConfig = typeof _appConfig;
type _AppContextExtensions = Partial<InferContextExtensionsFromAppConfig<_AppAppConfig>>;
type _AppAuthConfig = _MPConfigSub<typeof _modules, "auth"> & typeof _authConfig;
type _AppSessionAuthConfig = _AppAuthConfig;
type _AppSession = NonNullable<InferSessionFromAuthConfig<_AppSessionAuthConfig>> | null;

type _CollectionsAPI = { [K in keyof AppCollections]: CollectionAPI<AppCollections[K], AppCollections> };
type _JobHandlerCollections = _ModuleCollections & {
	announcements: typeof _coll_announcements;
	cities: typeof _coll_cities;
	cityMembers: typeof _coll_cityMembers;
	contacts: typeof _coll_contacts;
	documents: typeof _coll_documents;
	news: typeof _coll_news;
	pages: typeof _coll_pages;
	submissions: typeof _coll_submissions;
};
type _JobHandlerCollectionsAPI = { [K in keyof _JobHandlerCollections]: CollectionAPI<_JobHandlerCollections[K], _JobHandlerCollections> };
type _ExecutionContextJob<T> = T extends { name: infer TName extends string; schema: z.ZodSchema<infer TPayload> } ? QueueJobType<TPayload, TName> : never;
type _ExecutionContextJobs = {};
type _ExecutionContextServiceDefinitions = {};
type _ExecutionContextDefaultServices = ServiceInstancesInNamespace<_ExecutionContextServiceDefinitions, "services">;
type _AppCollectionDefinitions = AppCollections & Record<string, AnyCollectionOrBuilder>;
type _AppGlobalDefinitions = AppGlobals & Record<string, AnyGlobalOrBuilder>;
type _AppQuestpieConfig = Omit<QuestpieConfig, "app" | "db" | "collections" | "channels" | "globals" | "auth" | "~contextExtensions"> & {
	app: (typeof _runtime)["app"];
	db: (typeof _runtime)["db"];
	collections: _AppCollectionDefinitions;
	channels: AppChannels;
	globals: _AppGlobalDefinitions;
	auth: _AppAuthConfig;
	storage: (typeof _runtime)["storage"];
	"~contextExtensions": _AppContextExtensions;
};
type _AppQuestpieBase = Questpie<_AppQuestpieConfig>;
type _AppDb = DrizzleClientFromQuestpieConfig<_AppQuestpieConfig>;
type _AppGlobalsAPI = _AppQuestpieBase["globals"];
type _AppStorage = _AppQuestpieBase["storage"];
type _AppTables = TablesFromConfig<_AppQuestpieConfig>;
export type _AppQuestpie = Omit<_AppQuestpieBase, "collections" | "globals"> & {
	collections: _CollectionsAPI;
	globals: _AppGlobalsAPI;
};

export type AppCrdt = CrdtRegistryFromApp<{ collections: AppCollections; globals: AppGlobals }>;
export type AppCrdtClient = CrdtClientAPI<AppCrdt>;
export type AppCrdtServer = CrdtServerAPI<AppCrdt>;

// ── AppContext augmentation — auto-types ALL handlers ──────
type _AppInfraRecord = {
	// Infrastructure
	app: _AppQuestpie;
	db: _AppDb;
	email: _AppQuestpie["email"];
	queue: QueueClient<AppJobs>;
	storage: _AppStorage;
	kv: _AppQuestpie["kv"];
	logger: _AppQuestpie["logger"];
	search: _AppQuestpie["search"];
	realtime: _AppQuestpie["realtime"];
	channels: ChannelsService<AppChannels>;
	crdt: AppCrdtServer;

	// Entity APIs
	collections: _CollectionsAPI;
	globals: _AppGlobalsAPI;
	tables: _AppTables;

	// Request-scoped
	session: _AppSession;
	principal?: Principal;
	actor?: AuthorityActor;
	t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

	// User services
	services: _AppDefaultServices;
};
type _AppInfraContext = _AppInfraRecord & _AppCustomServiceNamespaces;
type _AppCoreContext = _AppContextExtensions & _AppInfraContext;
type _ServiceCreateInfra = Omit<_AppInfraRecord, "services"> & { services: Questpie.Services };

declare global {
	namespace Questpie {
		interface AppContext extends _AppCoreContext, _AppTopLevelServices {}

		interface JobHandlerContext {
			// Infrastructure
			db: _AppDb;
			email: _AppQuestpie["email"];
			queue: QueueClient<_ExecutionContextJobs>;
			storage: _AppStorage;
			kv: _AppQuestpie["kv"];
			logger: _AppQuestpie["logger"];
			search: _AppQuestpie["search"];
			realtime: _AppQuestpie["realtime"];
			channels: ChannelsService<AppChannels>;

			// Entity APIs
			collections: _JobHandlerCollectionsAPI;
			globals: _AppGlobalsAPI;
			tables: _AppTables;

			// Request-scoped
			session: _AppSession;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

			// Top-level services (namespace: null)
			workflows?: _AppTopLevelServices extends { workflows: infer W } ? W : never;

			// User services
			services: _ExecutionContextDefaultServices;
		}

		interface WorkflowContext {
			// Infrastructure
			db: _AppDb;
			email: _AppQuestpie["email"];
			queue: QueueClient<_ExecutionContextJobs>;
			storage: _AppStorage;
			kv: _AppQuestpie["kv"];
			logger: _AppQuestpie["logger"];
			search: _AppQuestpie["search"];
			realtime: _AppQuestpie["realtime"];
			channels: ChannelsService<AppChannels>;

			// Entity APIs
			collections: _JobHandlerCollectionsAPI;
			globals: _AppGlobalsAPI;
			tables: _AppTables;

			// Request-scoped
			session: _AppSession;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

			// Top-level services (namespace: null)
			workflows?: _AppTopLevelServices extends { workflows: infer W } ? W : never;

			// User services
			services: _ExecutionContextDefaultServices;
		}

		interface Services extends _AppServicesSeam {}
		interface ServiceCreateContext extends _AppContextExtensions, _ServiceCreateInfra {}
		// Names-only marker — the `ServiceCreateContext` fallback conditional
		// probes THIS interface's keys instead of the real one (whose base
		// resolves through module service definitions and would cycle).
		interface ServiceCreateContextGenerated { generated: unknown }

		// Typed service surface for appConfig({ context }) resolvers.
		// Excludes _AppContextExtensions — the resolver produces them.
		interface ContextResolverContext {
			collections: _CollectionsAPI;
			globals: _AppGlobalsAPI;
			logger: _AppQuestpie["logger"];
			kv: _AppQuestpie["kv"];
			queue: QueueClient<AppJobs>;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;
			services: _AppDefaultServices;
		}

		// App-level hook / default-access ctx infra seams (CL-05).
		// Filled with the real infra MINUS _AppContextExtensions, so the
		// app-level hooks/access predicates get precise db/session/
		// collections/globals/queue WITHOUT re-entering the extensions cycle.
		interface AppHookContext extends _AppInfraContext {}
		interface AppDefaultAccessContext extends _AppInfraContext {}

		// appConfig({ context }) resolver session/db — off the cyclic edge.
		interface ContextResolverBase {
			session: _AppSession;
			db: _AppDb;
		}

		interface Registry {
			collections: _Registry_Collections;
			channels: _Registry_Channels;
			globals: _Registry_Globals;
			jobs: _Registry_Jobs;
			routes: _Registry_Routes;
			services: _Registry_Services;
			emails: _Registry_Emails;
			"~fieldTypes": _Registry_FieldTypes & _AllModuleFields;
			views: _Registry_Views;
			components: _Registry_Components;
			blocks: _Registry_Blocks;
		}
	}
}

/** Resolved auth session for this app (`{ user, session } | null`). */
export type AppAuthConfig = _AppAuthConfig;

export type AppSession = _AppSession;

/** Authenticated user shape from the app session. */
export type AppSessionUser = NonNullable<_AppSession>["user"];
