/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate -c src/questpie/server/questpie.config.ts

import "./names.gen";
// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_announcements from "../collections/announcements";
import _coll_cities from "../collections/cities";
import _coll_cityMembers from "../collections/city-members";
import _coll_contacts from "../collections/contacts";
import _coll_documents from "../collections/documents";
import _coll_news from "../collections/news";
import _coll_pages from "../collections/pages";
import _coll_submissions from "../collections/submissions";

// ── Globals ────────────────────────────────────────────────
import _glob_site_settings from "../globals/site-settings";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260725T184252_realtimeV3Umbrella from "../migrations/20260725T184252_realtime-v3-umbrella";
import _mig_20260726T163039_queueTransactionalDispatch from "../migrations/20260726T163039_queue-transactional-dispatch";
import _mig_20260730T182023_optimisticConcurrencyRevisions from "../migrations/20260730T182023_optimistic-concurrency-revisions";
import _mig_20260731T000040_realtimeIdempotency1 from "../migrations/20260731T000040_realtime-idempotency-1";
import _mig_20260731T084648_realtimeIdempotency1 from "../migrations/20260731T084648_realtime-idempotency-1";
import _mig_20260804T091856_uploadMultipleColumn from "../migrations/20260804T091856_upload-multiple-column";
import _mig_20260805T165224_realtimeDrainCursorIndex from "../migrations/20260805T165224_realtime-drain-cursor-index";
import _mig_20260805T180807_realtimeSettlementRetention from "../migrations/20260805T180807_realtime-settlement-retention";
import _mig_20260806T151904_removeRealtimeHead from "../migrations/20260806T151904_remove-realtime-head";

// ── Blocks ─────────────────────────────────────────────────
import { accordionBlock as _bloc_accordion } from "../blocks/accordion";
import { announcementBannerBlock as _bloc_announcementBanner } from "../blocks/announcement-banner";
import { columnsBlock as _bloc_columns } from "../blocks/columns";
import { contactsListBlock as _bloc_contactsList } from "../blocks/contacts-list";
import { ctaBlock as _bloc_cta } from "../blocks/cta";
import { dividerBlock as _bloc_divider } from "../blocks/divider";
import { documentsListBlock as _bloc_documentsList } from "../blocks/documents-list";
import { galleryBlock as _bloc_gallery } from "../blocks/gallery";
import { headingBlock as _bloc_heading } from "../blocks/heading";
import { heroBlock as _bloc_hero } from "../blocks/hero";
import { imageBlock as _bloc_image } from "../blocks/image";
import { imageTextBlock as _bloc_imageText } from "../blocks/image-text";
import { latestNewsBlock as _bloc_latestNews } from "../blocks/latest-news";
import { spacerBlock as _bloc_spacer } from "../blocks/spacer";
import { textBlock as _bloc_text } from "../blocks/text";
import { videoBlock as _bloc_video } from "../blocks/video";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _openapi from "../config/openapi";

import type { RouteParamsFromKey, RouteWithParams } from "questpie/types";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { CodegenResolvedModulePropArr, ExtractModulePropArr, Override, ServiceCustomNamespaceInstances, ServiceInstanceOf, ServiceInstancesInNamespace, ServiceTopLevelInstances } from "questpie/types";
type _RouteDefinitionWithoutHandler<T> = T extends { mode: "raw" } ? Omit<T, "handler"> & { handler: (args: unknown) => Response | Promise<Response> } : Omit<T, "handler"> & { handler: (args: unknown) => unknown | Promise<unknown> };
export type _ModuleCollections = CodegenResolvedModulePropArr<typeof _modules, "collections">;
export type _ModuleChannels = CodegenResolvedModulePropArr<typeof _modules, "channels">;
export type _ModuleGlobals = CodegenResolvedModulePropArr<typeof _modules, "globals">;
export type _ModuleJobs = CodegenResolvedModulePropArr<typeof _modules, "jobs">;
export type _ModuleRoutes = CodegenResolvedModulePropArr<typeof _modules, "routes">;
export type _ModuleServices = {};
export type _ModuleFieldTypes = CodegenResolvedModulePropArr<typeof _modules, "fieldTypes">;
export type _ModuleViews = CodegenResolvedModulePropArr<typeof _modules, "views">;
export type _ModuleComponents = CodegenResolvedModulePropArr<typeof _modules, "components">;
export type _ModuleBlocks = CodegenResolvedModulePropArr<typeof _modules, "blocks">;
// Registry category extraction from modules
export type _Registry_Collections = CodegenResolvedModulePropArr<typeof _modules, "collections">;
export type _Registry_Channels = CodegenResolvedModulePropArr<typeof _modules, "channels">;
export type _Registry_Globals = CodegenResolvedModulePropArr<typeof _modules, "globals">;
export type _Registry_Jobs = CodegenResolvedModulePropArr<typeof _modules, "jobs">;
export type _Registry_Routes = CodegenResolvedModulePropArr<typeof _modules, "routes">;
export type _Registry_Services = {};
export type _Registry_Emails = CodegenResolvedModulePropArr<typeof _modules, "emails">;
export type _Registry_FieldTypes = CodegenResolvedModulePropArr<typeof _modules, "fieldTypes">;
export type _Registry_Views = CodegenResolvedModulePropArr<typeof _modules, "views">;
export type _Registry_Components = CodegenResolvedModulePropArr<typeof _modules, "components">;
export type _Registry_Blocks = CodegenResolvedModulePropArr<typeof _modules, "blocks">;

// Recursive module property extraction (for fields contributed at each level)
import type { ExtractModuleProp } from "questpie/types";

export type _AllModuleFields = ExtractModuleProp<{ modules: typeof _modules }, "fields">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = Override<_ModuleCollections, {
	announcements: typeof _coll_announcements;
	cities: typeof _coll_cities;
	cityMembers: typeof _coll_cityMembers;
	contacts: typeof _coll_contacts;
	documents: typeof _coll_documents;
	news: typeof _coll_news;
	pages: typeof _coll_pages;
	submissions: typeof _coll_submissions;
}>;

/** All channels in the app (modules + user, user overrides) */
export type AppChannels = _ModuleChannels;

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = Override<_ModuleGlobals, {
	site_settings: typeof _glob_site_settings;
}>;

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs;

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes;

/** All service definitions in the app (modules + user, user overrides). */
type _AppServiceDefinitions = _ModuleServices;

/** All services in the app as resolved service instances. */
export type AppServices = {
	[K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]>;
};
export type _AppDefaultServices = ServiceInstancesInNamespace<_AppServiceDefinitions, "services">;
export type _AppServicesSeam = { [K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]> };
export type _AppTopLevelServices = ServiceTopLevelInstances<_AppServiceDefinitions>;
export type _AppCustomServiceNamespaces = ServiceCustomNamespaceInstances<_AppServiceDefinitions>;

/** All email templates in the app — use with email.sendTemplate() */
export type AppEmailTemplates = Record<string, never>;

/** All fieldtypes in the app (modules + user, user overrides) */
export type AppFieldTypes = _ModuleFieldTypes;

/** All views in the app (modules + user, user overrides) */
export type AppViews = _ModuleViews;

/** All components in the app (modules + user, user overrides) */
export type AppComponents = _ModuleComponents;

/** All blocks in the app (modules + user, user overrides) */
export type AppBlocks = Override<Override<Override<Override<Override<Override<Override<Override<Override<Override<Override<Override<Override<Override<Override<Override<_ModuleBlocks, { [K in typeof _bloc_accordion.state.name]: typeof _bloc_accordion }>, { [K in typeof _bloc_announcementBanner.state.name]: typeof _bloc_announcementBanner }>, { [K in typeof _bloc_columns.state.name]: typeof _bloc_columns }>, { [K in typeof _bloc_contactsList.state.name]: typeof _bloc_contactsList }>, { [K in typeof _bloc_cta.state.name]: typeof _bloc_cta }>, { [K in typeof _bloc_divider.state.name]: typeof _bloc_divider }>, { [K in typeof _bloc_documentsList.state.name]: typeof _bloc_documentsList }>, { [K in typeof _bloc_gallery.state.name]: typeof _bloc_gallery }>, { [K in typeof _bloc_heading.state.name]: typeof _bloc_heading }>, { [K in typeof _bloc_hero.state.name]: typeof _bloc_hero }>, { [K in typeof _bloc_image.state.name]: typeof _bloc_image }>, { [K in typeof _bloc_imageText.state.name]: typeof _bloc_imageText }>, { [K in typeof _bloc_latestNews.state.name]: typeof _bloc_latestNews }>, { [K in typeof _bloc_spacer.state.name]: typeof _bloc_spacer }>, { [K in typeof _bloc_text.state.name]: typeof _bloc_text }>, { [K in typeof _bloc_video.state.name]: typeof _bloc_video }>;
