/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate -c src/questpie/server/questpie.config.ts

import { acquireGeneratedApp, createContextFactory } from "questpie/app";
import { createAppForRuntime } from "./app-factory";
export { createAppForRuntime } from "./app-factory";
import "./names.gen";
import type { AccessContext, CollectionSelect, CrdtClientAPI, CrdtRegistryFromApp, CrdtServerAPI, GlobalSelect, HookContext, Where } from "questpie/types";
import type { AppCollections, AppChannels, AppGlobals, AppRoutes } from "./entities.gen";
import type { _AppQuestpie, AppAuthConfig, AppCrdt, AppSession, AppSessionUser } from "./context.gen";

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_announcements from "../collections/announcements";
import _coll_cities from "../collections/cities";
import _coll_cityMembers from "../collections/city-members";
import _coll_contacts from "../collections/contacts";
import _coll_documents from "../collections/documents";
import _coll_news from "../collections/news";
import _coll_pages from "../collections/pages";
import _coll_submissions from "../collections/submissions";

// ── Globals ────────────────────────────────────────────────
import _glob_site_settings from "../globals/site-settings";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260725T184252_realtimeV3Umbrella from "../migrations/20260725T184252_realtime-v3-umbrella";
import _mig_20260726T163039_queueTransactionalDispatch from "../migrations/20260726T163039_queue-transactional-dispatch";
import _mig_20260730T182023_optimisticConcurrencyRevisions from "../migrations/20260730T182023_optimistic-concurrency-revisions";
import _mig_20260731T000040_realtimeIdempotency1 from "../migrations/20260731T000040_realtime-idempotency-1";
import _mig_20260731T084648_realtimeIdempotency1 from "../migrations/20260731T084648_realtime-idempotency-1";
import _mig_20260804T091856_uploadMultipleColumn from "../migrations/20260804T091856_upload-multiple-column";
import _mig_20260805T165224_realtimeDrainCursorIndex from "../migrations/20260805T165224_realtime-drain-cursor-index";
import _mig_20260805T180807_realtimeSettlementRetention from "../migrations/20260805T180807_realtime-settlement-retention";
import _mig_20260806T151904_removeRealtimeHead from "../migrations/20260806T151904_remove-realtime-head";

// ── Blocks ─────────────────────────────────────────────────
import { accordionBlock as _bloc_accordion } from "../blocks/accordion";
import { announcementBannerBlock as _bloc_announcementBanner } from "../blocks/announcement-banner";
import { columnsBlock as _bloc_columns } from "../blocks/columns";
import { contactsListBlock as _bloc_contactsList } from "../blocks/contacts-list";
import { ctaBlock as _bloc_cta } from "../blocks/cta";
import { dividerBlock as _bloc_divider } from "../blocks/divider";
import { documentsListBlock as _bloc_documentsList } from "../blocks/documents-list";
import { galleryBlock as _bloc_gallery } from "../blocks/gallery";
import { headingBlock as _bloc_heading } from "../blocks/heading";
import { heroBlock as _bloc_hero } from "../blocks/hero";
import { imageBlock as _bloc_image } from "../blocks/image";
import { imageTextBlock as _bloc_imageText } from "../blocks/image-text";
import { latestNewsBlock as _bloc_latestNews } from "../blocks/latest-news";
import { spacerBlock as _bloc_spacer } from "../blocks/spacer";
import { textBlock as _bloc_text } from "../blocks/text";
import { videoBlock as _bloc_video } from "../blocks/video";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _openapi from "../config/openapi";

export type * from "./entities.gen";
export type * from "./context.gen";

/**
 * Select/document type for a collection key — prefer over `Record<string, any>` for docs.
 */
export type CollectionDoc<K extends keyof AppCollections> = CollectionSelect<AppCollections[K]>;

/**
 * Select/document type for a global key.
 */
export type GlobalDoc<K extends keyof AppGlobals> = GlobalSelect<AppGlobals[K]>;

/**
 * Typed `where` filter for a collection key — prefer over `Record<string, unknown>`
 * when building a `where` clause dynamically before a `find`/`findOne` call.
 */
export type CollectionWhere<K extends keyof AppCollections> = Where<AppCollections[K], AppConfig>;

/**
 * Access-rule ctx for shared helpers. `K` narrows `data` to that collection's row.
 *
 * CYCLE RULE: import these only from files NOT imported by a collection
 * (routes, services, jobs, scripts). Helpers imported by collections take
 * the package-level `AccessContext` from "questpie" instead — see the
 * type-inference reference.
 *
 * @example
 * ```ts
 * export async function isOwner(ctx: AccessRuleContext<"posts">) {
 *   return ctx.data?.authorId === ctx.session?.user.id; // ctx.collections typed
 * }
 * ```
 */
export type AccessRuleContext<K extends keyof AppCollections | unknown = unknown> =
	AccessContext<K extends keyof AppCollections ? CollectionDoc<K> : unknown>;

/**
 * Hook ctx for shared helpers. `K` narrows `data` to that collection's row.
 * Same cycle rule as `AccessRuleContext`.
 */
export type HookRuleContext<K extends keyof AppCollections | unknown = unknown> =
	HookContext<K extends keyof AppCollections ? CollectionDoc<K> : unknown>;

/**
 * Flat config type for client APIs.
 * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.
 * For handler context, use `AppContext` (auto-typed via module augmentation).
 */
export type AppConfig = {
	collections: AppCollections;
	channels: AppChannels;
	crdt: AppCrdt;
	globals: AppGlobals;
	routes: AppRoutes;
	storage: (typeof _runtime)["storage"];
	auth: AppAuthConfig;
};

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

var _appLease = acquireGeneratedApp("city-portal-example:src/questpie/server:src/questpie/server/questpie.config.ts", () => createAppForRuntime(_runtime));
var _appPromise = _appLease.promise;

export const app = (await _appPromise) as unknown as _AppQuestpie;

export async function destroyApp(): Promise<void> {
	await _appLease.shutdown();
}

const _hot = (import.meta as ImportMeta & { hot?: { dispose(callback: () => void | Promise<void>): void } }).hot;
_hot?.dispose(() => _appLease.release());

/** Fully typed QUESTPIE app instance. */
export type App = typeof app;

// ── createContext — typed context for scripts ──────────────
/**
 * Create a typed AppContext for use in scripts, tests, or standalone code.
 * Resolves all services and provides flat access to infrastructure.
 *
 * @example
 * ```ts
 * import { createContext } from "#questpie";
 *
 * const ctx = await createContext();
 * const posts = await ctx.collections.posts.find({});
 * ```
 */
export async function createContext(
	options?: Parameters<ReturnType<typeof createContextFactory>>[0],
) {
	return createContextFactory(app)(options);
}

// Factories: import { collection, global, ... } from '#questpie/factories';
