/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import { createApp, createContextFactory } from "questpie/app";
import "./names.gen";
import type { AccessContext, AppDefinition, CollectionSelect, GlobalSelect, HookContext, Where } from "questpie/types";
import type { AppCollections, AppChannels, AppGlobals, AppRoutes } from "./entities.gen";
import type { _AppQuestpie, AppAuthConfig, AppSession, AppSessionUser } from "./context.gen";

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_announcements from "../collections/announcements";
import _coll_cities from "../collections/cities";
import _coll_cityMembers from "../collections/city-members";
import _coll_contacts from "../collections/contacts";
import _coll_documents from "../collections/documents";
import _coll_news from "../collections/news";
import _coll_pages from "../collections/pages";
import _coll_submissions from "../collections/submissions";

// ── Globals ────────────────────────────────────────────────
import _glob_site_settings from "../globals/site-settings";

// ── Migrations ─────────────────────────────────────────────
import _mig_20260211T164057_bright_yellow_tiger from "../migrations/20260211T164057_bright_yellow_tiger";
import _mig_20260721T210525_kind_pink_dolphin from "../migrations/20260721T210525_kind_pink_dolphin";

// ── Blocks ─────────────────────────────────────────────────
import { accordionBlock as _bloc_accordion } from "../blocks/accordion";
import { announcementBannerBlock as _bloc_announcementBanner } from "../blocks/announcement-banner";
import { columnsBlock as _bloc_columns } from "../blocks/columns";
import { contactsListBlock as _bloc_contactsList } from "../blocks/contacts-list";
import { ctaBlock as _bloc_cta } from "../blocks/cta";
import { dividerBlock as _bloc_divider } from "../blocks/divider";
import { documentsListBlock as _bloc_documentsList } from "../blocks/documents-list";
import { galleryBlock as _bloc_gallery } from "../blocks/gallery";
import { headingBlock as _bloc_heading } from "../blocks/heading";
import { heroBlock as _bloc_hero } from "../blocks/hero";
import { imageBlock as _bloc_image } from "../blocks/image";
import { imageTextBlock as _bloc_imageText } from "../blocks/image-text";
import { latestNewsBlock as _bloc_latestNews } from "../blocks/latest-news";
import { spacerBlock as _bloc_spacer } from "../blocks/spacer";
import { textBlock as _bloc_text } from "../blocks/text";
import { videoBlock as _bloc_video } from "../blocks/video";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _openapi from "../config/openapi";

export type * from "./entities.gen";
export type * from "./context.gen";

/**
 * Select/document type for a collection key — prefer over `Record<string, any>` for docs.
 */
export type CollectionDoc<K extends keyof AppCollections> = CollectionSelect<AppCollections[K]>;

/**
 * Select/document type for a global key.
 */
export type GlobalDoc<K extends keyof AppGlobals> = GlobalSelect<AppGlobals[K]>;

/**
 * Typed `where` filter for a collection key — prefer over `Record<string, unknown>`
 * when building a `where` clause dynamically before a `find`/`findOne` call.
 */
export type CollectionWhere<K extends keyof AppCollections> = Where<AppCollections[K], AppConfig>;

/**
 * Access-rule ctx for shared helpers. `K` narrows `data` to that collection's row.
 *
 * CYCLE RULE: import these only from files NOT imported by a collection
 * (routes, services, jobs, scripts). Helpers imported by collections take
 * the package-level `AccessContext` from "questpie" instead — see the
 * type-inference reference.
 *
 * @example
 * ```ts
 * export async function isOwner(ctx: AccessRuleContext<"posts">) {
 *   return ctx.data?.authorId === ctx.session?.user.id; // ctx.collections typed
 * }
 * ```
 */
export type AccessRuleContext<K extends keyof AppCollections | unknown = unknown> =
	AccessContext<K extends keyof AppCollections ? CollectionDoc<K> : unknown>;

/**
 * Hook ctx for shared helpers. `K` narrows `data` to that collection's row.
 * Same cycle rule as `AccessRuleContext`.
 */
export type HookRuleContext<K extends keyof AppCollections | unknown = unknown> =
	HookContext<K extends keyof AppCollections ? CollectionDoc<K> : unknown>;

/**
 * Flat config type for client APIs.
 * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.
 * For handler context, use `AppContext` (auto-typed via module augmentation).
 */
export type AppConfig = {
	collections: AppCollections;
	channels: AppChannels;
	globals: AppGlobals;
	routes: AppRoutes;
	storage: (typeof _runtime)["storage"];
	auth: AppAuthConfig;
};

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

var _appPromise: Promise<unknown> | undefined;

_appPromise = createApp(
	({
		modules: _modules,
		collections: {
			announcements: _coll_announcements,
			cities: _coll_cities,
			cityMembers: _coll_cityMembers,
			contacts: _coll_contacts,
			documents: _coll_documents,
			news: _coll_news,
			pages: _coll_pages,
			submissions: _coll_submissions,
		},
		globals: {
			site_settings: _glob_site_settings,
		},
		migrations: [_mig_20260211T164057_bright_yellow_tiger, _mig_20260721T210525_kind_pink_dolphin],
		blocks: {
			[_bloc_accordion.state.name]: _bloc_accordion,
			[_bloc_announcementBanner.state.name]: _bloc_announcementBanner,
			[_bloc_columns.state.name]: _bloc_columns,
			[_bloc_contactsList.state.name]: _bloc_contactsList,
			[_bloc_cta.state.name]: _bloc_cta,
			[_bloc_divider.state.name]: _bloc_divider,
			[_bloc_documentsList.state.name]: _bloc_documentsList,
			[_bloc_gallery.state.name]: _bloc_gallery,
			[_bloc_heading.state.name]: _bloc_heading,
			[_bloc_hero.state.name]: _bloc_hero,
			[_bloc_image.state.name]: _bloc_image,
			[_bloc_imageText.state.name]: _bloc_imageText,
			[_bloc_latestNews.state.name]: _bloc_latestNews,
			[_bloc_spacer.state.name]: _bloc_spacer,
			[_bloc_text.state.name]: _bloc_text,
			[_bloc_video.state.name]: _bloc_video,
		},
		config: {
			app: _appConfig,
			auth: _authConfig,
			admin: _adminConfig,
			openapi: _openapi,
		},
	}) satisfies AppDefinition,
	_runtime,
);

export const app = (await _appPromise) as unknown as _AppQuestpie;

/** Fully typed QUESTPIE app instance. */
export type App = typeof app;

// ── createContext — typed context for scripts ──────────────
/**
 * Create a typed AppContext for use in scripts, tests, or standalone code.
 * Resolves all services and provides flat access to infrastructure.
 *
 * @example
 * ```ts
 * import { createContext } from "#questpie";
 *
 * const ctx = await createContext();
 * const posts = await ctx.collections.posts.find({});
 * ```
 */
export async function createContext(
	options?: Parameters<ReturnType<typeof createContextFactory>>[0],
) {
	while (!_appPromise) {
		await new Promise((resolve) => setTimeout(resolve, 0));
	}

	return createContextFactory((await _appPromise) as _AppQuestpie)(options);
}

// Factories: import { collection, global, ... } from '#questpie/factories';
