/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Module entity-name key sets (distributive `keyof`) ─────
type _ModuleCollectionsKeyNames = (typeof _modules)[number] extends infer M ? M extends { collections: infer C } ? keyof C & string : never : never;
type _ModuleGlobalsKeyNames = (typeof _modules)[number] extends infer M ? M extends { globals: infer C } ? keyof C & string : never : never;
type _ModuleJobsKeyNames = (typeof _modules)[number] extends infer M ? M extends { jobs: infer C } ? keyof C & string : never : never;

declare global {
	namespace Questpie {
		interface CollectionKeys extends Record<_ModuleCollectionsKeyNames, unknown> {}
		interface GlobalKeys extends Record<_ModuleGlobalsKeyNames, unknown> {}
		interface JobKeys extends Record<_ModuleJobsKeyNames, unknown> {}
	}
}
