/**
 * Common Admin Types
 *
 * Base types used across admin augmentation: component references,
 * component type registry, locale configuration, and action references.
 */

import type { I18nText } from "questpie/shared";

// ============================================================================
// Admin Locale Configuration
// ============================================================================

/**
 * Admin locale configuration for UI language support.
 * Separate from content locales - UI can have different languages than content.
 *
 * @example
 * ```ts
 * import { adminConfig } from "#questpie/factories";
 *
 * export default adminConfig({
 *   locale: {
 *     locales: ["en", "sk"],  // UI available in 2 languages
 *     defaultLocale: "en",
 *   },
 * });
 * ```
 */
export interface AdminLocaleConfig {
	/** Available UI locales for admin interface */
	locales: string[];
	/** Default UI locale */
	defaultLocale: string;
}

// ============================================================================
// Admin Configuration Types
// ============================================================================

/**
 * Reference to a server-registered component.
 * Used for icons, badges, and other UI elements defined on server.
 *
 * @example
 * ```ts
 * { type: "icon", props: { name: "ph:users" } }
 * ```
 */
export interface ComponentReference<
	TType extends string = string,
	TProps extends Record<string, unknown> = Record<string, unknown>,
> {
	type: TType;
	props: TProps;
}

/**
 * Icon component reference with typed props.
 */
type IconReference = ComponentReference<"icon", { name: string }>;

/**
 * Badge component reference with typed props.
 */
type BadgeReference = ComponentReference<
	"badge",
	{ text: string; color?: string }
>;

// ============================================================================
// Component Type Registry — Plugin-Extensible
// ============================================================================

/**
 * Open augmentation point for component type names.
 * Codegen augments this interface from module-contributed component maps,
 * so user code gets autocomplete for valid component type names.
 *
 * When no modules are loaded (empty registry), `ComponentType` falls back to `string`.
 *
 * @example
 * ```ts
 * // Generated by codegen:
 * declare module "@questpie/admin/server" {
 *   interface ComponentTypeRegistry extends Record<_ComponentsNames_Strict, {}> {}
 * }
 *
 * // Third-party plugin can extend:
 * declare module "@questpie/admin/server" {
 *   interface ComponentTypeRegistry {
 *     avatar: {};
 *     statusBadge: {};
 *   }
 * }
 * ```
 */
export interface ComponentTypeRegistry {}

/**
 * Union of all registered component type names.
 * Falls back to `string` when no types are registered (empty ComponentTypeRegistry).
 */
export type ComponentType = [keyof ComponentTypeRegistry] extends [never]
	? string
	: keyof ComponentTypeRegistry;

/**
 * Reference to an action
 */
export type ActionReference = string | { type: string; config?: unknown };
