import { convert } from "html-to-text";

import { extractAppServices } from "#questpie/server/config/app-context.js";
import { tryGetContext } from "#questpie/server/config/context.js";
import { getNodeEnv } from "#questpie/server/utils/env.js";

import type { MailAdapter } from "./adapter.js";
import { ConsoleAdapter } from "./adapters/console.adapter.js";
import type {
	EmailTemplateDefinition,
	EmailTemplateNames,
	GetEmailTemplate,
	InferEmailTemplateInput,
	EmailResult,
} from "./template.js";
import type {
	MailerConfig,
	MailOptions,
	SerializableMailOptions,
} from "./types.js";

const isDev = getNodeEnv() !== "production";

/**
 * Main mailer service
 */
export class MailerService<
	TTemplates extends Record<string, any> = Record<string, any>,
> {
	private templates: Map<string, EmailTemplateDefinition<any, any>>;
	private defaultFrom?: string;
	private defaultAdapter: MailAdapter | null = null;

	constructor(private config: MailerConfig<TTemplates>) {
		this.templates = new Map();
		if (config.templates) {
			for (const [key, template] of Object.entries(config.templates)) {
				// Key by record key (camelCase) — matches AppEmailTemplates generated by codegen.
				// e.g. "newBlogPost" from emails/new-blog-post.ts
				this.templates.set(key, template);
			}
		}
		this.defaultFrom = config.defaults?.from;
	}

	/**
	 * Get the mail adapter, falling back to ConsoleAdapter in development
	 */
	private async getAdapter(): Promise<MailAdapter> {
		const adapter = await this.config.adapter;
		if (adapter) {
			return adapter;
		}

		// In development, use ConsoleAdapter as default
		if (isDev) {
			if (!this.defaultAdapter) {
				this.defaultAdapter = new ConsoleAdapter();
			}
			return this.defaultAdapter;
		}

		throw new Error(
			"QUESTPIE: Email adapter is not configured. Provide adapter in .build({ email: { adapter: ... } })",
		);
	}

	/**
	 * Resolve the template-handler services, preferring an explicit context
	 * (for callers outside a request/job scope) over the ambient AppContext
	 * (AsyncLocalStorage).
	 *
	 * `hasContext` is false only when NEITHER is available. Every user-code
	 * entry point now establishes ambient context — HTTP, CRUD, jobs (queue
	 * wrap), admin actions — so a false here is a genuinely contextless call.
	 *
	 * `services` is typed `object`, not `Record<string, unknown>`, and the
	 * laundering spread is gone. The value is spread into the handler args and
	 * handed to a per-template handler, so nothing reads it structurally; the
	 * index signature only forced tsc to prove every member of the very wide
	 * concrete AppContext assignable to `unknown`, property by property.
	 *
	 * Measured, and read this before "optimizing" a hot comparison elsewhere:
	 * this pair WAS the two most expensive comparisons in the typecheck
	 * (2 x 2,990 ms). Removing them saved ~0.7% of total relation time, not
	 * 12%, because tsc caches relation results — whoever compares that shape
	 * FIRST pays, everyone after is free. The bill simply moved to the next
	 * caller (config/questpie.ts, 8.9 ms -> 2,907 ms). Per-comparison rankings
	 * measure cache-warming order, not where the work lives.
	 */
	private resolveHandlerContext(ctx?: {
		app?: unknown;
		db?: unknown;
		session?: unknown;
	}): { services: object; hasContext: boolean } {
		if (ctx?.app) {
			return {
				services: extractAppServices(ctx.app, {
					db: ctx.db,
					session: ctx.session,
				}),
				hasContext: true,
			};
		}
		const stored = tryGetContext();
		if (!stored?.app) {
			return { services: {}, hasContext: false };
		}
		return {
			services: extractAppServices(stored.app, {
				db: stored.db,
				session: stored.session,
			}),
			hasContext: true,
		};
	}

	/**
	 * Serialize mail options (convert HTML to plain text if needed)
	 */
	private serializeMailOptions(options: MailOptions): SerializableMailOptions {
		let { html, text } = options;

		if (html && !text) {
			text = convert(html);
		}

		if (!html && !text) {
			throw new Error("No text or html provided");
		}

		return {
			...options,
			from: options.from || this.defaultFrom || "noreply@example.com",
			text: text || "",
			html: html || "",
		};
	}

	/**
	 * Send an email
	 */
	async send(options: MailOptions): Promise<void> {
		const serializedMail = this.serializeMailOptions(options);
		const adapter = await this.getAdapter();
		return adapter.send(serializedMail);
	}

	/**
	 * Render an email template without sending it.
	 * Useful for previewing emails in the admin UI.
	 *
	 * @returns The rendered email result with subject, html, and optional text
	 */
	async renderTemplate<K extends EmailTemplateNames<TTemplates>>(options: {
		template: K;
		input: InferEmailTemplateInput<GetEmailTemplate<TTemplates, K>>;
		locale?: string;
		/**
		 * Explicit app context for callers outside a request/job scope. Prefer
		 * the ambient context (now established everywhere); pass this only as a
		 * deliberate escape hatch.
		 */
		ctx?: { app?: unknown; db?: unknown; session?: unknown };
	}): Promise<EmailResult> {
		const templateDef = this.templates.get(options.template as string);
		if (!templateDef) {
			throw new Error(`Template "${String(options.template)}" not found.`);
		}

		// Validate input with Zod schema
		const validatedInput = templateDef.schema.parse(options.input);

		// Build handler args: AppContext services + input + locale
		const { services, hasContext } = this.resolveHandlerContext(options.ctx);
		const handlerArgs = {
			...services,
			input: validatedInput,
			locale: options.locale,
		};

		// Defense in depth: with no ambient/explicit context the app-service
		// keys (collections, db, queue, …) are absent. Surface a clear,
		// actionable error the instant a handler reaches for one — instead of
		// the cryptic downstream "collections is undefined" the prod crash hit.
		// Handlers that only use `input`/`locale` are unaffected.
		const guardedArgs = hasContext
			? handlerArgs
			: new Proxy(handlerArgs, {
					get: (target, prop, receiver) => {
						if (typeof prop === "symbol" || prop in target) {
							return Reflect.get(target, prop, receiver);
						}
						throw new Error(
							`[QUESTPIE] email template '${String(options.template)}' handler needs app context — ` +
								"call inside a job/request scope (now wrapped) or pass ctx to sendTemplate().",
						);
					},
				});

		// Call handler (may be async)
		const result = await templateDef.handler(guardedArgs as any);

		if (!result.subject) {
			throw new Error(
				`Email handler for "${String(options.template)}" must return a subject`,
			);
		}
		if (!result.html) {
			throw new Error(
				`Email handler for "${String(options.template)}" must return html`,
			);
		}

		return result;
	}

	/**
	 * Send an email using a defined template
	 */
	async sendTemplate<K extends EmailTemplateNames<TTemplates>>(options: {
		template: K;
		input: InferEmailTemplateInput<GetEmailTemplate<TTemplates, K>>;
		to: string | string[];
		subject?: string;
		from?: string;
		cc?: string | string[];
		bcc?: string | string[];
		replyTo?: string;
		locale?: string;
		ctx?: { app?: unknown; db?: unknown; session?: unknown };
	}): Promise<void> {
		const result = await this.renderTemplate({
			template: options.template,
			input: options.input,
			locale: options.locale,
			ctx: options.ctx,
		});

		return this.send({
			to: options.to,
			subject: options.subject || result.subject,
			from: options.from,
			cc: options.cc,
			bcc: options.bcc,
			replyTo: options.replyTo,
			html: result.html,
			text: result.text,
		});
	}
}
