import { Database, Blocks, ArrowLeftRight, Layers } from "lucide-react";

const approaches = [
	{
		icon: Database,
		title: "Your Schema is Drizzle",
		description:
			"No proprietary schema DSL. Use native Drizzle ORM column types directly. Migrations auto-generated by Drizzle Kit. Full PostgreSQL power.",
		links: [
			{ label: "Drizzle ORM", href: "https://orm.drizzle.team/" },
			{ label: "Fields Reference", href: "/docs/core-concepts/fields" },
		],
	},
	{
		icon: Blocks,
		title: "Native Libraries, Not Abstractions",
		description:
			"Better Auth for authentication. pg-boss for background jobs. Nodemailer + React Email for transactional email. Flydrive for file storage. Learn once, use everywhere.",
		links: [
			{ label: "Better Auth", href: "https://www.better-auth.com/" },
			{ label: "pg-boss", href: "https://github.com/timgit/pg-boss" },
		],
	},
	{
		icon: ArrowLeftRight,
		title: "Adapter Pattern",
		description:
			"Swap queue backend (pg-boss, BullMQ, custom). Swap email provider (SMTP, Sendgrid, Resend). Swap storage (local, S3, R2). Your infrastructure, your choice.",
		links: [
			{ label: "Queue Guide", href: "/docs/guides/queue-jobs" },
			{ label: "Storage Guide", href: "/docs/guides/storage-upload" },
		],
	},
	{
		icon: Layers,
		title: "Decoupled by Design",
		description:
			"Backend schema is pure data. Admin UI is a separate package. Build multiple frontends on the same backend. No UI code in your schema definitions.",
		links: [
			{ label: "Collections", href: "/docs/core-concepts/collections" },
			{ label: "Globals", href: "/docs/core-concepts/globals" },
		],
	},
];

export function OurApproach() {
	return (
		<section className="py-24 border-t border-border/50">
			<div className="w-full max-w-7xl mx-auto px-4">
				<div className="text-center max-w-2xl mx-auto space-y-4 mb-16">
					<h2 className="font-mono text-sm tracking-[0.2em] uppercase text-primary">
						Our Approach
					</h2>
					<h3 className="text-3xl md:text-4xl font-bold">
						Native Libraries, Zero Lock-in
					</h3>
					<p className="text-muted-foreground">
						We integrate the best tools in the TypeScript ecosystem instead of
						reinventing them. Everything you learn here applies outside QUESTPIE
						too.
					</p>
				</div>

				<div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
					{approaches.map((approach, i) => (
						<div
							key={i}
							className="group p-6 border border-border bg-card/30 hover:border-primary/50 hover:bg-card/50 transition-all space-y-4"
						>
							<div className="inline-flex items-center justify-center w-12 h-12 bg-primary/10 border border-primary/20">
								<approach.icon className="w-6 h-6 text-primary" />
							</div>

							<h4 className="text-lg font-bold group-hover:text-primary transition-colors">
								{approach.title}
							</h4>

							<p className="text-sm text-muted-foreground leading-relaxed">
								{approach.description}
							</p>

							<div className="flex flex-wrap gap-2 pt-2">
								{approach.links.map((link, j) => (
									<a
										key={j}
										href={link.href}
										className="text-xs font-mono text-primary hover:underline underline-offset-2"
									>
										{link.label}
									</a>
								))}
							</div>
						</div>
					))}
				</div>
			</div>
		</section>
	);
}
