/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Routes ────────────────────────────────────────────
import _route_sandbox_rpc from "../routes/sandbox/rpc";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { RouteDefinition, RouteParamsFromKey } from "questpie/types";

export type ExecutorCollections = Record<never, never>;

export type ExecutorGlobals = Record<never, never>;

export type ExecutorJobs = Record<never, never>;

export type ExecutorRoutes = {
	"sandbox/rpc": typeof _route_sandbox_rpc extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"sandbox/rpc">> : typeof _route_sandbox_rpc;
};

export type ExecutorFieldTypes = Record<never, never>;

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type ExecutorModule = {
	name: "questpie-executor";
	routes: ExecutorRoutes;
	collections: ExecutorCollections;
	globals: ExecutorGlobals;
	jobs: ExecutorJobs;
	fieldTypes: ExecutorFieldTypes;
	messages: Record<never, never>;
	services: Record<never, never>;
	emails: Record<never, never>;
	migrations: readonly unknown[];
	seeds: readonly unknown[];
};

const _module: ExecutorModule = {
	name: "questpie-executor" as const,
	routes: {
		"sandbox/rpc": _route_sandbox_rpc,
	} as ExecutorRoutes,
	collections: {},
	globals: {},
	jobs: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
};

export default _module;
