import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { projectObservationSignalProjection } from "../../compiler/src/observation";

const packageRoot = resolve(import.meta.dir, "..");
const target = resolve(packageRoot, "src/generated/signal-projection.gen.ts");
const projection = projectObservationSignalProjection("4.0.0-beta.2");
const output = `// Generated by scripts/generate-signal-projection.ts. Do not edit.\nexport const SIGNAL_PROJECTION_ARTIFACT = ${JSON.stringify(projection.artifact)} as const;\n\nexport const SIGNAL_PROJECTION_DIGEST = ${JSON.stringify(projection.digest)} as const;\n`;

if (process.argv.includes("--check")) {
	let current = "";
	try {
		current = readFileSync(target, "utf8");
	} catch {
		// The deterministic comparison below owns the diagnostic.
	}
	if (current !== output) {
		console.error(
			"opentelemetry: generated signal projection is stale; run bun run generate:projection",
		);
		process.exit(1);
	}
} else {
	await Bun.write(target, output);
}
