/**
 * Executor Module
 *
 * Opt-in host-side sandbox/executor capability module — mounts the
 * `POST /api/sandbox/rpc` broker route (the trusted host side of the
 * untrusted sandbox bindings path).
 *
 * Exports:
 * - `executorModule` — static module definition (generated by codegen from file convention)
 * - `ExecutorModule` — type of the static module
 */
import generatedModule from "./.generated/module.js";

export type {
	ExecutorCollections,
	ExecutorFieldTypes,
	ExecutorGlobals,
	ExecutorJobs,
	ExecutorModule,
	ExecutorRoutes,
} from "./.generated/module.js";

export const executorModule = generatedModule;

export default executorModule;
