/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module
import "./registries.js";


// ── Sub-Modules ────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_account from "../collections/account";
import _coll_admin_locks from "../collections/admin-locks";
import _coll_admin_preferences from "../collections/admin-preferences";
import _coll_admin_saved_views from "../collections/admin-saved-views";
import _coll_apikey from "../collections/apikey";
import _coll_assets from "../collections/assets";
import _coll_jwks from "../collections/jwks";
import _coll_oauthAccessToken from "../collections/oauth-access-token";
import _coll_oauthClient from "../collections/oauth-client";
import _coll_oauthConsent from "../collections/oauth-consent";
import _coll_oauthRefreshToken from "../collections/oauth-refresh-token";
import _coll_session from "../collections/session";
import _coll_user from "../collections/user";
import _coll_verification from "../collections/verification";

// ── Routes ────────────────────────────────────────────
import { adminConfigFunctions as _route_adminConfig } from "../routes/admin-config";
import { actionFunctions as _route_executeAction } from "../routes/execute-action";
import { translateAdminMessage as _route_i18nHelpers } from "../routes/i18n-helpers";
import { localeFunctions as _route_locales } from "../routes/locales";
import { previewFunctions as _route_preview } from "../routes/preview";
import { reactiveFunctions as _route_reactive } from "../routes/reactive";
import { getApp as _route_routeHelpers } from "../routes/route-helpers";
import { setupFunctions as _route_setup } from "../routes/setup";
import { translationFunctions as _route_translations } from "../routes/translations";
import { widgetDataFunctions as _route_widgetData } from "../routes/widget-data";

// ── Views ────────────────────────────────────────────
import _view_collectionForm from "../views/form";
import _view_collectionTable from "../views/table";
import _view_globalForm from "../views/global-form";
import _view_listView from "../views/list-view";

// ── Components ────────────────────────────────────────────
import _comp_badge from "../components/badge";
import _comp_icon from "../components/icon";

// ── Singles ────────────────────────────────────────────────
import _adminConfig from "../config/admin";
import _fields from "../fields";
import _plugin from "../plugin";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { RouteDefinition, RouteParamsFromKey } from "questpie/types";

export type AdminCollections = {
	account: typeof _coll_account;
	admin_locks: typeof _coll_admin_locks;
	admin_preferences: typeof _coll_admin_preferences;
	admin_saved_views: typeof _coll_admin_saved_views;
	apikey: typeof _coll_apikey;
	assets: typeof _coll_assets;
	jwks: typeof _coll_jwks;
	oauthAccessToken: typeof _coll_oauthAccessToken;
	oauthClient: typeof _coll_oauthClient;
	oauthConsent: typeof _coll_oauthConsent;
	oauthRefreshToken: typeof _coll_oauthRefreshToken;
	session: typeof _coll_session;
	user: typeof _coll_user;
	verification: typeof _coll_verification;
};

export type AdminGlobals = Record<never, never>;

export type AdminJobs = Record<never, never>;

export type AdminRoutes = { i18nHelpers: typeof _route_i18nHelpers extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"i18nHelpers">> : typeof _route_i18nHelpers; routeHelpers: typeof _route_routeHelpers extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"routeHelpers">> : typeof _route_routeHelpers } & typeof _route_adminConfig & typeof _route_executeAction & typeof _route_locales & typeof _route_preview & typeof _route_reactive & typeof _route_setup & typeof _route_translations & typeof _route_widgetData;

export type AdminFieldTypes = Record<never, never>;

export type AdminViews = {
	collectionForm: typeof _view_collectionForm;
	collectionTable: typeof _view_collectionTable;
	globalForm: typeof _view_globalForm;
	listView: typeof _view_listView;
};

export type AdminComponents = {
	badge: typeof _comp_badge;
	icon: typeof _comp_icon;
};

export type AdminBlocks = Record<never, never>;

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type AdminModule = {
	name: "questpie-admin";
	modules: typeof _modules;
	collections: AdminCollections;
	routes: AdminRoutes;
	views: AdminViews;
	components: AdminComponents;
	globals: AdminGlobals;
	jobs: AdminJobs;
	fieldTypes: AdminFieldTypes;
	blocks: AdminBlocks;
	messages: Record<never, never>;
	services: Record<never, never>;
	emails: Record<never, never>;
	migrations: readonly unknown[];
	seeds: readonly unknown[];
	config: {
		admin: typeof _adminConfig;
	};
	fields: typeof _fields;
	plugin: typeof _plugin;
};

const _module: AdminModule = {
	name: "questpie-admin" as const,
	modules: _modules,
	collections: {
		account: _coll_account,
		admin_locks: _coll_admin_locks,
		admin_preferences: _coll_admin_preferences,
		admin_saved_views: _coll_admin_saved_views,
		apikey: _coll_apikey,
		assets: _coll_assets,
		jwks: _coll_jwks,
		oauthAccessToken: _coll_oauthAccessToken,
		oauthClient: _coll_oauthClient,
		oauthConsent: _coll_oauthConsent,
		oauthRefreshToken: _coll_oauthRefreshToken,
		session: _coll_session,
		user: _coll_user,
		verification: _coll_verification,
	} as AdminCollections,
	routes: {
		..._route_adminConfig,
		..._route_executeAction,
		i18nHelpers: _route_i18nHelpers,
		..._route_locales,
		..._route_preview,
		..._route_reactive,
		routeHelpers: _route_routeHelpers,
		..._route_setup,
		..._route_translations,
		..._route_widgetData,
	} as AdminRoutes,
	views: {
		collectionForm: _view_collectionForm,
		collectionTable: _view_collectionTable,
		globalForm: _view_globalForm,
		listView: _view_listView,
	} as AdminViews,
	components: {
		badge: _comp_badge,
		icon: _comp_icon,
	} as AdminComponents,
	globals: {},
	jobs: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	blocks: {},
	config: {
		admin: _adminConfig,
	},
	fields: _fields,
	plugin: _plugin,
};

export default _module;
