/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Admin Extensions ───────────────────────────────────────
import { component, editView, listView } from "../../../registry-helpers.js";

// ── Collections ────────────────────────────────────────────
import _coll_account from "../collections/account.js";
import _coll_apikey from "../collections/apikey.js";
import _coll_assets from "../collections/assets.js";
import _coll_locks from "../collections/locks.js";
import _coll_preferences from "../collections/preferences.js";
import _coll_savedViews from "../collections/saved-views.js";
import _coll_session from "../collections/session.js";
import _coll_user from "../collections/user.js";
import _coll_verification from "../collections/verification.js";
// ── Singles ────────────────────────────────────────────────
import _fields from "../fields.js";
// ── Functions ──────────────────────────────────────────────
import { adminConfigFunctions } from "../functions/admin-config.js";
import { actionFunctions } from "../functions/execute-action.js";
import { localeFunctions } from "../functions/locales.js";
import { previewFunctions } from "../functions/preview.js";
import { reactiveFunctions } from "../functions/reactive.js";
import { setupFunctions } from "../functions/setup.js";
import { translationFunctions } from "../functions/translations.js";
import { widgetDataFunctions } from "../functions/widget-data.js";
// ── Sub-Modules ────────────────────────────────────────────
import _modules from "../modules.js";
import _sidebar from "../sidebar.js";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface AdminCollections {
	account: typeof _coll_account;
	adminLocks: typeof _coll_locks;
	adminPreferences: typeof _coll_preferences;
	adminSavedViews: typeof _coll_savedViews;
	apikey: typeof _coll_apikey;
	assets: typeof _coll_assets;
	session: typeof _coll_session;
	user: typeof _coll_user;
	verification: typeof _coll_verification;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-admin" as const,
	modules: _modules,
	collections: {
		user: _coll_user,
		assets: _coll_assets,
		session: _coll_session,
		account: _coll_account,
		verification: _coll_verification,
		apikey: _coll_apikey,
		adminSavedViews: _coll_savedViews,
		adminPreferences: _coll_preferences,
		adminLocks: _coll_locks,
	} as AdminCollections,
	functions: {
		...setupFunctions,
		...localeFunctions,
		...previewFunctions,
		...adminConfigFunctions,
		...actionFunctions,
		...translationFunctions,
		...widgetDataFunctions,
		...reactiveFunctions,
	},
	fields: _fields,
	listViews: { table: listView("table") },
	editViews: { form: editView("form") },
	components: {
		icon: component("icon"),
		badge: component("badge"),
	},
	sidebar: [_sidebar],
	dashboard: [] as const,
};

export type AdminModule = typeof _module;
export default _module;
