export { adminConfig } from "../server/augmentation.js";
export type {
	ActionReference,
	ActionsConfigContext,
	AdminBlockConfig,
	AdminCollectionConfig,
	AdminConfigContext,
	AdminConfigInput,
	AdminGlobalConfig,
	AdminLocaleConfig,
	AdminShellRailPlacement,
	AdminShellRouteRules,
	BlockCategoryConfig,
	BuiltinActionType,
	ComponentDefinition,
	ComponentFactory,
	ComponentReference,
	ComponentType,
	ComponentTypeRegistry,
	DashboardActionFactory,
	DashboardActionProxy,
	DashboardCallback,
	DashboardCallbackContext,
	DashboardConfigContext,
	DashboardContribution,
	DashboardItemDef,
	DashboardProxy,
	DashboardSectionDef,
	EditViewDefinition,
	EditViewFactory,
	FieldLayoutItem,
	FilterViewsByKind,
	FormFieldLayoutItem,
	FormReactiveConfig,
	FormReactiveContext,
	FormSectionLayout,
	FormSidebarConfig,
	FormTabConfig,
	FormTabsLayout,
	FormViewConfig,
	FormViewConfigContext,
	ListViewConfig,
	ListViewConfigContext,
	ListViewDefinition,
	ListViewFactory,
	PreviewConfig,
	ServerActionContext,
	ServerActionDefinition,
	ServerActionDownload,
	ServerActionEffects,
	ServerActionError,
	ServerActionForm,
	ServerActionFormField,
	ServerActionHandler,
	ServerActionRedirect,
	ServerActionResult,
	ServerActionSuccess,
	ServerActionsConfig,
	ServerBrandingConfig,
	ServerAdminShellConfig,
	ServerAdminShellRailConfig,
	ServerChartWidget,
	ServerCustomWidget,
	ServerDashboardAction,
	ServerDashboardConfig,
	ServerDashboardItem,
	ServerDashboardSection,
	ServerDashboardTab,
	ServerDashboardTabs,
	ServerDashboardWidget,
	ServerProgressWidget,
	ServerQuickAction,
	ServerQuickActionsWidget,
	ServerRecentItemsWidget,
	ServerSidebarCollectionItem,
	ServerSidebarConfig,
	ServerSidebarDividerItem,
	ServerSidebarGlobalItem,
	ServerSidebarItem,
	ServerSidebarLinkItem,
	ServerSidebarPageItem,
	ServerSidebarSection,
	ServerStatsWidget,
	ServerTableWidget,
	ServerTimelineWidget,
	ServerValueWidget,
	SidebarCallback,
	SidebarCallbackContext,
	SidebarConfigContext,
	SidebarContribution,
	SidebarItemDef,
	SidebarProxy,
	SidebarSectionDef,
	ViewDefinition,
	ViewKind,
	ViewKindRegistry,
	WidgetAccessRule,
	WidgetFetchContext,
} from "../server/augmentation.js";

export {
	component,
	editView,
	filterViewsByKind,
	listView,
	view,
} from "../server/registry-helpers.js";

export {
	createActionCallbackProxy,
	createActionProxy,
	createComponentCallbackProxy,
	createComponentProxy,
	createDashboardCallbackContext,
	createDashboardContributionProxy,
	createFieldProxy,
	createSidebarCallbackContext,
	createSidebarContributionProxy,
	createViewCallbackProxy,
	createViewProxy,
	resolveDashboardCallback,
	resolveSidebarCallback,
} from "../server/proxy-factories.js";

export {
	type AnyBlockBuilder,
	type AnyBlockDefinition,
	BlockBuilder,
	type BlockBuilderState,
	type BlockDefinition,
	type BlockPrefetchContext,
	type BlockPrefetchFn,
	type BlockPrefetchWith,
	type BlockPrefetchWithOptions,
	type BlockSchema,
	type BlocksPrefetchContext,
	block,
	createBlocksPrefetchHook,
	type ExpandedRecord,
	type ExpandWithResult,
	getBlocksByCategory,
	type InferBlockData,
	type InferBlockValues,
	introspectBlock,
	introspectBlocks,
	processBlocksDocument,
	processDocumentBlocksPrefetch,
} from "../server/block/index.js";

export {
	type AuthSession,
	type GetAdminSessionOptions,
	getAdminSession,
	isAdminUser,
	type RequireAdminAuthOptions,
	requireAdminAuth,
} from "../server/auth-helpers.js";

export * from "../server/adapters/index.js";
