/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate -c src/questpie/server/questpie.config.ts

import { createApp } from "questpie/app";
import type { AppDefinition, RuntimeConfig } from "questpie/types";
import type { _AppQuestpie, AppSession } from "./context.gen";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import { inventoryMovements as _coll_inventoryMovements } from "../collections/inventory-movements";
import { machines as _coll_machines } from "../collections/machines";
import { materials as _coll_materials } from "../collections/materials";
import { operations as _coll_operations } from "../collections/operations";
import { productionOrders as _coll_productionOrders } from "../collections/production-orders";
import { toyMaterials as _coll_toyMaterials } from "../collections/toy-materials";
import { toys as _coll_toys } from "../collections/toys";

// ── Globals ────────────────────────────────────────────────
import { siteSettings as _glob_siteSettings } from "../globals/site-settings";

// ── Jobs ───────────────────────────────────────────────────
import _job_recalculateMaterialPlan from "../jobs/recalculate-material-plan";

// ── Routes ─────────────────────────────────────────────────
import _route_rpc_planning_capacitySummary from "../routes/rpc/planning/capacity-summary";
import _route_rpc_planning_receiveMaterials from "../routes/rpc/planning/receive-materials";
import _route_rpc_planning_startProduction from "../routes/rpc/planning/start-production";

// ── Services ───────────────────────────────────────────────
import _svc_capacityPlanner from "../services/capacity-planner";

// ── Emails ─────────────────────────────────────────────────
import _email_productionScheduled from "../emails/production-scheduled";

// ── Seeds ──────────────────────────────────────────────────
import _seed_demo from "../seeds/demo";

// ── Workflows ──────────────────────────────────────────────
import _wf_nightlyCapacityReview from "../workflows/nightly-capacity-review";
import _wf_productionOrderPlan from "../workflows/production-order-plan";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _openapi from "../config/openapi";

const _appDefinition = ({
	modules: _modules,
	collections: {
		inventoryMovements: _coll_inventoryMovements,
		machines: _coll_machines,
		materials: _coll_materials,
		operations: _coll_operations,
		productionOrders: _coll_productionOrders,
		toyMaterials: _coll_toyMaterials,
		toys: _coll_toys,
	},
	globals: {
		siteSettings: _glob_siteSettings,
	},
	jobs: {
		recalculateMaterialPlan: _job_recalculateMaterialPlan,
	},
	routes: {
		"rpc/planning/capacitySummary": _route_rpc_planning_capacitySummary,
		"rpc/planning/receiveMaterials": _route_rpc_planning_receiveMaterials,
		"rpc/planning/startProduction": _route_rpc_planning_startProduction,
	},
	services: {
		capacityPlanner: _svc_capacityPlanner,
	},
	emailTemplates: {
		productionScheduled: _email_productionScheduled,
	},
	seeds: [_seed_demo],
	workflows: {
		[_wf_nightlyCapacityReview.name]: _wf_nightlyCapacityReview,
		[_wf_productionOrderPlan.name]: _wf_productionOrderPlan,
	},
	config: {
		app: _appConfig,
		auth: _authConfig,
		admin: _adminConfig,
		openapi: _openapi,
	},
}) satisfies AppDefinition;

export const createAppForRuntime = (async (runtime: RuntimeConfig) =>
	(await createApp(_appDefinition, runtime)) as unknown as _AppQuestpie) as ((
	runtime: RuntimeConfig,
) => Promise<_AppQuestpie>) & {
	readonly "~types"?: { session: AppSession };
};
