/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import "./names.gen.js";
// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import { inventoryMovements as _coll_inventoryMovements } from "../collections/inventory-movements";
import { machines as _coll_machines } from "../collections/machines";
import { materials as _coll_materials } from "../collections/materials";
import { operations as _coll_operations } from "../collections/operations";
import { productionOrders as _coll_productionOrders } from "../collections/production-orders";
import { toyMaterials as _coll_toyMaterials } from "../collections/toy-materials";
import { toys as _coll_toys } from "../collections/toys";

// ── Globals ────────────────────────────────────────────────
import { siteSettings as _glob_siteSettings } from "../globals/site-settings.global";

// ── Jobs ───────────────────────────────────────────────────
import _job_recalculateMaterialPlan from "../jobs/recalculate-material-plan";

// ── Routes ─────────────────────────────────────────────────
import _route_rpc_planning_capacitySummary from "../routes/rpc/planning/capacity-summary";
import _route_rpc_planning_receiveMaterials from "../routes/rpc/planning/receive-materials";
import _route_rpc_planning_startProduction from "../routes/rpc/planning/start-production";

// ── Services ───────────────────────────────────────────────
import _svc_capacityPlanner from "../services/capacity-planner";

// ── Emails ─────────────────────────────────────────────────
import _email_productionScheduled from "../emails/production-scheduled";

// ── Seeds ──────────────────────────────────────────────────
import _seed_demo_seed from "../seeds/demo.seed";

// ── Workflows ──────────────────────────────────────────────
import _wf_nightlyCapacityReview from "../workflows/nightly-capacity-review";
import _wf_productionOrderPlan from "../workflows/production-order-plan";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _openapi from "../config/openapi";

import type { RouteParamsFromKey, RouteWithParams } from "questpie/types";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { ExtractModulePropArr, ServiceCustomNamespaceInstances, ServiceInstanceOf, ServiceInstancesInNamespace, ServiceTopLevelInstances } from "questpie/types";
type _RouteDefinitionWithoutHandler<T> = T extends { mode: "raw" } ? Omit<T, "handler"> & { handler: (args: unknown) => Response | Promise<Response> } : Omit<T, "handler"> & { handler: (args: unknown) => unknown | Promise<unknown> };
export type _ModuleCollections = ExtractModulePropArr<typeof _modules, "collections">;
export type _ModuleGlobals = ExtractModulePropArr<typeof _modules, "globals">;
export type _ModuleJobs = ExtractModulePropArr<typeof _modules, "jobs">;
export type _ModuleRoutes = ExtractModulePropArr<typeof _modules, "routes">;
export type _ModuleServices = {};
export type _ModuleFieldTypes = ExtractModulePropArr<typeof _modules, "fieldTypes">;
export type _ModuleViews = ExtractModulePropArr<typeof _modules, "views">;
export type _ModuleComponents = ExtractModulePropArr<typeof _modules, "components">;
export type _ModuleBlocks = ExtractModulePropArr<typeof _modules, "blocks">;
export type _ModuleWorkflows = ExtractModulePropArr<typeof _modules, "workflows">;
// Registry category extraction from modules
export type _Registry_Collections = ExtractModulePropArr<typeof _modules, "collections">;
export type _Registry_Globals = ExtractModulePropArr<typeof _modules, "globals">;
export type _Registry_Jobs = ExtractModulePropArr<typeof _modules, "jobs">;
export type _Registry_Routes = ExtractModulePropArr<typeof _modules, "routes">;
export type _Registry_Services = {};
export type _Registry_Emails = ExtractModulePropArr<typeof _modules, "emails">;
export type _Registry_FieldTypes = ExtractModulePropArr<typeof _modules, "fieldTypes">;
export type _Registry_Views = ExtractModulePropArr<typeof _modules, "views">;
export type _Registry_Components = ExtractModulePropArr<typeof _modules, "components">;
export type _Registry_Blocks = ExtractModulePropArr<typeof _modules, "blocks">;
export type _Registry_Workflows = ExtractModulePropArr<typeof _modules, "workflows">;

// Recursive module property extraction (for fields contributed at each level)
import type { ExtractModuleProp } from "questpie/types";

export type _AllModuleFields = ExtractModuleProp<{ modules: typeof _modules }, "fields">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = _ModuleCollections & {
	inventoryMovements: typeof _coll_inventoryMovements;
	machines: typeof _coll_machines;
	materials: typeof _coll_materials;
	operations: typeof _coll_operations;
	productionOrders: typeof _coll_productionOrders;
	toyMaterials: typeof _coll_toyMaterials;
	toys: typeof _coll_toys;
};

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = _ModuleGlobals & {
	siteSettings: typeof _glob_siteSettings;
};

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs & {
	recalculateMaterialPlan: Omit<typeof _job_recalculateMaterialPlan, "handler"> & { handler: (args: unknown) => Promise<unknown> };
};

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes & {
	"rpc/planning/capacitySummary": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_rpc_planning_capacitySummary>, RouteParamsFromKey<"rpc/planning/capacitySummary">>;
	"rpc/planning/receiveMaterials": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_rpc_planning_receiveMaterials>, RouteParamsFromKey<"rpc/planning/receiveMaterials">>;
	"rpc/planning/startProduction": RouteWithParams<_RouteDefinitionWithoutHandler<typeof _route_rpc_planning_startProduction>, RouteParamsFromKey<"rpc/planning/startProduction">>;
};

/** All service definitions in the app (modules + user, user overrides). */
type _AppServiceDefinitions = _ModuleServices & {
	capacityPlanner: typeof _svc_capacityPlanner;
};

/** All services in the app as resolved service instances. */
export type AppServices = {
	[K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]>;
};
export type _AppDefaultServices = ServiceInstancesInNamespace<_AppServiceDefinitions, "services">;
export type _AppTopLevelServices = ServiceTopLevelInstances<_AppServiceDefinitions>;
export type _AppCustomServiceNamespaces = ServiceCustomNamespaceInstances<_AppServiceDefinitions>;

/** All email templates in the app — use with email.sendTemplate() */
export type AppEmailTemplates = {
	productionScheduled: typeof _email_productionScheduled;
};

/** All fieldtypes in the app (modules + user, user overrides) */
export type AppFieldTypes = _ModuleFieldTypes;

/** All views in the app (modules + user, user overrides) */
export type AppViews = _ModuleViews;

/** All components in the app (modules + user, user overrides) */
export type AppComponents = _ModuleComponents;

/** All blocks in the app (modules + user, user overrides) */
export type AppBlocks = _ModuleBlocks;

/** All workflows in the app (modules + user, user overrides) */
export type AppWorkflows = _ModuleWorkflows
	& { [K in typeof _wf_nightlyCapacityReview.name]: Omit<typeof _wf_nightlyCapacityReview, "handler" | "onFailure"> & { handler: (args: unknown) => Promise<unknown>; onFailure?: (args: unknown) => Promise<void> } }
	& { [K in typeof _wf_productionOrderPlan.name]: Omit<typeof _wf_productionOrderPlan, "handler" | "onFailure"> & { handler: (args: unknown) => Promise<unknown>; onFailure?: (args: unknown) => Promise<void> } };
