/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import { createApp, createContextFactory, type AnyCollectionOrBuilder, type AnyGlobalOrBuilder, type AppDefinition, type CollectionAPI, type DrizzleClientFromQuestpieConfig, type InferContextExtensionsFromAppConfig, type InferSessionFromAuthConfig, type MailerService, type Questpie, type QuestpieConfig, type QueueClient, type RouteParamsFromKey, type RouteWithParams, type TablesFromConfig } from "questpie";

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import { inventoryMovements as _coll_inventoryMovements } from "../collections/inventory-movements";
import { machines as _coll_machines } from "../collections/machines";
import { materials as _coll_materials } from "../collections/materials";
import { operations as _coll_operations } from "../collections/operations";
import { productionOrders as _coll_productionOrders } from "../collections/production-orders";
import { toyMaterials as _coll_toyMaterials } from "../collections/toy-materials";
import { toys as _coll_toys } from "../collections/toys";

// ── Globals ────────────────────────────────────────────────
import { siteSettings as _glob_siteSettings } from "../globals/site-settings.global";

// ── Jobs ───────────────────────────────────────────────────
import _job_recalculateMaterialPlan from "../jobs/recalculate-material-plan";

// ── Routes ─────────────────────────────────────────────────
import _route_rpc_planning_capacitySummary from "../routes/rpc/planning/capacity-summary";
import _route_rpc_planning_receiveMaterials from "../routes/rpc/planning/receive-materials";
import _route_rpc_planning_startProduction from "../routes/rpc/planning/start-production";

// ── Services ───────────────────────────────────────────────
import _svc_capacityPlanner from "../services/capacity-planner";

// ── Emails ─────────────────────────────────────────────────
import _email_productionScheduled from "../emails/production-scheduled";

// ── Seeds ──────────────────────────────────────────────────
import _seed_demo_seed from "../seeds/demo.seed";

// ── Workflows ──────────────────────────────────────────────
import _wf_nightlyCapacityReview from "../workflows/nightly-capacity-review";
import _wf_productionOrderPlan from "../workflows/production-order-plan";

// ── Core Singles ───────────────────────────────────────────
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _openapi from "../config/openapi";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { ServiceCustomNamespaceInstances, ServiceInstanceOf, ServiceInstancesInNamespace, ServiceTopLevelInstances, UnionToIntersection } from "questpie";
type _Module = (typeof _modules)[number];
type _MPRaw<K extends string> = UnionToIntersection<_Module extends infer M ? M extends Record<K, infer V> ? V : never : never>;
type _MP<K extends string> = [_MPRaw<K>] extends [never] ? {} : _MPRaw<K>;
type _ModuleConfig = _MP<"config">;
type _AppAppConfig = _ModuleConfig extends { app: infer TApp } ? TApp : {};
type _AppContextExtensions = Partial<InferContextExtensionsFromAppConfig<_AppAppConfig>>;
type _AppAuthConfig = (_ModuleConfig extends { auth: infer TAuth } ? TAuth : {}) & typeof _authConfig;
type _AppSession = NonNullable<InferSessionFromAuthConfig<_AppAuthConfig>> | null;

type _ModuleCollections = _MP<"collections">;
type _ModuleGlobals = _MP<"globals">;
type _ModuleJobs = _MP<"jobs">;
type _ModuleRoutes = _MP<"routes">;
type _ModuleServices = _MP<"services">;
type _ModuleFieldTypes = _MP<"fieldTypes">;
type _ModuleViews = _MP<"views">;
type _ModuleComponents = _MP<"components">;
type _ModuleBlocks = _MP<"blocks">;
type _ModuleWorkflows = _MP<"workflows">;
// Registry category extraction from modules
type _Registry_Collections = _MP<"collections">;
type _Registry_Globals = _MP<"globals">;
type _Registry_Jobs = _MP<"jobs">;
type _Registry_Routes = _MP<"routes">;
type _Registry_Services = _MP<"services">;
type _Registry_Emails = _MP<"emails">;
type _Registry_FieldTypes = _MP<"fieldTypes">;
type _Registry_Views = _MP<"views">;
type _Registry_Components = _MP<"components">;
type _Registry_Blocks = _MP<"blocks">;
type _Registry_Workflows = _MP<"workflows">;

// Recursive module property extraction (for fields contributed at each level)
import type { ExtractModuleProp } from "questpie";

type _AllModuleFields = ExtractModuleProp<{ modules: typeof _modules }, "fields">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = _ModuleCollections & {
	inventoryMovements: typeof _coll_inventoryMovements;
	machines: typeof _coll_machines;
	materials: typeof _coll_materials;
	operations: typeof _coll_operations;
	productionOrders: typeof _coll_productionOrders;
	toyMaterials: typeof _coll_toyMaterials;
	toys: typeof _coll_toys;
};

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = _ModuleGlobals & {
	siteSettings: typeof _glob_siteSettings;
};

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs & {
	recalculateMaterialPlan: typeof _job_recalculateMaterialPlan;
};

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes & {
	"rpc/planning/capacitySummary": RouteWithParams<typeof _route_rpc_planning_capacitySummary, RouteParamsFromKey<"rpc/planning/capacitySummary">>;
	"rpc/planning/receiveMaterials": RouteWithParams<typeof _route_rpc_planning_receiveMaterials, RouteParamsFromKey<"rpc/planning/receiveMaterials">>;
	"rpc/planning/startProduction": RouteWithParams<typeof _route_rpc_planning_startProduction, RouteParamsFromKey<"rpc/planning/startProduction">>;
};

/** All service definitions in the app (modules + user, user overrides). */
type _AppServiceDefinitions = _ModuleServices & {
	capacityPlanner: typeof _svc_capacityPlanner;
};

/** All services in the app as resolved service instances. */
export type AppServices = {
	[K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]>;
};
type _AppDefaultServices = ServiceInstancesInNamespace<_AppServiceDefinitions, "services">;
type _AppTopLevelServices = ServiceTopLevelInstances<_AppServiceDefinitions>;
type _AppCustomServiceNamespaces = ServiceCustomNamespaceInstances<_AppServiceDefinitions>;

/** All email templates in the app — use with email.sendTemplate() */
export type AppEmailTemplates = {
	productionScheduled: typeof _email_productionScheduled;
};

/** All fieldtypes in the app (modules + user, user overrides) */
export type AppFieldTypes = _ModuleFieldTypes;

/** All views in the app (modules + user, user overrides) */
export type AppViews = _ModuleViews;

/** All components in the app (modules + user, user overrides) */
export type AppComponents = _ModuleComponents;

/** All blocks in the app (modules + user, user overrides) */
export type AppBlocks = _ModuleBlocks;

/** All workflows in the app (modules + user, user overrides) */
export type AppWorkflows = _ModuleWorkflows
	& { [K in typeof _wf_nightlyCapacityReview.name]: typeof _wf_nightlyCapacityReview }
	& { [K in typeof _wf_productionOrderPlan.name]: typeof _wf_productionOrderPlan };

export type AppRouteKeys = "rpc/planning/startProduction" | "rpc/planning/receiveMaterials" | "rpc/planning/capacitySummary";

type _CollectionsAPI = { [K in keyof AppCollections]: CollectionAPI<AppCollections[K], AppCollections> };
type _AppCollectionDefinitions = AppCollections & Record<string, AnyCollectionOrBuilder>;
type _AppGlobalDefinitions = AppGlobals & Record<string, AnyGlobalOrBuilder>;
type _AppQuestpieConfig = Omit<QuestpieConfig, "app" | "db" | "collections" | "globals" | "auth"> & {
	app: (typeof _runtime)["app"];
	db: (typeof _runtime)["db"];
	collections: _AppCollectionDefinitions;
	globals: _AppGlobalDefinitions;
	auth: _AppAuthConfig;
};
type _AppQuestpieBase = Questpie<_AppQuestpieConfig>;
type _AppDb = DrizzleClientFromQuestpieConfig<_AppQuestpieConfig>;
type _AppGlobalsAPI = _AppQuestpieBase["globals"];
type _AppStorage = _AppQuestpieBase["storage"];
type _AppTables = TablesFromConfig<_AppQuestpieConfig>;
type _AppQuestpie = Omit<_AppQuestpieBase, "collections" | "globals"> & {
	collections: _CollectionsAPI;
	globals: _AppGlobalsAPI;
};

// ── AppContext augmentation — auto-types ALL handlers ──────
declare global {
	namespace Questpie {
		interface AppContext extends _AppTopLevelServices, _AppCustomServiceNamespaces, _AppContextExtensions {
			// Infrastructure
			db: _AppDb;
			email: MailerService<AppEmailTemplates>;
			queue: QueueClient<AppJobs>;
			storage: _AppStorage;
			kv: _AppQuestpie["kv"];
			logger: _AppQuestpie["logger"];
			search: _AppQuestpie["search"];
			realtime: _AppQuestpie["realtime"];

			// Entity APIs
			collections: _CollectionsAPI;
			globals: _AppGlobalsAPI;
			tables: _AppTables;

			// Request-scoped
			session: _AppSession;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

			// User services
			services: _AppDefaultServices;
		}

		interface ServiceCreateContext extends AppContext {}

		interface Registry {
			collections: _Registry_Collections;
			globals: _Registry_Globals;
			jobs: _Registry_Jobs;
			routes: _Registry_Routes;
			services: _Registry_Services;
			emails: _Registry_Emails;
			"~fieldTypes": _Registry_FieldTypes & _AllModuleFields;
			views: _Registry_Views;
			components: _Registry_Components;
			blocks: _Registry_Blocks;
			workflows: _Registry_Workflows;
		}
	}
}

/**
 * Flat config type for client APIs.
 * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.
 * For handler context, use `AppContext` (auto-typed via module augmentation).
 */
export type AppConfig = {
	collections: AppCollections & Record<string, any>;
	globals: AppGlobals & Record<string, any>;
	routes: AppRoutes;
	auth: typeof _authConfig;
};

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

export const app = await createApp(
	({
		modules: _modules,
		collections: {
			inventoryMovements: _coll_inventoryMovements,
			machines: _coll_machines,
			materials: _coll_materials,
			operations: _coll_operations,
			productionOrders: _coll_productionOrders,
			toyMaterials: _coll_toyMaterials,
			toys: _coll_toys,
		},
		globals: {
			siteSettings: _glob_siteSettings,
		},
		jobs: {
			recalculateMaterialPlan: _job_recalculateMaterialPlan,
		},
		routes: {
			"rpc/planning/capacitySummary": _route_rpc_planning_capacitySummary,
			"rpc/planning/receiveMaterials": _route_rpc_planning_receiveMaterials,
			"rpc/planning/startProduction": _route_rpc_planning_startProduction,
		},
		services: {
			capacityPlanner: _svc_capacityPlanner,
		},
		emailTemplates: {
			productionScheduled: _email_productionScheduled,
		},
		seeds: [_seed_demo_seed],
		workflows: {
			[_wf_nightlyCapacityReview.name]: _wf_nightlyCapacityReview,
			[_wf_productionOrderPlan.name]: _wf_productionOrderPlan,
		},
		config: {
			auth: _authConfig as any,
			admin: _adminConfig as any,
			openapi: _openapi as any,
		},
	}) satisfies AppDefinition,
	_runtime,
) as _AppQuestpie;

/** Fully typed QUESTPIE app instance. */
export type App = typeof app;

// ── createContext — typed context for scripts ──────────────
/**
 * Create a typed AppContext for use in scripts, tests, or standalone code.
 * Resolves all services and provides flat access to infrastructure.
 *
 * @example
 * ```ts
 * import { createContext } from "#questpie";
 *
 * const ctx = await createContext();
 * const posts = await ctx.collections.posts.find({});
 * ```
 */
export const createContext = createContextFactory(app);

// Factories: import { collection, global, ... } from '#questpie/factories';
