/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Module entity-name key sets (distributive `keyof`) ─────
type _ModuleCollectionsKeyNames = (typeof _modules)[number] extends infer M ? M extends { collections: infer C } ? keyof C & string : never : never;
type _ModuleChannelsKeyNames = (typeof _modules)[number] extends infer M ? M extends { channels: infer C } ? keyof C & string : never : never;
type _ModuleGlobalsKeyNames = (typeof _modules)[number] extends infer M ? M extends { globals: infer C } ? keyof C & string : never : never;
type _ModuleJobsKeyNames = (typeof _modules)[number] extends infer M ? M extends { jobs: infer C } ? keyof C & string : never : never;
type _ModuleRoutesKeyNames = (typeof _modules)[number] extends infer M ? M extends { routes: infer C } ? keyof C & string : never : never;
type _ModuleServicesKeyNames = (typeof _modules)[number] extends infer M ? M extends { services: infer C } ? keyof C & string : never : never;
type _ModuleFieldTypesKeyNames = (typeof _modules)[number] extends infer M ? M extends { fieldTypes: infer C } ? keyof C & string : never : never;
type _ModuleViewsKeyNames = (typeof _modules)[number] extends infer M ? M extends { views: infer C } ? keyof C & string : never : never;
type _ModuleComponentsKeyNames = (typeof _modules)[number] extends infer M ? M extends { components: infer C } ? keyof C & string : never : never;
type _ModuleBlocksKeyNames = (typeof _modules)[number] extends infer M ? M extends { blocks: infer C } ? keyof C & string : never : never;
type _ModuleWorkflowsKeyNames = (typeof _modules)[number] extends infer M ? M extends { workflows: infer C } ? keyof C & string : never : never;

declare global {
	namespace Questpie {
		interface CollectionKeys extends Record<_ModuleCollectionsKeyNames, unknown> {}
		interface ChannelKeys extends Record<_ModuleChannelsKeyNames, unknown> {}
		interface GlobalKeys extends Record<_ModuleGlobalsKeyNames, unknown> {}
		interface JobKeys extends Record<_ModuleJobsKeyNames, unknown> {}
		interface RouteKeys extends Record<_ModuleRoutesKeyNames, unknown> {}
		interface ServiceKeys extends Record<_ModuleServicesKeyNames, unknown> {}
		interface FieldTypeKeys extends Record<_ModuleFieldTypesKeyNames, unknown> {}
		interface ViewKeys extends Record<_ModuleViewsKeyNames, unknown> {}
		interface ComponentKeys extends Record<_ModuleComponentsKeyNames, unknown> {}
		interface BlockKeys extends Record<_ModuleBlocksKeyNames, unknown> {}
		interface WorkflowKeys extends Record<_ModuleWorkflowsKeyNames, unknown> {}
	}
}
