/**
 * Admin Client Config
 *
 * Auto-generated by questpie codegen — do not edit.
 *
 * Pass this directly to <AdminLayoutProvider admin={admin} />
 */

import _modules from "../modules";
type _AdminModuleMergeAcc = Record<string, unknown>;
const _mergedModules = (Array.isArray(_modules)
	? _modules.reduce<_AdminModuleMergeAcc>((acc, mod) => {
		for (const [k, v] of Object.entries(mod)) acc[k] = typeof v === "object" && v !== null && !Array.isArray(v) ? { ...(typeof acc[k] === "object" && acc[k] !== null && !Array.isArray(acc[k]) ? acc[k] as Record<string, unknown> : {}), ...(v as Record<string, unknown>) } : v;
		return acc;
	}, {}) : _modules) as _AdminModuleMergeAcc;
import _view_fileDetail from "../views/file-detail";
import _view_filesView from "../views/files-view";
import _view_taskDetail from "../views/task-detail";
import _comp_autopilotWorkRail from "../components/autopilot-work-rail";
import { AutopilotWorkRailCore as _comp_autopilotWorkRailCore } from "../components/autopilot-work-rail-core";
import _comp_fileRenderBlob from "../components/file-render-blob";
import _comp_fileRenderDocument from "../components/file-render-document";
import _comp_fileRenderHtml from "../components/file-render-html";
import _comp_fileRenderImage from "../components/file-render-image";
import _comp_fileRenderMarkdown from "../components/file-render-markdown";
import _comp_fileRenderMiniapp from "../components/file-render-miniapp";
import _comp_fileRenderOffice from "../components/file-render-office";
import _comp_fileRenderPdf from "../components/file-render-pdf";
import _comp_fileRenderVideo from "../components/file-render-video";
import _comp_filesViewComponent from "../components/files-view-component";
import _comp_knowledgeDetailComponent from "../components/knowledge-detail-component";
import _comp_knowledgeHost from "../components/knowledge-host";
import { messageText as _comp_messageParts } from "../components/message-parts";
import _comp_taskDetailComponent from "../components/task-detail-component";
import _pg_autopilotChat from "../pages/autopilot-chat";
import _pg_knowledgeHost from "../pages/knowledge-host";
import _pg_projectInspection from "../pages/project-inspection";
import _pg_runDetail from "../pages/run-detail";

const admin = {
	blocks: { ...(_mergedModules["blocks"] as Record<string, unknown>) },
	views: { ...(_mergedModules["views"] as Record<string, unknown>), [_view_fileDetail.name]: _view_fileDetail, [_view_filesView.name]: _view_filesView, [_view_taskDetail.name]: _view_taskDetail },
	components: { ...(_mergedModules["components"] as Record<string, unknown>), autopilotWorkRail: _comp_autopilotWorkRail, autopilotWorkRailCore: _comp_autopilotWorkRailCore, fileRenderBlob: _comp_fileRenderBlob, fileRenderDocument: _comp_fileRenderDocument, fileRenderHtml: _comp_fileRenderHtml, fileRenderImage: _comp_fileRenderImage, fileRenderMarkdown: _comp_fileRenderMarkdown, fileRenderMiniapp: _comp_fileRenderMiniapp, fileRenderOffice: _comp_fileRenderOffice, fileRenderPdf: _comp_fileRenderPdf, fileRenderVideo: _comp_fileRenderVideo, filesViewComponent: _comp_filesViewComponent, knowledgeDetailComponent: _comp_knowledgeDetailComponent, knowledgeHost: _comp_knowledgeHost, messageParts: _comp_messageParts, taskDetailComponent: _comp_taskDetailComponent },
	fields: { ...(_mergedModules["fields"] as Record<string, unknown>) },
	pages: { ...(_mergedModules["pages"] as Record<string, unknown>), autopilotChat: _pg_autopilotChat, knowledgeHost: _pg_knowledgeHost, projectInspection: _pg_projectInspection, runDetail: _pg_runDetail },
	widgets: { ...(_mergedModules["widgets"] as Record<string, unknown>) },
};

export default admin;
