/**
 * Admin Client Config
 *
 * Auto-generated by questpie codegen — do not edit.
 *
 * Pass this directly to <AdminLayoutProvider admin={admin} />
 */

import _modules from "../modules";
const _mergedModules = Array.isArray(_modules)
	? _modules.reduce((acc: any, m: any) => {
		for (const [k, v] of Object.entries(m)) acc[k] = typeof v === "object" && v !== null && !Array.isArray(v) ? { ...acc[k], ...v } : v;
		return acc;
	}, {} as any) : _modules;
import _view_filesView from "../views/files-view";
import _view_knowledgeDetail from "../views/knowledge-detail";
import _view_taskDetail from "../views/task-detail";
import _comp_autopilotWorkRail from "../components/autopilot-work-rail";
import _comp_filesViewComponent from "../components/files-view-component";
import _comp_taskDetailComponent from "../components/task-detail-component";
import _pg_projectInspection from "../pages/project-inspection";

const admin = {
	blocks: { ..._mergedModules.blocks },
	views: { ..._mergedModules.views, [_view_filesView.name]: _view_filesView, [_view_knowledgeDetail.name]: _view_knowledgeDetail, [_view_taskDetail.name]: _view_taskDetail },
	components: { ..._mergedModules.components, "autopilotWorkRail": _comp_autopilotWorkRail, "filesViewComponent": _comp_filesViewComponent, "taskDetailComponent": _comp_taskDetailComponent },
	fields: { ..._mergedModules.fields },
	pages: { ..._mergedModules.pages, "projectInspection": _pg_projectInspection },
	widgets: { ..._mergedModules.widgets },
};

export default admin;
