/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { auditLogCollection as _coll_admin_audit_log } from "../collections/audit-log";

// ── Jobs ────────────────────────────────────────────
import { auditCleanupJob as _job_auditCleanup } from "../jobs/audit-cleanup";

// ── Singles ────────────────────────────────────────────────
import _adminConfig from "../config/admin";
import _appConfig from "../config/app";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export type AuditCollections = {
	admin_audit_log: typeof _coll_admin_audit_log;
};

export type AuditChannels = Record<never, never>;

export type AuditGlobals = Record<never, never>;

export type AuditJobs = {
	auditCleanup: Omit<typeof _job_auditCleanup, "handler"> & { handler: (args: unknown) => Promise<unknown> };
};

export type AuditRoutes = Record<never, never>;

export type AuditFieldTypes = Record<never, never>;

export type AuditViews = Record<never, never>;

export type AuditComponents = Record<never, never>;

export type AuditBlocks = Record<never, never>;

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type AuditModule = {
	name: "questpie-audit";
	collections: AuditCollections;
	jobs: AuditJobs;
	channels: AuditChannels;
	globals: AuditGlobals;
	routes: AuditRoutes;
	fieldTypes: AuditFieldTypes;
	views: AuditViews;
	components: AuditComponents;
	blocks: AuditBlocks;
	messages: Record<never, never>;
	services: Record<never, never>;
	emails: Record<never, never>;
	migrations: readonly unknown[];
	seeds: readonly unknown[];
	config: {
		admin: typeof _adminConfig;
		app: typeof _appConfig;
	};
};

const _module: AuditModule = {
	name: "questpie-audit" as const,
	collections: {
		admin_audit_log: _coll_admin_audit_log,
	} as AuditCollections,
	jobs: {
		auditCleanup: _job_auditCleanup,
	} as AuditJobs,
	channels: {},
	globals: {},
	routes: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	views: {},
	components: {},
	blocks: {},
	config: {
		admin: _adminConfig,
		app: _appConfig,
	},
};

export default _module;
