/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { auditLogCollection as _coll_adminAuditLog } from "../collections/audit-log.collection.js";
import _dashboard from "../dashboard.js";

// ── Singles ────────────────────────────────────────────────
import _hooks from "../hooks.js";
// ── Jobs ───────────────────────────────────────────────────
import { auditCleanupJob as _job_auditCleanup } from "../jobs/audit-cleanup.job.js";
import _sidebar from "../sidebar.js";

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-audit" as const,
	collections: {
		adminAuditLog: _coll_adminAuditLog,
	},
	jobs: {
		auditCleanup: _job_auditCleanup,
	},
	hooks: _hooks,
	sidebar: [_sidebar],
	dashboard: [_dashboard],
};

export type AuditModule = typeof _module;
export default _module;
