/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Jobs ────────────────────────────────────────────
import _job_indexRecords from "../jobs/index-records";
import _job_scheduledTransition from "../jobs/scheduled-transition";

// ── Routes ────────────────────────────────────────────
import _route_collection from "../routes/[collection]";
import _route_collection_PATCH from "../routes/[collection].patch";
import _route_collection_POST from "../routes/[collection].post";
import _route_collection_id from "../routes/[collection]/[id]";
import _route_collection_id_DELETE from "../routes/[collection]/[id].delete";
import _route_collection_id_PATCH from "../routes/[collection]/[id].patch";
import _route_collection_id_audit from "../routes/[collection]/[id]/audit";
import _route_collection_id_restore from "../routes/[collection]/[id]/restore";
import _route_collection_id_revert from "../routes/[collection]/[id]/revert";
import _route_collection_id_transition from "../routes/[collection]/[id]/transition";
import _route_collection_id_versions from "../routes/[collection]/[id]/versions";
import _route_collection_count from "../routes/[collection]/count";
import _route_collection_deleteMany from "../routes/[collection]/delete-many";
import _route_collection_files_spread_key from "../routes/[collection]/files/[...key]";
import _route_collection_meta from "../routes/[collection]/meta";
import _route_collection_schema from "../routes/[collection]/schema";
import _route_collection_updateBatch from "../routes/[collection]/update-batch";
import _route_collection_upload from "../routes/[collection]/upload";
import _route_auth_spread_path from "../routes/auth/[...path]";
import _route_globals_name from "../routes/globals/[name]";
import _route_globals_name_PATCH from "../routes/globals/[name].patch";
import _route_globals_name_audit from "../routes/globals/[name]/audit";
import _route_globals_name_meta from "../routes/globals/[name]/meta";
import _route_globals_name_revert from "../routes/globals/[name]/revert";
import _route_globals_name_schema from "../routes/globals/[name]/schema";
import _route_globals_name_transition from "../routes/globals/[name]/transition";
import _route_globals_name_versions from "../routes/globals/[name]/versions";
import _route_health from "../routes/health";
import _route_realtime from "../routes/realtime";
import _route_search from "../routes/search";
import _route_search_reindex_collection from "../routes/search/reindex/[collection]";

// ── Services ────────────────────────────────────────────
import _svc_auth from "../services/auth";
import _svc_collectionsApi from "../services/collections-api";
import _svc_db from "../services/db";
import _svc_email from "../services/email";
import _svc_executor from "../services/executor";
import _svc_globalsApi from "../services/globals-api";
import _svc_i18n from "../services/i18n";
import _svc_kv from "../services/kv";
import _svc_logger from "../services/logger";
import _svc_queue from "../services/queue";
import _svc_realtime from "../services/realtime";
import _svc_search from "../services/search";
import _svc_storage from "../services/storage";

// ── FieldTypes ────────────────────────────────────────────
import { booleanFieldType as _ftype_boolean } from "../fields/boolean";
import { fromFieldType as _ftype_custom } from "../fields/from";
import { dateFieldType as _ftype_date } from "../fields/date";
import { datetimeFieldType as _ftype_datetime } from "../fields/datetime";
import { emailFieldType as _ftype_email } from "../fields/email";
import { jsonFieldType as _ftype_json } from "../fields/json";
import { numberFieldType as _ftype_number } from "../fields/number";
import { objectFieldType as _ftype_object } from "../fields/object";
import { relationFieldType as _ftype_relation } from "../fields/relation";
import { selectFieldType as _ftype_select } from "../fields/select";
import { textFieldType as _ftype_text } from "../fields/text";
import { textareaFieldType as _ftype_textarea } from "../fields/textarea";
import { timeFieldType as _ftype_time } from "../fields/time";
import { uploadFieldType as _ftype_upload } from "../fields/upload";
import { urlFieldType as _ftype_url } from "../fields/url";

// ── Singles ────────────────────────────────────────────────
import _appConfig from "../config/app";

// ── Entity key registry (names only — acyclic by construction) ─────
declare global {
	namespace Questpie {
		interface JobKeys { indexRecords: unknown; scheduledTransition: unknown }
	}
}

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { RouteDefinition, RouteParamsFromKey } from "questpie/types";

export interface CoreJobs {
	indexRecords: Omit<typeof _job_indexRecords, "handler"> & { handler: (args: unknown) => Promise<unknown> };
	scheduledTransition: Omit<typeof _job_scheduledTransition, "handler"> & { handler: (args: unknown) => Promise<unknown> };
}

export interface CoreRoutes {
	"[collection]": typeof _route_collection extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]">> : typeof _route_collection;
	"[collection]:PATCH": typeof _route_collection_PATCH extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]:PATCH">> : typeof _route_collection_PATCH;
	"[collection]:POST": typeof _route_collection_POST extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]:POST">> : typeof _route_collection_POST;
	"[collection]/[id]": typeof _route_collection_id extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/[id]">> : typeof _route_collection_id;
	"[collection]/[id]:DELETE": typeof _route_collection_id_DELETE extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/[id]:DELETE">> : typeof _route_collection_id_DELETE;
	"[collection]/[id]:PATCH": typeof _route_collection_id_PATCH extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/[id]:PATCH">> : typeof _route_collection_id_PATCH;
	"[collection]/[id]/audit": typeof _route_collection_id_audit extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/[id]/audit">> : typeof _route_collection_id_audit;
	"[collection]/[id]/restore": typeof _route_collection_id_restore extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/[id]/restore">> : typeof _route_collection_id_restore;
	"[collection]/[id]/revert": typeof _route_collection_id_revert extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/[id]/revert">> : typeof _route_collection_id_revert;
	"[collection]/[id]/transition": typeof _route_collection_id_transition extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/[id]/transition">> : typeof _route_collection_id_transition;
	"[collection]/[id]/versions": typeof _route_collection_id_versions extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/[id]/versions">> : typeof _route_collection_id_versions;
	"[collection]/count": typeof _route_collection_count extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/count">> : typeof _route_collection_count;
	"[collection]/deleteMany": typeof _route_collection_deleteMany extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/deleteMany">> : typeof _route_collection_deleteMany;
	"[collection]/files/[...key]": typeof _route_collection_files_spread_key extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/files/[...key]">> : typeof _route_collection_files_spread_key;
	"[collection]/meta": typeof _route_collection_meta extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/meta">> : typeof _route_collection_meta;
	"[collection]/schema": typeof _route_collection_schema extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/schema">> : typeof _route_collection_schema;
	"[collection]/updateBatch": typeof _route_collection_updateBatch extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/updateBatch">> : typeof _route_collection_updateBatch;
	"[collection]/upload": typeof _route_collection_upload extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"[collection]/upload">> : typeof _route_collection_upload;
	"auth/[...path]": typeof _route_auth_spread_path extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"auth/[...path]">> : typeof _route_auth_spread_path;
	"globals/[name]": typeof _route_globals_name extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"globals/[name]">> : typeof _route_globals_name;
	"globals/[name]:PATCH": typeof _route_globals_name_PATCH extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"globals/[name]:PATCH">> : typeof _route_globals_name_PATCH;
	"globals/[name]/audit": typeof _route_globals_name_audit extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"globals/[name]/audit">> : typeof _route_globals_name_audit;
	"globals/[name]/meta": typeof _route_globals_name_meta extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"globals/[name]/meta">> : typeof _route_globals_name_meta;
	"globals/[name]/revert": typeof _route_globals_name_revert extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"globals/[name]/revert">> : typeof _route_globals_name_revert;
	"globals/[name]/schema": typeof _route_globals_name_schema extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"globals/[name]/schema">> : typeof _route_globals_name_schema;
	"globals/[name]/transition": typeof _route_globals_name_transition extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"globals/[name]/transition">> : typeof _route_globals_name_transition;
	"globals/[name]/versions": typeof _route_globals_name_versions extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"globals/[name]/versions">> : typeof _route_globals_name_versions;
	health: typeof _route_health extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"health">> : typeof _route_health;
	realtime: typeof _route_realtime extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"realtime">> : typeof _route_realtime;
	search: typeof _route_search extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"search">> : typeof _route_search;
	"search/reindex/[collection]": typeof _route_search_reindex_collection extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"search/reindex/[collection]">> : typeof _route_search_reindex_collection;
}

export interface CoreServices {
	auth: typeof _svc_auth;
	collectionsApi: typeof _svc_collectionsApi;
	db: typeof _svc_db;
	email: typeof _svc_email;
	executor: typeof _svc_executor;
	globalsApi: typeof _svc_globalsApi;
	i18n: typeof _svc_i18n;
	kv: typeof _svc_kv;
	logger: typeof _svc_logger;
	queue: typeof _svc_queue;
	realtime: typeof _svc_realtime;
	search: typeof _svc_search;
	storage: typeof _svc_storage;
}

export interface CoreFieldTypes {
	boolean: typeof _ftype_boolean;
	custom: typeof _ftype_custom;
	date: typeof _ftype_date;
	datetime: typeof _ftype_datetime;
	email: typeof _ftype_email;
	json: typeof _ftype_json;
	number: typeof _ftype_number;
	object: typeof _ftype_object;
	relation: typeof _ftype_relation;
	select: typeof _ftype_select;
	text: typeof _ftype_text;
	textarea: typeof _ftype_textarea;
	time: typeof _ftype_time;
	upload: typeof _ftype_upload;
	url: typeof _ftype_url;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type CoreModule = {
	name: "questpie-core";
	jobs: CoreJobs;
	routes: CoreRoutes;
	services: CoreServices;
	fieldTypes: CoreFieldTypes;
	collections: {};
	globals: {};
	messages: {};
	emails: {};
	migrations: readonly unknown[];
	seeds: readonly unknown[];
	config: {
		app: typeof _appConfig;
	};
};

const _module: CoreModule = {
	name: "questpie-core" as const,
	jobs: {
		indexRecords: _job_indexRecords,
		scheduledTransition: _job_scheduledTransition,
	} as CoreJobs,
	routes: {
		"[collection]": _route_collection,
		"[collection]:PATCH": _route_collection_PATCH,
		"[collection]:POST": _route_collection_POST,
		"[collection]/[id]": _route_collection_id,
		"[collection]/[id]:DELETE": _route_collection_id_DELETE,
		"[collection]/[id]:PATCH": _route_collection_id_PATCH,
		"[collection]/[id]/audit": _route_collection_id_audit,
		"[collection]/[id]/restore": _route_collection_id_restore,
		"[collection]/[id]/revert": _route_collection_id_revert,
		"[collection]/[id]/transition": _route_collection_id_transition,
		"[collection]/[id]/versions": _route_collection_id_versions,
		"[collection]/count": _route_collection_count,
		"[collection]/deleteMany": _route_collection_deleteMany,
		"[collection]/files/[...key]": _route_collection_files_spread_key,
		"[collection]/meta": _route_collection_meta,
		"[collection]/schema": _route_collection_schema,
		"[collection]/updateBatch": _route_collection_updateBatch,
		"[collection]/upload": _route_collection_upload,
		"auth/[...path]": _route_auth_spread_path,
		"globals/[name]": _route_globals_name,
		"globals/[name]:PATCH": _route_globals_name_PATCH,
		"globals/[name]/audit": _route_globals_name_audit,
		"globals/[name]/meta": _route_globals_name_meta,
		"globals/[name]/revert": _route_globals_name_revert,
		"globals/[name]/schema": _route_globals_name_schema,
		"globals/[name]/transition": _route_globals_name_transition,
		"globals/[name]/versions": _route_globals_name_versions,
		health: _route_health,
		realtime: _route_realtime,
		search: _route_search,
		"search/reindex/[collection]": _route_search_reindex_collection,
	} as CoreRoutes,
	services: {
		auth: _svc_auth,
		collectionsApi: _svc_collectionsApi,
		db: _svc_db,
		email: _svc_email,
		executor: _svc_executor,
		globalsApi: _svc_globalsApi,
		i18n: _svc_i18n,
		kv: _svc_kv,
		logger: _svc_logger,
		queue: _svc_queue,
		realtime: _svc_realtime,
		search: _svc_search,
		storage: _svc_storage,
	} as CoreServices,
	fieldTypes: {
		boolean: _ftype_boolean,
		custom: _ftype_custom,
		date: _ftype_date,
		datetime: _ftype_datetime,
		email: _ftype_email,
		json: _ftype_json,
		number: _ftype_number,
		object: _ftype_object,
		relation: _ftype_relation,
		select: _ftype_select,
		text: _ftype_text,
		textarea: _ftype_textarea,
		time: _ftype_time,
		upload: _ftype_upload,
		url: _ftype_url,
	} as CoreFieldTypes,
	collections: {},
	globals: {},
	messages: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	config: {
		app: _appConfig,
	},
};

export default _module;
