/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Jobs ────────────────────────────────────────────
import _job_indexRecords from "../jobs/index-records";
import _job_scheduledTransition from "../jobs/scheduled-transition";

// ── Routes ────────────────────────────────────────────
import _route_health from "../routes/health";
import _route_search from "../routes/search";
import _route_search_reindex__collection_ from "../routes/search/reindex/[collection]";

// ── Services ────────────────────────────────────────────
import _svc_auth from "../services/auth";
import _svc_collectionsApi from "../services/collections-api";
import _svc_db from "../services/db";
import _svc_email from "../services/email";
import _svc_globalsApi from "../services/globals-api";
import _svc_i18n from "../services/i18n";
import _svc_kv from "../services/kv";
import _svc_locale from "../services/locale";
import _svc_logger from "../services/logger";
import _svc_queue from "../services/queue";
import _svc_realtime from "../services/realtime";
import _svc_search from "../services/search";
import _svc_session from "../services/session";
import _svc_storage from "../services/storage";

// ── Singles ────────────────────────────────────────────────
import _appConfig from "../config/app";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface CoreJobs {
	indexRecords: typeof _job_indexRecords;
	scheduledTransition: typeof _job_scheduledTransition;
}

export interface CoreRoutes {
	health: typeof _route_health;
	search: typeof _route_search;
	"search/reindex/[collection]": typeof _route_search_reindex__collection_;
}

export interface CoreServices {
	auth: typeof _svc_auth;
	collectionsApi: typeof _svc_collectionsApi;
	db: typeof _svc_db;
	email: typeof _svc_email;
	globalsApi: typeof _svc_globalsApi;
	i18n: typeof _svc_i18n;
	kv: typeof _svc_kv;
	locale: typeof _svc_locale;
	logger: typeof _svc_logger;
	queue: typeof _svc_queue;
	realtime: typeof _svc_realtime;
	search: typeof _svc_search;
	session: typeof _svc_session;
	storage: typeof _svc_storage;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-core" as const,
	jobs: {
		indexRecords: _job_indexRecords,
		scheduledTransition: _job_scheduledTransition,
	} as CoreJobs,
	routes: {
		health: _route_health,
		search: _route_search,
		"search/reindex/[collection]": _route_search_reindex__collection_,
	} as CoreRoutes,
	services: {
		auth: _svc_auth,
		collectionsApi: _svc_collectionsApi,
		db: _svc_db,
		email: _svc_email,
		globalsApi: _svc_globalsApi,
		i18n: _svc_i18n,
		kv: _svc_kv,
		locale: _svc_locale,
		logger: _svc_logger,
		queue: _svc_queue,
		realtime: _svc_realtime,
		search: _svc_search,
		session: _svc_session,
		storage: _svc_storage,
	} as CoreServices,
	collections: {},
	globals: {},
	messages: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	config: {
		app: _appConfig,
	},
};

export type CoreModule = typeof _module;
export default _module;
