import { mergeAdminConfig } from "#questpie/server/config/admin-sidebar-merge.js";
import {
	resolveAppUrl,
	resolveDbConfig,
	resolveSecret,
	resolveStorageConfig,
} from "#questpie/server/config/cloud-env.js";
import type { GlobalHooksState } from "#questpie/server/config/global-hooks-types.js";
import type {
	AppModuleInput,
	AppDefinition,
	ModuleDefinition,
	RealtimeConfigInput,
	ResolvedRuntimeConfig,
	RuntimeConfig,
	RuntimeConfigInput,
} from "#questpie/server/config/module-types.js";
import { Questpie } from "#questpie/server/config/questpie.js";
import type {
	QuestpieConfig,
	StorageConfig,
} from "#questpie/server/config/types.js";
import {
	mergeMessagesIntoConfig,
	mergeTranslationsConfig,
} from "#questpie/server/i18n/translator.js";
import coreModule from "#questpie/server/modules/core/.generated/module.js";
import { mergeAuthOptions } from "#questpie/server/modules/core/integrated/auth/merge.js";
import { createCrdtRuntimeManifests } from "#questpie/server/modules/core/integrated/crdt/manifest-runtime.js";

type RuntimeConfigStorageInputGuard<TInput> = TInput extends {
	storage?: infer TStorage;
}
	? TStorage extends StorageConfig | undefined
		? unknown
		: { storage?: never }
	: unknown;

function resolveRealtimeConfig(
	realtime: RealtimeConfigInput | undefined,
): RuntimeConfig["realtime"] {
	if (realtime === true) return {};
	return realtime;
}

// ============================================================================
// module() — identity function for type inference
// ============================================================================

/**
 * Define a module as a plain data object.
 * Modules contribute collections, globals, jobs, routes, fields,
 * auth config, migrations, messages, etc.
 *
 * @example
 * ```ts
 * import { module, collection } from "questpie";
 *
 * export const myModule = module({
 *   name: "my-module",
 *   collections: { posts: postCollection },
 *   jobs: { sendNewsletter },
 *   messages: { en: { "my.key": "Hello" } },
 * });
 * ```
 */
// `const` is load-bearing. Without it the `modules: [dep]` literal widens to an
// array, and the folds in codegen-type-utils.ts only walk tuples, so every
// dependency's collections, routes and jobs vanish from the consuming app's
// types with no error. Codegen dodges this by writing `as const` in modules.ts.
// Hand-written modules had nothing. See test/types/module-dependency-inference.test-d.ts.
export function module<const T extends ModuleDefinition>(definition: T): T {
	return definition;
}

// ============================================================================
// runtimeConfig() — cloud-aware runtime config with env auto-detection
// ============================================================================

/**
 * Define the runtime configuration for `questpie.config.ts`.
 * Contains only runtime infrastructure (db, adapters, secret) and plugin registrations.
 * No entity definitions — those come from the definition object generated by codegen.
 *
 * **Cloud-aware**: `app` and `db` are optional. When omitted they are resolved
 * automatically from environment variables:
 *
 * | Field     | QUESTPIE Cloud env        | Standard fallback       | Default              |
 * |-----------|---------------------------|-------------------------|----------------------|
 * | `app.url` | `QUESTPIE_APP_URL`        | `APP_URL`               | `http://localhost:3000` |
 * | `db.url`  | `QUESTPIE_DB`             | `DATABASE_URL`          | *(throws)*           |
 * | `secret`  | `QUESTPIE_SECRET`         | `BETTER_AUTH_SECRET`    | `undefined`          |
 * | `storage` | `QUESTPIE_STORAGE_*`      | —                       | local `./uploads`    |
 *
 * When `QUESTPIE_STORAGE_ENDPOINT`, `QUESTPIE_STORAGE_BUCKET`,
 * `QUESTPIE_STORAGE_ACCESS_KEY`, and `QUESTPIE_STORAGE_SECRET_KEY` are all set,
 * an S3-compatible Files SDK storage adapter is auto-configured (requires `@aws-sdk/client-s3`).
 *
 * @example Zero-config on QUESTPIE Cloud:
 * ```ts
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 * });
 * ```
 *
 * @example Explicit overrides:
 * ```ts
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 *   app: { url: process.env.APP_URL! },
 *   db: { url: process.env.DATABASE_URL! },
 *   secret: process.env.SECRET,
 *   email: { adapter: new ConsoleAdapter() },
 * });
 * ```
 *
 */
export function runtimeConfig<const TInput extends RuntimeConfigInput>(
	input: TInput & RuntimeConfigStorageInputGuard<TInput>,
): ResolvedRuntimeConfig<TInput> {
	const resolved = {
		...input,
		app: { url: resolveAppUrl(input.app?.url) },
		db: resolveDbConfig(input.db),
		secret: resolveSecret(input.secret as string | undefined),
		storage: resolveStorageConfig(input.storage),
		realtime: resolveRealtimeConfig(input.realtime),
	} as unknown as ResolvedRuntimeConfig<TInput>;

	return resolved;
}

// ============================================================================
// Module resolution — depth-first, left-to-right
// ============================================================================

/** Walk the module tree depth-first, children before their parent. */
function flattenModules(
	modules: readonly AppModuleInput[],
): ModuleDefinition[] {
	const flat: ModuleDefinition[] = [];
	for (const mod of modules) {
		if (mod.modules && mod.modules.length > 0) {
			flat.push(...flattenModules(mod.modules));
		}
		flat.push(mod as ModuleDefinition);
	}
	return flat;
}

/**
 * Flatten the module tree into merge order: depth-first, left to right,
 * every dependency ahead of the module that depends on it.
 *
 * A module reached more than once — the diamond, where two modules share a
 * dependency, or an app lists a module it already gets transitively — keeps its
 * FIRST position. That is the only position where it still precedes everything
 * that depends on it. Keeping the last one instead put the dependency after its
 * dependent and quietly flipped which one's collections and config won.
 *
 * Two DIFFERENT modules under one name is a different thing and it throws. Name
 * is the merge key, so one of the two would vanish with nothing to notice it.
 */
function resolveModules(
	modules: readonly AppModuleInput[],
): ModuleDefinition[] {
	const flat = flattenModules(modules);
	const firstByName = new Map<
		string,
		{ index: number; mod: ModuleDefinition }
	>();
	const resolved: ModuleDefinition[] = [];

	for (let i = 0; i < flat.length; i++) {
		const mod = flat[i];
		const first = firstByName.get(mod.name);

		if (!first) {
			firstByName.set(mod.name, { index: i, mod });
			resolved.push(mod);
			continue;
		}

		// Same module reached twice. Already in merge order at first.index.
		if (first.mod === mod) continue;

		throw new Error(
			`[QUESTPIE] Two different modules are both named "${mod.name}", ` +
				`at positions ${first.index} and ${i} of the resolved module list. ` +
				`Module name is the merge key, so one would silently replace the other. ` +
				`Rename one of them.\n` +
				`Resolved order: ${flat.map((m, n) => `${n}:${m.name}`).join(", ")}`,
		);
	}

	return resolved;
}

// ============================================================================
// Merge infrastructure
// ============================================================================

/**
 * Merge function: `(existing, incoming) → merged`.
 *
 * The strategy tables below are core-owned and module-private. A plugin cannot
 * register one for its own key; an unlisted key falls to the duck-typed generic
 * merge in {@link mergeGenericKey}. These helpers are exported because the core
 * tables read better naming them, and because a plugin folding its own state
 * can reuse them:
 * - {@link mergeRecord} — spread-merge two objects
 * - {@link mergeConcat} — concatenate two arrays
 * - {@link lastWins} — incoming replaces existing
 */
export type MergeFn = (existing: any, incoming: any) => any;

/** Spread-merge two records: `{ ...a, ...b }`. */
export const mergeRecord: MergeFn = (a, b) => ({
	...(a || {}),
	...(b || {}),
});

/** Concatenate two arrays: `[...a, ...b]`. */
export const mergeConcat: MergeFn = (a, b) => [...(a || []), ...(b || [])];

/** Merge two objects by concatenating any array-valued properties and merging the rest. */
export const mergeDeepConcat: MergeFn = (a, b) => {
	const result = { ...(a || {}) };
	for (const [key, value] of Object.entries(b || {})) {
		if (Array.isArray(result[key]) && Array.isArray(value)) {
			result[key] = [...result[key], ...value];
		} else if (
			result[key] !== undefined &&
			typeof result[key] === "object" &&
			typeof value === "object" &&
			!Array.isArray(value)
		) {
			result[key] = { ...result[key], ...value };
		} else {
			result[key] = value;
		}
	}
	return result;
};

/** Last value wins (incoming replaces existing). */
export const lastWins: MergeFn = (_a, b) => b;

/** Deep-merge message dictionaries by locale. */
function mergeMessages(
	a: Record<string, Record<string, string>>,
	b?: Record<string, Record<string, string>>,
): Record<string, Record<string, string>> {
	if (!b) return a;
	const result: Record<string, Record<string, string>> = { ...a };
	for (const [locale, msgs] of Object.entries(b)) {
		result[locale] = { ...(result[locale] || {}), ...msgs };
	}
	return result;
}

/** Normalize a hooks value into an array (handles single entry or already-array). */
function normalizeHookEntries<T>(value: T | T[] | undefined): T[] {
	if (!value) return [];
	if (Array.isArray(value)) return value;
	return [value];
}

/** Concatenate global hook arrays (normalizes single-entry inputs). */
function mergeGlobalHooks(
	a: GlobalHooksState | undefined,
	b: GlobalHooksState | undefined,
): GlobalHooksState | undefined {
	if (!a && !b) return undefined;
	if (!a) return b;
	if (!b) return a;
	return {
		collections: [
			...normalizeHookEntries(a.collections),
			...normalizeHookEntries(b.collections),
		],
		globals: [
			...normalizeHookEntries(a.globals),
			...normalizeHookEntries(b.globals),
		],
	};
}

// ============================================================================
// Config bucket merge
// ============================================================================

/**
 * Per-config-key sub-property merge strategies.
 *
 * A config key listed here merges below the key, one sub-property at a time.
 * Everything else replaces the whole object, so when two modules write the
 * same config key the later one wins outright. `auth` and `admin` are not in
 * this map: {@link mergeConfigKey} branches on them by name.
 *
 * Core-owned, like {@link MERGE_FNS}. A plugin cannot add an entry.
 */
const CONFIG_KEY_MERGE = new Map<string, Map<string, MergeFn>>([
	[
		"app",
		new Map<string, MergeFn>([
			["locale", lastWins],
			["access", lastWins],
			["hooks", (a, b) => mergeGlobalHooks(a, b)],
			["context", lastWins],
		]),
	],
]);

/**
 * Merge a single config key using its declared sub-property merge strategies.
 * Falls back to lastWins for unknown sub-keys.
 */
function mergeConfigKey(configKey: string, existing: any, incoming: any): any {
	// Special case: auth is deep-merged as a whole via mergeAuthOptions
	if (configKey === "auth") {
		return mergeAuthOptions(existing ?? {}, incoming ?? {});
	}

	if (configKey === "admin") {
		return mergeAdminConfig(existing ?? {}, incoming ?? {});
	}

	const subKeyMerges = CONFIG_KEY_MERGE.get(configKey);
	if (!subKeyMerges) {
		// No sub-key merge declared — lastWins on the whole config key
		return incoming;
	}

	// Sub-key-level merge
	const result = { ...(existing || {}) };
	for (const [key, value] of Object.entries(incoming || {})) {
		const subMerge = subKeyMerges.get(key);
		if (subMerge && result[key] !== undefined) {
			result[key] = subMerge(result[key], value);
		} else {
			result[key] = value;
		}
	}
	return result;
}

/**
 * Merge the `config` bucket from two module-like objects.
 * Each key in the config bucket (app, auth, admin, openapi, etc.)
 * is merged independently using its per-key merge strategy.
 */
function mergeConfigBucket(existing: any, incoming: any): any {
	const result = { ...(existing || {}) };
	for (const [key, value] of Object.entries(incoming || {})) {
		if (result[key] !== undefined) {
			result[key] = mergeConfigKey(key, result[key], value);
		} else {
			result[key] = value;
		}
	}
	return result;
}

// ============================================================================
// Module merge functions
// ============================================================================

/**
 * Merge functions for known module keys.
 *
 * Each entry maps a key name to `(existing, incoming) → merged`. A key not in
 * this map uses auto-detect merge (see {@link mergeGenericKey}):
 * - Object + Object → spread merge
 * - Array + Array → concatenate
 * - Otherwise → incoming wins
 *
 * This table is core-owned and module-private. A plugin cannot register a
 * strategy for its own key, so a plugin key is whatever the generic merge makes
 * of it. That is the extension point, and it covers the shapes plugin keys
 * actually take.
 */
const MERGE_FNS = new Map<string, MergeFn>([
	["collections", mergeRecord],
	["channels", mergeRecord],
	["globals", mergeRecord],
	["jobs", mergeRecord],
	["routes", mergeRecord],
	["fields", mergeRecord],
	["services", mergeRecord],
	["messages", (a, b) => mergeMessages(a, b)],
	["migrations", mergeConcat],
	["seeds", mergeConcat],
	["config", mergeConfigBucket],
]);

/** Keys skipped during module merging (structural, not data). */
const STRUCTURAL_KEYS = new Set(["name", "modules", "plugin"]);

/**
 * Known infrastructure keys on RuntimeConfig that should NOT be forwarded
 * to `instance.state`. Only truly unknown extension keys pass through.
 *
 * @see RuntimeConfig in module-types.ts for the full list.
 */
/**
 * Every RuntimeConfig key create-app reads must be listed here.
 *
 * A key that is read but unlisted is classified as an unknown plugin extension
 * and copied into `instance.state`, which breaks twice over: it becomes a ghost
 * duplicate of infrastructure config that nothing reads, and
 * `buildExtensionState` duck-types `.build()` one level into every extension
 * record — so a config member that happens to expose `build()` is silently
 * replaced by its return value. `crdt`, `observability` and `executor` were all
 * missing here while being consumed below; see
 * test/config/runtime-consumed-keys.test.ts.
 */
const RUNTIME_CONSUMED_KEYS = new Set([
	"plugins",
	"app",
	"db",
	"secret",
	"storage",
	"email",
	"queue",
	"search",
	"realtime",
	"logger",
	"kv",
	"translations",
	"autoMigrate",
	"autoSeed",
	"cli",
	"crdt",
	"observability",
	"executor",
]);

/**
 * Keys consumed by QuestpieConfig construction or definition metadata.
 * Everything NOT in this set flows to `instance.state` for plugins to read
 * (e.g., admin reads sidebar, dashboard, branding, blocks, views, components).
 *
 * Fully generic — any plugin's extension keys automatically flow through
 * without being listed anywhere.
 */
const CONFIG_CONSUMED_KEYS = new Set([
	// Module-mergeable keys (from MERGE_FNS → become QuestpieConfig properties)
	...MERGE_FNS.keys(),
	// Derived key (computed from messages + config, not from modules directly)
	"translations",
	// Definition-only keys (used directly in config construction, not merged)
	"emailTemplates",
	// Validated env (from env.ts) — stored as `app.env`, not extension state
	"env",
	// Structural
	"name",
	"modules",
	// Codegen-only (never leaks to instance.state)
	"plugin",
]);

/** Create an empty merged state with correct initial values for known keys. */
function emptyMergedState(): Record<string, any> {
	return {
		collections: {},
		channels: {},
		globals: {},
		jobs: {},
		routes: {},
		fields: {},
		services: {},
		migrations: [],
		seeds: [],
		messages: {},
		config: {},
		translations: undefined,
	};
}

/**
 * Merge a module (or module-like object) into accumulated state.
 *
 * For keys in {@link MERGE_FNS}, the declared merge function is used.
 * For unknown keys (plugin extensions), auto-detect merge is applied.
 * Structural keys ("name", "modules") are skipped.
 */
function mergeModuleIntoState(
	state: Record<string, any>,
	mod: Record<string, any>,
): Record<string, any> {
	const result: Record<string, any> = { ...state };

	for (const key of Object.keys(mod)) {
		if (STRUCTURAL_KEYS.has(key)) continue;

		const incoming = mod[key];
		if (incoming === undefined) continue;

		const mergeFn = MERGE_FNS.get(key);
		if (mergeFn) {
			result[key] = mergeFn(state[key], incoming);
		} else {
			mergeGenericKey(result, key, state[key], incoming);
		}
	}

	return result;
}

/**
 * Auto-detect merge for extension keys (not in {@link MERGE_FNS}):
 * - Array + Array → concatenate
 * - Object + Object → spread merge
 * - Otherwise → incoming wins
 */
function mergeGenericKey(
	result: Record<string, any>,
	key: string,
	existing: any,
	incoming: any,
): void {
	if (Array.isArray(incoming) && Array.isArray(existing)) {
		result[key] = [...existing, ...incoming];
	} else if (Array.isArray(incoming)) {
		result[key] = [...incoming];
	} else if (
		incoming != null &&
		typeof incoming === "object" &&
		!Array.isArray(incoming) &&
		typeof existing === "object" &&
		!Array.isArray(existing) &&
		existing != null
	) {
		result[key] = { ...existing, ...incoming };
	} else {
		result[key] = incoming;
	}
}

// ============================================================================
// Extension state extraction
// ============================================================================

/**
 * Extract extension state — all merged keys NOT consumed by QuestpieConfig.
 * Stored on `instance.state` for plugins to read (e.g., admin reads
 * sidebar, dashboard, branding, blocks, views, components).
 *
 * Fully generic — any plugin's extension keys automatically flow through
 * without being listed anywhere.
 *
 * @param merged - Fully merged state from all modules + user entities
 * @param runtimeExtensions - Unknown keys read off questpie.config.ts. This is
 *   the live path, not a legacy one: the caller passes
 *   `extractRuntimeExtensions(runtime)`, and applying it here is the last step
 *   of the precedence chain, the one that puts runtime config above every
 *   module contribution.
 */
function buildExtensionState(
	merged: Record<string, any>,
	runtimeExtensions?: Record<string, unknown>,
): Record<string, unknown> {
	const extensionState: Record<string, unknown> = {};

	// Extract all non-config keys from merged state
	for (const [key, value] of Object.entries(merged)) {
		if (!CONFIG_CONSUMED_KEYS.has(key) && value !== undefined) {
			extensionState[key] = value;
		}
	}

	// Runtime config outranks every module. Applied last, so this is where that
	// happens.
	if (runtimeExtensions) {
		for (const [key, value] of Object.entries(runtimeExtensions)) {
			if (CONFIG_CONSUMED_KEYS.has(key) || value === undefined) continue;

			const existing = extensionState[key];

			// Array: append the runtime entries after the module ones
			if (Array.isArray(existing) && value != null) {
				extensionState[key] = Array.isArray(value)
					? [...existing, ...value]
					: [...existing, value];
			}
			// Otherwise: runtime replaces
			else {
				extensionState[key] = value;
			}
		}
	}

	// Auto-build any builder instances in extension state records.
	// This handles e.g. BlockBuilder → BlockDefinition without coupling
	// the core engine to specific builder types from other packages.
	// Duck-type check: if a value has a .build() method, call it.
	for (const [key, value] of Object.entries(extensionState)) {
		if (value && typeof value === "object" && !Array.isArray(value)) {
			const record = value as Record<string, unknown>;
			let rebuilt = false;
			const builtRecord: Record<string, unknown> = {};
			for (const [k, v] of Object.entries(record)) {
				if (v && typeof (v as any).build === "function") {
					builtRecord[k] = (v as any).build();
					rebuilt = true;
				} else {
					builtRecord[k] = v;
				}
			}
			if (rebuilt) {
				extensionState[key] = builtRecord;
			}
		}
	}

	return extensionState;
}

/**
 * Extract unknown extension keys from RuntimeConfig.
 * Filters out known infrastructure keys so only truly unknown
 * plugin-contributed keys (e.g. `channels`, `workflowsRuntime`) flow through
 * to `instance.state`.
 */
function extractRuntimeExtensions(
	runtime: Record<string, unknown> | undefined,
): Record<string, unknown> | undefined {
	if (!runtime) return undefined;
	const extensions: Record<string, unknown> = {};
	let hasAny = false;
	for (const [key, value] of Object.entries(runtime)) {
		if (!RUNTIME_CONSUMED_KEYS.has(key) && value !== undefined) {
			extensions[key] = value;
			hasAny = true;
		}
	}
	return hasAny ? extensions : undefined;
}

// ============================================================================
// createApp() — the main entry point
// ============================================================================

/**
 * Create and return a fully initialized Questpie CMS app.
 *
 * ```ts
 * createApp(definition, runtime)
 * ```
 * - `definition` — generated by codegen, contains modules + user entities + config bucket
 * - `runtime` — from `questpie.config.ts`, contains db/adapters/secret/plugins
 *
 */
export async function createApp(
	definition: { modules: readonly AppModuleInput[] },
	runtime: RuntimeConfig,
): Promise<Questpie<QuestpieConfig>>;
export async function createApp(
	definition: AppDefinition,
	runtime: RuntimeConfig,
): Promise<Questpie<QuestpieConfig>>;
export async function createApp(
	definition: AppDefinition | { modules: readonly AppModuleInput[] },
	runtime: RuntimeConfig,
): Promise<Questpie<QuestpieConfig>> {
	return createAppFromDefinition(definition as AppDefinition, runtime);
}

// ============================================================================
// New architecture: createApp(definition, runtime)
// ============================================================================

/**
 * Create a Questpie app from a definition object + runtime config.
 *
 */
async function createAppFromDefinition(
	definition: AppDefinition,
	runtime: RuntimeConfig,
): Promise<Questpie<QuestpieConfig>> {
	// 1. Extract root-level entities into an implicit __user module.
	//    This wraps user-provided collections/globals/etc. into a proper module
	//    so they participate in the same merge pipeline as all other modules.
	//    The __user module is appended last → user entities override module contributions.
	const { modules: defModules, ...rootEntities } = definition;
	const hasRootEntities = Object.keys(rootEntities).some(
		(k) => rootEntities[k] !== undefined,
	);
	// Auto-prepend coreModule so its hooks/jobs are always available.
	// Dedup: if user already listed coreModule, keep theirs (last-write-wins).
	const userModules = defModules ?? [];
	const hasCoreAlready = userModules.some((m) => m.name === coreModule.name);
	const allModules = [
		...(hasCoreAlready ? [] : [coreModule as unknown as ModuleDefinition]),
		...userModules,
		...(hasRootEntities
			? [{ name: "__user", ...rootEntities } as ModuleDefinition]
			: []),
	];

	// 2. Resolve modules depth-first
	const flatModules = resolveModules(allModules);

	// 3. Merge all module contributions (including __user)
	let merged = emptyMergedState();
	for (const mod of flatModules) {
		merged = mergeModuleIntoState(merged, mod);
	}

	// 4. Convert messages to translations config
	const mergedTranslations = mergeMessagesIntoConfig(
		merged.translations,
		merged.messages,
	);
	const finalTranslations = runtime.translations
		? mergeTranslationsConfig(mergedTranslations, runtime.translations)
		: mergedTranslations;

	// 5. Build QuestpieConfig — extract consumed config keys
	const allJobs = merged.jobs;
	const hasJobs = Object.keys(allJobs).length > 0;

	// Extract config bucket values
	const cfg = merged.config ?? {};
	const appCfg = cfg.app ?? {};
	const authCfg = cfg.auth ?? {};

	const cmsConfig: QuestpieConfig = {
		app: runtime.app,
		db: runtime.db,
		secret: runtime.secret,
		collections: merged.collections,
		channels: merged.channels,
		globals: merged.globals,
		locale: appCfg.locale,
		auth: authCfg,
		storage: runtime.storage,
		// Read off `merged`, not `definition`. A module that ships an emails/
		// directory contributes its templates through the merge like everything
		// else, and reading the root definition skipped every one of them. The
		// app's own emails/ still arrives, because root entities ride in __user.
		email: merged.emailTemplates
			? { ...(runtime.email ?? {}), templates: merged.emailTemplates }
			: runtime.email,
		queue:
			hasJobs && runtime.queue
				? {
						jobs: allJobs,
						adapter: runtime.queue.adapter,
					}
				: undefined,
		routes: Object.keys(merged.routes).length > 0 ? merged.routes : undefined,
		search: runtime.search,
		realtime: runtime.realtime,
		crdt: runtime.crdt,
		logger: runtime.logger,
		kv: runtime.kv,
		// Was missing until 2026-07-29, which meant `runtimeConfig({
		// observability: { adapter } })` was accepted by the types, silently
		// dropped here, and the service came up disabled — so the documented way
		// to turn tracing on did nothing at all.
		observability: runtime.observability,
		executor: runtime.executor,
		migrations: {
			migrations: [...merged.migrations],
		},
		seeds: {
			seeds: [...merged.seeds],
		},
		autoMigrate: runtime.autoMigrate,
		autoSeed: runtime.autoSeed,
		translations: finalTranslations,
		globalHooks: appCfg.hooks,
		defaultAccess: appCfg.access,
		services:
			Object.keys(merged.services).length > 0 ? merged.services : undefined,
	};

	// 6. Create Questpie instance
	const instance = new Questpie(cmsConfig);

	// 6b. Validated env (from env.ts) — typed via the generated app type.
	if (merged.env && typeof merged.env === "object") {
		instance.env = merged.env as Readonly<Record<string, unknown>>;
	}

	// 7. Store extension state + config bucket on instance.state
	const runtimeExtensions = extractRuntimeExtensions(
		runtime as Record<string, unknown>,
	);
	const extensionState = buildExtensionState(merged, runtimeExtensions);

	// The entire merged config bucket goes to instance.state.config — no filtering.
	// Runtime already extracted what it needs (locale, hooks, auth, etc.) into cmsConfig.
	// state.config is the single source of truth for all plugin configs at runtime.
	if (Object.keys(cfg).length > 0) {
		extensionState.config = cfg;
	}

	instance.state = extensionState;
	instance.crdtManifests = createCrdtRuntimeManifests({
		registry: instance.crdtRegistry,
		config: runtime.crdt,
		artifact: merged.crdtManifest,
		allowMissingForGeneration:
			process.env.QUESTPIE_CRDT_MANIFEST_GENERATION === "1",
	});

	await instance._initServices();

	return instance;
}
