import type {
	AppConfig,
	AppDefinition,
	AppEntities,
	ModuleDefinition,
	RuntimeConfig,
} from "#questpie/server/config/module-types.js";
import type { GlobalHooksState } from "#questpie/server/config/global-hooks-types.js";
import { Questpie } from "#questpie/server/config/questpie.js";
import type { QuestpieConfig } from "#questpie/server/config/types.js";
import {
	mergeMessagesIntoConfig,
	mergeTranslationsConfig,
} from "#questpie/server/i18n/translator.js";
import { mergeAuthOptions } from "#questpie/server/integrated/auth/merge.js";

// ============================================================================
// module() — identity function for type inference
// ============================================================================

/**
 * Define a module as a plain data object.
 * Modules contribute collections, globals, jobs, functions, fields,
 * auth config, migrations, messages, etc.
 *
 * @example
 * ```ts
 * import { module, collection } from "questpie";
 *
 * export const myModule = module({
 *   name: "my-module",
 *   collections: { posts: postCollection },
 *   jobs: { sendNewsletter },
 *   messages: { en: { "my.key": "Hello" } },
 * });
 * ```
 */
export function module<T extends ModuleDefinition>(definition: T): T {
	return definition;
}

// ============================================================================
// config() — identity function for type inference (legacy)
// ============================================================================

/**
 * Define the application config — the shape of `questpie.config.ts`.
 * Composes modules with runtime settings (db, app url, adapters).
 *
 * For new code, use `runtimeConfig()` instead — runtime-only config
 * without entity definitions.
 *
 * @see RFC §12 (config() Full API)
 */
export function config<T extends AppConfig>(input: T): T {
	return input;
}

// ============================================================================
// runtimeConfig() — identity function for new architecture
// ============================================================================

/**
 * Define the runtime configuration for `questpie.config.ts`.
 * Contains only runtime infrastructure (db, adapters, secret) and plugin registrations.
 * No entity definitions — those come from the definition object generated by codegen.
 *
 * @example
 * ```ts
 * // questpie.config.ts
 * import { runtimeConfig } from "questpie";
 * import { adminPlugin } from "@questpie/admin/server";
 *
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 *   app: { url: process.env.APP_URL! },
 *   db: { url: process.env.DATABASE_URL! },
 *   secret: process.env.SECRET,
 *   email: { adapter: new ConsoleAdapter() },
 * });
 * ```
 *
 * @see RFC-MODULE-ARCHITECTURE §3.1 (Functions)
 */
export function runtimeConfig<T extends RuntimeConfig>(input: T): T {
	return input;
}

// ============================================================================
// Module resolution — depth-first, left-to-right
// ============================================================================

/**
 * Flatten modules depth-first per RFC §13.7.
 * Dependencies are resolved before the module that depends on them.
 * Duplicate modules (by name) are deduplicated — last occurrence wins.
 */
function resolveModules(modules: ModuleDefinition[]): ModuleDefinition[] {
	const flat: ModuleDefinition[] = [];
	for (const mod of modules) {
		if (mod.modules && mod.modules.length > 0) {
			flat.push(...resolveModules(mod.modules));
		}
		flat.push(mod);
	}
	// Deduplicate by name — keep last occurrence (later wins)
	const seen = new Map<string, number>();
	for (let i = 0; i < flat.length; i++) {
		seen.set(flat[i].name, i);
	}
	return flat.filter((_, i) => {
		const mod = flat[i];
		return seen.get(mod.name) === i;
	});
}

// ============================================================================
// Module merging
// ============================================================================

interface MergedState {
	collections: Record<string, any>;
	globals: Record<string, any>;
	jobs: Record<string, any>;
	functions: Record<string, any>;
	routes: Record<string, any>;
	fields: Record<string, any>;
	services: Record<string, any>;
	auth: Record<string, any>;
	migrations: any[];
	seeds: any[];
	messages: Record<string, Record<string, string>>;
	defaultAccess: any;
	hooks: GlobalHooksState | undefined;
	translations: any;
	// Admin extension keys (stored on Questpie instance as .state)
	[key: string]: any;
}

function emptyMergedState(): MergedState {
	return {
		collections: {},
		globals: {},
		jobs: {},
		functions: {},
		routes: {},
		fields: {},
		services: {},
		auth: {},
		migrations: [],
		seeds: [],
		messages: {},
		defaultAccess: undefined,
		hooks: undefined,
		translations: undefined,
	};
}

function mergeMessages(
	a: Record<string, Record<string, string>>,
	b?: Record<string, Record<string, string>>,
): Record<string, Record<string, string>> {
	if (!b) return a;
	const result: Record<string, Record<string, string>> = { ...a };
	for (const [locale, msgs] of Object.entries(b)) {
		result[locale] = { ...(result[locale] || {}), ...msgs };
	}
	return result;
}

function mergeGlobalHooks(
	a: GlobalHooksState | undefined,
	b: GlobalHooksState | undefined,
): GlobalHooksState | undefined {
	if (!a && !b) return undefined;
	if (!a) return b;
	if (!b) return a;
	return {
		collections: [...(a.collections || []), ...(b.collections || [])],
		globals: [...(a.globals || []), ...(b.globals || [])],
	};
}

/** Known core keys on ModuleDefinition — everything else is an extension. */
const CORE_MODULE_KEYS = new Set([
	"name",
	"modules",
	"collections",
	"globals",
	"jobs",
	"functions",
	"routes",
	"fields",
	"services",
	"auth",
	"migrations",
	"seeds",
	"messages",
	"defaultAccess",
	"hooks",
]);

function mergeModuleIntoState(
	state: MergedState,
	mod: ModuleDefinition,
): MergedState {
	const result: MergedState = {
		...state,
		collections: { ...state.collections, ...(mod.collections || {}) },
		globals: { ...state.globals, ...(mod.globals || {}) },
		jobs: { ...state.jobs, ...(mod.jobs || {}) },
		functions: { ...state.functions, ...(mod.functions || {}) },
		routes: { ...state.routes, ...(mod.routes || {}) },
		fields: { ...state.fields, ...(mod.fields || {}) },
		services: { ...state.services, ...(mod.services || {}) },
		auth: mergeAuthOptions(state.auth, mod.auth ?? {}),
		migrations: [...state.migrations, ...(mod.migrations || [])],
		seeds: [...state.seeds, ...(mod.seeds || [])],
		messages: mergeMessages(state.messages, mod.messages),
		defaultAccess: mod.defaultAccess ?? state.defaultAccess,
		hooks: mergeGlobalHooks(state.hooks, mod.hooks),
	};

	// Merge extension keys (admin: listViews, editViews, components, blocks, sidebar, dashboard, branding, adminLocale)
	for (const key of Object.keys(mod)) {
		if (!CORE_MODULE_KEYS.has(key)) {
			const existing = state[key];
			const incoming = mod[key];

			// Array extension keys (sidebar/dashboard contributions) — concatenate
			if (Array.isArray(incoming) && Array.isArray(existing)) {
				result[key] = [...existing, ...incoming];
			} else if (Array.isArray(incoming)) {
				result[key] = [...incoming];
			}
			// Object extension keys — spread-merge (listViews, editViews, components, blocks, branding)
			else if (
				incoming != null &&
				typeof incoming === "object" &&
				!Array.isArray(incoming) &&
				typeof existing === "object" &&
				!Array.isArray(existing) &&
				existing != null
			) {
				result[key] = { ...existing, ...incoming };
			}
			// Primitive extension keys — last-wins (adminLocale)
			else if (incoming !== undefined) {
				result[key] = incoming;
			}
		}
	}

	return result;
}

/**
 * Merge extension keys from entities or definition into merged state.
 * Handles array concatenation, object spread-merge, and primitive last-wins.
 */
function mergeExtensionKeys(
	merged: MergedState,
	source: Record<string, unknown>,
): void {
	for (const key of Object.keys(source)) {
		if (
			!CORE_MODULE_KEYS.has(key) &&
			key !== "name" &&
			key !== "modules" &&
			key !== "locale" &&
			key !== "contextResolver"
		) {
			const incoming = source[key];
			const existing = merged[key];

			// Array extension keys — concatenate
			if (Array.isArray(incoming) && Array.isArray(existing)) {
				merged[key] = [...existing, ...incoming];
			} else if (Array.isArray(incoming)) {
				merged[key] = [...incoming];
			}
			// Object extension keys — spread-merge
			else if (
				incoming != null &&
				typeof incoming === "object" &&
				!Array.isArray(incoming) &&
				typeof existing === "object" &&
				!Array.isArray(existing) &&
				existing != null
			) {
				merged[key] = { ...existing, ...incoming };
			}
			// Primitive — last-wins
			else if (incoming !== undefined) {
				merged[key] = incoming;
			}
		}
	}
}

// ============================================================================
// Extension state for admin config
// ============================================================================

const EXTENSION_KEYS = [
	"listViews",
	"editViews",
	"components",
	"blocks",
	"sidebar",
	"dashboard",
	"branding",
	"adminLocale",
];

function buildExtensionState(
	merged: MergedState,
	configOverrides?: Record<string, unknown>,
): Record<string, unknown> {
	const extensionState: Record<string, unknown> = {};
	for (const key of EXTENSION_KEYS) {
		const configValue = configOverrides?.[key];
		const mergedValue = merged[key];

		// For array extension keys (sidebar/dashboard contributions),
		// append config-level contribution to module-level array
		if (Array.isArray(mergedValue) && configValue != null) {
			extensionState[key] = Array.isArray(configValue)
				? [...mergedValue, ...configValue]
				: [...mergedValue, configValue];
		} else if (configValue !== undefined || mergedValue !== undefined) {
			// For object/primitive keys: config-level overrides module-level
			extensionState[key] = configValue ?? mergedValue;
		}
	}
	return extensionState;
}

// ============================================================================
// createApp() — the main entry point
// ============================================================================

/**
 * Detect whether the second argument is a RuntimeConfig (new signature)
 * or AppEntities/undefined (legacy signature).
 *
 * RuntimeConfig always has `db` and `app` keys. AppEntities does not.
 */
function isRuntimeConfig(arg: unknown): arg is RuntimeConfig {
	return (
		arg != null &&
		typeof arg === "object" &&
		"db" in arg &&
		"app" in arg &&
		typeof (arg as Record<string, unknown>).app === "object" &&
		typeof (arg as Record<string, unknown>).db === "object"
	);
}

/**
 * Create a Questpie app instance.
 *
 * Supports two calling conventions:
 *
 * **New architecture** (RFC-MODULE-ARCHITECTURE):
 * ```ts
 * createApp(definition, runtime)
 * ```
 * - `definition` — generated by codegen, contains modules + user entities
 * - `runtime` — from `questpie.config.ts`, contains db/adapters/secret/plugins
 *
 * **Legacy** (RFC-FILE-CONVENTION):
 * ```ts
 * createApp(appConfig, entities?)
 * ```
 * - `appConfig` — mixed config (modules + runtime)
 * - `entities` — codegen-discovered user entities
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App — .generated/index.ts)
 */
export function createApp(
	configOrDefinition: AppConfig | AppDefinition,
	entitiesOrRuntime?: AppEntities | RuntimeConfig,
) {
	// Detect new vs legacy signature
	if (isRuntimeConfig(entitiesOrRuntime)) {
		return createAppFromDefinition(
			configOrDefinition as AppDefinition,
			entitiesOrRuntime,
		);
	}

	// Legacy signature: createApp(appConfig, entities?)
	return createAppLegacy(
		configOrDefinition as AppConfig,
		entitiesOrRuntime as AppEntities | undefined,
	);
}

// ============================================================================
// New architecture: createApp(definition, runtime)
// ============================================================================

/**
 * Create a Questpie app from a definition object + runtime config.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1
 */
function createAppFromDefinition(
	definition: AppDefinition,
	runtime: RuntimeConfig,
) {
	// 1. Resolve modules depth-first
	const flatModules = resolveModules(definition.modules ?? []);

	// 2. Merge all module contributions
	let merged = emptyMergedState();
	for (const mod of flatModules) {
		merged = mergeModuleIntoState(merged, mod);
	}

	// 3. Merge user entities on top (user always wins over modules)
	merged = mergeModuleIntoState(merged, {
		name: "user",
		collections: definition.collections,
		globals: definition.globals,
		jobs: definition.jobs,
		functions: definition.functions,
		routes: definition.routes,
		services: definition.services,
		auth: definition.auth,
		migrations: definition.migrations,
		seeds: definition.seeds,
		messages: definition.messages,
		defaultAccess: definition.defaultAccess,
		hooks: definition.hooks,
	});

	// Copy extension keys from definition (e.g. blocks, sidebar, dashboard, branding)
	mergeExtensionKeys(merged, definition);

	// 4. Convert messages to translations config
	const mergedTranslations = mergeMessagesIntoConfig(
		merged.translations,
		merged.messages,
	);
	const finalTranslations = runtime.translations
		? mergeTranslationsConfig(mergedTranslations, runtime.translations)
		: mergedTranslations;

	// 5. Build QuestpieConfig
	const allJobs = merged.jobs;
	const hasJobs = Object.keys(allJobs).length > 0;

	const cmsConfig: QuestpieConfig = {
		app: runtime.app,
		db: runtime.db,
		secret: runtime.secret,
		collections: merged.collections,
		globals: merged.globals,
		locale: definition.locale,
		auth: mergeAuthOptions(merged.auth, {}),
		storage: runtime.storage,
		email: definition.emailTemplates
			? { ...(runtime.email ?? {}), templates: definition.emailTemplates }
			: runtime.email,
		queue:
			hasJobs && runtime.queue
				? {
						jobs: allJobs,
						adapter: runtime.queue.adapter,
					}
				: undefined,
		functions:
			Object.keys(merged.functions).length > 0 ? merged.functions : undefined,
		routes: Object.keys(merged.routes).length > 0 ? merged.routes : undefined,
		search: runtime.search,
		realtime: runtime.realtime,
		logger: runtime.logger,
		kv: runtime.kv,
		migrations: {
			migrations: [...merged.migrations],
		},
		seeds: {
			seeds: [...merged.seeds],
		},
		autoMigrate: runtime.autoMigrate,
		autoSeed: runtime.autoSeed,
		translations: finalTranslations,
		contextResolver: definition.contextResolver,
		globalHooks: merged.hooks,
		defaultAccess: definition.defaultAccess ?? merged.defaultAccess,
		services:
			Object.keys(merged.services).length > 0 ? merged.services : undefined,
	};

	// 6. Create Questpie instance
	const instance = new Questpie(cmsConfig);

	// 7. Store admin-specific extension state
	const extensionState = buildExtensionState(merged);
	if (Object.keys(extensionState).length > 0) {
		instance.state = extensionState;
	}

	return instance;
}

// ============================================================================
// Legacy: createApp(appConfig, entities?)
// ============================================================================

/**
 * Legacy createApp — takes mixed config + optional entities.
 */
function createAppLegacy(appConfig: AppConfig, entities?: AppEntities) {
	// 1. Resolve modules depth-first
	const flatModules = resolveModules(appConfig.modules ?? []);

	// 2. Merge all module contributions
	let merged = emptyMergedState();
	for (const mod of flatModules) {
		merged = mergeModuleIntoState(merged, mod);
	}

	// 3. Merge user entities on top (user always wins over modules)
	if (entities) {
		merged = mergeModuleIntoState(merged, {
			name: "user",
			collections: entities.collections,
			globals: entities.globals,
			jobs: entities.jobs,
			functions: entities.functions,
			routes: entities.routes,
			auth: entities.auth,
			migrations: entities.migrations,
			seeds: entities.seeds,
			messages: entities.messages,
		});

		// Copy extension keys from entities (e.g. blocks from admin plugin)
		mergeExtensionKeys(merged, entities);
	}

	// 4. Convert messages to translations config
	const mergedTranslations = mergeMessagesIntoConfig(
		merged.translations,
		merged.messages,
	);
	// Also merge with any config-level translations
	const finalTranslations = appConfig.translations
		? mergeTranslationsConfig(mergedTranslations, appConfig.translations)
		: mergedTranslations;

	// 5. Build QuestpieConfig
	const allJobs = merged.jobs;
	const hasJobs = Object.keys(allJobs).length > 0;

	const cmsConfig: QuestpieConfig = {
		app: appConfig.app,
		db: appConfig.db,
		secret: appConfig.secret,
		collections: merged.collections,
		globals: merged.globals,
		locale: appConfig.locale,
		auth: mergeAuthOptions(merged.auth, appConfig.auth ?? {}),
		storage: appConfig.storage,
		email: appConfig.email,
		queue:
			hasJobs && appConfig.queue
				? {
						jobs: allJobs,
						adapter: appConfig.queue.adapter,
					}
				: undefined,
		functions:
			Object.keys(merged.functions).length > 0 ? merged.functions : undefined,
		routes: Object.keys(merged.routes).length > 0 ? merged.routes : undefined,
		search: appConfig.search,
		realtime: appConfig.realtime,
		logger: appConfig.logger,
		kv: appConfig.kv,
		migrations: {
			migrations: [...merged.migrations, ...(appConfig.migrations || [])],
		},
		seeds: {
			seeds: [...merged.seeds, ...(appConfig.seeds || [])],
		},
		autoMigrate: appConfig.autoMigrate,
		autoSeed: appConfig.autoSeed,
		translations: finalTranslations,
		contextResolver: appConfig.contextResolver,
		globalHooks: mergeGlobalHooks(merged.hooks, appConfig.hooks),
		defaultAccess: appConfig.defaultAccess ?? merged.defaultAccess,
	};

	// 6. Create Questpie instance
	const instance = new Questpie(cmsConfig);

	// 7. Store admin-specific extension state for getAdminConfig
	const extensionState = buildExtensionState(merged, appConfig as Record<string, unknown>);
	if (Object.keys(extensionState).length > 0) {
		instance.state = extensionState;
	}

	return instance;
}
