import type { BetterAuthOptions } from "better-auth";
import type { Adapter } from "files-sdk";

import type { CollectionAccess } from "#questpie/server/collection/builder/types.js";

// ============================================================================
// Auth Config — type for auth.ts file convention
// ============================================================================

/**
 * Auth configuration type for the `auth.ts` file convention.
 * Accepts Better Auth options (email/password, social providers, plugins, etc.).
 *
 * @example
 * ```ts
 * // auth.ts
 * import type { AuthConfig } from "questpie";
 *
 * export default {
 *   emailAndPassword: { enabled: true },
 *   socialProviders: {
 *     google: { clientId: "...", clientSecret: "..." },
 *   },
 * } satisfies AuthConfig;
 * ```
 *
 * @see RFC §9 (Auth)
 */
export type AuthConfig = BetterAuthOptions;

export type {
	CallbackParamDefinition,
	CategoryDeclaration,
	CodegenPlugin,
	CodegenResult,
	CodegenTargetContribution,
	CodegenTargetGenerateContext,
	CodegenTargetOutput,
	CrossTargetValidator,
	DiscoveredFile,
	DiscoverPattern,
	DiscoveryResult,
	MultiTargetCodegenResult,
	ProjectionError,
	RegistryExtension,
	ResolvedTarget,
	ScaffoldConfig,
	ScaffoldContext,
	SingletonFactory,
} from "#questpie/cli/codegen/types.js";

import type { CodegenPlugin } from "#questpie/cli/codegen/types.js";
import type { GlobalHooksState } from "#questpie/server/config/global-hooks-types.js";
import type {
	AnyCollectionOrBuilder,
	AnyGlobalOrBuilder,
	ContextResolver,
	DbConfig,
	LocaleConfig,
	StorageConfig,
} from "#questpie/server/config/types.js";
import type { TranslationsConfig } from "#questpie/server/i18n/types.js";
import type { Migration } from "#questpie/server/migration/types.js";
import type { ExecutorConfig } from "#questpie/server/modules/core/integrated/executor/types.js";
import type { KVConfig } from "#questpie/server/modules/core/integrated/kv/types.js";
import type { LoggerConfig } from "#questpie/server/modules/core/integrated/logger/types.js";
import type { MailerConfig } from "#questpie/server/modules/core/integrated/mailer/types.js";
import type {
	JobDefinition,
	QueueAdapter,
} from "#questpie/server/modules/core/integrated/queue/types.js";
import type { RealtimeConfig } from "#questpie/server/modules/core/integrated/realtime/types.js";
import type { SearchAdapter } from "#questpie/server/modules/core/integrated/search/types.js";
import type {
	RouteDefinition,
	StoredRouteDefinition,
} from "#questpie/server/routes/types.js";
import type { Seed, SeedCategory } from "#questpie/server/seed/types.js";

// ============================================================================
// Module Definition — what module() accepts
// ============================================================================

/**
 * Module definition — a static plain object describing what a module contributes.
 * Modules are generated by codegen from the file system. No factory functions.
 *
 * Admin-specific properties (listViews, formViews, components, blocks,
 * sidebar, dashboard, branding, adminLocale) are added via declaration
 * merging by `@questpie/admin`.
 *
 * @see RFC-MODULE-ARCHITECTURE §2 (Core Concepts)
 */
export interface ModuleDefinition {
	/** Unique module name (e.g. "questpie-starter", "questpie-admin"). */
	name: string;

	/** Dependency modules — resolved depth-first before this module. */
	modules?: ModuleDefinition[];

	/** Collections this module contributes. Later modules override by key. */
	collections?: Record<string, AnyCollectionOrBuilder>;

	/** Globals this module contributes. Later modules override by key. */
	globals?: Record<string, AnyGlobalOrBuilder>;

	/** Job definitions this module contributes. */
	jobs?: Record<string, JobDefinition<any, any>>;

	/** Route definitions this module contributes. */
	routes?: Record<string, RouteDefinition>;

	/** Custom field types this module contributes (extends the `f` proxy). */
	fields?: Record<string, any>;

	/** Services this module contributes. Keyed by service name. */
	services?: Record<
		string,
		import("#questpie/server/services/define-service.js").ServiceBuilder<any>
	>;

	/** Migrations this module contributes — concatenated with others. */
	migrations?: Migration[];

	/** Seeds this module contributes — concatenated with others. */
	seeds?: Seed[];

	/**
	 * Backend messages keyed by locale.
	 * Deep-merged per locale — later modules override individual keys.
	 */
	messages?: Record<string, Record<string, string>>;

	/**
	 * Config bucket — each config file maps to one key.
	 * Plugins augment AppStateConfig to declare their config keys.
	 * Merged per-key across modules using plugin-declared strategies.
	 */
	config?: import("./app-state-config.js").ResolvedAppStateConfig;

	/**
	 * Codegen plugin(s) this module contributes.
	 * Auto-extracted by codegen from modules.ts during the pre-pass.
	 * Excluded from module merge — only used at codegen time.
	 */
	plugin?:
		| import("#questpie/cli/codegen/types.js").CodegenPlugin
		| import("#questpie/cli/codegen/types.js").CodegenPlugin[];

	/**
	 * Extensible — plugins add category keys via declaration merging
	 * (views, components, blocks, etc.)
	 */
	[key: string]: unknown;
}

/**
 * Relaxed module input accepted by `createApp()`.
 *
 * Generated modules expose narrow record interfaces without string index
 * signatures. Those remain structurally valid module inputs at runtime, but
 * they are not assignable to `ModuleDefinition` directly. `createApp()`
 * accepts this looser shape and normalizes it internally before merging.
 */
export interface AppModuleInput {
	/** Unique module name (e.g. "questpie-starter", "questpie-admin"). */
	name: string;

	/** Dependency modules — resolved depth-first before this module. */
	modules?: readonly AppModuleInput[];

	/**
	 * Extensible module payload.
	 * Known keys (collections, routes, config, etc.) are interpreted at runtime.
	 */
	[key: string]: unknown;
}

// ============================================================================
// App Config Input — composite config/app.ts type
// ============================================================================

/**
 * Input type for `config/app.ts` — a composite config file that consolidates
 * locale, access, hooks, and context resolver into a single file.
 *
 * Used with `appConfig()` factory for type inference.
 *
 * @example
 * ```ts
 * // config/app.ts
 * import { appConfig } from "questpie/app";
 *
 * export default appConfig({
 *   locale: { locales: [{ code: "en" }, { code: "sk" }], defaultLocale: "en" },
 *   access: { read: true, create: true, update: true, delete: true },
 *   hooks: { collections: [...], globals: [...] },
 *   context: async ({ session }) => ({ role: session?.user?.role ?? "guest" }),
 * });
 * ```
 */
/**
 * App-level default access rule — ctx is the lazy infra seam
 * `ResolvedAppDefaultAccessContext`, NOT the augmented `AccessContext`.
 * Contextual typing of a function here must not route through the merged
 * AppContext: the augmentation lives in the generated index, which consumes
 * `typeof config/app.ts` — any function whose params resolve through the
 * augmentation collapses the whole chain (TS2456). The seam is filled by
 * codegen with the real infra (db/session/collections/...) WITHOUT the
 * extension edge, so it stays cycle-free yet precise (pre-codegen it degrades
 * to a loose non-`any` default, not the old all-`any` base). Collection-level
 * `.access()` rules keep the fully augmented ctx.
 */
export type AppDefaultAccessRule =
	| boolean
	| ((
			ctx: import("#questpie/server/config/app-context.js").ResolvedAppDefaultAccessContext & {
				data?: unknown;
				input?: unknown;
				locale?: string;
				request?: Request;
			},
	  ) =>
			| boolean
			| Record<string, unknown>
			| Promise<boolean | Record<string, unknown>>);

/** App-level default access map — see {@link AppDefaultAccessRule}. */
export interface AppDefaultAccess {
	read?: AppDefaultAccessRule;
	create?: AppDefaultAccessRule;
	update?: AppDefaultAccessRule;
	delete?: AppDefaultAccessRule;
	transition?: AppDefaultAccessRule;
	serve?: AppDefaultAccessRule;
	introspect?: AppDefaultAccessRule;
}

export interface AppConfigInput {
	locale?: LocaleConfig;
	access?: AppDefaultAccess;
	hooks?: import("#questpie/server/config/global-hooks-types.js").GlobalHooksInput;
	context?: ContextResolver;
}

declare const __appAccessStorageBrand: unique symbol;
/**
 * Opaque storage for app-level default access rules on the `appConfig()`
 * RETURN type. Function-valued rules must not survive into
 * `typeof appConfig-file` — their parameter types (AccessContext) re-enter
 * the generated index through the `_ModuleConfig` extraction and collapse
 * the whole AppContext augmentation (TS2456). Same erasure precedent as
 * `CollectionAccessStorage` on the collection builder.
 */
export type AppAccessStorage = Record<string, unknown> & {
	readonly [__appAccessStorageBrand]?: never;
};

declare const __appHooksStorageBrand: unique symbol;
/** Opaque storage for app-level hooks on the `appConfig()` return type. @see AppAccessStorage */
export type AppHooksStorage = Record<string, unknown> & {
	readonly [__appHooksStorageBrand]?: never;
};

/**
 * The `appConfig()` RETURN shape: access/hooks erased to opaque storage
 * (nothing downstream consumes their types), `context` preserved verbatim
 * (its return type drives the generated context-extension inference — which
 * is why resolver returns must be explicitly annotated, never inferred from
 * CRUD results).
 */
export type AppConfigResolved<T extends AppConfigInput> = {
	locale?: T["locale"];
	context?: T["context"];
	access?: AppAccessStorage;
	hooks?: AppHooksStorage;
};

// ============================================================================
// Runtime Config — what questpie.config.ts exports (new architecture)
// ============================================================================

/**
 * Plugin-owned runtime configuration keys.
 *
 * Packages can augment this interface to add typed keys to both
 * {@link RuntimeConfig} and `app.state`.
 *
 * @example
 * ```ts
 * declare module "questpie" {
 *   interface RuntimeConfigExtensions {
 *     myPluginRuntime?: MyPluginRuntimeConfig;
 *   }
 * }
 * ```
 */
export interface RuntimeConfigExtensions {}

/**
 * Runtime configuration — the shape of `questpie.config.ts` in the new architecture.
 * Contains only runtime infrastructure (db, adapters, secret) and plugin registrations.
 * No entity definitions (collections, globals, etc.) — those come from the definition
 * object generated by codegen.
 *
 * Created via `runtimeConfig({ ... })`.
 *
 * @example
 * ```ts
 * // questpie.config.ts
 * import { runtimeConfig } from "questpie/app";
 * import { adminPlugin } from "@questpie/admin/plugin";
 *
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 *   app: { url: process.env.APP_URL! },
 *   db: { url: process.env.DATABASE_URL! },
 *   secret: process.env.SECRET,
 *   email: { adapter: new ConsoleAdapter() },
 * });
 * ```
 *
 * @see RFC-MODULE-ARCHITECTURE §3.1 (Functions), §8.1 (User Project)
 */
export interface RuntimeConfig<
	TDb extends DbConfig = DbConfig,
	TStorage extends StorageConfig | undefined = StorageConfig | undefined,
> extends RuntimeConfigExtensions {
	/** Codegen plugins — discover additional file patterns and extend generated output. */
	plugins?: readonly CodegenPlugin[];

	/** Application URL (required). */
	app: { url: string };

	/** Database connection (required). */
	db: TDb;

	/** Secret key for signing tokens. */
	secret?: string;

	/** Storage configuration. */
	storage?: TStorage;

	/** Email configuration with adapter. */
	email?: MailerConfig;

	/** Queue configuration with adapter. */
	queue?: { adapter: QueueAdapter };

	/** Search adapter for full-text search. */
	search?: SearchAdapter;

	/** Realtime configuration. */
	realtime?: RealtimeConfig;

	/** Logger configuration. */
	logger?: LoggerConfig;

	/** KV store configuration. */
	kv?: KVConfig;

	/** Executor configuration (sandboxed / trusted code execution). */
	executor?: ExecutorConfig;

	/** I18n translations config (backend messages). */
	translations?: TranslationsConfig;

	/** Auto-migrate on startup. */
	autoMigrate?: boolean;

	/** Auto-seed on startup. */
	autoSeed?: boolean | SeedCategory | SeedCategory[];

	/** CLI-specific configuration (used by `questpie` CLI commands). */
	cli?: {
		/** Migration directory for generated migrations. @default "./src/migrations" */
		migrations?: { directory?: string };
		/** Seed directory for generated seeds. @default "./src/seeds" */
		seeds?: { directory?: string };
	};

	/**
	 * Extensible — admin plugin may read additional keys from here.
	 */
	[key: string]: unknown;
}

// ============================================================================
// RuntimeConfigInput — input type for runtimeConfig() with cloud defaults
// ============================================================================

export type RealtimeConfigInput = true | RealtimeConfig;

/**
 * Input type for {@link runtimeConfig} — accepts the same shape as
 * {@link RuntimeConfig} but `app` and `db` are **optional** because they can
 * be auto-resolved from environment variables.
 *
 * **Resolution order** (for each field):
 * 1. Explicit value passed by the user (wins).
 * 2. `QUESTPIE_*` environment variables (set by QUESTPIE Cloud).
 * 3. Standard env vars (`DATABASE_URL`, `APP_URL`, `BETTER_AUTH_SECRET`).
 * 4. Sensible defaults (`http://localhost:3000` for app URL).
 *
 * If `db` cannot be resolved from any source, `runtimeConfig()` throws.
 *
 * @example Zero-config for QUESTPIE Cloud:
 * ```ts
 * // questpie.config.ts — just works when QUESTPIE_* env vars are set
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 * });
 * ```
 *
 * @example Explicit overrides:
 * ```ts
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 *   app: { url: "https://my-app.example.com" },
 *   db: { url: process.env.MY_CUSTOM_DB! },
 * });
 * ```
 *
 * @see {@link RuntimeConfig} for the resolved output type.
 */
export type RuntimeConfigInput<
	TDb extends DbConfig = DbConfig,
	TStorage extends StorageConfig | undefined = StorageConfig | undefined,
> = Partial<Pick<RuntimeConfig<TDb, TStorage>, "app" | "db">> &
	Omit<RuntimeConfig<TDb, TStorage>, "app" | "db" | "realtime"> & {
		/** Realtime configuration. Use `true` to enable defaults. */
		realtime?: RealtimeConfigInput;
	};

type DbFromRuntimeConfigInput<TInput> = TInput extends { db: infer TDb }
	? TDb extends DbConfig
		? TDb
		: DbConfig
	: DbConfig;

type StorageFromRuntimeConfigInput<TInput> = "storage" extends keyof TInput
	? TInput extends { storage?: infer TStorage }
		? TStorage extends StorageConfig | undefined
			? TStorage
			: StorageConfig<Adapter> | undefined
		: StorageConfig<Adapter> | undefined
	: StorageConfig | undefined;

export type ResolvedRuntimeConfig<TInput extends RuntimeConfigInput<any, any>> =
	Omit<
		RuntimeConfig<
			DbFromRuntimeConfigInput<TInput>,
			StorageFromRuntimeConfigInput<TInput>
		>,
		"app" | "db" | "secret" | "storage" | "realtime"
	> &
		Omit<TInput, "app" | "db" | "secret" | "storage" | "realtime"> & {
			app: { url: string };
			db: DbFromRuntimeConfigInput<TInput>;
			secret: string | undefined;
			storage: StorageFromRuntimeConfigInput<TInput>;
			realtime: TInput extends { realtime: infer TRealtime }
				? TRealtime extends true
					? RealtimeConfig
					: TRealtime extends RealtimeConfig
						? TRealtime
						: RealtimeConfig | undefined
				: RealtimeConfig | undefined;
		};

// ============================================================================
// App Definition — what codegen generates (first arg to createApp)
// ============================================================================

/**
 * Application definition — the full entity tree generated by codegen.
 * Passed as the first argument to `createApp(definition, runtime)`.
 *
 * Contains modules (from `modules.ts`), user entities (from file convention),
 * and plugin-discovered items (e.g. blocks, sidebar, dashboard, branding).
 *
 * @example
 * ```ts
 * // .generated/index.ts
 * export const app: App = createApp(
 *   {
 *     modules: _modules,
 *     collections: { posts: _coll_posts },
 *     globals: { siteSettings: _glob_siteSettings },
 *     routes: { "webhooks/stripe": _route_webhooks_stripe, createBooking: _fn_createBooking },
 *     auth: _auth,
 *     locale: _locale,
 *     sidebar: _sidebar,
 *     dashboard: _dashboard,
 *     branding: _branding,
 *   },
 *   _runtime,
 * ) as unknown as App;
 * ```
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App)
 */
export interface AppDefinition {
	/** Modules from `modules.ts` — static module imports. */
	modules?: readonly AppModuleInput[];

	/**
	 * Validated env object from `env.ts` (the `env()` factory).
	 * Stored on the instance as `app.env`; the generated app type
	 * narrows it to the inferred env shape.
	 */
	env?: Readonly<Record<string, unknown>>;

	/** Collections discovered from `collections/` directory. */
	collections?: Record<string, AnyCollectionOrBuilder>;

	/** Globals discovered from `globals/` directory. */
	globals?: Record<string, AnyGlobalOrBuilder>;

	/** Jobs discovered from `jobs/` directory. */
	jobs?: Record<string, JobDefinition<any, any>>;

	/** Routes discovered from `routes/` directory. */
	routes?: Record<string, StoredRouteDefinition>;

	/** Services discovered from `services/` directory. */
	services?: Record<
		string,
		import("#questpie/server/services/define-service.js").ServiceBuilder<
			any,
			any,
			any
		>
	>;

	/** Email templates discovered from `emails/` directory. */
	emailTemplates?: Record<
		string,
		import("#questpie/server/modules/core/integrated/mailer/template.js").EmailTemplateDefinition<
			any,
			any
		>
	>;

	/** Auth config from `auth.ts`. Deep-merged on top of module auth. */
	auth?: BetterAuthOptions | Record<string, any>;

	/** Content locale config from `locale.ts`. */
	locale?: LocaleConfig;

	/** Global lifecycle hooks from `hooks.ts`. */
	hooks?: GlobalHooksState;

	/** Default access rules from `access.ts`. */
	defaultAccess?: CollectionAccess;

	/**
	 * Messages from `messages/` directory, keyed by locale.
	 * Deep-merged on top of module messages.
	 */
	messages?: Record<string, Record<string, string>>;

	/** User-level migrations. */
	migrations?: Migration[];

	/** User-level seeds. */
	seeds?: Seed[];

	/**
	 * Extensible — admin plugin augments this interface to add:
	 * blocks, sidebar, dashboard, branding, adminLocale.
	 */
	[key: string]: unknown;
}

// ============================================================================
// Config Input — what config() accepts (legacy, use RuntimeConfig for new code)
// ============================================================================

/**
 * Application configuration — the shape of `questpie.config.ts`.
 * Created via `config({ ... })`. Passed to `createApp()` along with
 * discovered entities from file convention (or hand-written).
 *
 * For new code, use `RuntimeConfig` with `runtimeConfig()` instead.
 *
 * @see RFC §12 (config() Full API), §12.1 (Config Shape)
 */
export interface AppConfig {
	/** Modules to compose — order matters, later overrides earlier. */
	modules?: ModuleDefinition[];

	/** Application URL (required). */
	app: { url: string };

	/** Database connection (required). */
	db: DbConfig;

	/** Secret key for signing tokens. */
	secret?: string;

	/** Storage configuration. */
	storage?: StorageConfig;

	/** Email configuration with adapter. */
	email?: MailerConfig;

	/** Queue configuration with adapter. */
	queue?: { adapter: QueueAdapter };

	/** Search adapter for full-text search. */
	search?: SearchAdapter;

	/** Realtime configuration. */
	realtime?: RealtimeConfig;

	/** Logger configuration. */
	logger?: LoggerConfig;

	/** KV store configuration. */
	kv?: KVConfig;

	/** Executor configuration (sandboxed / trusted code execution). */
	executor?: ExecutorConfig;

	/** Auth configuration — deep-merged with module auth contributions. */
	auth?: BetterAuthOptions | Record<string, any>;

	/** Content localization. */
	locale?: LocaleConfig;

	/** Default access control (applied when entities don't define their own). */
	defaultAccess?: CollectionAccess;

	/** Global lifecycle hooks. */
	hooks?: GlobalHooksState;

	/** I18n translations config (backend messages). */
	translations?: TranslationsConfig;

	/** Auto-migrate on startup. */
	autoMigrate?: boolean;

	/** Auto-seed on startup. */
	autoSeed?: boolean | SeedCategory | SeedCategory[];

	/** CLI-specific configuration (used by `questpie` CLI commands). */
	cli?: {
		/** Migration directory for generated migrations. @default "./src/migrations" */
		migrations?: { directory?: string };
		/** Seed directory for generated seeds. @default "./src/seeds" */
		seeds?: { directory?: string };
	};

	/** User-level migrations (from project, not modules). */
	migrations?: Migration[];

	/** User-level seeds (from project, not modules). */
	seeds?: Seed[];

	/**
	 * Extensible — admin module augments this interface to add:
	 * adminLocale, branding, sidebar, dashboard.
	 */
	[key: string]: unknown;
}

// ============================================================================
// App Entities — what codegen discovers (second arg to legacy createApp)
// ============================================================================

/**
 * Entities discovered by file convention or codegen.
 * Passed as the second argument to the legacy `createApp(config, entities)`.
 *
 * For new code, use `AppDefinition` with `createApp(definition, runtime)`.
 *
 * @see RFC §15.1 (Complete .generated/index.ts Example)
 */
export interface AppEntities {
	/** Collections discovered from `collections/` directory. */
	collections?: Record<string, AnyCollectionOrBuilder>;

	/** Globals discovered from `globals/` directory. */
	globals?: Record<string, AnyGlobalOrBuilder>;

	/** Jobs discovered from `jobs/` directory. */
	jobs?: Record<string, JobDefinition<any, any>>;

	/** Routes discovered from `routes/` directory. */
	routes?: Record<string, RouteDefinition>;

	/** Auth config from `auth.ts`. Deep-merged on top of module auth. */
	auth?: BetterAuthOptions | Record<string, any>;

	/**
	 * Messages from `messages/` directory, keyed by locale.
	 * Deep-merged on top of module messages.
	 */
	messages?: Record<string, Record<string, string>>;

	/** User-level migrations. */
	migrations?: Migration[];

	/** User-level seeds. */
	seeds?: Seed[];

	/**
	 * Extensible — admin module augments this interface to add:
	 * blocks.
	 */
	[key: string]: unknown;
}

// ============================================================================
// Module Type Extraction Utilities
// ============================================================================

/**
 * Extract property `K` from a single module type, recursing into sub-modules.
 * Resolution order: depth-first, sub-modules first, then self (self overrides sub-modules).
 *
 * @example
 * ```ts
 * type AdminCollections = ExtractFromModule<ReturnType<typeof admin>, "collections">;
 * // { user: ..., assets: ..., session: ..., adminSavedViews: ..., ... }
 * ```
 */
export type ExtractFromModule<M, K extends string> = (M extends {
	modules: infer Sub extends readonly any[];
}
	? ExtractFromModuleArray<Sub, K>
	: {}) &
	(K extends keyof M ? (M[K] extends Record<string, any> ? M[K] : {}) : {});

/**
 * Extract property `K` from an array of module types, left-to-right.
 * Later modules override earlier ones (intersection semantics).
 *
 * @example
 * ```ts
 * type AllModuleCollections = ExtractFromModuleArray<typeof [starterModule, adminModule], "collections">;
 * ```
 */
export type ExtractFromModuleArray<
	A extends readonly any[],
	K extends string,
> = A extends readonly [infer First, ...infer Rest]
	? ExtractFromModule<First, K> & ExtractFromModuleArray<Rest, K>
	: {};

/**
 * Extract property `K` from a config type's `modules` array.
 * Top-level entry point for extracting module contributions.
 *
 * @example
 * ```ts
 * // In .generated/index.ts:
 * import _config from "../questpie.config";
 *
 * type ModuleCollections = ExtractModulesProperty<typeof _config, "collections">;
 * type ModuleJobs = ExtractModulesProperty<typeof _config, "jobs">;
 * type ModuleRoutes = ExtractModulesProperty<typeof _config, "routes">;
 * ```
 *
 * @see RFC §15.1 (Complete .generated/index.ts Example)
 */
export type ExtractModulesProperty<Config, K extends string> = Config extends {
	modules: infer M extends readonly any[];
}
	? ExtractFromModuleArray<M, K>
	: {};
