import { migration } from "questpie/services"
import type { OperationSnapshot } from "questpie/migration"
import { sql } from "drizzle-orm"
import snapshotJson from "./snapshots/20260615T084209_swift_orange_eagle.json"

const snapshot = snapshotJson as OperationSnapshot

export default migration({
	id: "swiftOrangeEagle20260615T084209",
	async up({ db }) {
		await db.execute(sql`CREATE EXTENSION IF NOT EXISTS "pg_trgm";`)
		await db.execute(sql`ALTER TABLE "apikey" ADD COLUMN "configId" varchar(255) DEFAULT 'default' NOT NULL;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "key" DROP NOT NULL;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "filename" DROP NOT NULL;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "mime_type" DROP NOT NULL;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "size" DROP NOT NULL;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "user" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "user" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "apikey" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "apikey" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "admin_saved_views" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "admin_saved_views" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "admin_preferences" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "admin_preferences" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "barbers" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "barbers" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "services" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "services" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "barber_services" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "barber_services" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "appointments" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "appointments" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "reviews" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "reviews" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "pages" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "pages" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "site_settings" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "site_settings" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "site_settings_i18n" ALTER COLUMN "footerLinks" SET DEFAULT '[{"label":"Services","href":"/services","isExternal":false},{"label":"Our Team","href":"/barbers","isExternal":false},{"label":"Contact","href":"/contact","isExternal":false},{"label":"Privacy Policy","href":"/privacy","isExternal":false}]';`)
		await db.execute(sql`ALTER TABLE "site_settings_versions" ALTER COLUMN "version_created_at" SET DATA TYPE timestamp(3) USING "version_created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "site_settings_versions" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "site_settings_versions" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "site_settings_i18n_versions" ALTER COLUMN "footerLinks" SET DEFAULT '[{"label":"Services","href":"/services","isExternal":false},{"label":"Our Team","href":"/barbers","isExternal":false},{"label":"Contact","href":"/contact","isExternal":false},{"label":"Privacy Policy","href":"/privacy","isExternal":false}]';`)
		await db.execute(sql`ALTER TABLE "questpie_realtime_log" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "questpie_search" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "questpie_search" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "questpie_search_facets" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "session" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "session" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "account" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "account" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "verification" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "verification" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "admin_locks" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "admin_locks" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "admin_audit_log" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "admin_audit_log" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "user" ALTER COLUMN "image" SET DATA TYPE varchar(500) USING "image"::varchar(500);`)
		await db.execute(sql`ALTER TABLE "blog_posts" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "blog_posts" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "site_settings_i18n" ALTER COLUMN "navigation" SET DEFAULT '[{"label":"Home","href":"/","isExternal":false},{"label":"Services","href":"/services","isExternal":false},{"label":"Our Team","href":"/barbers","isExternal":false},{"label":"Contact","href":"/contact","isExternal":false}]';`)
		await db.execute(sql`ALTER TABLE "site_settings_i18n_versions" ALTER COLUMN "navigation" SET DEFAULT '[{"label":"Home","href":"/","isExternal":false},{"label":"Services","href":"/services","isExternal":false},{"label":"Our Team","href":"/barbers","isExternal":false},{"label":"Contact","href":"/contact","isExternal":false}]';`)
		await db.execute(sql`ALTER TABLE "pages_versions" ALTER COLUMN "version_created_at" SET DATA TYPE timestamp(3) USING "version_created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "pages_versions" ALTER COLUMN "created_at" SET DATA TYPE timestamp(3) USING "created_at"::timestamp(3);`)
		await db.execute(sql`ALTER TABLE "pages_versions" ALTER COLUMN "updated_at" SET DATA TYPE timestamp(3) USING "updated_at"::timestamp(3);`)
	},
	async down({ db }) {
		await db.execute(sql`ALTER TABLE "apikey" DROP COLUMN "configId";`)
		await db.execute(sql`ALTER TABLE "account" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "account" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "apikey" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "apikey" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "key" SET NOT NULL;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "filename" SET NOT NULL;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "mime_type" SET NOT NULL;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "size" SET NOT NULL;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "assets" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "session" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "session" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "user" ALTER COLUMN "image" SET DATA TYPE varchar(2048) USING "image"::varchar(2048);`)
		await db.execute(sql`ALTER TABLE "user" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "user" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "verification" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "verification" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "admin_locks" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "admin_locks" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "admin_preferences" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "admin_preferences" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "admin_saved_views" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "admin_saved_views" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "admin_audit_log" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "admin_audit_log" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "appointments" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "appointments" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "barber_services" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "barber_services" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "barbers" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "barbers" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "blog_posts" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "blog_posts" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "pages" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "pages" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "pages_versions" ALTER COLUMN "version_created_at" SET DATA TYPE timestamp USING "version_created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "pages_versions" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "pages_versions" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "reviews" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "reviews" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "services" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "services" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "site_settings" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "site_settings" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "site_settings_i18n" ALTER COLUMN "navigation" SET DEFAULT '[{"label":"Home","href":"/"},{"label":"Services","href":"/services"},{"label":"Our Team","href":"/barbers"},{"label":"Blog","href":"/blog"},{"label":"Contact","href":"/contact"}]';`)
		await db.execute(sql`ALTER TABLE "site_settings_i18n" ALTER COLUMN "footerLinks" SET DEFAULT '[{"label":"Services","href":"/services"},{"label":"Our Team","href":"/barbers"},{"label":"Contact","href":"/contact"},{"label":"Privacy Policy","href":"/privacy"}]';`)
		await db.execute(sql`ALTER TABLE "site_settings_versions" ALTER COLUMN "version_created_at" SET DATA TYPE timestamp USING "version_created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "site_settings_versions" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "site_settings_versions" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "site_settings_i18n_versions" ALTER COLUMN "navigation" SET DEFAULT '[{"label":"Home","href":"/"},{"label":"Services","href":"/services"},{"label":"Our Team","href":"/barbers"},{"label":"Blog","href":"/blog"},{"label":"Contact","href":"/contact"}]';`)
		await db.execute(sql`ALTER TABLE "site_settings_i18n_versions" ALTER COLUMN "footerLinks" SET DEFAULT '[{"label":"Services","href":"/services"},{"label":"Our Team","href":"/barbers"},{"label":"Contact","href":"/contact"},{"label":"Privacy Policy","href":"/privacy"}]';`)
		await db.execute(sql`ALTER TABLE "questpie_realtime_log" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "questpie_search" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "questpie_search" ALTER COLUMN "updated_at" SET DATA TYPE timestamp USING "updated_at"::timestamp;`)
		await db.execute(sql`ALTER TABLE "questpie_search_facets" ALTER COLUMN "created_at" SET DATA TYPE timestamp USING "created_at"::timestamp;`)
	},
	snapshot,
})
