/**
 * Tests: codegen module template generation
 *
 * Covers:
 * 1. `generateModuleTemplate` — minimal module (empty)
 * 2. Collections — record emission with type interfaces
 * 3. Jobs — record emission
 * 4. Routes — flat emission with bundles
 * 5. Migrations, seeds — array emission
 * 6. Singles — auth, fields, sidebar (moduleEmit: "array")
 * 7. Sub-modules via modules.ts
 * 8. Registry augmentation via registryKey
 * 9. Type prefix derivation (questpie-admin → Admin)
 * 10. Named vs default import generation
 * 11. Extra module properties with extracted consts
 * 12. Empty stubs for declared categories without files
 * 13. keyFromProperty categories skip named type interfaces
 */
import { describe, expect, it } from "bun:test";

import { generateModuleTemplate } from "../../src/cli/codegen/module-template.js";
import type {
	CategoryDeclaration,
	DiscoveredFile,
	DiscoveryResult,
} from "../../src/cli/codegen/types.js";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function makeFile(
	key: string,
	opts: {
		varName?: string;
		importPath?: string;
		exportType?: "default" | "named" | "unknown";
		namedExportName?: string;
		factoryArgument?: string;
		source?: string;
		isBundle?: boolean;
	} = {},
): DiscoveredFile {
	return {
		absolutePath: `/root/${key}.ts`,
		key,
		varName: opts.varName ?? `_${key.replace(/[./]/g, "_")}`,
		importPath: opts.importPath ?? `../${key}`,
		exportType: opts.exportType ?? "default",
		namedExportName: opts.namedExportName,
		factoryArgument: opts.factoryArgument,
		source: opts.source ?? `${key}.ts`,
		isBundle: opts.isBundle,
	};
}

function emptyResult(categoryNames: string[] = []): DiscoveryResult {
	const categories = new Map<string, Map<string, DiscoveredFile>>();
	for (const name of categoryNames) {
		categories.set(name, new Map());
	}
	return {
		categories,
		singles: new Map(),
		spreads: new Map(),
	};
}

/** Minimal category meta with just collections and jobs. */
function baseCategoryMeta(): Map<string, CategoryDeclaration> {
	return new Map<string, CategoryDeclaration>([
		[
			"collections",
			{
				dirs: ["collections"],
				prefix: "coll",
				emit: "record",
				registryKey: true,
			},
		],
		[
			"globals",
			{
				dirs: ["globals"],
				prefix: "glob",
				emit: "record",
				registryKey: true,
			},
		],
		[
			"jobs",
			{
				dirs: ["jobs"],
				prefix: "job",
				emit: "record",
				registryKey: true,
			},
		],
		[
			"routes",
			{
				dirs: ["routes", "functions"],
				prefix: "route",
				emit: "record",
				recursive: true,
				keySeparator: "/",
				registryKey: true,
				includeInAppState: true,
			},
		],
		[
			"migrations",
			{
				dirs: ["migrations"],
				prefix: "mig",
				emit: "array",
				typeEmit: "none",
			},
		],
		[
			"seeds",
			{
				dirs: ["seeds"],
				prefix: "seed",
				emit: "array",
				typeEmit: "none",
			},
		],
		[
			"messages",
			{
				dirs: ["messages"],
				prefix: "msg",
				emit: "record",
				typeEmit: "messages",
			},
		],
	]);
}

function cat(
	result: DiscoveryResult,
	name: string,
): Map<string, DiscoveredFile> {
	let map = result.categories.get(name);
	if (!map) {
		map = new Map();
		result.categories.set(name, map);
	}
	return map;
}

// ─────────────────────────────────────────────────────────────────────────────
// Minimal module
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — minimal", () => {
	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: emptyResult(),
		categoryMeta: new Map(),
	});

	it("emits auto-generated header", () => {
		expect(output).toContain("AUTO-GENERATED by questpie codegen");
	});

	it("emits module name as const", () => {
		expect(output).toContain('"questpie-test" as const');
	});

	it("emits module type export", () => {
		expect(output).toContain("export type TestModule = {");
	});

	it("emits default export", () => {
		expect(output).toContain("export default _module;");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Type prefix derivation
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — type prefix", () => {
	it("derives Admin from questpie-admin", () => {
		const { code: output } = generateModuleTemplate({
			moduleName: "questpie-admin",
			discovered: emptyResult(),
			categoryMeta: new Map(),
		});
		expect(output).toContain("export type AdminModule = {");
	});

	it("derives Billing from billing (no questpie- prefix)", () => {
		const { code: output } = generateModuleTemplate({
			moduleName: "billing",
			discovered: emptyResult(),
			categoryMeta: new Map(),
		});
		expect(output).toContain("export type BillingModule = {");
	});

	it("derives UserAuth from questpie-user-auth (multi-segment)", () => {
		const { code: output } = generateModuleTemplate({
			moduleName: "questpie-user-auth",
			discovered: emptyResult(),
			categoryMeta: new Map(),
		});
		expect(output).toContain("export type UserAuthModule = {");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Collections — record emission with type interface
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — collections", () => {
	const result = emptyResult(["collections"]);
	const colls = cat(result, "collections");
	colls.set(
		"posts",
		makeFile("posts", {
			varName: "_coll_posts",
			importPath: "../collections/posts",
		}),
	);
	colls.set(
		"comments",
		makeFile("comments", {
			varName: "_coll_comments",
			importPath: "../collections/comments",
		}),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-blog",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits imports for each collection", () => {
		expect(output).toContain(
			'import _coll_comments from "../collections/comments";',
		);
		expect(output).toContain('import _coll_posts from "../collections/posts";');
	});

	it("emits named type alias for collections (NOT interface — interfaces lack implicit index signatures and break Record constraints app-wide)", () => {
		expect(output).toContain("export type BlogCollections = {");
		expect(output).not.toContain("export interface BlogCollections");
		expect(output).toContain("comments: typeof _coll_comments;");
		expect(output).toContain("posts: typeof _coll_posts;");
	});

	it("emits record in module object with type assertion", () => {
		expect(output).toContain("collections: {");
		expect(output).toContain("comments: _coll_comments,");
		expect(output).toContain("posts: _coll_posts,");
		expect(output).toContain("} as BlogCollections,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Routes — nested emission with bundles
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — routes with slash-separated keys", () => {
	const result = emptyResult(["routes"]);
	const routes = cat(result, "routes");
	routes.set(
		"admin/stats",
		makeFile("admin/stats", { varName: "_route_admin_stats" }),
	);
	routes.set(
		"admin/users/export",
		makeFile("admin/users/export", { varName: "_route_admin_users_export" }),
	);
	routes.set(
		"getConfig",
		makeFile("getConfig", { varName: "_route_getConfig" }),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits flat record with camelCase slash keys", () => {
		expect(output).toContain("routes: {");
		expect(output).toContain('"admin/stats": _route_admin_stats,');
		expect(output).toContain(
			'"admin/users/export": _route_admin_users_export,',
		);
		expect(output).toContain("getConfig: _route_getConfig,");
	});

	it("emits flat type alias with camelCase slash keys and __brand-guarded entries", () => {
		expect(output).toContain("export type TestRoutes = {");
		expect(output).toContain(
			'"admin/stats": typeof _route_admin_stats extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"admin/stats">> : typeof _route_admin_stats;',
		);
		expect(output).toContain(
			'"admin/users/export": typeof _route_admin_users_export extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"admin/users/export">> : typeof _route_admin_users_export;',
		);
		expect(output).toContain(
			'getConfig: typeof _route_getConfig extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"getConfig">> : typeof _route_getConfig;',
		);
	});
});

describe("generateModuleTemplate — bundle routes", () => {
	const result = emptyResult(["routes"]);
	const routes = cat(result, "routes");
	routes.set(
		"setup",
		makeFile("setup", { varName: "_route_setup", isBundle: true }),
	);
	routes.set(
		"getConfig",
		makeFile("getConfig", { varName: "_route_getConfig" }),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("spreads bundle files into routes object", () => {
		expect(output).toContain("..._route_setup,");
	});

	it("emits leaf files as record values", () => {
		expect(output).toContain("getConfig: _route_getConfig,");
	});

	it("includes all entries in type (intersection for bundles)", () => {
		// When bundles are present, type is emitted as intersection, not interface
		expect(output).toContain("export type TestRoutes =");
		expect(output).toContain(
			'getConfig: typeof _route_getConfig extends { __brand: "route" } ? RouteDefinition<unknown, unknown, RouteParamsFromKey<"getConfig">> : typeof _route_getConfig',
		);
		expect(output).toContain("typeof _route_setup");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Migrations, seeds — array emission
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — array emission", () => {
	const result = emptyResult(["migrations"]);
	const migs = cat(result, "migrations");
	migs.set("001_init", makeFile("001_init", { varName: "_mig_001_init" }));
	migs.set(
		"002_addUsers",
		makeFile("002_addUsers", { varName: "_mig_002_addUsers" }),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits flat array", () => {
		expect(output).toContain("migrations: [_mig_001_init, _mig_002_addUsers],");
	});

	it("does not emit type interface for array categories", () => {
		expect(output).not.toContain("TestMigrations");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Named imports
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — named imports", () => {
	const result = emptyResult(["collections"]);
	const colls = cat(result, "collections");
	colls.set(
		"posts",
		makeFile("posts", {
			varName: "_coll_posts",
			exportType: "named",
			namedExportName: "postsCollection",
			importPath: "../collections/posts",
		}),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits named import with alias", () => {
		expect(output).toContain(
			'import { postsCollection as _coll_posts } from "../collections/posts";',
		);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Sub-modules via modules.ts
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — sub-modules", () => {
	const result = emptyResult();
	result.singles.set(
		"modules",
		makeFile("modules", {
			varName: "_modules",
			importPath: "../modules",
		}),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: new Map(),
	});

	it("emits modules import", () => {
		expect(output).toContain('import _modules from "../modules";');
	});

	it("emits modules in module object", () => {
		expect(output).toContain("modules: _modules,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Singles (auth, fields, sidebar with moduleEmit: "array")
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — singles", () => {
	const result = emptyResult();
	result.singles.set(
		"fields",
		makeFile("fields", { varName: "_fields", importPath: "../fields" }),
	);
	result.singles.set(
		"defaultAccess",
		makeFile("defaultAccess", {
			varName: "_defaultAccess",
			importPath: "../default-access",
		}),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: new Map(),
	});

	it("emits singles as direct properties", () => {
		expect(output).toContain("defaultAccess: _defaultAccess,");
		expect(output).toContain("fields: _fields,");
	});
});

describe("generateModuleTemplate — plugin single", () => {
	const result = emptyResult();
	result.singles.set(
		"plugin",
		makeFile("plugin", { varName: "_plugin", importPath: "../plugin" }),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: new Map(),
	});

	it("emits plugin import", () => {
		expect(output).toContain('import _plugin from "../plugin";');
	});

	it("emits plugin as direct property in module object", () => {
		expect(output).toContain("plugin: _plugin,");
	});
});

describe("generateModuleTemplate — config bucket singles", () => {
	const result = emptyResult();
	result.singles.set(
		"adminConfig",
		makeFile("adminConfig", {
			varName: "_adminConfig",
			importPath: "../config/admin",
		}),
	);
	// Add configKey to the discovered file
	(result.singles.get("adminConfig") as any).configKey = "admin";

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: new Map(),
	});

	it("emits config bucket with configKey singles", () => {
		expect(output).toContain("config: {");
		expect(output).toContain("admin: _adminConfig,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Registry augmentation
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — no Registry augmentation", () => {
	const result = emptyResult(["collections"]);
	const colls = cat(result, "collections");
	colls.set("posts", makeFile("posts", { varName: "_coll_posts" }));

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("does NOT emit Registry augmentation (handled by root template)", () => {
		expect(output).not.toContain("interface Registry {");
		expect(output).not.toContain("declare global {");
	});
});

describe("generateModuleTemplate — no Registry even with custom registryKey", () => {
	const meta = new Map<string, CategoryDeclaration>([
		[
			"views",
			{
				dirs: ["views"],
				prefix: "view",
				emit: "record",
				registryKey: "~views",
			},
		],
	]);

	const result = emptyResult(["views"]);
	const views = cat(result, "views");
	views.set("table", makeFile("table", { varName: "_view_table" }));

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: meta,
	});

	it("does NOT emit Registry augmentation (handled by root template)", () => {
		expect(output).not.toContain("interface Registry {");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Empty stubs for declared categories
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — empty stubs", () => {
	const result = emptyResult(["collections", "jobs", "migrations"]);
	// Only collections has files
	const colls = cat(result, "collections");
	colls.set("posts", makeFile("posts", { varName: "_coll_posts" }));

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits empty record for declared categories without files", () => {
		expect(output).toContain("globals: {},");
		expect(output).toContain("jobs: {},");
		expect(output).toContain("routes: {},");
		expect(output).toContain("messages: {},");
	});

	it("emits empty array for array categories without files", () => {
		expect(output).toContain("migrations: [] as const,");
		expect(output).toContain("seeds: [] as const,");
	});

	it("does not emit empty stub for collections (has files)", () => {
		// collections should be a real record, not an empty stub
		expect(output).toContain("posts: _coll_posts,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Extra module properties with extracted consts
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — extra module properties", () => {
	const meta = new Map<string, CategoryDeclaration>([
		[
			"listViews",
			{
				dirs: [],
				prefix: "lv",
				emit: "record",
				registryKey: "listViews",
			},
		],
	]);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-admin",
		discovered: emptyResult(),
		categoryMeta: meta,
		extraModuleProperties: [
			"listViews: { table: _reg_table, form: _reg_form },",
		],
	});

	it("extracts registry properties to const before _module", () => {
		expect(output).toContain(
			"const _reg_listViews = { table: _reg_table, form: _reg_form };",
		);
	});

	it("references extracted const in module object", () => {
		expect(output).toContain("listViews: _reg_listViews,");
	});

	it("does NOT emit Registry augmentation (handled by root template)", () => {
		expect(output).not.toContain("interface Registry {");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// keyFromProperty — runtime-keyed type alias
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — keyFromProperty", () => {
	const meta = new Map<string, CategoryDeclaration>([
		[
			"views",
			{
				dirs: ["views"],
				prefix: "view",
				emit: "record",
				registryKey: true,
				keyFromProperty: "name",
			},
		],
	]);

	const result = emptyResult(["views"]);
	const views = cat(result, "views");
	views.set("table", makeFile("table", { varName: "_view_table" }));

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-admin",
		discovered: result,
		categoryMeta: meta,
	});

	it("uses keyFromProperty in module object", () => {
		expect(output).toContain("[_view_table.name]: _view_table,");
	});

	it("emits a runtime-keyed type alias for keyFromProperty categories", () => {
		expect(output).toContain("export type AdminViews =");
		expect(output).toContain(
			"{ [K in typeof _view_table.name]: typeof _view_table };",
		);
	});

	it("does NOT emit Registry augmentation (handled by root template)", () => {
		expect(output).not.toContain("interface Registry {");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// keyFromSource — the type has to be keyed the same way the record is
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — keyFromSource", () => {
	const meta = new Map<string, CategoryDeclaration>([
		[
			"blocks",
			{
				dirs: ["blocks"],
				prefix: "block",
				emit: "record",
				registryKey: false,
				keyFromSource: "basename",
			},
		],
	]);

	const result = emptyResult(["blocks"]);
	cat(result, "blocks").set(
		"imageText",
		makeFile("imageText", {
			varName: "_block_imageText",
			source: "blocks/image-text.tsx",
		}),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-admin",
		discovered: result,
		categoryMeta: meta,
	});

	it("keys the runtime record by basename", () => {
		expect(output).toContain('"image-text": _block_imageText,');
	});

	// The record is emitted as `{ ... } as AdminBlocks`. Keying the type off the
	// file key while the record is keyed off the basename makes the two shapes
	// disjoint, and TypeScript rejects the cast inside a file nobody may edit.
	it("keys the named type the same way", () => {
		expect(output).toContain('"image-text": typeof _block_imageText;');
		expect(output).not.toContain("imageText: typeof _block_imageText;");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Messages — typeEmit: "messages" skips named type
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — messages", () => {
	const result = emptyResult(["messages"]);
	const msgs = cat(result, "messages");
	msgs.set("en", makeFile("en", { varName: "_msg_en" }));
	msgs.set("sk", makeFile("sk", { varName: "_msg_sk" }));

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits messages as record without type assertion", () => {
		expect(output).toContain("messages: {");
		expect(output).toContain("en: _msg_en,");
		expect(output).toContain("sk: _msg_sk,");
		// No "as TestMessages" assertion
		expect(output).not.toContain("as TestMessages");
	});

	it("does not emit named type interface for messages", () => {
		expect(output).not.toContain("export interface TestMessages");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Extra imports and type declarations
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — extra imports", () => {
	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: emptyResult(),
		categoryMeta: new Map(),
		extraImports: [{ name: "{ filterViewsByKind }", path: "questpie/admin" }],
		extraTypeDeclarations: ["export type CustomType = string;"],
	});

	it("emits extra plugin imports", () => {
		expect(output).toContain(
			'import { filterViewsByKind } from "questpie/admin";',
		);
	});

	it("emits extra type declarations", () => {
		expect(output).toContain("export type CustomType = string;");
	});
});

describe("generateModuleTemplate — channel factory argument metadata", () => {
	it("emits source metadata under the codegen symbol for module conflict checks", () => {
		const result = emptyResult(["channels"]);
		result.categories.get("channels")!.set(
			"chatRoom",
			makeFile("chatRoom", {
				source: "channels/chat-room.ts",
				factoryArgument: "chat-room-[roomId]",
			}),
		);

		const { code } = generateModuleTemplate({
			moduleName: "questpie-chat",
			discovered: result,
			categoryMeta: new Map([
				[
					"channels",
					{
						dirs: ["channels"],
						prefix: "chan",
						factoryFunctions: ["channel"],
						factoryArgument: { label: "wire pattern", unique: true },
					} satisfies CategoryDeclaration,
				],
			]),
		});

		expect(code).toContain(
			'[Symbol.for("questpie.codegen.module-metadata.v1")]',
		);
		expect(code).toContain('"value":"chat-room-[roomId]"');
		expect(code).toContain('"source":"channels/chat-room.ts"');
		expect(code).toContain("channels: {");
		expect(code).toContain("chatRoom: _chatRoom");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// createAppKey — the key a category takes on the module object
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — createAppKey", () => {
	/** Mirrors the core plugin's emails declaration. */
	const meta = new Map<string, CategoryDeclaration>([
		[
			"emails",
			{
				dirs: ["emails"],
				prefix: "email",
				emit: "record",
				typeEmit: "emails",
				createAppKey: "emailTemplates",
				registryKey: "emails",
			},
		],
	]);

	const result = emptyResult(["emails"]);
	cat(result, "emails").set(
		"welcome",
		makeFile("welcome", { varName: "_email_welcome" }),
	);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: meta,
	});

	it("keys the runtime member by createAppKey", () => {
		// create-app only ever reads `emailTemplates`. `emails` is not a consumed
		// key, so templates emitted under it die on instance.state.
		expect(output).toContain("emailTemplates: {");
		expect(output).toContain("welcome: _email_welcome,");
		expect(output).not.toContain("\temails: {");
	});

	it("keys the type member by createAppKey", () => {
		expect(output).toContain("emailTemplates: TestEmails;");
		expect(output).not.toContain("emails: TestEmails;");
	});

	it("keys the empty stub by createAppKey too", () => {
		// This is the shape every module ships today — an emails/ directory that
		// does not exist yet.
		const { code } = generateModuleTemplate({
			moduleName: "questpie-test",
			discovered: emptyResult(),
			categoryMeta: meta,
		});
		expect(code).toContain("emailTemplates: {},");
		expect(code).toContain("emailTemplates: Record<never, never>;");
		expect(code).not.toContain("emails:");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Header
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — regenerate header", () => {
	it("names a command that exists", () => {
		const { code } = generateModuleTemplate({
			moduleName: "questpie-test",
			discovered: emptyResult(),
			categoryMeta: new Map(),
		});
		expect(code).toContain("// Regenerate with: questpie generate");
		// `questpie generate` registers no --module flag and commander is not in
		// allowUnknownOption mode, so the old header errored out.
		expect(code).not.toContain("--module");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Spread singles (mergeStrategy: "spread")
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — spreads", () => {
	const result = emptyResult();
	result.spreads.set("sidebar", [
		makeFile("sidebar", { varName: "_sidebar", importPath: "../sidebar" }),
		makeFile("sidebarBilling", {
			varName: "_sidebar_billing",
			importPath: "../features/billing/sidebar",
		}),
	]);

	const { code: output } = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: new Map(),
	});

	it("imports every spread file", () => {
		expect(output).toContain('import _sidebar from "../sidebar";');
		expect(output).toContain(
			'import _sidebar_billing from "../features/billing/sidebar";',
		);
	});

	it("emits the same concatenation the app template emits", () => {
		expect(output).toContain(
			"sidebar: [...(_sidebar ?? []), ...(_sidebar_billing ?? [])],",
		);
	});

	it("declares the member on the module type", () => {
		expect(output).toContain("sidebar: readonly unknown[];");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// registries.ts
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — registries.ts imports", () => {
	const meta = new Map<string, CategoryDeclaration>([
		[
			"views",
			{
				dirs: ["views"],
				prefix: "view",
				emit: "record",
				registryKey: true,
				recordPlaceholder: "$VIEWS_RECORD",
			},
		],
	]);

	const result = emptyResult(["views"]);
	cat(result, "views").set(
		"table",
		makeFile("table", {
			varName: "_view_table",
			importPath: "../views/table",
			exportType: "named",
			namedExportName: "tableView",
		}),
	);

	const { registriesCode } = generateModuleTemplate({
		moduleName: "questpie-admin",
		discovered: result,
		categoryMeta: meta,
	});

	it("honours named exports, as module.ts does", () => {
		// A hardcoded default import here resolved to nothing for every view or
		// component whose entity is a named export — which factory discovery makes
		// the common case.
		expect(registriesCode).toContain(
			'import type { tableView as _view_table } from "../views/table";',
		);
	});

	it("keeps the imports type-only", () => {
		// module.ts side-effect imports registries.ts. A value import would pull
		// every view into the runtime graph ahead of the module that owns them.
		expect(registriesCode).not.toContain("import _view_table from");
	});

	it("augments the registry from the rebuilt local type", () => {
		expect(registriesCode).toContain("type _RegViews = {");
		expect(registriesCode).toContain(
			"interface ViewsRegistry extends _RegViews {}",
		);
	});
});

describe("generateModuleTemplate — registries.ts keyFromProperty", () => {
	const meta = new Map<string, CategoryDeclaration>([
		[
			"views",
			{
				dirs: ["views"],
				prefix: "view",
				emit: "record",
				registryKey: true,
				recordPlaceholder: "$VIEWS_RECORD",
				keyFromProperty: "name",
			},
		],
	]);

	const result = emptyResult(["views"]);
	cat(result, "views").set(
		"table",
		makeFile("table", { varName: "_view_table", importPath: "../views/table" }),
	);

	const { code, registriesCode } = generateModuleTemplate({
		moduleName: "questpie-admin",
		discovered: result,
		categoryMeta: meta,
	});

	it("keys the registry type by the runtime property, like the module type", () => {
		// The module object keys by `_view_table.name`. The registry keying by the
		// filename instead made autocomplete disagree with the runtime.
		expect(code).toContain("[_view_table.name]: _view_table,");
		expect(registriesCode).toContain(
			"{ [K in typeof _view_table.name]: typeof _view_table };",
		);
		expect(registriesCode).not.toContain("table: typeof _view_table");
	});
});
