import { readFile } from "node:fs/promises";

import type { HarnessV1 } from "@ai-sdk/harness";
import { createCodex, type CodexHarnessSettings } from "@ai-sdk/harness-codex";

export const CODEX_ADAPTER_VERSION = "1.0.29";
export const CODEX_SDK_VERSION = "0.144.1";
export const CODEX_CLI_VERSION = CODEX_SDK_VERSION;
export const DEPRECATED_CODEX_MODEL = "gpt-5.3-codex";

const CODEX_BOOTSTRAP_DIR = "/tmp/harness/codex";
const bridgeAsset = (name: "bun.lock" | "package.json") =>
	new URL(`./codex-bridge/${name}`, import.meta.url);

export type QuestpieCodexSettings = Omit<CodexHarnessSettings, "model"> & {
	/**
	 * Required deliberately: the upstream adapter's implicit gpt-5.3-codex
	 * default is deprecated and must never decide a production model for us.
	 */
	model: string;
};

/**
 * Compatibility gate for @ai-sdk/harness-codex@1.0.29.
 *
 * The upstream adapter installs its SDK from bridge assets inside every fresh
 * sandbox, so a root dependency override cannot change the executed CLI. This
 * wrapper keeps the reviewed adapter while replacing only that bootstrap
 * manifest/lock with exact @openai/codex-sdk@0.144.1 assets generated by Bun.
 *
 * Rollback: remove this wrapper/export and use createCodex directly after the
 * upstream adapter publishes an age-qualified SDK/model fix.
 */
export function createQuestpieCodex(
	settings: QuestpieCodexSettings,
): HarnessV1 {
	const model = settings.model.trim();
	if (!model) {
		throw new Error("Codex compatibility requires an explicit model");
	}
	if (model === DEPRECATED_CODEX_MODEL) {
		throw new Error(`Codex model "${DEPRECATED_CODEX_MODEL}" is deprecated`);
	}

	const upstream = createCodex({ ...settings, model });
	const getUpstreamBootstrap = upstream.getBootstrap;
	if (!getUpstreamBootstrap) {
		throw new Error("Codex adapter bootstrap is unavailable");
	}
	let bootstrapPromise: ReturnType<NonNullable<typeof upstream.getBootstrap>>;

	return {
		...upstream,
		async getBootstrap() {
			bootstrapPromise ??= (async () => {
				const bootstrap = await getUpstreamBootstrap();

				const [manifest, lock] = await Promise.all([
					readFile(bridgeAsset("package.json"), "utf8"),
					readFile(bridgeAsset("bun.lock"), "utf8"),
				]);
				const upstreamFiles = bootstrap.files.filter(
					(file) =>
						!file.path.endsWith("/package.json") &&
						!file.path.endsWith("/pnpm-lock.yaml"),
				);

				return {
					...bootstrap,
					files: [
						...upstreamFiles,
						{
							path: `${CODEX_BOOTSTRAP_DIR}/package.json`,
							content: manifest,
						},
						{
							path: `${CODEX_BOOTSTRAP_DIR}/bun.lock`,
							content: lock,
						},
					],
					commands: [
						{ command: `mkdir -p ${CODEX_BOOTSTRAP_DIR}` },
						{
							command: `bun install --cwd ${CODEX_BOOTSTRAP_DIR} --frozen-lockfile`,
						},
					],
				};
			})();

			return bootstrapPromise;
		},
	};
}
