#!/usr/bin/env bun
/**
 * QUESTPIE skill "Full Compiled Document" generator.
 *
 * Each shipped skill points at an `AGENTS.md` - the paste-one-file bundle that
 * expands SKILL.md plus every reference inline. That bundle is DERIVED: its
 * single source of truth is `SKILL.md` + `references/*.md`. Hand-editing it
 * drifts the copy from the sources (the observed failure mode: a fictional API
 * claim that had to be manually deleted from AGENTS.md). This script regenerates
 * it from the sources so it cannot drift.
 *
 * The reference ORDER is read from SKILL.md itself (the order `references/X.md`
 * links appear), so SKILL.md stays the single source for structure too - adding
 * a reference to its "Reference Topics" table is all it takes to include it.
 *
 *   bun run scripts/build-skill-docs.ts           # regenerate every skill's AGENTS.md
 *   bun run scripts/build-skill-docs.ts --check    # exit 1 if any AGENTS.md is stale (CI gate)
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT_DIR = resolve(import.meta.dir, "..");
const SKILLS_DIR = join(ROOT_DIR, "skills");

/** Skills that ship a compiled AGENTS.md (sources = SKILL.md + references/). */
const SKILLS = ["questpie", "questpie-admin"];

/** Drop YAML frontmatter, returning the markdown body. */
function stripFrontmatter(md: string): string {
	if (!md.startsWith("---")) return md.trimStart();
	const close = md.indexOf("\n---", 3);
	if (close === -1) return md.trimStart();
	const newline = md.indexOf("\n", close + 1);
	return md.slice(newline + 1).trimStart();
}

/** Drop the "This skill builds on X." lineage line - noise inside one bundle. */
function stripLineage(body: string): string {
	return body.replace(/^This skill builds on [^\n]*\n+/, "");
}

/** Reference filenames in the order they first appear in the SKILL.md body. */
function referenceOrder(skillBody: string): string[] {
	const seen = new Set<string>();
	const order: string[] = [];
	const pattern = /references\/([\w-]+\.md)/g;
	let match: RegExpExecArray | null;
	while ((match = pattern.exec(skillBody)) !== null) {
		if (!seen.has(match[1])) {
			seen.add(match[1]);
			order.push(match[1]);
		}
	}
	return order;
}

function buildSkill(skill: string): {
	path: string;
	content: string;
	refs: string[];
} {
	const dir = join(SKILLS_DIR, skill);
	const refsDir = join(dir, "references");
	const skillBody = stripFrontmatter(
		readFileSync(join(dir, "SKILL.md"), "utf8"),
	).trim();

	// Only this skill's own reference files - SKILL.md may also point at another
	// skill's references (e.g. admin → questpie's multi-tenancy.md); those are
	// cross-skill pointers, not local files to inline.
	const existing = existsSync(refsDir)
		? readdirSync(refsDir)
				.filter((f) => f.endsWith(".md"))
				.sort()
		: [];
	const mentioned = referenceOrder(skillBody).filter((r) =>
		existing.includes(r),
	);
	const leftover = existing.filter((r) => !mentioned.includes(r));
	if (leftover.length > 0) {
		console.warn(
			`  note: ${skill} references not linked from SKILL.md (appended): ${leftover.join(", ")}`,
		);
	}
	const refs = [...mentioned, ...leftover];

	const banner =
		`<!-- GENERATED by scripts/build-skill-docs.ts - DO NOT EDIT.\n` +
		`     Sources: skills/${skill}/SKILL.md + skills/${skill}/references/*.md\n` +
		`     Regenerate: bun run scripts/build-skill-docs.ts -->`;

	const parts = [banner, skillBody];
	for (const ref of refs) {
		const refBody = stripLineage(
			stripFrontmatter(
				readFileSync(join(dir, "references", ref), "utf8"),
			).trim(),
		).trim();
		parts.push(refBody);
	}

	return {
		path: join(dir, "AGENTS.md"),
		content: `${parts.join("\n\n---\n\n")}\n`,
		refs,
	};
}

const check = process.argv.includes("--check");
let stale = 0;

for (const skill of SKILLS) {
	const { path, content, refs } = buildSkill(skill);
	let current: string | null = null;
	try {
		current = readFileSync(path, "utf8");
	} catch {
		current = null;
	}

	if (check) {
		if (current !== content) {
			stale++;
			console.error(
				`STALE: skills/${skill}/AGENTS.md - run: bun run scripts/build-skill-docs.ts`,
			);
		} else {
			console.log(`ok: skills/${skill}/AGENTS.md`);
		}
	} else {
		writeFileSync(path, content);
		console.log(
			`wrote skills/${skill}/AGENTS.md (${content.split("\n").length} lines, ${refs.length} references)`,
		);
	}
}

if (check && stale > 0) process.exit(1);
