/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { locksCollection as _coll_admin_locks } from "../collections/locks.collection";
import { adminPreferencesCollection as _coll_admin_preferences } from "../collections/admin-preferences";
import { savedViewsCollection as _coll_admin_saved_views } from "../collections/saved-views";

// ── Entity key registry (names only — acyclic by construction) ─────
declare global {
	namespace Questpie {
		interface CollectionKeys { admin_locks: unknown; admin_preferences: unknown; admin_saved_views: unknown }
	}
}

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface AdminPreferencesCollections {
	admin_locks: typeof _coll_admin_locks;
	admin_preferences: typeof _coll_admin_preferences;
	admin_saved_views: typeof _coll_admin_saved_views;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type AdminPreferencesModule = {
	name: "questpie-admin-preferences";
	collections: AdminPreferencesCollections;
	globals: {};
	jobs: {};
	routes: {};
	messages: {};
	services: {};
	emails: {};
	migrations: readonly unknown[];
	seeds: readonly unknown[];
	fieldTypes: {};
	views: {};
	components: {};
	blocks: {};
};

const _module: AdminPreferencesModule = {
	name: "questpie-admin-preferences" as const,
	collections: {
		admin_locks: _coll_admin_locks,
		admin_preferences: _coll_admin_preferences,
		admin_saved_views: _coll_admin_saved_views,
	} as AdminPreferencesCollections,
	globals: {},
	jobs: {},
	routes: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	views: {},
	components: {},
	blocks: {},
};

export default _module;
