/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { locksCollection as _coll_admin_locks } from "../collections/locks.collection";
import { adminPreferencesCollection as _coll_admin_preferences } from "../collections/admin-preferences";
import { savedViewsCollection as _coll_admin_saved_views } from "../collections/saved-views";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export type AdminPreferencesCollections = {
	admin_locks: typeof _coll_admin_locks;
	admin_preferences: typeof _coll_admin_preferences;
	admin_saved_views: typeof _coll_admin_saved_views;
};

export type AdminPreferencesGlobals = Record<never, never>;

export type AdminPreferencesJobs = Record<never, never>;

export type AdminPreferencesRoutes = Record<never, never>;

export type AdminPreferencesFieldTypes = Record<never, never>;

export type AdminPreferencesViews = Record<never, never>;

export type AdminPreferencesComponents = Record<never, never>;

export type AdminPreferencesBlocks = Record<never, never>;

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type AdminPreferencesModule = {
	name: "questpie-admin-preferences";
	collections: AdminPreferencesCollections;
	globals: AdminPreferencesGlobals;
	jobs: AdminPreferencesJobs;
	routes: AdminPreferencesRoutes;
	fieldTypes: AdminPreferencesFieldTypes;
	views: AdminPreferencesViews;
	components: AdminPreferencesComponents;
	blocks: AdminPreferencesBlocks;
	messages: Record<never, never>;
	services: Record<never, never>;
	emails: Record<never, never>;
	migrations: readonly unknown[];
	seeds: readonly unknown[];
};

const _module: AdminPreferencesModule = {
	name: "questpie-admin-preferences" as const,
	collections: {
		admin_locks: _coll_admin_locks,
		admin_preferences: _coll_admin_preferences,
		admin_saved_views: _coll_admin_saved_views,
	} as AdminPreferencesCollections,
	globals: {},
	jobs: {},
	routes: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	views: {},
	components: {},
	blocks: {},
};

export default _module;
