/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module
import "./registries.js";


// ── Sub-Modules ────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_account from "../collections/account";
import _coll_apikey from "../collections/apikey";
import _coll_assets from "../collections/assets";
import _coll_session from "../collections/session";
import _coll_user from "../collections/user";
import _coll_verification from "../collections/verification";

// ── Jobs ────────────────────────────────────────────
import _job_realtimeCleanup from "../jobs/realtime-cleanup";

// ── Messages ────────────────────────────────────────────
import _msg_en from "../messages/en";

// ── Singles ────────────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";
import _fields from "../fields";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export type StarterCollections = {
	account: typeof _coll_account;
	apikey: typeof _coll_apikey;
	assets: typeof _coll_assets;
	session: typeof _coll_session;
	user: typeof _coll_user;
	verification: typeof _coll_verification;
};

export type StarterGlobals = Record<never, never>;

export type StarterJobs = {
	realtimeCleanup: Omit<typeof _job_realtimeCleanup, "handler"> & { handler: (args: unknown) => Promise<unknown> };
};

export type StarterRoutes = Record<never, never>;

export type StarterFieldTypes = Record<never, never>;

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export type StarterModule = {
	name: "questpie-starter";
	modules: typeof _modules;
	collections: StarterCollections;
	jobs: StarterJobs;
	globals: StarterGlobals;
	routes: StarterRoutes;
	fieldTypes: StarterFieldTypes;
	messages: Record<never, never>;
	services: Record<never, never>;
	emails: Record<never, never>;
	migrations: readonly unknown[];
	seeds: readonly unknown[];
	config: {
		app: typeof _appConfig;
		auth: typeof _authConfig;
	};
	fields: typeof _fields;
};

const _module: StarterModule = {
	name: "questpie-starter" as const,
	modules: _modules,
	collections: {
		account: _coll_account,
		apikey: _coll_apikey,
		assets: _coll_assets,
		session: _coll_session,
		user: _coll_user,
		verification: _coll_verification,
	} as StarterCollections,
	jobs: {
		realtimeCleanup: _job_realtimeCleanup,
	} as StarterJobs,
	messages: {
		en: _msg_en,
	},
	globals: {},
	routes: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	fieldTypes: {},
	config: {
		app: _appConfig,
		auth: _authConfig,
	},
	fields: _fields,
};

export default _module;
