/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Factory registry augmentations for module. Separate file to avoid circular refs.
// IMPORTANT: This file must NOT import from module.ts to avoid circular imports.

import type _fields from "../fields";
type _FieldTypes = typeof _fields;

declare global {
	namespace Questpie {
		interface FieldTypesMap extends _FieldTypes {}
	}
}
