/**
 * Scans source files for Phosphor icon references (ph:icon-name)
 * and generates a minimal JSON bundle with only the used icons.
 *
 * Usage: bun run packages/admin/scripts/generate-icon-bundle.ts
 *
 * Output: packages/admin/src/client/icons/phosphor-bundle.ts
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

// biome-ignore lint: require is fine in scripts
const ph = require("@iconify/json/json/ph.json") as {
	prefix: string;
	icons: Record<string, { body: string; width?: number; height?: number }>;
	aliases?: Record<string, { parent: string }>;
	width?: number;
	height?: number;
};

const ROOT = resolve(import.meta.dirname, "../../..");

// Scan for all ph:icon-name references
const grepResult = execSync(
	'grep -roh "ph:[a-z0-9-]*" --include="*.ts" --include="*.tsx" packages/ apps/ examples/ 2>/dev/null | sort -u',
	{ cwd: ROOT },
)
	.toString()
	.trim();

const usedNames = grepResult
	.split("\n")
	.map((s) => s.replace("ph:", ""))
	.filter(Boolean);

// Build minimal icon set
const minimal: {
	prefix: string;
	icons: Record<string, unknown>;
	width?: number;
	height?: number;
} = {
	prefix: ph.prefix,
	icons: {},
	width: ph.width,
	height: ph.height,
};

for (const name of usedNames) {
	if (ph.icons[name]) {
		minimal.icons[name] = ph.icons[name];
	} else if (ph.aliases?.[name]) {
		minimal.icons[name] = ph.icons[ph.aliases[name].parent];
	}
}

const json = JSON.stringify(minimal);

const output = `// Auto-generated by scripts/generate-icon-bundle.ts — DO NOT EDIT
// Contains ${Object.keys(minimal.icons).length} Phosphor icons (${(json.length / 1024).toFixed(1)}KB)
import { addCollection } from "@iconify/react";

const data = ${json} as const;

addCollection(data);
`;

const outPath = resolve(ROOT, "packages/admin/src/client/icons/phosphor-bundle.ts");
writeFileSync(outPath, output);

console.log(
	`Generated ${outPath}\n  ${Object.keys(minimal.icons).length} icons, ${(json.length / 1024).toFixed(1)}KB`,
);
