/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import { createApp } from "questpie/app";
import type { AppDefinition, RuntimeConfig } from "questpie/types";
import type { _AppQuestpie, AppSession } from "./context.gen";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import { articles as _coll_articles } from "../collections/articles";
import { categories as _coll_categories } from "../collections/categories";
import { adminUser as _coll_user } from "../collections/admin-user";

// ── Globals ────────────────────────────────────────────────
import { siteSettings as _glob_siteSettings } from "../globals/site-settings";

// ── Services ───────────────────────────────────────────────
import _svc_analytics from "../services/analytics";
import _svc_reporting from "../services/reporting";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

const _appDefinition = ({
	modules: _modules,
	collections: {
		articles: _coll_articles,
		categories: _coll_categories,
		user: _coll_user,
	},
	globals: {
		siteSettings: _glob_siteSettings,
	},
	services: {
		analytics: _svc_analytics,
		reporting: _svc_reporting,
	},
	config: {
		app: _appConfig,
		auth: _authConfig,
	},
}) satisfies AppDefinition;

export const createAppForRuntime = (async (runtime: RuntimeConfig) =>
	(await createApp(_appDefinition, runtime)) as unknown as _AppQuestpie) as ((
	runtime: RuntimeConfig,
) => Promise<_AppQuestpie>) & {
	readonly "~types"?: { session: AppSession };
};
