/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate -c test/types/__fullapp__/questpie.config.ts

import "./names.gen";
// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import { articles as _coll_articles } from "../collections/articles";
import { categories as _coll_categories } from "../collections/categories";
import { adminUser as _coll_user } from "../collections/admin-user";

// ── Globals ────────────────────────────────────────────────
import { siteSettings as _glob_siteSettings } from "../globals/site-settings";

// ── Services ───────────────────────────────────────────────
import _svc_analytics from "../services/analytics";
import _svc_reporting from "../services/reporting";

// ── Core Singles ───────────────────────────────────────────
import _appConfig from "../config/app";
import _authConfig from "../config/auth";

import type { RouteParamsFromKey, RouteWithParams } from "questpie/types";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { ExtractModulePropArr, ExtractModulePropArrOverride, Override, ServiceCustomNamespaceInstances, ServiceInstanceOf, ServiceInstancesInNamespace, ServiceTopLevelInstances } from "questpie/types";
type _RouteDefinitionWithoutHandler<T> = T extends { mode: "raw" } ? Omit<T, "handler"> & { handler: (args: unknown) => Response | Promise<Response> } : Omit<T, "handler"> & { handler: (args: unknown) => unknown | Promise<unknown> };
export type _ModuleCollections = ExtractModulePropArrOverride<typeof _modules, "collections">;
export type _ModuleChannels = ExtractModulePropArr<typeof _modules, "channels">;
export type _ModuleGlobals = ExtractModulePropArr<typeof _modules, "globals">;
export type _ModuleJobs = ExtractModulePropArr<typeof _modules, "jobs">;
export type _ModuleRoutes = ExtractModulePropArr<typeof _modules, "routes">;
export type _ModuleServices = {};
export type _ModuleFieldTypes = ExtractModulePropArr<typeof _modules, "fieldTypes">;
// Registry category extraction from modules
export type _Registry_Collections = ExtractModulePropArrOverride<typeof _modules, "collections">;
export type _Registry_Channels = ExtractModulePropArr<typeof _modules, "channels">;
export type _Registry_Globals = ExtractModulePropArr<typeof _modules, "globals">;
export type _Registry_Jobs = ExtractModulePropArr<typeof _modules, "jobs">;
export type _Registry_Routes = ExtractModulePropArr<typeof _modules, "routes">;
export type _Registry_Services = {};
export type _Registry_Emails = ExtractModulePropArr<typeof _modules, "emails">;
export type _Registry_FieldTypes = ExtractModulePropArr<typeof _modules, "fieldTypes">;

// Recursive module property extraction (for fields contributed at each level)
import type { ExtractModuleProp } from "questpie/types";

export type _AllModuleFields = ExtractModuleProp<{ modules: typeof _modules }, "fields">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = Override<_ModuleCollections, {
	articles: typeof _coll_articles;
	categories: typeof _coll_categories;
	user: typeof _coll_user;
}>;

/** All channels in the app (modules + user, user overrides) */
export type AppChannels = _ModuleChannels;

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = _ModuleGlobals & {
	siteSettings: typeof _glob_siteSettings;
};

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs;

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes;

/** All service definitions in the app (modules + user, user overrides). */
type _AppServiceDefinitions = _ModuleServices & {
	analytics: typeof _svc_analytics;
	reporting: typeof _svc_reporting;
};

/** All services in the app as resolved service instances. */
export type AppServices = {
	[K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]>;
};
export type _AppDefaultServices = ServiceInstancesInNamespace<_AppServiceDefinitions, "services">;
export type _AppServicesSeam = { [K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]> };
export type _AppTopLevelServices = ServiceTopLevelInstances<_AppServiceDefinitions>;
export type _AppCustomServiceNamespaces = ServiceCustomNamespaceInstances<_AppServiceDefinitions>;

/** All email templates in the app — use with email.sendTemplate() */
export type AppEmailTemplates = Record<string, never>;

/** All fieldtypes in the app (modules + user, user overrides) */
export type AppFieldTypes = _ModuleFieldTypes;
