/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Typed factory functions with plugin extensions. Regenerate with: questpie generate

// ── Core Imports ───────────────────────────────────────────
import { CollectionBuilder, GlobalBuilder, builtinFields, type EmptyCollectionState, type EmptyGlobalState, type BuiltinFields } from "questpie/builders";

// Merged field factories — builtins + module-contributed (e.g. richText, blocks) + user fields
const _rawFieldDefs = { ...builtinFields } as const;

const _allFieldDefs = _rawFieldDefs;

// ── Entity key registry (names only — acyclic by construction) ─────
declare global {
	namespace Questpie {
		interface CollectionKeys { articles: unknown; categories: unknown; user: unknown }
		interface GlobalKeys { siteSettings: unknown }
		interface ServiceKeys { analytics: unknown; reporting: unknown }
	}
}

// ── Plugin Imports ─────────────────────────────────────────
import { type AppConfigInput, type AuthConfig } from "questpie/types";

// Field types — populated by module codegen via Questpie.FieldTypesMap
type _AllFieldTypes = Questpie.FieldTypesMap;

// ════════════════════════════════════════════════════════════
// Factory functions
// ════════════════════════════════════════════════════════════

/**
 * Create a typed collection builder with plugin extensions.
 *
 * @example
 * ```ts
 * import { collection } from "#questpie/factories";
 *
 * export default collection("posts")
 *   .fields(({ f }) => ({ title: f.text(255).required() }))
 * ```
 */
export function collection<TName extends string>(name: TName): CollectionBuilder<EmptyCollectionState<TName, undefined, _AllFieldTypes>> {
	return CollectionBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs);
}

/**
 * Create a typed global builder with plugin extensions.
 */
export function global<TName extends string>(name: TName): GlobalBuilder<EmptyGlobalState<TName, undefined, _AllFieldTypes>> {
	return GlobalBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs);
}

// ════════════════════════════════════════════════════════════
// Singleton factory functions
// ════════════════════════════════════════════════════════════

/** Typed factory for appConfig config. */
export function appConfig<T extends AppConfigInput>(config: T): T { return config; }

/** Typed factory for authConfig config. */
export function authConfig<T extends AuthConfig>(config: T): T { return config; }
